### PR TITLE
[Enhancement] enable multi_platform variable for RHEL

### PR DESCRIPTION
**Pull request by redhatrises**
- Replace Red Hat Enterprise Linux platform tags to multi_platform_rhel

### CODE REVIEW

**Comment by redhatrises** [comment]
Can add to all the `shared/oval` Fedora checks as well.

**Comment by iankko** [comment]
* Functionality review - verified on all three (Red Hat Enterprise Linux 6, 7, and Fedora) that change once applied builds & works correctly on all three of the products.

* Completeness review - the proposed change doesn't seem to be complete. It doesn't modify / includes ```multi_platform_rhel``` variable for all (shared) OVAL checks it could / should (IOW for all OVAL checks containing both ```Red Hat Enterprise Linux 6``` and ```Red Hat Enterprise Linux 7``` as platform specifier currently).

The proposal touches 76 files. But running e.g. the following bash snippet:
```
#!/bin/bash

if [ $# -ne "1" ]
then
  echo -e "\nUsage: $0 Provide path to scap-security-guide/shared/oval directory:\n"
  exit 1
fi

for i in ${1}/*.xml
do
  grep -P "Red Hat Enterprise Linux 6" $i > /dev/null; RHEL6=$?
  grep -P "Red Hat Enterprise Linux 7" $i > /dev/null; RHEL7=$?
  if [ $RHEL6 -eq 0 ] && [ $RHEL7 -eq 0 ]
  then
    # Print just filename for found entry
    basename $i
  fi
done
```

with providing path to ```scap-security-guide/shared/oval``` directory returns there are 94 OVAL (shared) OVAL checks containing both ```Red Hat Enterprise Linux 6``` and ```Red Hat Enterprise Linux 7```. 

Making a diff (which OVAL checks are proposed to be changed now wrt to which shared OVAL checks should be updated [because they contain both RHEL-6 and RHEL-7 in the <platform> specifier]) returns the following OVAL checks not covered by the change above yet:
```
> accounts_password_minlen_login_defs.xml
> accounts_root_path_dirs_no_write.xml
> accounts_umask_etc_bashrc.xml
> accounts_umask_etc_csh_cshrc.xml
> accounts_umask_etc_login_defs.xml
> accounts_umask_etc_profile.xml
> ensure_gpgcheck_never_disabled.xml
> file_permissions_etc_gshadow.xml
> file_permissions_etc_passwd.xml
> file_permissions_etc_shadow.xml
> install_antivirus.xml
> package_aide_installed.xml
> service_telnetd_disabled.xml
> sysconfig_networking_bootproto_ifcfg.xml
> system_info_architecture_x86_64.xml
> system_info_architecture_x86.xml
> umask_for_daemons.xml
> userowner_shadow_file.xml
```

So please apply the above requested change also to the remaining 18 OVAL checks listed above yet. Otherwise the change looks good to me.

Thank you for the patch!
Jan

**Comment by redhatrises** [comment]
@iankko Thanks for the review. My script must have not been complete, so it missed those. This should be fixed now.

**Comment by iankko** [comment]
@redhatrises 
> @iankko Thanks for the review. My script must have not been complete, so it missed those. This should be fixed now.

Thanks, verified the updated version is fine (& still works properly on all three products for both XCCDF & DS content versions). ACK.

**Pull request merged**
