### PR TITLE
Ticket#932 use sysctl net xcc df values

### PR DESCRIPTION
**Pull request by GautamSatish**
These are the changes for issue #932 .

The following are the changes:

Modified the create modules to use the updated CSV file and templates.
	>modified:   ../../shared/oval/templates/create_sysctl_checks.py
	>modified:   ../../shared/remediations/bash/templates/create_sysctl_bash.py

New template files which use the XCCDF:value field:
	>new file:   input/oval/templates/template_sysctl_runtime_var
	>new file:   input/oval/templates/template_sysctl_static_var
	>new file:   input/remediations/bash/templates/template_sysctl_var

Modified the SYSCTL CSV file:
	>modified:   input/oval/templates/sysctl_values.csv

Retained a copy of the original SYSCTL CSV file:
	>new file:   input/oval/templates/sysctl_values_orig.csv

Corrected an input in this file:
	>modified:   input/xccdf/system/network/kernel.xml

Corrected the path to sysctl in this template file:
	>modified:   input/remediations/bash/templates/template_sysctl

The rest of the files are auto-generated.

PS: I have not made the documentation changes WRT the rule names in this PR. I felt there are too many changes for a single PR. I will raise a new PR for the changes to rule names and profiles using them.

### CODE REVIEW

**Comment by iankko** [comment]
@openscap-jenkins [ok to test]

**Comment by iankko** [comment]
The reported Jenkins failure is unrelated to the code changes performed within this PR. Will review this one (the Debian/8 missing oval:ssg:def:138 error to be corrected within different PR soon).

**Comment by GautamSatish** [comment]
I was getting a Debian error similar to this in my local "make jenkins" as well. Since the associated file and error didn't appear related, I assumed it would go away when the build was done here but looks like something is breaking. I will check this out.

I apologize for the confusion.

**Comment by iankko** [comment]
@GautamSatish 
> I was getting a Debian error similar to this in my local "make jenkins" as well. Since the associated file and error didn't appear related, I assumed it would go away when the build was done here but looks like something is breaking. I will check this out.
> 
I apologize for the confusion.

No worries. That failing ```Debian/8 make validate``` issue is not related to your PR (we know about it for 1-2 days already, just didn't find the time slot to get it corrected yet).

 Anyway, it should be taken care now for in:
&nbsp; &nbsp; https://github.com/OpenSCAP/scap-security-guide/pull/950

**Comment by redhatrises** [comment]
@GautamSatish Do these changes also apply to RHEL7 as well?

**Comment by iankko** [comment]
This looks good to me. Tested on RHEL-6 with this change being applied and the various ```sysctl``` remediations seem still to be working fine (after performing the remediation, the modified ovals are called to do a new scan, and these ovals return correct results).

I have used the following pretty horribly looking snippet to find the ```sysctl_``` OVAL files needing changing this:
```
for i in $(grep -rH 'should be set to \"' sysctl_* | cut -d ':' -f 1); do \
i=$(basename $i .xml) && cd ../xccdf && grep -rHn "<oval id=\"$i" * && cd ../oval; done
```
Having the above snippet called on this change being applied from the ```RHEL/6/input/oval``` directory it prints out the following:
```
$ cd RHEL/6/input/oval/
oval]$ for i in $(grep -rH 'should be set to \"' sysctl_* | cut -d ':' -f 1); do i=$(basename $i .xml) && cd ../xccdf && grep -rHn "<oval id=\"$i" * && cd ../oval; done
system/network/ipv6.xml:137:<oval id="sysctl_net_ipv6_conf_default_accept_ra" value="sysctl_net_ipv6_conf_default_accept_ra_value" />
system/network/ipv6.xml:153:<oval id="sysctl_net_ipv6_conf_default_accept_redirects" value="sysctl_net_ipv6_conf_default_accept_redirects_value" />
```
Thus the ```sysctl_net_ipv6_conf_default_accept_ra``` and ```sysctl_net_ipv6_conf_default_accept_redirects``` ```RHEL/6``` OVAL checks should be updated yet with the very same change.

Running the above snippet for ```RHEL/7``` content (from ```RHEL/7/input/oval``` folder I get the following):
```
$ cd scap-security-guide/RHEL/7/input/oval/
$ for i in $(grep -rH 'should be set to \"' sysctl_* | cut -d ':' -f 1); do i=$(basename $i .xml) && cd ../xccdf && grep -rHn "<oval id=\"$i" * && cd ../oval; done
system/network/kernel.xml:238:<oval id="sysctl_net_ipv4_conf_all_accept_redirects" value="sysctl_net_ipv4_conf_all_accept_redirects_value" />
system/network/kernel.xml:222:<oval id="sysctl_net_ipv4_conf_all_accept_source_route" value="sysctl_net_ipv4_conf_all_accept_source_route_value" />
system/network/kernel.xml:274:<oval id="sysctl_net_ipv4_conf_all_log_martians" value="sysctl_net_ipv4_conf_all_log_martians_value" />
system/network/kernel.xml:414:<oval id="sysctl_net_ipv4_conf_all_rp_filter" value="sysctl_net_ipv4_conf_all_rp_filter_value" />
system/network/kernel.xml:256:<oval id="sysctl_net_ipv4_conf_all_secure_redirects" value="sysctl_net_ipv4_conf_all_secure_redirects_value" />
system/network/kernel.xml:43:<oval id="sysctl_net_ipv4_conf_all_send_redirects" />
system/network/kernel.xml:324:<oval id="sysctl_net_ipv4_conf_default_accept_redirects" />
system/network/kernel.xml:292:<oval id="sysctl_net_ipv4_conf_default_log_martians" value="sysctl_net_ipv4_conf_default_log_martians_value" />
system/network/kernel.xml:433:<oval id="sysctl_net_ipv4_conf_default_rp_filter" value="sysctl_net_ipv4_conf_default_rp_filter_value" />
system/network/kernel.xml:341:<oval id="sysctl_net_ipv4_conf_default_secure_redirects" value="sysctl_net_ipv4_conf_default_secure_redirects_value" />
system/network/kernel.xml:26:<oval id="sysctl_net_ipv4_conf_default_send_redirects" />
system/network/kernel.xml:358:<oval id="sysctl_net_ipv4_icmp_echo_ignore_broadcasts" value="sysctl_net_ipv4_icmp_echo_ignore_broadcasts_value" />
system/network/kernel.xml:374:<oval id="sysctl_net_ipv4_icmp_ignore_bogus_error_responses" value="sysctl_net_ipv4_icmp_ignore_bogus_error_responses_value" />
system/network/kernel.xml:61:<oval id="sysctl_net_ipv4_ip_forward" />
system/network/kernel.xml:395:<oval id="sysctl_net_ipv4_tcp_syncookies" value="sysctl_net_ipv4_tcp_syncookies_value" />
system/network/ipv6.xml:154:<oval id="sysctl_net_ipv6_conf_all_accept_ra" value="sysctl_net_ipv6_conf_all_accept_ra_value" />
system/network/ipv6.xml:187:<oval id="sysctl_net_ipv6_conf_all_accept_redirects" value="sysctl_net_ipv6_conf_all_accept_redirects_value" />
system/network/ipv6.xml:48:<oval id="sysctl_net_ipv6_conf_all_disable_ipv6" />
system/network/ipv6.xml:171:<oval id="sysctl_net_ipv6_conf_default_accept_ra" value="sysctl_net_ipv6_conf_default_accept_ra_value" />
system/network/ipv6.xml:203:<oval id="sysctl_net_ipv6_conf_default_accept_redirects" value="sysctl_net_ipv6_conf_default_accept_redirects_value" />
```

So Gabe is right (@redhatrises thanks for that catch!) those files will need to be updated (in some of the upcoming PRs) too. 

I will merge this one (the scope of the changes performed in this PR is pretty enough already). The ```RHEL/6``` ipv6 related OVAL changes and ```RHEL/7``` related sysctl OVAL changes can be performed later (easier to review more smaller PRs, than one big one).

ACK from me for merging of this. @GautamSatish Thank you for the changes!

**Comment by GautamSatish** [comment]
Hello, Thank you for merging this. I will update the ipv6 related changes and the RHEL7 changes in smaller PRs.

**Pull request merged**
