### PR TITLE
Update SUSE11 and 12 XCCDF content to use shared XCCDF content

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by yuumasato** [comment]
Some rules went missing, like `no_shelllogin_for_systemaccounts and` `securetty_root_login_console_only`. 
I don't have a complete list though.

**Comment by redhatrises** [comment]
None of those rules are enabled in the profiles. With this move, the validation has to be done to verify that those rules apply to SUSE products now whereas that validation was not done before.

**Comment by mpreisler** [comment]
ACK

**Comment by mpreisler** [comment]
@redhatrises We should implement some way how we can specialize parts of the shared XCCDF for RHEL or SUSE. Some parts of the descriptions will be RHEL only otherwise. We should probably just use the `XSLT` `if` elements and check for `prodtype`.

**Comment by redhatrises** [comment]
> We should probably just use the XSLT if elements and check for prodtype.

@mpreisler I believe that this is already done by adding `sle11` or `sle12` to `prodtype`. See https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/xccdf/system/permissions/files.xml#L147 for an example.

**Pull request merged**
