### PR TITLE
Remove usage of templates/static/ directory

### PR DESCRIPTION
**Pull request by redhatrises**
- Removes the usage of the templates/static/ directory to remove confusion
  around its existence (multiple feedback on this). This puts the content back
  into their appropriate remediation and oval content directories.

### CODE REVIEW

**Comment by shawndwells** [comment]
Huuuuge +1. Long needed, thank you!!

**Comment by redhatrises** [comment]
Bump for review. This is holding up future PRs.

**Comment by shawndwells** [comment]
Looked good to me. Didn't merge earlier because Jenkins was still building.

Don't have access to GH right now to merge, but ack from me. 

Shawn Wells

**Comment by mpreisler** [comment]
This needs a thorough review because it's a huge change. I will try to review later today. I like the change itself but might ask for some README.md files around to make this easier on contributors. The templates should link to the normal "static" folders via README.md and the static should explain when to use templates instead and link to the templates README.md. Either that or we put both into developer docs.

**Comment by redhatrises** [comment]
agreed @mpreisler. I am planning on updating the docs after I have finished the directory structure/naming updates which I am planning on putting in the developer docs.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
