### PR TITLE
ansible: dconf_gnome_disable_*

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by redhatrises** [comment]
You know @shawndwells if you made this into a template.... It would be easier.

**Comment by shawndwells** [comment]
probably. but was quicker for me to hack it out like this.

**Comment by shawndwells** [comment]
mostly self serving. have some events next week that need better ansible coverage.... so trying to get these scripts in

**Comment by mpreisler** [comment]
OK, I don't like that it's not templated but I guess we can merge it now and template later so I am willing to compromise here. I think we should really strive to template everything though.

ACK

**Pull request merged**
