### PR TITLE
Update RHEL 6 STIG Reference to V1R18

### LINKED ISSUE #2757: Update DISA STIG for RHEL 6 to V1R18
#### Description of problem:
`shared/references/disa-stig-rhel6-v1r16-xccdf-manual.xml`
should be v1r18

#### SCAP Security Guide Version:
0.1.38

#### Operating System Version:
RHEL 6.9

#### Steps to Reproduce:

1.  N/A

#### Actual Results:
ssg aligns with disa

#### Expected Results:
ssg behind on stig revision

### PR DESCRIPTION
**Pull request by jamescassell**
#### Description:

- Update to latest DISA STIG Reference for RHEL 6

#### Rationale:

- it's good to have the latest reference

- Fixes #2757 #2759 

I had trouble regenerating the stig_overlay.xml, so I'll leave that for someone else / later.

### CODE REVIEW

**Comment by redhatrises** [comment]
@jamescassell it is preferable.

**Comment by shawndwells** [comment]
@redhatrises is right. SSG never referenced v1r17, jumped directly to v1r18. Helps keep the code repo clean.

**Comment by jamescassell** [comment]
I disagree, but it's your project, so I've updated the PR accordingly.  Original commits available here: https://github.com/jamescassell/scap-security-guide/commits/stig-rhel6-v1r18-v1

**Comment by redhatrises** [comment]
Ack. Thanks @jamescassell

**Pull request merged**
