### PR TITLE
Issue #1886: Add a remediation for rsyslog_remote_loghost

### PR DESCRIPTION
**Pull request by jan-cerny**
The remote host address will be specified by a value, so
the users can customize it by the IP or URI of the server.
If they don't so, remediation won't be performed.

### CODE REVIEW

**Comment by mpreisler** [comment]
```
File '/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-fedora23/build/ssg-rhel6-ds.xml' line 43705: Element '{http://checklists.nist.gov/xccdf/1.2}sub', attribute 'idref': 'dangling reference to rsyslog_remote_loghost_address!' is not a valid value of the atomic type 'xs:NCName'.
File '/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-fedora23/build/ssg-rhel6-ds.xml' line 43705: Element '{http://checklists.nist.gov/xccdf/1.2}sub', attribute 'idref': Warning: No precomputed value available, the value was either invalid or something strange happend.
```

The value also has to be added fro RHEL6.

**Comment by jan-cerny** [comment]
@mpreisler OK, thank you for investigating, I will fix it.

**Comment by jan-cerny** [comment]
I have added the value also for RHEL6.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
