### PR TITLE
Added SSH checks for explicitely disable ssh tunneling and VPN capabilities

### PR DESCRIPTION
**Pull request by savon-noir**
Added SSH checks for explicitely disable ssh tunneling and VPN capabilities:
    - sshd_disable_tcpfwd (AllowTcpForwarding)
    - sshd_disable_x11fwd (X11Forwarding)
    - sshd_disable_tunnel (PermitTunnel)

### CODE REVIEW

**Comment by savon-noir** [comment]
hello. comments taken into account in last commit of pull requests. I took the new ssh.xml from the last published version.

**Comment by redhatrises** [comment]
@savon-noir please update your branch and fix the merge conflicts.

**Comment by redhatrises** [comment]
@savon-noir since the OVAL checks support both `RHEL/6` and `RHEL/7`, please move the OVAL checks to the `shared/oval` directory and create soft links in the appropriate directories.

For example:
```
mv RHEL/6/input/checks/sshd_disable_tcpfwd.xml shared/oval
ln -s shared/oval/sshd_disable_tcpfwd.xml RHEL/6/input/checks/sshd_disable_tcpfwd.xml
ln -s shared/oval/sshd_disable_tcpfwd.xml RHEL/7/input/checks/sshd_disable_tcpfwd.xml
```

**Comment by savon-noir** [comment]
done

**Comment by redhatrises** [comment]
@savon-noir looks like the merge conflicts need to be fixed. There are a bunch of these git diff merge issues in the commit files.

```
+<<<<<<< HEAD
+<ident cce="26555-3" />
+<oval id="sshd_use_approved_ciphers" />
+<ref nist="AC-3,AC-17(2),SI-7,IA-5(1)(c),IA-7" disa="803,1144,1145,1146" />
+=======
<ident cce="27051-2" /> 	<ident cce="27051-2" />
<oval id="sshd_use_approved_ciphers" /> 	<oval id="sshd_use_approved_ciphers" />
<ref nist="AC-3,AC-17(2),AU-10(5),IA-5(1)(c),IA-7" disa="" /> 	<ref nist="AC-3,AC-17(2),AU-10(5),IA-5(1)(c),IA-7" disa="" />
+>>>>>>> master
```

**Comment by savon-noir** [comment]
:( i need to check this out then..

**Comment by mpreisler** [comment]
No activity and massive merge conflicts, closing... Please open a new PR if necessary.

**Pull request closed without merging**
