### PR TITLE
Added "anssi" profile to the RHEL7 product

### PR DESCRIPTION
**Pull request by mpreisler**
#### Description:

There are only 3 rules for now but this will enable us to collaborate on
the profile.

#### Rationale:

ANSSI is requested more and more by our users.

### CODE REVIEW

**Comment by redhatrises** [comment]
@mpreisler there are 4 different profiles for Debian and Ubuntu. Should we also account for that here rather than just having a single ANSSI profile?

**Comment by mpreisler** [comment]
@redhatrises good point, I think we should, I wasn't aware of this. I will adapt this PR accordingly.

**Comment by redhatrises** [comment]
Looks good for starters. More to come I am sure. Ack.

**Comment by shawndwells** [comment]
(ties to https://bugzilla.redhat.com/show_bug.cgi?id=1497415)

**Pull request merged**
