### PR TITLE
Disable overriding of OVAL_5.11 by OVAL_5.10

### PR DESCRIPTION
**Pull request by ybznek**
Blocked by https://github.com/OpenSCAP/scap-security-guide/pull/1659 (shared commits). It will need rebase.

It should fail of build rather than do some unwanted overriding.

### CODE REVIEW

**Comment by mpreisler** [comment]
Needs rebase.

**Comment by ybznek** [comment]
test this please (need test jenkins)

**Comment by ybznek** [comment]
Rebased

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
