### PR TITLE
Debian 8 enhancements

### PR DESCRIPTION
**Pull request by pthierry38**
* Add better guide production (references and remediation scripts accessible).
* Add per-profile guide generation (based on RHEL Makefile)
* Add complete support for OVAL 5.11
* Add few tests for basic services s.a. auditd, cron, etc.

### CODE REVIEW

**Comment by iankko** [comment]
[add to whitelist]

**Comment by isimluk** [comment]
Please avoid merge commits in pull-requests. Always use `git rebase`.

**Comment by pthierry38** [comment]
Ok. I will avoid this next time.

**Comment by isimluk** [comment]
Thanks! :-)

**Comment by pthierry38** [comment]
ok I take a look on this with @electrosenpai this morning.

**Comment by pthierry38** [comment]
We have tested a make validate without any errors on Debian with oscap 1.2.7 and cannot reproduce the same error as Jenkins. Although, we can't launch make with default target due to rpm call. We try to check it on a Fedora VM to validate the behavior of our work.

**Comment by pthierry38** [comment]
@redhatrises and others :
We have tried, with @electrosenpai to build our ssg (branch debian_8) on Fedora 23. Make validate is working well and the last commands of the jenkins job are clean. We are not able to reproduce the error and have no access to RHEL image :-/ If you have any ideas ?

**Comment by electrosenpai** [comment]
We tried on : 
```
Linux bjorn 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

and it's working :

```
make
[...]
+ cd /root/scap-security-guide/rpmbuild/BUILD
+ rm -rf scap-security-guide-0.1.26.1.201512101318GITf79624d
+ exit 0
```

**Comment by iankko** [comment]
@electrosenpai 
> We tried on : 
```
Linux bjorn 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
> 
and it's working :
>
```
make
[...]
+ cd /root/scap-security-guide/rpmbuild/BUILD
+ rm -rf scap-security-guide-0.1.26.1.201512101318GITf79624d
+ exit 0
```

It's working with the newer version of the OpenSCAP probably have Debian CPE definition included in it's own database. This can be verified e.g. by running:

```oscap -V | grep cpe``` on Debian system (if that output shows ```cpe:/o:debianproject:debian:8``` among others already, that internal CPE definition would be used instead of OVAL definition from ```
scap-security-guide/Debian/8/input/oval/installed_OS_is_debian8.xml```. But on systems where this CPE won't be defined yet (like e.g. on RHEL-6 system the above Jenkins is failing at) the ```installed_OS_is_debian.xml``` definition will be used instead of that CPE to determine, if the corresponding benchmark is applicable to that platform or not.

And having had a look at that ```installed_OS_is_debian8.xml``` definition, there are multiple issues currently with that one:
* invalid platform specifier 'Debian8' (now). Should be ```Debian 8``` (that's what's actually defined in ```combineovals.py``` script),
* missing ```test_debian8``` test (OVAL object with that ID was used instead of that one).

The attached patch will fix this issue: 
[0001-BugFix-Debian-8-Fix-installed_OS_is_debian8-OVAL-def.txt](https://github.com/OpenSCAP/scap-security-guide/files/58238/0001-BugFix-Debian-8-Fix-installed_OS_is_debian8-OVAL-def.txt)

<b>Note:</b> It will fix the failing ```make``` target on systems not having Debian 8 CPE defined yet. But not ```make validate``` issue too (another patch will be necessary for that one).

**Comment by iankko** [comment]
I am going to merge this one manually (applying the last patch to get ```make``` working on RHEL-6 system [and other systems not having Debian 8 CPE definition yet]). The ```make validate``` issue will be fixed in some of the future PRs.

**Comment by pthierry38** [comment]
Thanks @iankko  for this help. I've applied your patch on the head of my debian_8 branch. I let you finish the integration for the validate issue.

**Comment by iankko** [comment]
@pthierry38 
The ```make validate``` fix should be now taken care by: 
&nsbp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/pull/910

See mainly the first commit of that changeset to see what was necessary to get changed (the issues were mainly in having XCCDF rules referencing invalid OVAL checks, have unreferenced OVAL checks, or XCCDF rules having inconsistent / invalid names with OVAL checks). Though the IDs can be changed, when creating the OVAL checks from the templates, the helper script define the format of the ID (example ```service_ntpd_enabled```). Since different ID was used in the XCCDF, there was:
* one missing OVAL check (the one for the XCDCF ID used),
* and one remaining / un-used OVAL check (created by the template helper *.py script)

See the [first commit](https://github.com/iankko/scap-security-guide/commit/daed11ee5332ed3c6a8d233f1f481cf39ddaecec ) for further details.

**Pull request merged**
