### PR TITLE
Remove xccdf2csv-stig module and transforms

### PR DESCRIPTION
**Pull request by cipherboy**
From what I can tell, this code is not used as part of the build system or the test suite. Further, the code uses `lxml.etree` whereas everywhere else uses `xml.etree.ElementTree`.

### CODE REVIEW

**Comment by cipherboy** [comment]
If anyone is using this, I'll close the pull request and replace it with one commenting the use case and merging the transforms into one in `/shared` (they're all identical).

**Comment by redhatrises** [comment]
This is actually a valuable tool for those who use Excel (for better or for worse). Not to be done in this PR, but it would be great to update.

**Comment by cipherboy** [comment]
@redhatrises Okay, I'll keep it and update in a separate PR. Why is it under "transforms" though -- should it be a "utils" instead? Perhaps moving one copy to "utils" should be part of @mpreisler's PR #2945.

**Comment by mpreisler** [comment]
> @redhatrises Okay, I'll keep it and update in a separate PR. Why is it under "transforms" though -- should it be a "utils" instead? Perhaps moving one copy to "utils" should be part of @mpreisler's PR #2945.

Yeah, I agree, it shouldn't be in transforms

**Comment by redhatrises** [comment]
@cipherboy I think it was placed there by accident.

**Comment by cipherboy** [comment]
Okay, based on feedback, I'm closing this.

**Pull request closed without merging**
