### PR TITLE
Build shorthand.xml as non-phony target

### PR DESCRIPTION
**Pull request by isimluk**
This improves performance of `make jenkins`.

### CODE REVIEW

**Comment by mpreisler** [comment]
Simon for president! Thanks a lot for this work, this is something SSG sorely needs for all the targets.

**Comment by iankko** [comment]
[re-test this please]

**Comment by isimluk** [comment]
Martin you can thank me later. My plan is to bring `time make jenkins` from 10 minutes on my laptop to under 2 minutes. I think that is reasonable.

**Comment by isimluk** [comment]
Anybody up for review. I have more cleanups to come. I just do not want to create a single biggest pull-request.

**Comment by jan-cerny** [comment]
lgtm, great, thank you!

**Comment by isimluk** [comment]
[re-test this please]

**Comment by isimluk** [comment]
Fixed @jan-cerny. Can we merge it now?

**Comment by jan-cerny** [comment]
@isimluk I think we can.

**Comment by isimluk** [comment]
Perfect! Thanks a lot!

**Pull request merged**
