### PR TITLE
[bugfix][RHEL/6] Fix ldap client TLS checks

### PR DESCRIPTION
**Pull request by redhatrises**
- Fix pam_ldap.conf TLS XCCDF and OVAL checks in RHEL/6
- Remove ldap_client_pam_ldap_present.xml

### CODE REVIEW

**Comment by redhatrises** [comment]
ok to test

**Comment by redhatrises** [comment]
Jenkins, ok to test.

**Comment by iankko** [comment]
@openscap-jenkins 
> Can one of the admins verify this patch?

Verified ```make validate``` target works for RHEL-6 content after this change on both:
* RHEL-6, and
* Fedora 22

systems (IOW in both cases -- with older && newer openscap versions).

Will review the SSG semantic changes of the touched files yet.

**Comment by iankko** [comment]
Change semantic review -- looks good to me. ACK.

**Pull request merged**
