### PR TITLE
[BugFix] [Various benchmarks] Fixes for issue #1225 and #1226

### PR DESCRIPTION
**Pull request by iankko**
Start generating the content of the ```<xccdf:metadata>``` benchmark element in various benchmark dynamically:
* obtain the ```<dc:publisher>``` and ```<dc:creator>``` values from the newly introduced ```ssg-project-name``` shared ```<xsl:variable```,
* obtain ```<dc:contributor>``` element values from the content of the currently present ```Contributors.md``` file,
* finally obtain ```<dc:source>``` value from the value of the ```ssg-benchmark-latest-uri``` shared ```<xsl:variable```

Fixes: https://github.com/OpenSCAP/scap-security-guide/issues/1226
Fixes: https://github.com/OpenSCAP/scap-security-guide/issues/1225

For the count of the commits within this PR - the changes are basically always the same, but in different benchmark (have split them into separate commits for [hopefully] better readability).

Please review.

Thank you, Jan

### CODE REVIEW

**Comment by iankko** [comment]
Looks like SSG Jenkins is currently stuck on some Jenkins / Hudson plugins.GithubAuthenticationToken exception:
* https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/label=node-el7/207/consoleFull
* https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/label=node-fedora23/207/console
* https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/label=node-el6-openscap-new/207/console

This is the issue of Jenkins SSG CI infrastructure (not related to changes in this PR).

**Comment by iankko** [comment]
@mpreisler or @redhatrises Could you hopefully review this one? Would be truly appreciated.

Thanks, Jan

**Comment by mpreisler** [comment]
ACK

**Comment by iankko** [comment]
@mpreisler 
Thanks for the review && ACK, Martin! (having this one fixed is big step towards RHEL/6 && RHEL/7 SSG content ScapVal passing effort).

**Pull request merged**
