### PR TITLE
Moved executables not used by the build system to misc, deleted unuse…

### PR DESCRIPTION
**Pull request by mpreisler**
…d code

Pretty minor stuff.

### CODE REVIEW

**Comment by redhatrises** [comment]
Nack on moving to misc. Let's keep this in utils. I want to remove `shared/misc` anyway.

**Comment by mpreisler** [comment]
@redhatrises utils has build system stuff, misc has other stuff. We can change the names but we should clearly separate them.

**Comment by redhatrises** [comment]
@mpreisler are any of the utils useful that have been deleted?

**Comment by redhatrises** [comment]
I think then that this PR should be closed and a new one opened that moves tools in their respective folders per irc discussion.

**Comment by mpreisler** [comment]
> @mpreisler are any of the utils useful that have been deleted?

The verify CCEs are not useful, they have been replaced by @cipherboy 's work and we now validate CCEs when building. No need to have an extra tool for it. Plus the verify-cce script is broken and using lxml.

**Comment by cipherboy** [comment]
@mpreisler / @redhatrises 

I agree with the executable move change.

With respect to removing `verify-cce.py`, if it were working, I'd suggest keeping it as it has different functionality than what is in the build system. However, it is broken, requires several changes to make it work, and it is not used as part of the build system. Therefore I'm inclined to remove it with a chance at replacing it with a working version as part of a later PR.

**Comment by redhatrises** [comment]
That's fine. I still think that we should close this PR and open a new one that refactors all the scripts in `./build-scripts` and either `shared/utils` or `./utils`. Get it all done at once.

**Pull request merged**
