### PR TITLE
update enable_dconf_user_profile to check if dconf installed

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells why all the extra whitespace?

**Comment by shawndwells** [comment]
@redhatrises Readability, but I can drop if a problem (we never really did make coding standards to speak of)

**Comment by redhatrises** [comment]
@shawndwells not necessarily a problem. It is just inconsistent with most of the OVAL in the fact that we don't typically have whitespace around `<definition />` or `<criteria />` elements.

**Comment by shawndwells** [comment]
@redhatrises fiiiinnnnneeee I got rid of the pretty spaces

**Comment by redhatrises** [comment]
[retest this please]

**Comment by redhatrises** [comment]
> @redhatrises fiiiinnnnneeee I got rid of the pretty spaces

hahaha.... ack.

**Pull request merged**
