### PR TITLE
[bugfix][RHEL/7] Various RHEL/7 STIG fixes

### PR DESCRIPTION
**Pull request by redhatrises**
- Add OVAL to check if sssd.conf exists; if not, sssd checks should pass as sssd
  is most likely not in use.
- Fix errors in sssd XCCDF
- Fix install_antivirus XCCDF severity level
- Ignore install_antivirus XCCDF Rule in STIG check as duplicate of McAfee A/V
- Add install_hids OVAL content
- Add remote/removable filesystem content to STIG
- *Remove* umask_for_deamons checks as the content only applies to init systems and *not* systemd systems

### CODE REVIEW

**Comment by mpreisler** [comment]
Shouldn't we be checking that sssd is not installed or not enabled rather than just that the sssd.conf is missing? Do users often install sssd and not configure it?

**Comment by redhatrises** [comment]
> Shouldn't we be checking that sssd is not installed or not enabled rather than just that the sssd.conf is missing?

I don't mind adding a check for it being installed/enabled if we should check for it, but we should also check if sssd.conf exists. Mainly because sssd.conf is not added by the rpm. It is either manually added or by script.

> Do users often install sssd and not configure it?

@mpreisler that is a possibility/reality for some users. Plus, some packages might get installed that have a dependency on sssd even if sssd is never configured/enabled.

What about checking for both the service being enabled and that sssd.conf exists?

**Comment by mpreisler** [comment]
> @mpreisler that is a possibility/reality for some users. Plus, some packages might get installed that have a dependency on sssd even if sssd is never configured/enabled.
> 
> What about checking for both the service being enabled and that sssd.conf exists?

@redhatrises sorry for the delay, I was OOO. Yeah, this makes sense to me.

**Comment by redhatrises** [comment]
>> @mpreisler that is a possibility/reality for some users. Plus, some packages might get installed that have a dependency on sssd even if sssd is never configured/enabled.
>> 
>> What about checking for both the service being enabled and that sssd.conf exists?

> @redhatrises sorry for the delay, I was OOO. Yeah, this makes sense to me.

@mpreisler no worries. Added the changes. Also found some other issues that needed to be fixed/enhanced.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
