### PR TITLE
Add some rules for protection of data in transit and adequate capacity to ensure availabity for  HIPAA

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Add rules for protection of data in transit
- Add rules for adequate capacity to ensure availability

#### Rationale:

- Protection of data in transit
  - rsh and telnet don't provide confidentiality or integrity.
  - ssh provides protection for data in transit.
- Adequate capacity to ensure availability
  - Store audit logs in separate partition
  - Configure audit actions for low storage
  - Enable rsyslog and remote storage

### CODE REVIEW

**Comment by shawndwells** [comment]
manually merged conflicts. should be good to merge PR once jenkins finishes.

**Comment by redhatrises** [comment]
@shawndwells could you do a rebase so that we don't have commit d8a556a?

**Comment by shawndwells** [comment]
On 2/2/18 6:45 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> could you do a rebase so
> that we don't have commit d8a556a
> <https://github.com/OpenSCAP/scap-security-guide/commit/d8a556ada13208f7fe714cb695b4b19431800ce2>?
No? Not my pull request.

**Comment by yuumasato** [comment]
Lol, rebased. I don't have idea how that happened.

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
There was some garbage in one of the commits. Fixed and ready for review.

**Comment by mpreisler** [comment]
Great stuff! ACK

**Pull request merged**
