### PR TITLE
[ansible] security_patches_up_to_date

### PR DESCRIPTION
**Pull request by mpreisler**

### CODE REVIEW

**Comment by redhatrises** [comment]
Wanna add the flags to this as well?

**Comment by mpreisler** [comment]
@redhatrises added the reboot flag, no clue about the other flags. I wish I could fix this proper and use package_command in the bash fix but there is no support for update in the command.

**Comment by redhatrises** [comment]
`complexity=low`
`disruption=high`
`strategy=patch`

**Comment by mpreisler** [comment]
> complexity=low
> disruption=high
> strategy=patch

aye aye, sir

**Comment by redhatrises** [comment]
hahaha..... ack

**Pull request merged**
