### PR TITLE
developer note on audit_rules_privileged_commands & remove from ospp profile

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells I think we should put this in the XCCDF description itself (maybe as a warning?). I would also expand the language to use somthing like:
`or for security profiles/guides that do not require individual audit rules broken out into separate rules`

**Comment by shawndwells** [comment]
OK. I was trying to be nice :) Will add it.

**Comment by dahaic** [comment]
Jenkins test this please.

**Comment by shawndwells** [comment]
don't have this branch anymore - closing

**Pull request closed without merging**
