### PR TITLE
Add platform script tag

### PR DESCRIPTION
**Pull request by redhatrises**
- Add to Chromium, Firefox, and JRE remediation scripts

### CODE REVIEW

**Comment by redhatrises** [comment]
The #768 PR should be merged before this one.

**Comment by iankko** [comment]
Taking this one for review (as it depends on 768 one).

**Comment by iankko** [comment]
Observation: This PR is "only" adding platform script tags to Chromium, Firefox, and JRE remediation scripts (there has been no other code changes) => It's enough to compare if count of previously merged remediation scripts == count of currently merged remediation scripts after the change for these three products.

Therefore comparison:
* First check the state before the ```shared/``` remediations functionality has been rewritten:
```
$ git checkout 3aa03f045e81605efc4021984d1c1cdc64cabaf3
..
$ ls Chromium/input/fixes/bash/*.sh | wc -l
37
$ ls Firefox/input/fixes/bash/*.sh | wc -l
28
$ ls JRE/input/fixes/bash/*.sh | wc -l
10
```

Comparing that with current state:
```
$ git checkout master
$ cd scap-security-guide/Chromium/
$ make | grep remediation
../shared/transforms/combinefixes.py ../config chromium input/fixes/bash output/bash-remediations.xml

Notification: Merged 0 remediation scripts into XML document.
xsltproc -stringparam fixes "../output/bash-remediations.xml" -o output/unlinked-chromium-xccdf.xml transforms/xccdf-addfixes.xslt output/unlinked-chromium-xccdf.xml
..
$ cd Firefox/
 make | grep remediation
../shared/transforms/combinefixes.py ../config firefox input/fixes/bash output/bash-remediations.xml

Notification: Merged 0 remediation scripts into XML document.
xsltproc -stringparam fixes "../output/bash-remediations.xml" -o output/unlinked-firefox-xccdf.xml transforms/xccdf-addfixes.xslt output/unlinked-firefox-xccdf.xml
..
$ cd JRE/
$ make | grep remediation
../shared/transforms/combinefixes.py ../config jre input/fixes/bash output/bash-remediations.xml

Notification: Merged 0 remediation scripts into XML document.
```

=> There's is some issue with this proposal. And the counter not being incremented doesn't seem to be the reason, since have checked, e.g. generated ```output/ssg-jre-xccdf.xml``` with the current ```master``` and there truly isn't any ```<fix>..</fix>``` element in that XCCDF.

@redhatrises Can you double-check what's wrong this this one?

**Comment by iankko** [comment]
@redhatrises 
Sorry, ignore my previous commit (that comparison was actually on a branch without your changes from this PR merged yet). Below are updated results:
```
$ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
..
$ cd Chromium/
..
$ make | grep remediation
../shared/transforms/combinefixes.py ../config chromium input/fixes/bash output/bash-remediations.xml

Notification: Merged 37 remediation scripts into XML document.
..
$ cd Firefox/
..
$ make | grep remediation
../shared/transforms/combinefixes.py ../config firefox input/fixes/bash output/bash-remediations.xml

Notification: Merged 28 remediation scripts into XML document.
..
$ cd JRE/
..
$ make | grep remed
../shared/transforms/combinefixes.py ../config jre input/fixes/bash output/bash-remediations.xml

Notification: Merged 10 remediation scripts into XML document.
```

So compared with the "previous state" part of the previous commit
( https://github.com/OpenSCAP/scap-security-guide/pull/769#issuecomment-145535125 )
it's visible this change is safe (the count of remediation scripts before the rewrite and after matches for different products).

Sorry again, mistake on my side (using two different git clone copies & one of them wasn't containing changes from this PR yet).

ACK for merging this one from me (see the stats in previous commit and this one).

**Pull request merged**
