### PR TITLE
dconf_gnome_screensaver_* ansible scripts

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells update dconf_gnome_screensaver_lock_enabled to have (ansible-populate var_screensaver_lock_delay)

**Comment by shawndwells** [comment]
@redhatrises that's not in the XCCDF

`````
<Rule id="dconf_gnome_screensaver_lock_enabled" severity="medium" prodtype="rhel7">
<title>Enable GNOME3 Screensaver Lock After Idle Period</title>
<description>
To activate locking of the screensaver in the GNOME3 desktop when it is activated,
add or set <tt>lock-enabled</tt> to <tt>true</tt> in
<tt>/etc/dconf/db/local.d/00-security-settings</tt>. For example:
<pre>[org/gnome/desktop/screensaver]
lock-enabled=true
</pre>
Once the settings have been added, add a lock to
<tt>/etc/dconf/db/local.d/locks/00-security-settings-lock</tt> to prevent user modification.
For example:
<pre>/org/gnome/desktop/screensaver/lock-enabled</pre>
After the settings have been set, run <tt>dconf update</tt>.
</description>
<ocil clause="screensaver locking is not enabled and/or has not been set or configured correctly">
To check the status of the idle screen lock activation, run the following command:
<pre>$ gsettings get org.gnome.desktop.screensaver lock-enabled</pre>
If properly configured, the output should be <tt>true</tt>.
To ensure that users cannot change how long until the the screensaver locks, run the following:
<pre>$ grep lock-enabled /etc/dconf/db/local.d/locks/*</pre>
If properly configured, the output for <tt>lock-enabled</tt> should be <tt>/org/gnome/desktop/screensaver/lock-enabled</tt>
</ocil>
<rationale>
A session lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity
of the information system but does not want to logout because of the temporary nature of the absense.
</rationale>
<platform idref="cpe:/a:machine" />
<ident prodtype="rhel7" cce="80112-6" />
<oval id="dconf_gnome_screensaver_lock_enabled" />
<ref prodtype="rhel7" stigid="010060" />
<ref nist="AC-11(b)" disa="56" pcidss="Req-8.1.8" ossrg="SRG-OS-000028-GPOS-00009,OS-SRG-000030-GPOS-00011" cjis="5.5.5" cui="3.1.10" />
</Rule>
`````

**Comment by redhatrises** [comment]
PR very very shortly changing that.

**Comment by shawndwells** [comment]
Self nack. Noticed I did not set the lock

**Comment by shawndwells** [comment]
p.s. all these should have ``dconf update`` run after remediation. How should that be handled?

**Comment by shawndwells** [comment]
meaning - we can do that through a shell call, but _should_ we?

**Comment by redhatrises** [comment]
@shawndwells see #2239 for new variable.

**Comment by redhatrises** [comment]
> meaning - we can do that through a shell call, but _should_ we?

If there is no other way, then IMO yes.... unless there is a dconf module.

**Comment by shawndwells** [comment]
p.s. yes, aware of the Ansible Dconf module but it's still in preview vs supported

http://docs.ansible.com/ansible/latest/dconf_module.html

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
