### PR TITLE
Set rsyslog_remote_loghost_address to default value "logcollector"

### PR DESCRIPTION
**Pull request by yuumasato**
Fail remediation of Rule `rsyslog_remote_loghost` if value of `value_rsyslog_remote_loghost_address` is NULL.

Do not return `fixed` if we didn't change anything.

### CODE REVIEW

**Comment by redhatrises** [comment]
please don't failed error messages to users in remediation scripts

**Comment by yuumasato** [comment]
@redhatrises Should I also remove message from Ansible remediation?

**Comment by redhatrises** [comment]
@yuumasato yes

**Comment by mpreisler** [comment]
> please don't print failed error messages to users in remediation scripts

wait, why not? doesn't that make it way easier to figure out what went wrong?

**Comment by redhatrises** [comment]
First off, none of our other scripts have that output. Second where are you going to see this message/output?

**Comment by mpreisler** [comment]
> First off, none of our other scripts have that output. Second where are you going to see this message/output?

when you run it you can see output. openscap even puts in status messages so that you know which remediation is being run right now.

**Comment by redhatrises** [comment]
Say that you run a scan without a report. What happens if you run a full scan, remediate, and miss the output, and it's not on your terminal or some reason or another? It would be better to remediate than providing stderr/stdout.

**Comment by yuumasato** [comment]
In this particular rule we are not able to remedy if value `vale_rsyslog_remote_loghost_address` is not filled in by user.

**Comment by yuumasato** [comment]
I have added the error message back into bash remediation.
The message makes it very easy to find out why remediation is failing.

**Comment by redhatrises** [comment]
I would still prefer that we move away from an error message and move to make this remediation valid so that it is never an error in remedation. Setting a default `cname` such as `logcollector` for a host would help the administrators/securit personnel even more. All they have to do is add the cname to DNS. If they don't like it, then they can change it with a customized profile. This way we don't need error messages or the usage of `NULL` in the XCCDF.

**Comment by yuumasato** [comment]
Does `rsyslog` fail or complain visibly if set remote loghost cannot be reached?

**Comment by dahaic** [comment]
Jenkins test this please

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by redhatrises** [comment]
> Does `rsyslog` fail or complain visibly if set remote loghost cannot be reached?

@yuumasato it does not, but with a cname defined at that point, IMO, we don't care as that is external to the system and on the infrastructure side. In other words, if you don't like the cname defined, change it; otherwise, add it to your DNS.

**Comment by yuumasato** [comment]
> it does not, but with a cname defined at that point, IMO, we don't care as that is external to the system and on the infrastructure side.

I'm afraid that we might be setting up false positives.
How about also adding a note to the Rule telling user that remediation of this will Rule will set remote loghost to `logcollector`?
Should the field used be `fixtext`?

**Comment by redhatrises** [comment]
> How about also adding a note to the Rule telling user that remediation of this will Rule will set remote loghost to `logcollector`?

Update the XCCDF description with <sub idref /> to say something like:
`Make sure that the DNS alias (CNAME) is set to <sub idref /> which needs to be resolvable for logs to be sent correctly to the centralized logging utility.`  Or somthing like that.

> Should the field used be `fixtext`?

I don't think so.

**Comment by yuumasato** [comment]
I have added a mention to value of `rsyslog_remote_loghost_collector' and changed workflow of remediations appropriately.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
