### PR TITLE
RHEL7: Add ANSIBLE_kernel_module_disabled

### PR DESCRIPTION
**Pull request by ybznek**
ansible kernel module disabled

### CODE REVIEW

**Comment by ybznek** [comment]
test this please

**Comment by iankko** [comment]
@ybznek 
This PR has conflicts with the current master. Could you fix them?

Thanks, Jan

**Comment by ybznek** [comment]
@iankko Sure, I will wait for merge of https://github.com/OpenSCAP/scap-security-guide/pull/1431

**Comment by iankko** [comment]
> @iankko Sure, I will wait for merge of #1431

#1431 has been dealt with now. Please fix the conflicts on this one yet.

**Comment by ybznek** [comment]
@iankko Should be rebased now, let's wait for jenkins test results.

**Comment by iankko** [comment]
Thanks. I will have a look.

**Comment by iankko** [comment]
LGTM.

The playbook template works fine for me (tried the following use-case with ```dccp``` module):
```
[root@localhost ~]# cat kernel_module.yml 
---
- hosts: localhost
  tasks:
  - name: Ensure kernel module 'dccp' is disabled
    lineinfile:
      create=yes
      dest="/etc/modprobe.d/{{item}}.conf"
      regexp="{{item}}"
      line="install {{item}} /bin/true"
    with_items:
     - dccp
```
and got the following output:
```
[root@localhost ~]# ansible-playbook kernel_module.yml 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Ensure kernel module 'dccp' is disabled] *********************************
changed: [localhost] => (item=dccp)

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[root@localhost ~]# cat /etc/modprobe.d/dccp.conf 
install dccp /bin/true

[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

[root@localhost ~]# rm -f /etc/modprobe.d/dccp.conf

[root@localhost ~]# ansible-playbook kernel_module.yml 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Ensure kernel module 'dccp' is disabled] *********************************
changed: [localhost] => (item=dccp)

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[root@localhost ~]# cat /etc/modprobe.d/dccp.conf 
install dccp /bin/true
```

ACK.

**Pull request merged**
