### PR TITLE
Minor PEP8 fixes in map_product_module.py

### PR DESCRIPTION
**Pull request by mpreisler**
Just a couple minor things, testing pep8speaks integration.

### CODE REVIEW

**Comment by mpreisler** [comment]
> Hello @mpreisler! Thanks for updating the PR.
> 
> In the file shared/modules/map_product_module.py, following are the PEP8 issues :
> Line 20:24: E127 continuation line over-indented for visual indent

This is awesome!

**Comment by redhatrises** [comment]
+1 100000%

**Comment by mpreisler** [comment]
2.5 seconds ladies and gentlemen, two and a half seconds!

```
full build:
new code: 0m58.417s
old code: 1m0.922s
```

**Comment by jan-cerny** [comment]
Great!

**Pull request merged**
