### PR TITLE
[Enhancement][RHEL/7] RHEL7 obsolete services and bluetooth checks/re…

### LINKED ISSUE #695: OVAL for RHEL7 service_bluetooth_disabled

### LINKED ISSUE #696: Remediation for RHEL7 service_bluetooth_disabled

### LINKED ISSUE #717: Remediation for RHEL7 service_telnetd_disabled

### LINKED ISSUE #721: OVAL for RHEL7 service_rexec_disabled

### LINKED ISSUE #722: Remediation for RHEL7 service_rexec_disabled

### LINKED ISSUE #723: OVAL for RHEL7 service_rsh_disabled

### LINKED ISSUE #724: Remediation for RHEL7 service_rsh_disabled

### LINKED ISSUE #726: OVAL for RHEL7 service_rlogin_disabled

### LINKED ISSUE #727: Remediation for RHEL7 service_rlogin_disabled

### PR DESCRIPTION
**Pull request by redhatrises**
…mediations

- Add template_socket_disabled for any future socket checks
- Add OVAL and remediation scripts for obsolete and bluetooth services
- Update XCCDF content for obsolete services
- Add socket macros

- Resolves #695
- Resolves #696
- Resolves #717
- Resolves #721
- Resolves #722
- Resolves #723
- Resolves #724
- Resolves #726
- Resolves #727

### CODE REVIEW

**Comment by mpreisler** [comment]
ok to test

**Comment by shawndwells** [comment]
I might be blind... I see the OVAL for #695 (`````RHEL/7/input/checks/oval_5.11/service_bluetooth_disabled.xml`````), but where is the remediation?

**Comment by shawndwells** [comment]
Appologies - should have been clear - the existing has been around for some time, but doesn't contain the inline sed repliace, e.g.: 
`````
+grep -qi disable /etc/xinetd.d/rexec && \
+  sed -i "s/disable.*/disable         = yes/gI" /etc/xinetd.d/rexec
`````

Can you update the remediation to be consistent with the others (or, for bonus points, create a bash remediation template that gets autogen'd during the OVAL templates?

**Comment by shawndwells** [comment]
Started cleaning up the make validate errors on RHEL7 and wanted to take advantage of your OVAL template. Added the inline sed:
`````
[redhatrises-rhel7_obsolete_blue 8e83282] Updated rhel7/bluetooth_disabled remediation to include inline sed
 1 file changed, 3 insertions(+)
`````

Ack and pushed.

**Pull request merged**
