### PR TITLE
Add playbook to configure pam_faillock

### PR DESCRIPTION
**Pull request by hooksie1**
Playbook uses pamd module to configure pam_faillock.

### CODE REVIEW

**Comment by hooksie1** [comment]
Should this include the even_deny_root argument or should that be left separate?

**Comment by redhatrises** [comment]
This also needs to be fixed according to the pam faillock rules. In addition, variables need to be used as well.

**Comment by mpreisler** [comment]
@openscap-ci add to whitelist

btw, ansible `pamd` module is in preview state and the interface can be changed with any minor release.

**Comment by hooksie1** [comment]
Do you want me to not use the pamd module? I can change it if you want.

**Comment by redhatrises** [comment]
Unfortunately, this Ansible remediation hardcodes `deny=3`, `unlock_time=never`, and `fail_interval=900`. This needs to get the remediation values from the XCCDF instead of hardcoding them.

**Comment by hooksie1** [comment]
I added the variables. If you don't want the pamd module, I can do something else. Do you only want stable modules?

**Comment by mpreisler** [comment]
> Do you want me to not use the pamd module? I can change it if you want.

On a second glance I think this should be fine, we are already using preview modules and it seems the community consensus is that it's better to use preview modules than command or lineinfile.

I will take a look at this.

**Comment by mpreisler** [comment]
The location of fixes changed in the meantime so I will have to merge this manually.

**Comment by redhatrises** [comment]
@mpreisler we need this in password-auth as well.

**Comment by mpreisler** [comment]
I decided to open this for another review before merging, I had to make extensive changes to make this work on current master. Please see #2543

**Pull request closed without merging**
