### PR TITLE
[Enhancement][Infrastructure] Add new script to help with creating new products

### PR DESCRIPTION
**Pull request by redhatrises**
- New python script in `shared/utils` to add a new product to SSG.

### CODE REVIEW

**Comment by redhatrises** [comment]
This PR is a RFC. I created a python script that could be used to help add new products/versions to SSG. What do you think? How can this be expanded? What should it do/not do? Is this script helpful?

I know that there is work to centralize templates. Should templates be a part of this script?

**Comment by iankko** [comment]
> I know that there is work to centralize templates. Should templates be a part of this script?

It's correct we plan to refactor the way / layout templates are used currently (and use them in much more higher ratio in newer versions). IMHO it would be doubled effort to try to include templates into your script now (since you would need to include current version, then the updated ones).

**Comment by redhatrises** [comment]
>>    I know that there is work to centralize templates. Should templates be a part of this script?

> It's correct we plan to refactor the way / layout templates are used currently (and use them in much more higher ratio in newer versions). IMHO it would be doubled effort to try to include templates into your script now (since you would need to include current version, then the updated ones).

@iankko agreed. Anything else for you?

**Comment by isimluk** [comment]
@redhatrises, thanks!

Would it make sense to add a `.gitignore` file into each directory and run `git add ` on it instantly?

Also, please do not bundle the templates from the build script at this point (I would like to continue cleaning up the infrastructure till the New Year).

**Comment by redhatrises** [comment]
> Would it make sense to add a `.gitignore` file into each directory and run `git add ` on it instantly? (just an idea)

@isimluk maybe in some cases. I was actually hoping that the end iteration of this would be to add some Makefiles and re-populate with some generic content or help.

> Also, please do not bundle the templates from the build script at this point (I would like to continue cleaning up the infrastructure till the New Year).

@isimluk No worries about this be @iankko's comment. I will either be closing this PR and re-opening, or I will be updating with commits.

**Comment by redhatrises** [comment]
Closing this PR as there is no more feedback. Thanks all!

**Pull request closed without merging**
