### PR TITLE
Further NIST 800-171 profile work

### PR DESCRIPTION
**Pull request by shawndwells**
Vast majority of 800-171 is now mapped to a rule

### CODE REVIEW

**Comment by shawndwells** [comment]
note to reviewer: profile currently has *all* sebool checks. As profile gets incrementally developed, planning to work w/NIST to deselect sebools that don't have anything to do with *native* features/software (aka, drop the ones on webmin, keep those about user mgmt, memory).

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

(testing jenkins after cmake merge)

**Comment by shawndwells** [comment]
PR broke w/CMake merge. Will rebase and note when ready.

**Comment by shawndwells** [comment]
bump for review

**Comment by shawndwells** [comment]
dang it, that's what I get for merging @redhatrises 's STIG PR ;) rebasing now . . .

**Comment by shawndwells** [comment]
@mpreisler / @redhatrises - any chance you guys could review this? Once merged, we can publish *draft* content in the NIST National Checklist Program against 800-171!

**Comment by mpreisler** [comment]
Took a look at this. CCE assignments look fine. The profile changes are OK. The one OVAL check added is also OK.

There are a bunch of TODO comments in the profile but if I understand this correctly that's OK for a draft.

ACK.

PS: Next time please run `git rebase -i master` to get rid of the merges. It makes it easier to bisect and browse git history. I will not hold this PR because of it.

**Pull request merged**
