### PR TITLE
ansible: sssd_*

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by shawndwells** [comment]
@openscap-ci please test this

**Comment by shawndwells** [comment]
@openscap-ci test this please

**Comment by redhatrises** [comment]
See https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/194/ for Jenkins build status.

**Comment by shawndwells** [comment]
jenkins done. all green
https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/194/

@mpreisler guessing the Jenkins-GH integration broke?

**Comment by mpreisler** [comment]
> @mpreisler guessing the Jenkins-GH integration broke?

I guess so, the jenkins master mysteriously broke down so I spun up a new one with the same var/lib/jenkins volume and it stopped working. No idea why yet and I don't have time to look into it right now. I hope to fix it later this week.

**Comment by shawndwells** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
