### PR TITLE
MollyJoBault remediation scripts + fixes by Shawn

### PR DESCRIPTION
**Pull request by mpreisler**
Hi,
I just took https://github.com/OpenSCAP/scap-security-guide/pull/1342 and https://github.com/MollyJoBault/scap-security-guide/pull/1 and put them together.

Would be a shame to let the remediation scripts go stale.

CC @MollyJoBault @shawndwells

### CODE REVIEW

**Comment by shawndwells** [comment]
On 8/11/16 9:25 AM, Martin Preisler wrote:
>
> Hi,
> I just took #1342
> <https://github.com/OpenSCAP/scap-security-guide/pull/1342> and
> MollyJoBault#1
> <https://github.com/MollyJoBault/scap-security-guide/pull/1> and put
> them together.
>
> Would be a shame to let the remediation scripts go stale.
>
> CC @MollyJoBault <https://github.com/MollyJoBault> @shawndwells
> <https://github.com/shawndwells>
>
Fair. Thanks Martin!

**Comment by iankko** [comment]
Unless someone beats me to it, I will review this on on Monday.

**Comment by shawndwells** [comment]
bump @iankko  :)

**Comment by radzy** [comment]
+1

**Comment by iankko** [comment]
@shawndwells 
Sorry for the delay (was on PTO). Will get to this shortly.

**Comment by iankko** [comment]
This has been merged manually now with the following changes yet:

[BugFix] [RHEL/7] Move existing RHEL-7 remediations:
    * ```accounts_password_pam_maxclassrepeat.sh```,
    * ```accounts_passwords_pam_faillock_deny_root.sh```,
    * ```accounts_tmout.sh```,
    * ```clean_components_post_updating.sh```,
    * ```ensure_gpgcheck_local_packages.sh```,
    * ```ensure_gpgcheck_repo_metadata.sh```,
    * ```grub2_enable_fips_mode.sh```,
    * ```mount_option_tmp_nodev.sh```,
    * ```mount_option_tmp_noexec.sh```,
    * ```mount_option_tmp_nosuid.sh```, and
    * ```sysctl_net_ipv6_conf_all_accept_source_route.sh```
    
into proper static directory for RHEL-7 remediations.
    
 [BugFix] [RHEL/7] Drop the RHEL-7 remediation for ```accounts_passwords_pam_unix_remember.sh``` rule, since it's not necessary (there's /shared multi_platform_rhel remediation for correct ```accounts_password_pam_unix_remember``` rule [note the missing ```s``` character])
    
[BugFix] [RHEL/7] Drop the RHEL- remediation for ```mount_option_var_tmp_bind.sh``` rule (it's whole content has been commented out, thus it was effectively doing nothing). Instead of that move RHEL-6 version of the remediation script for this rule into /shared directory and update the 'platform' to  'multi_platform_rhel'

**Comment by iankko** [comment]
Fixes: https://github.com/OpenSCAP/scap-security-guide/issues/1446
Fixes: https://github.com/OpenSCAP/scap-security-guide/issues/1445
Fixes: https://github.com/OpenSCAP/scap-security-guide/issues/1442

**Pull request merged**
