### PR TITLE
[Enhancement][RHEL/7] Finished moving RHEL7 XSLT to shared XSLT

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by iankko** [comment]
@redhatrises 
Hi Gabe, could you fix the Jenkins build failures (looks there's some ```title``` variable missing / to be defined yet). More from:
* https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/432/label=node-fedora24/console
....
```
xsltproc -stringparam overlay "../input/auxiliary/stig_overlay.xml" -o output/unlinked-stig-rhel7-xccdf.xml \
	transforms/xccdf-apply-overlay-stig.xslt output/xccdf-unlinked-final.xml
runtime error: file ../../shared/transforms/shared_table-srgmap.xslt line 15 element value-of
Variable 'title' has not been declared.
xmlXPathCompiledEval: evaluation failed
runtime error: file ../../shared/transforms/shared_table-srgmap.xslt line 15 element value-of
XPath evaluation returned no result.
Makefile:66: recipe for target 'table-stigs' failed
make[1]: *** [table-stigs] Error 10
```

**Comment by iankko** [comment]
The same issue seems to be present on other Jenkins slaves too.

**Comment by iankko** [comment]
@redhatrises 
> Thanks @iankko. I had a typo which is now fixed.

Thanks!

**Comment by iankko** [comment]
Below is the list of differences between current version and version once this PR changes are applied (and for each of them explanation why I think it's safe change):
* 
```
### Checking cci2html.xsl ###
Files old_repo/scap-security-guide/RHEL/7/transforms/cci2html.xsl and
new_repo/scap-security-guide/shared/transforms/shared_cci2html.xsl are identical
```
=> safe change, xslt was just moved
* 
```
### Checking oval-fix-test-attestation-urls.xslt ###
25,26d24
<   <xsl:include href="constants.xslt"/>
<
```
safe change since 'constants.xslt' doesn't seem to be required:
```
xsltproc -o output/ssg-rhel7-oval.xml transforms/oval-fix-test-attestation-urls.xslt output/ssg-rhel7-oval.xml
# echo $?
0
```
* 
```
### Checking table-add-srgitems.xslt ###
6,9d5
< <xsl:variable name="srgtable" select="document('../output/table-rhel7-srgmap-flat.xhtml')/html/body/table" />
< <xsl:variable name="cci_list" select="document('../../../shared/references/disa-cci-list.xml')/cci:cci_list" />
<
<
```
Safe change because the two variables are defined in new version of RHEL/7's table-add-srgitems transformation:
```
 cat transforms/table-add-srgitems.xslt 
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xccdf="http://checklists.nist.gov/xccdf/1.1" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:cci="http://iase.disa.mil/cci">

<xsl:include href="../../../shared/transforms/shared_table-add-srgitems.xslt"/>
<xsl:variable name="srgtable" select="document('../output/table-rhel7-srgmap-flat.xhtml')/html/body/table" />
<xsl:variable name="cci_list" select="document('../../../shared/references/disa-cci-list.xml')/cci:cci_list" />

</xsl:stylesheet>
```
* 
```
### Checking table-srgmap.xslt ###
10,16d9
< <xsl:include href="constants.xslt"/>
< <xsl:include href="table-style.xslt"/>
<
< <!-- expecting external variable "map-to-items", a filename to an XCCDF document with Rules and Groups -->
< <!-- put everything in it with a reference into "items" (should only be Rules and Groups) -->
< <xsl:variable name="items" select="document($map-to-items)//*[cdf:reference]" />
< <xsl:variable name="title" select="document($map-to-items)/cdf:Benchmark/cdf:title" />
```
Safe change because those variables are defined in new version of RHEL/7/transforms/table-srgmap.xslt
* 
```
### Checking xccdf-apply-overlay-stig.xslt ###
11,12d10
< <xsl:variable name="overlays" select="document($overlay)/xccdf:overlays" />
<
15c13
<     <title>Pre-release Final STIG for Red Hat Enterprise Linux 7</title>
---
>     <title>Pre-release Final STIG for <xsl:value-of select="$product_long_name" /></title>
```
Safe change
* 
```
### Checking xccdf2html.xslt ###
Files old_repo/scap-security-guide/RHEL/7/transforms/xccdf2html.xslt and
new_repo/scap-security-guide/shared/transforms/shared_xccdf2html.xslt are identical
```
Safe change (identical files, just moved)
* 
```
### Checking xccdf2shorthand.xslt ###
Files old_repo/scap-security-guide/RHEL/7/transforms/xccdf2shorthand.xslt and
new_repo/scap-security-guide/shared/transforms/shared_xccdf2shorthand.xslt are identical
```
Safe change (ditto)
* 
```
### Checking xccdf2stigformat.xslt ###
8,9d7
< <xsl:include href="constants.xslt"/>
<
20,21c18,19
<       <title>Pre-Draft Red Hat Enterprise Linux 7 Security Technical Implementation Guide</title>
<       <description>The Red Hat Enterprise Linux 7 Security Technical Implementation Guide (STIG) is published as a tool to improve the security of Department of Defense (DoD) information systems. Comments or proposed revisions to this document should be sent via e-mail to the following address: fso_spt@disa.mil.</description>
---
>       <title>Pre-Draft <xsl:value-of select="$product_long_name" /> Security Technical Implementation Guide</title>
>       <description>The <xsl:value-of select="$product_long_name" /> Security Technical Implementation Guide (STIG) is published as a tool to improve the security of Department of Defense (DoD) information systems. Comments or proposed revisions to this document should be sent via e-mail to the following address: fso_spt@disa.mil.</description>
71c69
<                       <dc:title>VMS Target Red Hat 6</dc:title>
---
>                       <dc:title>VMS Target <xsl:value-of select="$product_long_name" /></dc:title>
74c72
<                       <dc:subject>Red Hat 6</dc:subject>
---
>                       <dc:subject><xsl:value-of select="$product_long_name" /></dc:subject>
```
Safe change (hard-coded product names were replaced with variables)
* 
```
### Checking xccdf2table-profileccirefs.xslt ###
6,9d5
< <xsl:variable name="cci_list" select="document('../../../shared/references/disa-cci-list.xml')/cci:cci_list" />
< <xsl:variable name="os_srg" select="document('../../../shared/references/disa-os-srg-v1r1.xml')/cdf:Benchmark" />
< <xsl:variable name="ovaldefs" select="document('../output/unlinked-rhel7-oval.xml')/ovalns:oval_definitions" />
<
12,14d7
<
< <xsl:include href="constants.xslt"/>
< <xsl:include href="table-style.xslt"/>
```
Safe change because all those variables are defined in the new version of RHEL/7/transforms/xccdf2table-profileccirefs.xslt transformation:
```
# cat transforms/xccdf2table-profileccirefs.xslt 
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cdf="http://checklists.nist.gov/xccdf/1.1" xmlns:cci="http://iase.disa.mil/cci" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:ovalns="http://oval.mitre.org/XMLSchema/oval-definitions-5">

<xsl:import href="../../../shared/transforms/shared_xccdf2table-profileccirefs.xslt"/>

<xsl:variable name="cci_list" select="document('../../../shared/references/disa-cci-list.xml')/cci:cci_list" />
<xsl:variable name="os_srg" select="document('../../../shared/references/disa-os-srg-v1r1.xml')/cdf:Benchmark" />
<xsl:variable name="ovaldefs" select="document('../output/unlinked-rhel7-oval.xml')/ovalns:oval_definitions" />

<xsl:include href="constants.xslt"/>
<xsl:include href="table-style.xslt"/>

</xsl:stylesheet>
```

**Comment by iankko** [comment]
IMHO looks safe to be merged. ACK.

Thank you for the changes!

**Comment by redhatrises** [comment]
Thanks @iankko!

**Pull request merged**
