### PR TITLE
Add centos 7 as supported platform

### PR DESCRIPTION
**Pull request by bmx0r**
Hi,
As asked in "https://github.com/OpenSCAP/scap-security-guide/issues/374"
Here is a proposal to add centos7 in the rhel7 tree
I don't know if it is the right way to do it, but it seems to work for me...
If there is a better way, feel free to share, i'd love to adapt :)
Regards
Mike

### CODE REVIEW

**Comment by redhatrises** [comment]
@bmx0r thanks for the PR. This PR does not actually fix #374 as it just enables the OVAL content to recognize the CentOS platform (which really hasn't been the issue around supporting Derivative Operating Systems). For historical reasons read https://lists.fedorahosted.org/pipermail/scap-security-guide/2014-August/005997.html.

So as a part of this PR, the applicability_check needs to be applied to the OVAL checks that surround FIPS/certified crypto checks as well in addition to CentOS being added to ```config/oval.config``` and ```shared/transforms/combinechecks.py```

**Comment by bmx0r** [comment]
@redhatrises in fact i never intend to solve 374... My purpose was to enable centos7 the right way... as it is already done for rhel5 :p 
I took a look at the `oval.config` and `combinecheck` i add centos in them.

by the way if i understand well, combinecheck will allow dev to create checks with special tag in the affected part (ie multi_platform_rhel will auto add rhel6 and rhel7 platform tag) but since derivative platform are known to be really close maybe it could be nice to have a way to tell a check that he can be enabled for all derivative (ie alt_platform_rhel7 = "cenots7","Oel7",...)?

**Comment by isimluk** [comment]
In the past, there have been numerous discussion about centos CPE to be added to SSG. The conclusion has always been to not include. There has been some disagreement about fips/fisma/whatever compliance of centos systems. At some agencies, procurement managers believe they can use centos, at other agencies officers believe that they shall not.

I think this issue should be again taken to the ssg mailing list to solicit feedback.

**Comment by bmx0r** [comment]
Still in the RHEL/5 directory, cpe for  centos4 and 5 are included... 
Enabling the cpe doesn't mean you caution their level of compliance, but it could allow more people to create xccdf content based on the great work that you're doing here :)

**Comment by mpreisler** [comment]
Replaced by #567 

If you feel otherwise, please reopen.

**Pull request closed without merging**
