### PR TITLE
[Test suite] [RHEL/6] Add initial version of check_instances_test.py Python testing script for RHEL-6 content

### PR DESCRIPTION
**Pull request by iankko**
This PR adds initial version of ```check_instances_test.py``` testing script intended for automated testing of
RHEL-6 SSG content regressions wrt to issue: https://github.com/OpenSCAP/scap-security-guide/issues/433

It's far from being complete (since there still remain services to be investigated for their behaviour - if they honour just first or all particular config file options when parsing specific config file / file location). But even in current state it's able to report some discrepancies in OVAL textfilecontent54_objects definitions (e.g. for auditd or sysctl.conf rules).

The test will be gradually enhanced to cover all locations & once all the service / locations items have been reviewed, it can be configured to become part of existing ```make validate``` test to check when new textfilecontent54_object is added for existing config file / location, if it's ```operation``` and ```instance``` definitions follow the expected behavioural pattern for that service.

Also intentionally placed it to be RHEL-6 content specific since the ```verify_record_sanity``` routine from the test contains list of OVAL object exceptions (see MANUALLY_VERIFIED_SAFE_IDS list for further details). Once similar tests for RHEL-7 & Fedora content is created, the test can be enhanced to be one for all products.

Please review.

Thank you, Jan.

### CODE REVIEW

**Comment by redhatrises** [comment]
@iankko is there a way to have a more intuitive error message rather than just FAIL? It might help to say something about what result is expected and why it failed.

**Comment by iankko** [comment]
@redhatrises 
> @iankko is there a way to have a more intuitive error message rather than just FAIL?
Yeah, agree that current FAIL isn't very intuitive. Basically wanted to have some default value to return when the test wasn't evaluated yet. But agree with you in the current implementation isn't possible to distinguish if the test just wasn't checked (IOW it's not covered in the whitelisted cases above) or if it truly failed (was verified & failed).

> It might help to say something about what result is expected and why it failed.
Yeah, agree. Will provide another patch. Thanks for review!

**Comment by mpreisler** [comment]
I understand the reasoning for the checking scheme but saying how to fix a fail in the output will likely save a ton of effort in the future. Perhaps print out exactly all that was checked in case of a fail.

With a tiny bit more work this script can be made to work with both python2 and python3. I think that would be worth it.

**Comment by shawndwells** [comment]
@iankko, in comment https://github.com/OpenSCAP/scap-security-guide/pull/439#issuecomment-74048704 you mentioned there may be additional patches coming. still working on them?

**Comment by iankko** [comment]
@shawndwells 
> @iankko, in comment #439 (comment) you mentioned there may be additional patches coming. still working on them?

Yes, but for the original / initial version I will just fix issues from Gabe's & Martin's comment, so we can include the initial version (the longer story is till I can increase the set of covered services, I first need to test their actual behavior & then make corresponding code changes => it will be longer run till all objects generated in RHEL-6's OVAL file would be covered).

But I will fix the issues reported so far at least, so other people could contribute to the test too if / when interested.

**Comment by isimluk** [comment]
I would like to see this PR merged or dismissed. I would like to have 0 opened pull requests on Christmas. :)

For me this is a clear merge.
 - Not breaking anything
 - Adding an handy script
 - Not perfect on a first try but the issues are rather minor
 - It can be improved easily over the time.

But others may disagree.

**Comment by mpreisler** [comment]
Agreed with @isimluk

**Pull request merged**
