### PR TITLE
Removed the old JBossFuse6 content, this content is obsolete and does…

### PR DESCRIPTION
**Pull request by mpreisler**
…n't work. It has been replaced by `JBoss/Fuse/6` content.

The XCCDF of the old content has been broken by 99361a005b8738bd9463a00187816eb32bef4391 and nobody ever complained -- the `Benchmark` element was removed. Therefore I think nobody is using this. The OVAL doesn't validate either...

**THIS IS CONTROVERSIAL, PLEASE WAIT A BIT BEFORE MERGING** If nobody speaks out in a week I think it's safe to merge.

Do we want to remove the JBossEAP5 content as well? It has been obsoleted by `JBoss/EAP/5`.

### CODE REVIEW

**Comment by mpreisler** [comment]
Added 2 commits that remove `JBossEAP5`, we can remove them if we decide to keep `JBossEAP5`.

**Comment by redhatrises** [comment]
@mpreisler `JBossEAP5` content is still needed as `JBoss/EAP/5` is not yet all there.

**Comment by redhatrises** [comment]
@mpreisler good with removing the old JBossFuse6 content. I don't think that it is a controversial removal as it should be building normally.

**Comment by mpreisler** [comment]
@redhatrises Removed the two commits and push forced. Now this PR is only removing JBossFuse6.

**Comment by redhatrises** [comment]
Ack for this PR. Please wait until next week to merge just in case there are concerns raised.

**Comment by shawndwells** [comment]
On 11/28/16 4:03 PM, Martin Preisler wrote:
>
> …n't work. It has been replaced by |JBoss/Fuse/6| content.
>
> The XCCDF of the old content has been broken by 99361a0
> <https://github.com/OpenSCAP/scap-security-guide/commit/99361a005b8738bd9463a00187816eb32bef4391>
> and nobody ever complained -- the |Benchmark| element was removed.
> Therefore I think nobody is using this. The OVAL doesn't validate
> either...
>
> *THIS IS CONTROVERSIAL, PLEASE WAIT A BIT BEFORE MERGING* If nobody
> speaks out in a week I think it's safe to merge.
>
> Do we want to remove the JBossEAP5 content as well? It has been
> obsoleted by |JBoss/EAP/5|.
>

The Fuse6 content was written for XCCDFExec interpreter (not OpenSCAP).
Was authored by Bryan Saunders, Jason Wong and Kenny Peeples in support
of a US Gov customer (Navy, IIRC). Pinging them to get the latest.

**Comment by redhatrises** [comment]
Any objections to merging this PR? Would like to merge this by Friday.

**Comment by redhatrises** [comment]
As no one has responded since 12 days ago, I am going to go ahead and merge. We can revert if needed.

**Pull request merged**
