### PR TITLE
Expand some XCCDF descriptions and fixes

### PR DESCRIPTION
**Pull request by redhatrises**
- Expand some XCCDF descriptions to be more clear of what to set/verify
- Fix incorrect <sub idref/> variable reference
- Fix accounts_tmout.sh

### CODE REVIEW

**Comment by mpreisler** [comment]
@redhatrises I wonder why the variable reference wasn't caught. We have systems in place that should fail the build if we have invalid IDs we reference.

**Comment by redhatrises** [comment]
@mpreisler I don't think that we actually check for valid variables in `<sub idref/>` which is why it didn't error out.

**Comment by mpreisler** [comment]
> @mpreisler I don't think that we actually check for valid variables in <sub idref/> which is why it didn't error out.

We definitely do. It's done as part of the XCCDF 1.1 -> 1.2 transformation.

**Comment by mpreisler** [comment]
OK, I know why now. The ID is a valid ID for a rule but not for a value. That's why it's not caught by the check.

**Pull request merged**
