### PR TITLE
Profile titles changed for PCI-DSS and STIG

### PR DESCRIPTION
**Pull request by mpreisler**
Changed profile titles to be consistent. This improves UX in HTML guides, reports, SCAP Workbench and OSCAP Anaconda Addon.

Added draft info the descriptions.

### CODE REVIEW

**Comment by iankko** [comment]
@mpreisler 
Agree / ACK FWIW WRT to removing "Pre-release" string from the STIG RHEL-7 profile name (and keeping just "Draft" there).

For the rest (PCI-DSS) changes we want to have the "Draft" there - it's a sign, this effort has not been finished yet, and hasn't been validated by the PCI-DSS consortium for legitimacy / justifiability.

So I agree with removing "Pre-release" string from STIG RHEL-7 profile name (if that's percepted now as duplication). But would keep the "Draft" string there (for STIG && PCI-DSS).

**Comment by mpreisler** [comment]
I have removed Draft from profile titles because that's how it's done for all profiles except PCI-DSS and STIG. We keep this information in `<description>` where users can clearly read that these profiles are draft profiles. It seemed weird and inconsistent to do something different for just two profiles.

Not having super long profile titles is helpful for GUI tools. It's easier to figure out what to select when users don't have to skip 2-3 words for each profile title.

**Comment by iankko** [comment]
@mpreisler 
> I have removed Draft from profile titles because that's how it's done for all profiles except PCI-DSS and STIG. We keep this information in <description> where users can clearly read that these profiles are draft profiles. It seemed weird and inconsistent to do something different for just two profiles.
>
Not having super long profile titles is helpful for GUI tools. It's easier to figure out what to select when users don't have to skip 2-3 words for each profile title.

While in general I agree with this (not having super long text in the profile titles being better), the issue being OSCAP Anaconda Add-On use case - in the main screen it's not possible to display description of the profile (there are just titles). While the clarified-in-description approach would work for tools like e.g. SCAP Workbench, for OAA there isn't other way how to communicate the profile is just draft with the user than express this information in the title (the OAA main SCAP content selection dialog displays just profiles by their titles).

**Comment by mpreisler** [comment]
If this is the case then we have no choice but to add Draft to every profile we ship, maybe excluding a few exceptions.

**Comment by iankko** [comment]
@mpreisler 
> If this is the case then we have no choice but to add Draft to every profile we ship, maybe excluding a few exceptions.

OK. Makes sense.

Ad ```oscap-anaconda-addon``` not showing the description - taking back that. OAA is displaying the profile's description (checked most recent build), but it's not immediately visible it's a description.

I will review this, and in the future highlight the draft in the profile's description with bold font.

**Comment by iankko** [comment]
ACK. LGTM.

**Pull request merged**
