### PR TITLE
Rename and move platform/ directory

### PR DESCRIPTION
**Pull request by redhatrises**
- Rename the platform/ directory to cpe/ to accurately reflect what is in the directory
- Move the new cpe/ directory out of the oval/ directory as it really isn't OVAL

### CODE REVIEW

**Comment by redhatrises** [comment]
Requires #2373 to be merged first.

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by shawndwells** [comment]
Did you guys leave defense in depth event and go hop on GitHub?? Nerds! 👍🏼

**Comment by mpreisler** [comment]
> Did you guys leave defense in depth event and go hop on GitHub?? Nerds! 👍🏼

airport boredom ;-)

**Comment by mpreisler** [comment]
Awesome.

ACK

**Pull request merged**
