### PR TITLE
[RHEL7][issue 118] set login banners

### LINKED ISSUE #118: RHEL7 STIG: CCI-001384, CCI-001385, CCI-001386, CCI-001387, CCI-001388 The publicly accessible operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting access to the system.
AC-8 c 1, AC-8 c 2, AC-8 c 3	CCI-001384, CCI-001385, CCI-001386, CCI-001387, CCI-001388	SRG-OS-000228		The publicly accessible operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting access to the system.	"Display of a standardized and approved use notification before granting access to the publicly accessible operating system ensures privacy and security notification verbiage used is consistent with applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance.

System use notifications are required only for access via logon interfaces with human users and are not required when such human interfaces do not exist.

The banner must be formatted in accordance with DTM-08-060. Use the following verbiage for operating system that can accommodate banners of 1300 characters:

""You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only.

By using this IS (which includes any device attached to this IS), you consent to the following conditions:

-The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.

-At any time, the USG may inspect and seize data stored on this IS.

-Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose.

-This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy.

-Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.""
 
Use the following verbiage for operating systems that have severe limitations on the number of characters that can be displayed in the banner:

""I've read & consent to terms in IS user agreem't."""

### PR DESCRIPTION
**Pull request by shawndwells**
[RHEL7][issue 118] set login banners

resolves  #118 
    - updated CCEs (some were reused from rhel6)
    - added rules to stig profile
    - ./testcheck.py

Dropped GUI configuration checks so they wouldn't be included in the HTML guide yet. Can add back in once someone gets a chance to port instructions to RHEL7.

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells looks like the instructions are ported for RHEL7 as it is using the appropriate dconf settings rather than the gconf settings.

**Comment by redhatrises** [comment]
@shawndwells see https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Desktop_Migration_and_Administration_Guide/customizing-login-screen.html

**Comment by shawndwells** [comment]
added dconf back in

**Comment by redhatrises** [comment]
Fixed merge conflicts and merged.

**Pull request merged**
