### PR TITLE
Update references transforms

### PR DESCRIPTION
**Pull request by redhatrises**
- Use SRG instead of OSSRG in XSLT transforms
- Detect if SRG is OS or APP and add the correct SRG reference
- Format DISA CCI references correctly
- When there are no references, it adds the url to the non-existent reference which produces
  weird report outputs

### CODE REVIEW

**Comment by shawndwells** [comment]
Before patch:
image


After patch:
image


What am I missing?

**Comment by redhatrises** [comment]
@shawndwells here is what I get after the patch:

image

The NIST URL no longer appears.

**Comment by mpreisler** [comment]
This seems like a band-aid. Why are there empty reference elements in the first place? Shouldn't we just remove empty references?

**Comment by redhatrises** [comment]
@mpreisler personally I find it easier to add the missing reference if the attribute exists and is empty rather than adding the entire attribute. However even if we remove all the empty references, I think that we should still have this just in case someone adds something or misses it during review.

**Comment by redhatrises** [comment]
This is needed for a demo. Ack.

**Pull request merged**
