### PR TITLE
[wip] initial OSPP v4.2 draft profile

### PR DESCRIPTION
**Pull request by shawndwells**
#### Description:
Add new profile that aligns to draft OSPP 4.1 configuration annex:
https://commoncriteria.github.io/pp/operatingsystem/configannex.html

#### Rationale:

Eventually this will be the "base" profile for all US Gov. Will need to refactor existing ospp profile.

### CODE REVIEW

**Comment by dahaic** [comment]
@shawndwells great start with the profile! I just don't fancy the piggybacked osp7->osp13 change :) Can you do it in separate PR?

**Comment by shawndwells** [comment]
For sure. I noticed that too. I was working on another branch, checked out master, created the new, and this crap got pulled in.

And hey @mpreisler this is how you tell someone they did something stupid =P

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by shawndwells** [comment]
On 3/12/18 10:40 AM, Watson Yuuma Sato wrote:
> @shawndwells <https://github.com/shawndwells> We would like to merge
> this before the migration to |yaml| format.
> Could you revert the prodtype and rebase?

If I knew how. That code is from another code branch and doesn't
actually show up in my ospp branch locally.

**Comment by mpreisler** [comment]
I tried fixing the conflicts but almost every commit has a conflict and there is a ton of them. This may need some clever scripting to fix the conflicts.

**Comment by shawndwells** [comment]
Used the GitHub webUI to rebase and remove merge conflicts. Jenkins running now... will see if this took care of things.

**Comment by shawndwells** [comment]
Getting a fun new error. Will look at this tomorrow morning with fresh eyes.

`````
$ cmake ../ ; make -j4 rhel7
-- SCAP Security Guide 0.1.39
-- (see /var/www/html/scap-security-guide/BUILD.md for build instructions)
-- 
OpenSCAP Error:: XSLT file 'xccdf-guide.xsl' not found in path '/usr/local/share/openscap/xsl' when trying to transform '/tmp/tmpMD7OK4' [xslt.c:133]
Traceback (most recent call last):
  File "/var/www/html/scap-security-guide/shared/utils/oscap-svg-support.py", line 55, in <module>
    main()
  File "/var/www/html/scap-security-guide/shared/utils/oscap-svg-support.py", line 47, in main
    [oscap_executable, "xccdf", "generate", "guide", xccdf.name]
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/local/bin/oscap', 'xccdf', 'generate', 'guide', '/tmp/tmpMD7OK4']' returned non-zero exit status 1
`````

**Comment by shawndwells** [comment]
and from the actual make:
`````
$ make -j4 rhel7
[  0%] [  0%] Built target generate-internal-rhel7-guide.xml
Built target generate-internal-bash-remediation-functions.xml
[  0%] Built target generate-internal-rhel7-oval-unlinked.xml
[  0%] [  0%] Built target generate-internal-rhel7-shorthand.xml
Built target generate-internal-rhel7-anaconda-fixes.xml
[  0%] Built target generate-internal-rhel7-puppet-fixes.xml
[  0%] Built target generate-internal-rhel7-ansible-fixes.xml
[  0%] [  0%] [  0%] Built target generate-internal-rhel7-bash-fixes.xml
Built target generate-ssg-rhel7-cpe-dictionary.xml
[rhel7-content] generating xccdf-unlinked-resolved.xml
OpenSCAP Error: Schema file 'xccdf/1.1/xccdf-schema.xsd' not found in path '/usr/local/share/openscap/schemas' when trying to validate '/var/www/html/scap-security-guide/build/rhel7/xccdf-unlinked-resolved.xml' [validate.c:99]
Invalid XCCDF Checklist (1.1) content in /var/www/html/scap-security-guide/build/rhel7/xccdf-unlinked-resolved.xml. [oscap_source.c:342]
make[3]: *** [rhel7/xccdf-unlinked-resolved.xml] Error 1
make[2]: *** [rhel7/CMakeFiles/generate-internal-rhel7-xccdf-unlinked-resolved.xml.dir/all] Error 2
make[1]: *** [rhel7/CMakeFiles/rhel7.dir/rule] Error 2
`````

**Comment by shawndwells** [comment]
updated my openscap-utils:
````
$ oscap -V
OpenSCAP command line tool (oscap) 1.2.17
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/local/share/openscap/schemas
Default CPE files: /usr/local/share/openscap/cpe
Probes: /usr/local/libexec/openscap

==== Inbuilt CPE names ====

==== Supported OVAL objects and associated OpenSCAP probes ====
OVAL family   OVAL object                  OpenSCAP probe              
----------    ----------                   ----------      
`````

and now get a new error from 'make rhel7':
`````
Scanning dependencies of target generate-ssg-rhel7-oval.xml
[  9%] [  9%] [  9%] [rhel7-content] generating ssg-rhel7-xccdf.xml
[rhel7-content] generating ssg-rhel7-ocil.xml
[rhel7-content] generating ssg-rhel7-oval.xml
[ 18%] Built target generate-ssg-rhel7-ocil.xml
[ 18%] Built target generate-ssg-rhel7-oval.xml
Traceback (most recent call last):
  File "../../shared/utils/unselect-empty-xccdf-groups.py", line 151, in <module>
    main()
  File "../../shared/utils/unselect-empty-xccdf-groups.py", line 104, in main
    "Make sure the input file is a resolved XCCDF Benchmark."
RuntimeError: Make sure the input file is a resolved XCCDF Benchmark.
make[3]: *** [ssg-rhel7-xccdf.xml] Error 1
make[2]: *** [rhel7/CMakeFiles/generate-ssg-rhel7-xccdf.xml.dir/all] Error 2
make[1]: *** [rhel7/CMakeF
`````

**Comment by mpreisler** [comment]
This PR's git history is messy and we deemed it better to squash it and base it on latest master. Please continue in #2670

**Pull request closed without merging**
