### PR TITLE
Add SUSE11 stig_overlay.xml

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by shawndwells** [comment]
Where are the ``ownerid="GEN######"`` coming from?

**Comment by redhatrises** [comment]
The same place as the RHEL7 `stig_overlay.xml` `ownerid`s which is the `<title />` element from the manual STIG reference under `shared/references`.

**Comment by redhatrises** [comment]
[retest this please]

**Comment by mpreisler** [comment]
@redhatrises Is the overlay SUSE specific?

**Comment by redhatrises** [comment]
@mpreisler that is correct. All `stig_overlay.xml` files are product and version specific.

**Comment by mpreisler** [comment]
ACK

**Comment by shawndwells** [comment]
On 5/12/17 9:41 AM, redhatrises wrote:
> @mpreisler <https://github.com/mpreisler> that is correct. All
> |stig_overlay.xml| files are product and version specific.
But given there is no SuSE STIG, where did those identifiers come from?
Shouldn't the OS SRG be used?

**Comment by shawndwells** [comment]
@redhatrises meaning not where in the directory structure... but the identifiers themselves ;)

**Comment by redhatrises** [comment]
@shawndwells there is this SUSE STIG: http://iase.disa.mil/stigs/os/mainframe/Pages/zlinux.aspx

**Comment by shawndwells** [comment]
On 5/12/17 12:37 PM, redhatrises wrote:
>
> @shawndwells <https://github.com/shawndwells> there is this SUSE STIG:
> http://iase.disa.mil/stigs/os/mainframe/Pages/zlinux.aspx
>

Forgot about that. Suppose that's what I get for expecting linux STIGs
to be listed on the Linux STIG page:
http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx

**Pull request merged**
