### PR TITLE
Update SSH ciphers and MACs

### PR DESCRIPTION
**Pull request by shawndwells**
-  rijndael-cbc@lysator.liu.se was missing from SSH approved ciphers. Updated XCCDF and OVAL.
- RHEL6 and RHEL7 have different approved MACs. Moved OVAL from shared into rhel directories, updated regex

Right now OVAL checks for the enablement of *all* FIPS ciphers and MACs. A system that is configured to only enable a single cipher, while properly configured, would fail the OVAL. Created ticket https://github.com/OpenSCAP/scap-security-guide/issues/1686 to track this.

### CODE REVIEW

**Comment by redhatrises** [comment]
> Moved OVAL from shared into rhel directories, updated regex

@shawndwells why not have the OVAL handle both RHEL6 and RHEL7 scenarios rather than have two separate files?

**Comment by shawndwells** [comment]
psh, don't you go all "making sense" on me @redhatrises 

image

(will update PR and resubmit)

**Comment by redhatrises** [comment]
[retest this please]

**Comment by redhatrises** [comment]
Bump @shawndwells

**Pull request closed without merging**
