### PR TITLE
Add SSG related graphics and promo materials to the repo

### PR DESCRIPTION
**Pull request by mpreisler**
The repository is the obvious point of truth for any logos and other small/basic promo materials. These are fairly small SVG files, all compatible with Inkscape.

With the help of Peter Vrabec we were able to recover some of our lost SVG files with logos. I don't want to ever lose those materials again. I think adding them to the repo makes sense but am willing to consider other places to upload them if you think we shouldn't have this in the repo.

@shawndwells @redhatrises We should consider making stickers out of these. The icons are very well done IMO.

### CODE REVIEW

**Comment by mpreisler** [comment]
Actually, maybe a wiki page makes more sense. Thoughts?

**Comment by shawndwells** [comment]
On 7/17/17 1:21 PM, Martin Preisler wrote:
>
> Actually, maybe a wiki page makes more sense. Thoughts?
>
Definitely the repo. I have additional logo files too.

Would shared/logos make more sense?

**Comment by mpreisler** [comment]
I discovered that it's pretty annoying to upload files to github wiki pages right now. I am leaning towards creating a repo called OpenSCAP/promo with all OpenSCAP related materials. It doesn't bloat any repos and we can keep it in one place.

**Comment by shawndwells** [comment]
New repo fine by me. Could double purpose as a place to create a standard OpenSCAP deck too.

**Comment by mpreisler** [comment]
Yeah, thx for feedback. I will start a repo in a moment.

**Comment by mpreisler** [comment]
Closing this PR. The logos now live in https://github.com/OpenSCAP/promo/tree/master/scap-security-guide

**Pull request closed without merging**
