### PR TITLE
Very first attempt to implement systemd template.

### PR DESCRIPTION
**Pull request by isimluk**
Guys, this comes too erly for being really usefull. Still I believe it can be merged.

**However**, systemd test requires to change OVAL version for ssg/RHEL/7/ to 5.11. And also you will need to use --skip-valid during scanning. That is problemating because OVAL 5.11 was not yet released. I am not sure, what the release schedule is. :-( I am not sure if SSG wants to use OVAL 5.11 feature before it is released...

Therefore, I decided to contribute only template file and not the expansion (the `make copy`).

### CODE REVIEW

**Comment by shawndwells** [comment]
so, it's been a few months on this one.

@isimluk, is there an ETA on when RHEL7 will include an OVAL 5.11 scanner? it may have been discussed on the SSG mailing list, but I can't quickly find in the archives.

**Comment by isimluk** [comment]
OpenSCAP 1.2.x will not be part of RHEL-7.1. Perhaps we can work together to make it happen later. Feel free to close this PR if that helps with project governance in the mean time.

**Comment by shawndwells** [comment]
Thanks @isimluk . Bumping this out to 0.1.23 to give us some run way. Don't want to close out the PR as it may get forgotten about.

**Comment by iankko** [comment]
This is obsoleted by: https://github.com/OpenSCAP/scap-security-guide/pull/527 

Closing (no need to keep it opened longer).

**Pull request closed without merging**
