### PR TITLE
Unshadow all the CPE OVAL checks

### PR DESCRIPTION
**Pull request by mpreisler**
#### Description:

- Deduplicates OVAL code related to CPE checks, all of this is universal, you are checking whether the platform is something, so the check itself applies to everything, not just the target platform

#### Rationale:

- Less code is better
- Brings bugfixes to shared CPE OVALs to the products that copied the code and shadowed it, this fixes CPE OVAL on RHEL-OSP7, Debian and others.

### CODE REVIEW

**Comment by matejak** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
@mpreisler Jenkins test fails for legitimate reasons, please take a look at it.

**Comment by mpreisler** [comment]
rhel-osp7 is a problematic name, there must be parts of the build system that can't handle it

**Comment by shawndwells** [comment]
Iirc isn’t it just called “osp” now? The RHEL preface is old

**Comment by mpreisler** [comment]
Hmm, so the problem is that once we pull all the multi platform all checks into chromium and firefox it uncovers hidden dependencies and these 2 projects now fail. There are 2 options, either I can fix all the multi_platform_all stuff or add Chromium and Firefox to the CPE OVALs :-/

**Comment by mpreisler** [comment]
the debian8 CPE OVAL was unshadowed in #2966 
removed that commit from this PR

**Comment by mpreisler** [comment]
I have applied workarounds and this now builds on my machine and the test suite passes.

**Comment by yuumasato** [comment]
> I can fix all the multi_platform_all stuff 

@mpreisler by this you meant to expand multi_platform_all to Chromium and Firefox, or something else?

Nice workaround, this way Chromium and Firefox are not added to all multiplatform checks.
ACK from me.

Will wait for some more feedback before merging.

**Comment by mpreisler** [comment]
> @mpreisler by this you meant to expand multi_platform_all to Chromium and Firefox, or something else?

Yes but that uncovers other issues. Probably should be done in another PR.

**Comment by redhatrises** [comment]
Hmmm..... Chromium and Firefox aren't necessarily part of the unix family. Do they need to have that?

**Comment by mpreisler** [comment]
> Hmmm..... Chromium and Firefox aren't necessarily part of the unix family. Do they need to have that?

that is true but some of the checks extend it and the criteria differs depending on whether you are on unix family or not.

**Comment by yuumasato** [comment]
> Hmmm..... Chromium and Firefox aren't necessarily part of the unix family. Do they need to have that?

Maybe `installed_app_is_firefox` should be called `installed_app_is_unix_firefox`?

Also, CPE checks kinda need to be run everywhere. A CPE check for rhel7 should be able to run in an debian and return false.

**Comment by mpreisler** [comment]
> Also, CPE checks kinda need to be run everywhere. A CPE check for rhel7 should be able to run in an debian and return false.

yes, 100%

**Comment by yuumasato** [comment]
@redhatrises Do you have objections to the workaround?

**Comment by redhatrises** [comment]
Changing `installed_app_is_firefox` to `installed_app_is_unix_firefox`? If that is what you are referring to then, yes, that makes no sense to me since we have an extended_definition that checks if it is part of the unix family.

**Comment by yuumasato** [comment]
@redhatrises Sorry I was not clear. I was refering to commit b8bdebd.
I think renaming of the OVAL should be done in another PR.

**Comment by redhatrises** [comment]
@yuumasato no that is fine.

**Pull request merged**
