### PR TITLE
Generate remediation functions

### PR DESCRIPTION
**Pull request by mpreisler**
Opening a PR to check whether this is acceptable to the rest of the SSG community.

Initially I wanted to split up the shared remediations functions huge file. There are several smart ways how we could do that. But then I realized that having one huge file is not ideal so I split it up into separate files. It's much easier to generate the XML from that.

To get perfect XML escaping I am using ElementTree.

TODO:
- ~~support dependencies between functions~~
- ~~hook it up into cmake~~

### CODE REVIEW

**Comment by shawndwells** [comment]
Always a fan of breaking things into components. 

Should things go into ``shared/bash_remediation_functions/*.sh`` or align with existing structure, e.g. create ``shared/remediations/bash/functions/*.sh``? I favor the later.

**Comment by mpreisler** [comment]
@shawndwells There is nothing in shared/remediations anymore. So this would just be a deep structure of single directories.

**Comment by shawndwells** [comment]
@mpreisler currently there is [shared/bash/functions](https://github.com/OpenSCAP/scap-security-guide/tree/master/shared/remediations/bash/templates). I get that is going away with this PR.

Question was do we want shared/bash_remediation_functions, shared/ansible_remediation_functions, shared/$future_remediation_functions, or should they be nested in something like shared/remediations/$language/functions?

**Comment by shawndwells** [comment]
Typing all that out, I see your point about random directory depths tho. Kind of annoying.

**Comment by mpreisler** [comment]
Either way is fine by me. Keep in mind though that we are unlikely to have shared functions for ansible, puppet or anaconda. That leaves only bash. All other remediation languages are strong/convenient enough not to need shared functions.

**Comment by shawndwells** [comment]
You're right. Thanks for breaking it down for me :)

**Comment by mpreisler** [comment]
Rebased and fixed conflicts because of #2071

**Comment by mpreisler** [comment]
This is now ready for merging.

**Pull request merged**
