### PR TITLE
Remediations for /etc/cron.allow ownership

### LINKED ISSUE #1887: needs remediation: xccdf_org.ssgproject.content_rule_file_owner_cron_allow

### PR DESCRIPTION
**Pull request by jan-cerny**
Fixes #1887 and #1888.

### CODE REVIEW

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by mpreisler** [comment]
ACK

**Comment by mpreisler** [comment]
sidenote: I wish we had templating for this. There is a lot of rules like this.

**Comment by jan-cerny** [comment]
@mpreisler Yes, cool idea for refactoring, I will at least create a ticket for that.

**Pull request merged**
