### PR TITLE
OL7 was using one group outside of shared but everything else was shared

### PR DESCRIPTION
**Pull request by mpreisler**
This is required for #2592

### CODE REVIEW

**Comment by redhatrises** [comment]
Nack. The updating XCCDF for Oracle Linux is customized to solely Oracle. This PR needs to go further if it is being put into shared.

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
> Nack. The updating XCCDF for Oracle Linux is customized to solely Oracle. This PR needs to go further if it is being put into shared.

that is impossible at this point, we have to move to yaml and introduce ninja to fully fix this. What I could do is introduce rules of varying IDs and have the descriptions separately but then we'd have to merge it again later.

**Comment by mpreisler** [comment]
Blocker issue created: #2675

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by redhatrises** [comment]
Ack.

**Pull request merged**
