### PR TITLE
[bugfix][RHEL/6] Fix kickstarts to use distribution content

### PR DESCRIPTION
**Pull request by redhatrises**
- Don't use upstream git content (rhbz 1378489)

### CODE REVIEW

**Comment by redhatrises** [comment]
If desired, this can go into 0.1.31.

**Comment by mpreisler** [comment]
Let's have a discussion about this here before we merge it.

I don't have a strong opinion.

**Comment by redhatrises** [comment]
@mpreisler neither do I.

**Comment by shawndwells** [comment]
Upstream kickstarts pushing upstream code makes sense. Does the RHEL RPM take these files directly though?

**Comment by shawndwells** [comment]
If the downstream takes directly, perhaps we need two sets of kickstart files.

**Comment by redhatrises** [comment]
@shawndwells this is for `RHEL/6` kickstart files only. `RHEL/7` kickstart files do not use git at all and stick to what is shipped in the distro.

**Comment by mpreisler** [comment]
Makes sense to me to switch this to the package, similar to what we do in RHEL7 kickstart.

**Pull request merged**
