### PR TITLE
[Bugfix][RHEL/6] Fix ldap client TLS checks

### LINKED ISSUE #9: ldap_client_start_tls contains incorrect OCIL (or OVAL?)
Returns a pass when according to part of the SCC check and the manual check it should fail.

### LINKED ISSUE #10: ldap_client_tls_cacertpath returns pass when OCIL shows fail
Returns a pass when manual check and part of automated check return as failing.

### PR DESCRIPTION
**Pull request by redhatrises**
- Fix pam_ldap.conf TLS XCCDF and OVAL checks in RHEL/6
- Remove ldap_client_pam_ldap_present.xml
- Fixes #9 
- Fixes #10

### CODE REVIEW

**Comment by isimluk** [comment]
Lgtm. Thanks!

**Comment by mpreisler** [comment]
This pull request broke `make validate` in Jenkins.

```
make[1]: Entering directory `/home/jenkins/workspace/scap-security-guide/RHEL/6'
oscap xccdf validate-xml output/ssg-rhel6-xccdf.xml
oscap oval validate-xml --schematron output/ssg-rhel6-oval.xml
oscap cpe validate-xml output/ssg-rhel6-cpe-dictionary.xml
oscap oval validate-xml --schematron output/ssg-rhel6-cpe-oval.xml
oscap ds sds-validate output/ssg-rhel6-ds.xml
oscap xccdf validate-xml output/ssg-centos6-xccdf.xml
oscap ds sds-validate output/ssg-centos6-ds.xml
oscap xccdf validate-xml output/ssg-sl6-xccdf.xml
oscap ds sds-validate output/ssg-sl6-ds.xml
cd output; ../utils/verify-references.py --rules-with-invalid-checks --ovaldefs-unused ssg-rhel6-xccdf.xml
OVAL Check is not referenced by XCCDF: oval:ssg:def:435
make[1]: *** [validate] Error 1
make[1]: Leaving directory `/home/jenkins/workspace/scap-security-guide/RHEL/6'
make: *** [validate] Error 2
Build step 'Execute shell' marked build as failure
```

**Comment by isimluk** [comment]
Omg, I never do anything right. :-))

**Comment by isimluk** [comment]
I have reverted this pr in f5519f3edeff355d02bba25accdd556ecb01e76b. We need to fix the `make validate` first. Sorry for churning.

**Pull request merged**
