### PR TITLE
[Bugfix] Add CentOS gpgkey to XCCDF check

### LINKED ISSUE #629: ensure_redhat_gpgkey_installed test does not work for RHEL derivatives like CentOS
For rule id: ensure_redhat_gpgkey_installed, it appears to be looking
for /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release. I'm sure this works
fine for RHEL, but the CentOS content also references this same test,
which will fail since it should be looking for
/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6 instead. Perhaps a slightly
modified version of the test is necessary for the various derivatives of
RHEL like CentOS?

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #629

### CODE REVIEW

**Comment by iankko** [comment]
LGTM. ACK. Thank you for the change.

**Comment by mpreisler** [comment]
Shouldn't we also change the Rule title?

**Comment by iankko** [comment]
Was thinking about that -- but is is possible on the fly during the build update the title? Like if build on RHEL it would speak about Red Hat key, if on CentOS about the CentOS one?

**Comment by mpreisler** [comment]
That is definitely possible. A good place to implement it is in `enable-derivatives.py`.

**Comment by redhatrises** [comment]
Would a name change make more sense if Fedora and SL are added at some point in the future?

**Pull request merged**
