### PR TITLE
[BugFix] Fix profile names when generating HTML guides for Firefox, Java, Chromium, and Webmin products. Rename Java product to JRE

### PR DESCRIPTION
**Pull request by iankko**
This patchset is performing the following two things:
* The patch https://github.com/OpenSCAP/scap-security-guide/commit/66f6ba3f65aa53b4d8fd5f65260505f4a56ca8a0
  * updates profile names when generating HTML guides for Firefox, Java, Chromium, and Webmin products (the artificial ```allrules``` profile doesn't work with new openscap version, having HTML guide & report functionality rewritten. We need to specify exact profile name for each product in order the XCCDF rules to be displayed in the guide too),
  * besides that this change has changed profile name for Webmin product from ```webmin-stig-upstream``` to ```common``` profile. After searching the NVD repository site:
  https://web.nvd.nist.gov/view/ncp/repository

there's nothing like DISA STIG benchmark for Webmin product (when compared with ```Firefox``` and ```Java``` products:
  https://web.nvd.nist.gov/view/ncp/repository/checklistDetail?id=356 (Firefox)
  https://web.nvd.nist.gov/view/ncp/repository/checklistDetail?id=445 (JRE-1.7.0)
  https://web.nvd.nist.gov/view/ncp/repository/checklistDetail?id=444 (JRE-1.6.0)

for which the ```stig-$(PROD)-upstream``` profile makes sense. Therefore keep ```stig-$(PROD)-upstream``` profile name for Firefox and Java, but rename Webmin's profile to be ```common``` one).

* The patch https://github.com/OpenSCAP/scap-security-guide/commit/7cfd4f74c2078ed3be9078cc3501b568240570fd is performing the following:
  * Rename ```Java``` product to be ```JRE```. Java benchmark is based on the following two DISA STIG benchmarks:
  [1] https://web.nvd.nist.gov/view/ncp/repository/checklistDetail?id=445 (JRE-1.7.0)
  [2] https://web.nvd.nist.gov/view/ncp/repository/checklistDetail?id=444 (JRE-1.6.0)

and it has been reported to us that ```Java``` is not appropriate / too generic term (is the benchmark for ```J2EE, J2SE, JDK``` or all of them?). Since the [1] [2] benchmarks have ```JRE``` in the name, rename the product to ```JRE``` to indicate the benchmark is for Java Runtime Environment (JRE).

Besides renaming, update necessary parts of the former ```Java``` content build process, so the renamed ```JRE``` content would still build correctly. Also enable shipping of ```Firefox``` and ```JRE``` datastream benchmarks on RHEL-6, RHEL-7, and Fedora systems by default. For now we will be shipping just datastream version of the ```Firefox``` and ```JRE``` benchmarks by default, because:
* only those contain complete information to perform the scan without the need to specify ```Firefox```, ```JRE``` CPE dictionary
* the XCCDF and OVAL files for ```Firefox``` and ```JRE``` benchmarks to work properly it is necessary to provide the CPE dictionary for those products (since ```oscap``` doesn't contain inbuilt Firefox and JRE CPE definitions yet), therefore it's non-trivial to use these benchmarks in XCCDF form, and therefore we are *not* including them to RHEL-6, RHEL-7, and Fedora systems in the default RPM (```make rpm```) target build.

Testing report:
---
The aforementioned changes have been tested on:
* RHEL-6, 
* RHEL-7,  and
* Fedora 21

systems with the following versions of JDK:
* java-1.6.0-openjdk,
* java-1.7.0-openjdk, and
* java-1.8.0-openjdk

on all three of the systems, and AFAICT from testing the content for changed ```JRE``` product is working fine.

Please review.

Thank you, Jan.

### CODE REVIEW

**Comment by iankko** [comment]
Regarding the above ```We can’t automatically merge this pull request. ``` GH message yet. I can't see any merge conflict when trying to merge this PR into current master (WFM without issues). Maybe GH got confused just because PR wasn't created immediately after the last patch has been committed, but rather couple of hours ago.

Anyway looks this change will need to be merge manually (even when there aren't conflicts). Sorry for the inconvenience.

**Comment by mpreisler** [comment]
Consider merging `master` into your branch to solve the merge conflicts. The PR author is usually more suitable for conflict resolution because they are the best at understanding their own code :-)

**Comment by isimluk** [comment]
Actually, I would suggest rebase of local branch. (In cases, when the branch is only in private repo and not pushed to main repo). Just suggestion ;-P

**Comment by iankko** [comment]
Thanks for the hints, guys!

Have rebased the local branch to current upstream content (followed the rebase approach since have [read](https://robots.thoughtbot.com/keeping-a-github-fork-updated) that rebase produces a bit cleaner history).

While doing the rebase noticed there are multiple trailing whitespace issues present in the ```Java / JRE``` content. The underlying error message is below:
```
$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: [BugFix] [Chromium] [Firefox] [Java] [Webmin]
Applying: [BugFix] Rename 'Java' product to be 'JRE' product ('Java' has
Using index info to reconstruct a base tree...
M       Java/Makefile
<stdin>:256: trailing whitespace.
<tt>deployment.properties</tt> file. The System-level configuration for Java is
<stdin>:294: trailing whitespace.
To ensure that the Java properties file is set in
<stdin>:295: trailing whitespace.
<tt>/etc/.java/deployment/deployment.config</tt>, add or modify
<stdin>:296: trailing whitespace.
<tt>deployment.system.config</tt> to equal
<stdin>:307: trailing whitespace.
Without a proper path for the properties file, deployment would not be possible.
warning: squelched 986 whitespace errors
warning: 991 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging JRE/transforms/xccdf2table-profileccirefs.xslt
Auto-merging JRE/transforms/xccdf-ocilcheck2ref.xslt
Auto-merging JRE/transforms/shorthand2xccdf.xslt
Auto-merging JRE/input/guide.xml
Auto-merging JRE/Makefile
```

While at these files, fixed those trailing issues too (this is what patch https://github.com/iankko/scap-security-guide/commit/bdeb859e9cc90793f8fd99cace32c70925a4b87e is doing).

We will deal with whitespace trailing issues in other content too in post 0.1.23 release (will file ticket for that).

This PR should be ready for re-review now.

Thanks again!, Jan.

**Comment by isimluk** [comment]
A lot of good polish. Thanks!!

**Comment by iankko** [comment]
Thanks for the review, Simon!

**Pull request merged**
