### PR TITLE
add /etc/cron.daily check to aide_periodic_cron_checking

### PR DESCRIPTION
**Pull request by lsteinke**
Add check for periodic "aide --check" invocation in /etc/cron.daily.

### CODE REVIEW

**Comment by rsprudencio** [comment]
@openscap-jenkins  test this again please

**Comment by rsprudencio** [comment]
@openscap-jenkins test this please

**Comment by rsprudencio** [comment]
@openscap-jenkins test this please

**Comment by rsprudencio** [comment]
test this please

**Comment by rsprudencio** [comment]
@openscap-jenkins test this please

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by yuumasato** [comment]
Some weird error occurred on jenkins git plugin
@openscap-jenkins test this please

**Comment by rsprudencio** [comment]
@openscap-jenkins test this please

**Comment by rsprudencio** [comment]
@openscap-jenkins retest this please

**Comment by redhatrises** [comment]
Ack.

**Pull request merged**
