### PR TITLE
ansible: dconf_gnome_banner_enabled

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by jan-cerny** [comment]
It looks like something went wrong with your git. Try `git rebase -i upstream/master`.

**Comment by mpreisler** [comment]
@shawndwells I did reviews of a bunch of your PRs and I think your local `master` is busted. Make sure you always branch off of the upstream master, not your local.

**Comment by shawndwells** [comment]
On 8/30/17 3:06 PM, Martin Preisler wrote:
> @shawndwells <https://github.com/shawndwells> I did reviews of a bunch
> of your PRs and I think your local |master| is busted. Make sure you
> always branch off of the upstream master, not your local.

I blame you for telling me to "rebase -i upstream/master".... everything
broke after ;)

**Comment by shawndwells** [comment]
The PRs took several days of effort to create. I don't have the time to re-create all this work all over again, so killing this PR. Someone else will need to build out the ansible templates....

**Comment by mpreisler** [comment]
@shawndwells keep this open and lemme push into your fork and I can fix it if I have some extra time. Right now I can't even fetch your commits.

**Comment by mpreisler** [comment]
> It looks like something went wrong with your git. Try git rebase -i upstream/master.



> I blame you for telling me to "rebase -i upstream/master".... everything
> broke after ;)

I recommend blaming something else because this was high quality advice :)

**Comment by shawndwells** [comment]
I self admit needing to learn more about git and definitely appreciate the pointers. Not sure why rebasing does this to me, though.

**Comment by shawndwells** [comment]
On 8/30/17 3:27 PM, Martin Preisler wrote:
> @shawndwells <https://github.com/shawndwells> keep this open and lemme
> push into your fork and I can fix it if I have some extra time. Right
> now I can't even fetch your commits.

I had to blow away my entire github repo, so all the work has been
completely lost.

**Comment by mpreisler** [comment]
> I had to blow away my entire github repo, so all the work has been
> completely lost.

don't touch anything, I will try to get it via the github helper fake branches.

**Comment by mpreisler** [comment]
Recovered into https://github.com/mpreisler/scap-security-guide/tree/shawn_2283

Will fix it up and make a new PR when I get time.

**Pull request closed without merging**
