### PR TITLE
Continuing NIST 800-171 profile development

### PR DESCRIPTION
**Pull request by shawndwells**
further development of 800-171 profile

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells will you remove commit bf7e65b from this PR?

**Comment by shawndwells** [comment]
jenkins retest this please

**Comment by shawndwells** [comment]
@redhatrises fixed in https://github.com/OpenSCAP/scap-security-guide/pull/1623/commits/3c184430776708bfb7826ea6446b5caa654fe2db

**Comment by shawndwells** [comment]
@mpreisler recieving weird jenkins errors. doesn't look like the code has faults, but not sure what is going on. Last few lines from jenkins:

```
cp output/ssg-centos6-xccdf.xml dist/content
cp output/ssg-centos6-ds.xml dist/content
cp output/ssg-sl6-xccdf.xml dist/content
cp output/ssg-sl6-ds.xml dist/content
make[1]: Leaving directory `/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-el7/RHEL/6'
Build step 'Execute shell' marked build as failure
Set build name.
New build name is 'origin/pr/1623/merge - #970 - Failure'
Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: 'origin/pr/1623/merge - #970 - Building', new value: 'origin/pr/1623/merge - #970 - Failure'
Finished: FAILURE
```

**Comment by shawndwells** [comment]
@mpreisler scratch that. changes were needed (resolved in https://github.com/OpenSCAP/scap-security-guide/pull/1623/commits/03367c1050a044f58402a7780521127031c0a588). Error wasn't obvious to me via jenkins.

**Comment by shawndwells** [comment]
patch set ready for review

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
