### PR TITLE
[WIP] Improve docs

### PR DESCRIPTION
**Pull request by shawndwells**
Old docs were written in DocBook and Markdown. It sucked maintaining them, so nobody actually did.

Converting things to a Jekyll-based markdown format. 

Sample screen shots
image

image

### CODE REVIEW

**Comment by matejak** [comment]
Is there any reason not to use asciidoc, as we are already using it in our developer_guide?

Plus, there is lots of javascript and CSS added, but I have difficulties to find the actual text, do you plan to add that later, or I have missed it?

**Comment by mpreisler** [comment]
@shawndwells We have user and developer guides in docs/manual/developer_guide.adoc and user_manual.adoc. Any reason why we shouldn't extend those?

Also, asciidoc works well and is very lightweight, we are using it in openscap. I would strongly prefer it over yet more doc format.

**Comment by shawndwells** [comment]
On 4/9/18 10:53 AM, Martin Preisler wrote:
>
> @shawndwells <https://github.com/shawndwells> We have user and 
> developer guides in docs/manual/developer_guide.adoc and 
> user_manual.adoc. Any reason why we shouldn't extend those?
>
> Also, asciidoc works well and is very lightweight, we are using it in 
> openscap. I would strongly prefer it over yet more doc format.
>

Oh, interesting. I had no idea those documents even existed!

**Comment by redhatrises** [comment]
@shawndwells can this PR be closed? These docs could be added in some way to static.open-scap.org to appear in the way that you would like to see them.

**Comment by mpreisler** [comment]
I volunteer to help hook this into cmake and asciidoc so that it gets built and published at static.open-scap.org

**Comment by redhatrises** [comment]
Closing. This is tracked in #2782

**Pull request closed without merging**
