### PR TITLE
Fix Ansible remediations broken by Ansible bug.

### LINKED ISSUE #2559: Ansible `ini_file` module bug breaks some remediations.
#### Description of problem:

Ansible's `ini_file` module has a [known bug](https://github.com/ansible/ansible/issues/31968) that changes case of the `true` value, so instead of

`banner-message-enabled=true`,

`banner-message-enabled = True` is output to the file.

The upstream ansible bug is not fixed and the RHEL 7.4 Ansible 2.4.1.0 exhibits this behaviour.
Unfortunatelly, `dconf` is case-sensitive and an `Invalid value: True` error is output. This is the state that the playbook aims to induce: https://help.gnome.org/admin/system-admin-guide/stable/login-banner.html.en

This silently breaks the remediation as well as all remediations that depend on it.
Remediations that are possibly affected:

* dconf_gnome_banner_enabled.yml
* dconf_gnome_disable_automount.yml
* dconf_gnome_disable_restart_shutdown.yml
* dconf_gnome_disable_thumbnailers.yml
* dconf_gnome_disable_user_admin.yml
* dconf_gnome_disable_user_list.yml
* dconf_gnome_disable_wifi_create.yml
* dconf_gnome_disable_wifi_notification.yml
* dconf_gnome_screensaver_idle_activation_enabled.yml
* dconf_gnome_screensaver_lock_enabled.yml

#### Steps to Reproduce:

1. Apply the playbook that is attached
[login_banner_fix.txt](https://github.com/OpenSCAP/scap-security-guide/files/1652191/login_banner_fix.txt)
 to the file.
2. Run `dconf update`.
3. Notice the error message.
4. Fix the case in the `/etc/dconf/db/local.d/00-security-settings` file.
5. Re-run `dconf update`, now without any errors.

### PR DESCRIPTION
**Pull request by matejak**
This PR fixes #2559 by ~applying a workaround~ properly quoting the right-hand side value.
I have tested those modified remediations on a RHEL7 VM and it works as expected.

### CODE REVIEW

**Comment by matejak** [comment]
Sure, I have rebased and removed the spaces in `" true/false"`.

**Comment by dahaic** [comment]
@matejak one more to go! :)

**Comment by matejak** [comment]
Damn. Anyway, I have rebased again.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
