### PR TITLE
Import template generators (build time optimization)

### PR DESCRIPTION
**Pull request by mpreisler**
We run template generators separately as scripts and then parse what they output on stdout. This hides errors and warnings and is much slower than just using the classes and functions directly. I am not sure what the reason for running a script that runs more scripts was but I made a quick refactor to just use the generators as classes. This results in less code and it's much faster.

~~This PR is not finished, I want to clean it all up and write it more elegantly. But first I want consensus from the community that this is the way to go. Maybe there is a reason why we run all the scripts separately.~~

Configure time:
```
old code: 51s
new code: 26s
```

Build time:
```
old code: 3m 23s
new code: 2m 54s
```

(I am working on battery, the numbers plugged in are going to be better, just included this for a comparison)

### CODE REVIEW

**Comment by mpreisler** [comment]
plugged in the numbers are:
```
configure: 16s
build: 2m 3s
```

I would love some feedback from the community. This seems like the right way to go, it already uncovered a bunch of suspect things. For example we build packages_removed in shared csv but these are built again for the products where they belong. The packages_removed.csv in shared templates can't possibly generated OVAL because the OVAL is different for RHEL and Debian.

**Comment by jan-cerny** [comment]
This looks very interesting, The speedup is great.

I'm not aware of any reason why the scripts are run separately.

**Comment by mpreisler** [comment]
This breaks the build in a bizarre way. It's building the OVAL unlinked target 3 times when these changes are applied. If anybody can tell me why I would appreciate it.

**Comment by mpreisler** [comment]
Will wait for #2116 before I debug the weird build issue, it will make the build graph way simpler.

**Comment by mpreisler** [comment]
What a mystery:
- same targets on master and this branch
- same generated dirs - $CMAKE_CURRENT_BUILD_DIR/checks and remediations are the same, exactly the same
- same inputs except this branch is missing the python script deps, that shouldn't matter for this issue though
- exactly the same outputs

wtf is going on...
```

**Comment by mpreisler** [comment]
OK, I figured it out, the outputs weren't the same. We included outputs for things that were missing templates so they were never actually written out. That's why it kept rebuilding oval-unlinked.xml

**Comment by mpreisler** [comment]
There is some new issue with dep rescan. OVAL gets rebuilt even if none of the files changed... Need to figure out what's going on and fix it before we merge.

**Comment by mpreisler** [comment]
After this is merged by far the biggest time wasters will be OVAL validations:
```
262.925 RHEL/5/validation-ssg-rhel5-oval.xml
249.489 RHEL/6/validation-ssg-rhel6-oval.xml
235.243 RHEL/7/validation-ssg-rhel7-oval.xml
144.528 OpenStack/RHEL-OSP/7/validation-ssg-rhel-osp7-oval.xml
123.681 Fedora/validation-ssg-fedora-oval.xml
54.595 Ubuntu/14.04/validation-ssg-ubuntu1404-oval.xml
54.04 Debian/8/validation-ssg-debian8-oval.xml
51.334 Ubuntu/16.04/validation-ssg-ubuntu1604-oval.xml
47.8035 ssg-rhel6-ds.xml
41.4005 ssg-rhel7-ds.xml
```

time in seconds. OVAL schematron takes forever :-(

**Comment by mpreisler** [comment]
Rebased & fixed conflicts

**Comment by dahaic** [comment]
So the schematron rules with the O(n^3) and O(n^2), being official is something we should be running. But at the same time there is no reason to stick to it as a PR gating mechanism - what about making our own, simplified, schematron rules for PR gating, which will catch most common issues that happen during SSG development (that will be some small subset of all possible errors, due to the way our build system works).

And leaving official check to be run every day. And the very small subset of errors not yet catched by our gating can be fixed by us. (Together with gating schematron update).

**Comment by mpreisler** [comment]
@dahaic  I like the idea. I would even go as far as to avoid schematron for PR gating and only do it nightly. XSD will catch 99% of all issues, the schematron is for very special and rare issues.

I will implement a PR that makes schematron checking an option via cmake and default it to disabled. We can discuss this further there.

**Comment by yuumasato** [comment]
Ack. These improvements are great.

**Pull request merged**
