### PR TITLE
Debian update to formal debian naming

### PR DESCRIPTION
**Pull request by pthierry38**
* Because Debian is not using fixed numerotation for unstable and sid release, update to official Debian name (jessie for stable), other directories will be stretch (testing, future v9), sid and unstable (without numbering).
* Updated plateform check to verify the /etc/debian_version file existence (generic debian check) before checking its content (release specific check).
* More xccdf and profile cleaning (typos, etc.).
* Deleted autogenerated xml from git.

PS: the rebase has been hard to make, which means that I'm not up to date to the exact last commit, but the validate target is working for all content.

### CODE REVIEW

**Comment by isimluk** [comment]
Can you please avoid the merge commits in the pull-requests?

There is a very nice introduction to openscap contribution written by @msrubar at https://github.com/OpenSCAP/openscap/blob/maint-1.0/docs/contribute/contribute.adoc

He went into a detail how the rebase works.

I understand that conflicts happen (and I caused some of the conflicts for you in this case). However, if you run `git pull --rebase` in master or `git fetch origin/master; git rebase origin/master` in your topic branch, you will end-up in much more clearer log history.

**Comment by redhatrises** [comment]
IMHO, I would almost lean to a NACK on this as it is based off of a project codename, and IMHO release codenames for versions should not be used. In addition, the CPE's do not match https://web.nvd.nist.gov/view/cpe/detail?keyword=debian&nonDeprecatedOnly=true&namingFormat=2.3&cpeId=2951

**Comment by pthierry38** [comment]
You're right @redhatrises, it should still be version 8.x (9.x for testing). It will make ssg usage for sid and unstable unfeasable. I propose to close that PR, I will check with Debian guys in the meantime.

**Comment by pthierry38** [comment]
I will revert to original debian_8 branch (same as your master, and cherry-pick the few commits not associated to the renaming (directory cleaning, etc.). I will also update the debian cpe using the NVD naming.

**Comment by iankko** [comment]
@pthierry38 
Based on the above this PR can be closed, right? (you gonna to open a new one once the Debian CPE issue is clarified, right?)

**Comment by pthierry38** [comment]
close done. Useful updates (not associated to renaming) has been integrated to a clean branch.

**Pull request closed without merging**
