### PR TITLE
Ansible RHEL7 scripts to shared/

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by shawndwells** [comment]
Needed to show someone the Ansible process, updated a few things:

- Moved RHEL7 Ansible scripts into shared/
- Updated headers as appropriate (multi_rhel, severity, etc)
- Added CCENUM to title of tasks

**Comment by shawndwells** [comment]
$ cmake ../ && make -j4 rhel7
$ oscap xccdf generate fix --template urn:xccdf:fix:script:ansible --profile xccdf_org.ssgproject.content_profile_ospp-rhel7 --output ansible.yaml ssg-rhel7-ds.xml

results:
`````
- name: "CCE-27433-2: Set SSH Idle Timeout Interval"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^ClientAliveInterval"
    line="ClientAliveInterval 600"

- name: "CCE-27471-2: Disable SSH Access via Empty Passwords"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^PermitEmptyPasswords"
    line="PermitEmptyPasswords no"

- name: "CCE-27314-4: Enable SSH Warning Banner"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^Banner"
    line="Banner /etc/issue"

`````

**Comment by mpreisler** [comment]
What if there is no CCE assigned?

**Comment by shawndwells** [comment]
In theory, every XCCDF rule should have a CCE and that's checked as part of the build

**Comment by mpreisler** [comment]
> In theory, every XCCDF rule should have a CCE and that's checked as part of the build

Is this true for content that's not for RHEL?

**Comment by shawndwells** [comment]
On 4/20/17 7:49 PM, Martin Preisler wrote:
>
>     In theory, every XCCDF rule should have a CCE and that's checked
>     as part of the build
>
> Is this true for content that's not for RHEL?
>

Fair. From shared/transforms/xccdf-addremediations.xslt :
> <xsl:template match="text()" mode="fix_contents">
>   <xsl:param name="rule"/>
>   <xsl:choose>
>     <xsl:when test="contains(., '$CCENUM')">
>       <xsl:variable name="ident_cce"
> select="$rule/xccdf:ident[@system='https://nvd.nist.gov/cce/index.cfm']/text()"/>
>       <xsl:call-template name="find-and-replace">
>         <xsl:with-param name="text" select="."/>
>         <xsl:with-param name="replace" select="'$CCENUM'"/>
>         <xsl:with-param name="with" select="$ident_cce"/>
>       </xsl:call-template>
>     </xsl:when>
>     <xsl:otherwise>
>       <xsl:value-of select="."/>
>     </xsl:otherwise>
>   </xsl:choose>
> </xsl:template>

We could try and add some xsl:choose....
e.g.:


<xsl:template match="text()" mode="fix_contents">
  <xsl:param name="rule"/>
  <xsl:choose>
    <xsl:when test="contains(., '$CCENUM')">
      <xsl:variable name="ident_cce"
select="$rule/xccdf:ident[@system='https://nvd.nist.gov/cce/index.cfm']/text()"/>

|<xsl:choose> <xsl:whentest="not($ident_cce)"> |||<xsl:call-template name="find-and-replace">          <xsl:with-param
name="text" select="."/>          <xsl:with-param name="replace"
select="'$CCENUM'"/>          <xsl:with-param name="with"
select="UNASSIGNED"/>       </xsl:call-template>| </xsl:when>
<xsl:otherwise> |
|<xsl:call-template name="find-and-replace">         <xsl:with-param
name="text" select="."/>         <xsl:with-param name="replace"
select="'$CCENUM'"/>         <xsl:with-param name="with"
select="$ident_cce"/>       </xsl:call-template>
</xsl:otherwise></xsl:choose>|



     
    </xsl:when>
    <xsl:otherwise>
      <xsl:value-of select="."/>
    </xsl:otherwise>
  </xsl:choose>
</xsl:template>

**Comment by shawndwells** [comment]
(switching this to work in progress while I play with the xsl:when replacements

**Comment by mpreisler** [comment]
@shawndwells Could you please remove the CCENUM for now? Then we can merge this.

I will try to do a better all round solution by either expanding the xccdf-addremediations.xslt or changing the generate fix functionality in openscap. Both would allow us to add ansible tags and registry metadata.

**Comment by shawndwells** [comment]
On 5/8/17 2:44 PM, Martin Preisler wrote:
>
> @shawndwells <https://github.com/shawndwells> Could you please remove
> the CCENUM for now? Then we can merge this.
>
> I will try to do a better all round solution by either expanding the
> xccdf-addremediations.xslt or changing the generate fix functionality
> in openscap. Both would allow us to add ansible tags and registry
> metadata.
>

ok, done via 2bcc212 and bebdc19

**Comment by mpreisler** [comment]
Jenkins taking forever, it passed on everything expect F25 and I am tired of waiting for this.

ACK

**Pull request merged**
