### PR TITLE
Ansible tags improvements

### PR DESCRIPTION
**Pull request by mpreisler**
Include a bunch more in ansible tags.

Example:
```
    - name: Ensure sysctl net.ipv4.ip_forward is set to 0
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present
        reload: yes
      tags:
        - sysctl_net_ipv4_ip_forward
        - medium_severity
        - disable_strategy
        - low_complexity
        - medium_disruption
        - CCE-80157-1
        - NIST-800-53-CM-7
        - NIST-800-53-SC-5
        - NIST-800-53-SC-32
```

Allows users to skip high_disruption items, example:
`ansible-playbook --skip-tags=high_disruption ssg-rhel7-role-ospp-rhel7.yml`

Or only remediate high severity unless it's high disruption:
`ansible-playbook --tags=high_severity --skip-tags=high_disruption ssg-rhel7-role-ospp-rhel7.yml`

### CODE REVIEW

**Comment by mpreisler** [comment]
I can also add PCI-DSS Reqs and CJIS IDs if that's valuable. Thoughts?

**Comment by redhatrises** [comment]
ack.

**Comment by redhatrises** [comment]
> I can also add PCI-DSS Reqs and CJIS IDs if that's valuable. Thoughts?

@mpreisler please do. I accidentally jumped the gun and merged this PR before having you do so.

**Comment by shawndwells** [comment]
On 7/11/17 4:29 PM, Martin Preisler wrote:
>
> Include a bunch more in ansible tags.
>
> Example:
>
> |- name: Ensure sysctl net.ipv4.ip_forward is set to 0 sysctl: name:
> net.ipv4.ip_forward value: 0 state: present reload: yes tags: -
> sysctl_net_ipv4_ip_forward - medium_severity - disable_strategy -
> low_complexity - medium_disruption - CCE-80157-1 - NIST-800-53-CM-7 -
> NIST-800-53-SC-5 - NIST-800-53-SC-32 |
>
> Allows users to skip high_disruption items, example:
> |ansible-playbook --skip-tags=high_disruption
> ssg-rhel7-role-ospp-rhel7.yml|
>
> Or only remediate high severity unless it's high disruption:
> |ansible-playbook --tags=high_severity --skip-tags=high_disruption
> ssg-rhel7-role-ospp-rhel7.yml|
>

Plz plz plz document this ability somewhere

**Comment by mpreisler** [comment]
> Plz plz plz document this ability somewhere

We don't have any docs on the roles in general, let alone this. IMO it would be great if somebody less biased than me tried to write the docs, I am willing to chime in but if I write it it's gonna be very technical and I will skip important stuff.

**Pull request merged**
