### PR TITLE
Ansible file perms

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by mpreisler** [comment]
Already done by @WesleyCeraso 

See #2184 #2183 #2182

**Comment by shawndwells** [comment]
Well crap.

@WesleyCeraso any idea when those PRs will be ready to merge?

**Comment by WesleyCeraso** [comment]
@shawndwells I hope soon.
I have not created a template for file_user_owner_* files.
Additionally, I have not created remediations for the files file_permissions_binary_dirs, file_permissions_library_dirs and file_permissions_var_log_audit.

**Comment by WesleyCeraso** [comment]
@shawndwells all my PRs are merged now

**Comment by redhatrises** [comment]
@shawndwells is this PR still needed or do the templates take care of things?

**Comment by shawndwells** [comment]
@redhatrises still needed. the templates didn't address most of the file perm issues. but something went wrong in my repo, and I don't have the days needed to recreate all this work, so closing the PRs.

**Pull request closed without merging**
