### PR TITLE
[DO NOT MERGE] New structure of templates - preview

### PR DESCRIPTION
**Pull request by ybznek**
This PR introduces **new templates structure**. If you don't like it, please say it NOW.

- easy sharing of templates between product families (using multiple values in `# product`)
- all similar remediations will be in one file, we will see duplicates more easily
- no templates in products
- transformation of templates structure is scripted - We can currently change output format very easily (only before merging)
- do you want different file/directory structure?
- what format to store multiple snippets in one file do you prefer? (I've decided not to choose xml, due to xml entities vs bash)
- Use `# product: <dir>` or rather `platform <platform>` in header?
- should be merged after https://github.com/OpenSCAP/scap-security-guide/issues/1668

[skip-ci] - shouldn't work

**Example of duplicates - will be more visible, easier to remove:**
```
################################################################################
# product: shared
# oval-version: oval_5.10
################################################################################
# platform = multi_platform_rhel, multi_platform_fedora
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
# Include source function library.
. /usr/share/scap-security-guide/remediation_functions

package_command install PKGNAME



################################################################################
# product: Debian/8
# oval-version: oval_5.10
################################################################################
# platform = Debian 8
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
# Include source function library.

apt-get install PKGNAME



################################################################################
# product: Debian/8
# oval-version: oval_5.11
################################################################################
# platform = Debian 8
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
# Include source function library.

apt-get install PKGNAME



################################################################################
# product: Ubuntu/14.04
# oval-version: oval_5.10
################################################################################
# platform = Ubuntu 1404
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
# Include source function library.

apt-get install PKGNAME



################################################################################
# product: Ubuntu/16.04
# oval-version: oval_5.10
################################################################################
# platform = Ubuntu 1604
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
# Include source function library.

apt-get install PKGNAME

```
**LOG (flow of data):**
```
./shared/templates/template_ANACONDA_package_installed => shared/templates/package_installed/anaconda
./shared/templates/template_ANACONDA_package_removed => shared/templates/package_removed/anaconda
./shared/templates/template_ANSIBLE_kernel_module_disabled => shared/templates/kernel_module_disabled/ansible
./shared/templates/template_ANSIBLE_package_installed => shared/templates/package_installed/ansible
./shared/templates/template_ANSIBLE_package_removed => shared/templates/package_removed/ansible
./shared/templates/template_ANSIBLE_permissions => shared/templates/permissions/ansible
./shared/templates/template_ANSIBLE_service_disabled => shared/templates/service_disabled/ansible
./shared/templates/template_ANSIBLE_service_enabled => shared/templates/service_enabled/ansible
./shared/templates/template_BASH_accounts_password => shared/templates/accounts_password/bash
./shared/templates/template_BASH_kernel_module_disabled => shared/templates/kernel_module_disabled/bash
./shared/templates/template_BASH_package_installed => shared/templates/package_installed/bash
./shared/templates/template_BASH_package_removed => shared/templates/package_removed/bash
./shared/templates/template_BASH_permissions => shared/templates/permissions/bash
./shared/templates/template_BASH_regex_permissions => shared/templates/regex_permissions/bash
./shared/templates/template_BASH_service_disabled => shared/templates/service_disabled/bash
./shared/templates/template_BASH_service_enabled => shared/templates/service_enabled/bash
./shared/templates/template_BASH_sysctl => shared/templates/sysctl/bash
./shared/templates/template_BASH_sysctl_var => shared/templates/sysctl/bash_var
./shared/templates/template_PUPPET_package_installed => shared/templates/package_installed/puppet
./shared/templates/template_PUPPET_package_removed => shared/templates/package_removed/puppet
./shared/templates/template_PUPPET_service_disabled => shared/templates/service_disabled/puppet
./shared/templates/template_PUPPET_service_enabled => shared/templates/service_enabled/puppet
./shared/templates/template_common.py => shared/templates/common.py/oval
./shared/templates/template_sebool => shared/templates/sebool/oval
./shared/templates/template_umask => shared/templates/umask/oval
./shared/templates/template_var_accounts_user_umask_as_number => shared/templates/var_accounts_user_umask_as_number/oval
./Fedora/templates/template_BASH_package_removed => shared/templates/package_removed/bash
./Fedora/templates/template_OVAL_package_installed => shared/templates/package_installed/oval
./Fedora/templates/template_kernel_module_disabled => shared/templates/kernel_module_disabled/oval
./Fedora/templates/template_package_removed => shared/templates/package_removed/oval
./Fedora/templates/oval_5.11_templates/template_service_enabled => shared/templates/service_enabled/oval
./RHEL/5/templates/template_BASH_kernel_module_disabled => shared/templates/kernel_module_disabled/bash
./RHEL/5/templates/template_BASH_package_removed => shared/templates/package_removed/bash
./RHEL/5/templates/template_BASH_service_disabled => shared/templates/service_disabled/bash
./RHEL/5/templates/template_BASH_service_enabled => shared/templates/service_enabled/bash
./RHEL/5/templates/template_kernel_module_disabled => shared/templates/kernel_module_disabled/oval
./RHEL/6/templates/template_BASH_kernel_module_disabled => shared/templates/kernel_module_disabled/bash
./RHEL/6/templates/template_BASH_service_disabled => shared/templates/service_disabled/bash
./RHEL/6/templates/template_OVAL_package_installed => shared/templates/package_installed/oval
./RHEL/6/templates/template_package_removed => shared/templates/package_removed/oval
./RHEL/6/templates/template_service_disabled => shared/templates/service_disabled/oval
./RHEL/6/templates/template_service_enabled => shared/templates/service_enabled/oval
./RHEL/7/templates/template_BASH_service_disabled => shared/templates/service_disabled/bash
./RHEL/7/templates/template_kernel_module_disabled => shared/templates/kernel_module_disabled/oval
./RHEL/7/templates/template_sysctl => shared/templates/sysctl/oval
./RHEL/7/templates/template_sysctl_ipv6 => shared/templates/sysctl/oval_ipv6
./RHEL/7/templates/template_sysctl_runtime => shared/templates/sysctl/oval_runtime
./RHEL/7/templates/template_sysctl_runtime_var => shared/templates/sysctl/oval_runtime_var
./RHEL/7/templates/template_sysctl_static => shared/templates/sysctl/oval_static
./RHEL/7/templates/template_sysctl_static_var => shared/templates/sysctl/oval_static_var
./RHEL/7/templates/oval_5.11_templates/template_package_removed => shared/templates/package_removed/oval
./Debian/8/templates/template_BASH_package_installed => shared/templates/package_installed/bash
./Debian/8/templates/template_BASH_package_removed => shared/templates/package_removed/bash
./Debian/8/templates/template_OVAL_package_installed => shared/templates/package_installed/oval
./Debian/8/templates/template_package_removed => shared/templates/package_removed/oval
./Debian/8/templates/template_permissions => shared/templates/permissions/oval
./Debian/8/templates/template_service_disabled => shared/templates/service_disabled/oval
./Debian/8/templates/template_sysctl => shared/templates/sysctl/oval
./Debian/8/templates/template_sysctl_ipv6 => shared/templates/sysctl/oval_ipv6
./Debian/8/templates/template_sysctl_runtime => shared/templates/sysctl/oval_runtime
./Debian/8/templates/template_sysctl_runtime_var => shared/templates/sysctl/oval_runtime_var
./Debian/8/templates/template_sysctl_static => shared/templates/sysctl/oval_static
./Debian/8/templates/template_sysctl_static_var => shared/templates/sysctl/oval_static_var
./Debian/8/templates/oval_5.11_templates/template_BASH_package_installed => shared/templates/package_installed/bash
./Debian/8/templates/oval_5.11_templates/template_OVAL_package_installed => shared/templates/package_installed/oval
./Debian/8/templates/oval_5.11_templates/template_service_disabled => shared/templates/service_disabled/oval
./Debian/8/templates/oval_5.11_templates/template_service_enabled => shared/templates/service_enabled/oval
./Ubuntu/14.04/templates/template_BASH_package_installed => shared/templates/package_installed/bash
./Ubuntu/14.04/templates/template_BASH_package_removed => shared/templates/package_removed/bash
./Ubuntu/14.04/templates/template_OVAL_package_installed => shared/templates/package_installed/oval
./Ubuntu/14.04/templates/template_package_removed => shared/templates/package_removed/oval
./Ubuntu/14.04/templates/template_permissions => shared/templates/permissions/oval
./Ubuntu/14.04/templates/template_service_disabled => shared/templates/service_disabled/oval
./Ubuntu/14.04/templates/template_sysctl => shared/templates/sysctl/oval
./Ubuntu/14.04/templates/template_sysctl_ipv6 => shared/templates/sysctl/oval_ipv6
./Ubuntu/14.04/templates/template_sysctl_runtime => shared/templates/sysctl/oval_runtime
./Ubuntu/14.04/templates/template_sysctl_runtime_var => shared/templates/sysctl/oval_runtime_var
./Ubuntu/14.04/templates/template_sysctl_static => shared/templates/sysctl/oval_static
./Ubuntu/14.04/templates/template_sysctl_static_var => shared/templates/sysctl/oval_static_var
./Ubuntu/14.04/templates/oval_5.11_templates/template_OVAL_package_installed => shared/templates/package_installed/oval
./Ubuntu/14.04/templates/oval_5.11_templates/template_service_disabled => shared/templates/service_disabled/oval
./Ubuntu/14.04/templates/oval_5.11_templates/template_service_enabled => shared/templates/service_enabled/oval
./Ubuntu/16.04/templates/template_BASH_package_installed => shared/templates/package_installed/bash
./Ubuntu/16.04/templates/template_BASH_package_removed => shared/templates/package_removed/bash
./Ubuntu/16.04/templates/template_OVAL_package_installed => shared/templates/package_installed/oval
./Ubuntu/16.04/templates/template_package_removed => shared/templates/package_removed/oval
./Ubuntu/16.04/templates/template_permissions => shared/templates/permissions/oval
./Ubuntu/16.04/templates/template_service_disabled => shared/templates/service_disabled/oval
./Ubuntu/16.04/templates/template_sysctl => shared/templates/sysctl/oval
./Ubuntu/16.04/templates/template_sysctl_ipv6 => shared/templates/sysctl/oval_ipv6
./Ubuntu/16.04/templates/template_sysctl_runtime => shared/templates/sysctl/oval_runtime
./Ubuntu/16.04/templates/template_sysctl_runtime_var => shared/templates/sysctl/oval_runtime_var
./Ubuntu/16.04/templates/template_sysctl_static => shared/templates/sysctl/oval_static
./Ubuntu/16.04/templates/template_sysctl_static_var => shared/templates/sysctl/oval_static_var
./Ubuntu/16.04/templates/oval_5.11_templates/template_OVAL_package_installed => shared/templates/package_installed/oval
./Ubuntu/16.04/templates/oval_5.11_templates/template_service_disabled => shared/templates/service_disabled/oval
./Ubuntu/16.04/templates/oval_5.11_templates/template_service_enabled => shared/templates/service_enabled/oval
```

### CODE REVIEW

**Comment by mpreisler** [comment]
Please consider waiting with this for #1377 . The cmake system is very very very close to merging.

**Comment by ybznek** [comment]
@mpreisler Not a problem. I only wanted to get some feedback, now.

**Comment by redhatrises** [comment]
@ybznek please simplify the file/dir structure. I would rather see `shared/templates/{oval,bash,ansible,anaconda,puppet}`. IMO I really don't want to know manage directories for `service_enabled`, `service_disabled`, etc.

**Comment by ybznek** [comment]
@redhatrises Actually I think, that solution with templates in directories like `service_enabled` is cleaner. You can quickly see, whether we have implemented remediation in required language for specific functionality. And in case of sysctl* we have all templates close to each other.

**Comment by yuumasato** [comment]
When contributing, are your changes most of time `{oval,bash,ansible,anaconda,puppet}` or functionality focused? 
For example, do you usually change many oval files, maybe in different functionalities, or change many types of files around one functionality?
I think that folder directory should reflect it, and it will also have effect in new contributors.

I see value in the folders inside `shared/templates`. The separation in functionalities reflects my current way of how I would make changes.

> You can quickly see, whether we have implemented remediation in required language for specific functionality.

I think this separation in functionalities can help newcomer to identify files they should tinker with when contributing.

**Comment by ybznek** [comment]
@yuumasato so, do you agree with proposed structure?

**Comment by yuumasato** [comment]
@ybznek yes!

**Comment by ybznek** [comment]
I am not able to finish it, I will close it.

**Pull request closed without merging**
