### PR TITLE
Add create-stig-overlay.py for STIG overlay generation

### PR DESCRIPTION
**Pull request by redhatrises**
- Allows for a quickly generated or update stig_overlay.xml

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells for your review. One thing that I need to weigh in on is when a new stig_overlay.xml file is generated it might remove STIGIDs that are no longer in the stig, so should we keep all old STIGID mapping if it is no longer in a new DISA release version?

**Comment by redhatrises** [comment]
Bump @shawndwells.

**Comment by shawndwells** [comment]
I don't think we should keep the old mappings. Everytime DISA generates a new STIG, the RHEL-07-* numbers are subject to change. They described this as an unfortunate side effect of their VMS import process.

With that said, we might want to keep them in a temp space to review before totally blowing away. Maybe create a "old mappings" file? Not sure of the best approach.

also fyi - On PTO for next week. Responses will be relayed.

**Comment by shawndwells** [comment]
awesome utility. thank you!

**Pull request merged**
