### PR TITLE
Update profile names and descriptions

### PR DESCRIPTION
**Pull request by shawndwells**
- Update profile titles and descriptions
- mark draft profiles with ``[DRAFT]`` in profile title, comment them out from build system

### CODE REVIEW

**Comment by shawndwells** [comment]
also resolves https://github.com/OpenSCAP/scap-security-guide/issues/2572

**Comment by shawndwells** [comment]
@mpreisler this renames profiles like we chatted about.

bump for a review... future PRs will be held up on the profile renaming

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
NACK, this needs a rebase. @shawndwells make sure your master matches the upstream master exactly. then switch to the feature branch and run `git rebase -i master`

**Comment by shawndwells** [comment]
`````
$ git checkout master
Switched to branch 'master'

$ git fetch upstream

$ git checkout issue2572
Switched to branch 'issue2572'

$ git rebase -i master
# HEAD detached at 3d5c25c
# You are currently rebasing branch 'issue2572' on '2555c97'.
#   (all conflicts fixed: run "git rebase --continue")
#
nothing to commit, working directory clean

$ git push
Enter passphrase for key '/home/shawn/.ssh/redhat_id_rsa': 
To git@github.com:shawndwells/scap-security-guide.git
 ! [rejected]        issue2572 -> issue2572 (non-fast-forward)
error: failed to push some refs to 'git@github.com:shawndwells/scap-security-guide.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
`````

**Comment by shawndwells** [comment]
force pushed

**Comment by mpreisler** [comment]
git fetch XYZ doesn't update your local master, it just updates your FETCH_HEAD. you need to do `git checkout master; git pull --ff-only upstream master`

**Pull request closed without merging**
