### PR TITLE
Removed shared remediation_functions file

### LINKED ISSUE #1291: [RFE] [Infrastructure] Generate $(OUT)/remediation_functions.xml dynamically from shared/remediations/bash/templates/remediation_functions
See:
- https://github.com/OpenSCAP/scap-security-guide/pull/1270#issuecomment-222984282

[Thanks to a recent change](https://github.com/OpenSCAP/scap-security-guide/pull/1270) the remediation scripts are now part of final benchmark itself (no need to rely on external `/usr/share/scap-security-guide/remediation_functions` sh library).

But in the current form `shared/xccdf/remediation_functions.xml` has been generated manually only once (it's not regenerated during the build process). The issue here is each time a new function got added into `shared/remediations/bash/templates/remediation_functions` the `shared/xccdf/remediation_functions.xml` will need to be created again.

To get rid of this need, the above proposal mentions creation of `$(OUT)/remediation_functions.xml` file during each build from `shared/remediations/bash/templates/remediation_functions`.

We need to implement this.

### PR DESCRIPTION
**Pull request by mpreisler**
The file is a lie, there is no file. It's just used as a token to be replaced.

This should fix #1291 although I admit it's fixed in a drastically simpler way than the ticket suggests.

Let me know what you think.

CC @dahaic as this is related to his PR #1644

### CODE REVIEW

**Comment by redhatrises** [comment]
Personally, I would rather generate remediation_functions.xml rather than delete the bash remediation_functions file which makes coding, debugging, and verifying bash scripts easier. I'm all for the `$SHARED_REMEDIATION_FUNCTIONS` variable.

**Comment by mpreisler** [comment]
@redhatrises Converting from XML to bash would be much easier, perhaps we could do that for debugging.

@iankko Do you have the script you used to generate the remediation_functions.xml? Or did you do it by hand?

**Comment by mpreisler** [comment]
The PR fails on ShellCheck on the $SHARED_REMEDIATION_FUNCTIONS. We should probably use a different token that has no meaning in shell.

**Comment by iankko** [comment]
@mpreisler 
> @iankko Do you have the script you used to generate the remediation_functions.xml? Or did you do it by hand?

Hey Martin,
  unfortunately no. Was generated by hand first time (needed to have first version out quickly to made a release).

But AFAICT something like the following could work - but was just thinking of it, didn't test / implement it:
* include the bash source of the bash implementation by `.` | `source`-ing it,
* then use something like `declare -f` to get the bash function definition including its code,
* finally replace the "forbidden XML characters" (in our case mainly "&" and "<" IIRC) with the corresponding XML entity numbers / sequences) in that code,
* generate `remediations.xml` from scratch, and replace the current form.

The idea was to keep *.sh version (so contributors could edit just bash form, which is more easily readable), and produce *.xml from it. But IIRC didn't solve the issue, how to produce the comments / descriptions for the functions (probably this was the reason this wasn't implemented yet). But maybe the function comments / descriptions could stay fixed, and be retrieved / extracted by each *.sh to *.xml generation step.

HTH, Jan

**Comment by mpreisler** [comment]
Rebased

**Comment by mpreisler** [comment]
@iankko Yeah, creating such a transform would be trivial. I am surprised you did it by hand. Writing the script to do it takes less time than doing it by hand.

This is stalled and needs more community feedback.

**Comment by mpreisler** [comment]
Will write a script to generate it at some point. Right now it's not a priority.

**Pull request closed without merging**
