### PR TITLE
Firewalld ansible fixes

### PR DESCRIPTION
**Pull request by mpreisler**
Also wanted to add ansible fix for DefaultZone but I couldn't figure out how to do it in an elegant way.

### CODE REVIEW

**Comment by redhatrises** [comment]
`complexity=low`
`strategy=restrict`
`disruption=high`

**Comment by mpreisler** [comment]
@redhatrises is it really restrict if we are enabling ports?

**Comment by redhatrises** [comment]
I guess it could be `configure`.

https://scap.nist.gov/specifications/xccdf/xccdf_element_dictionary.html#fixStrategyEnumType

**Comment by mpreisler** [comment]
@redhatrises DONE

**Comment by redhatrises** [comment]
Ack.

**Pull request merged**
