### PR TITLE
[Enhancement][Bugfix][RHEL6/7] Standardize XCCDF and OVAL names

### PR DESCRIPTION
**Pull request by redhatrises**
The XCCDF Rule id's and OVAL id's were mismatched. This fixes that.

### CODE REVIEW

**Comment by redhatrises** [comment]
Thought I would go a head and propose this for `0.1.27`. Some of the names may need to be the XCCDF rule name rather than the OVAL name.

**Comment by mpreisler** [comment]
I am not saying it's a blocker for merging but I would much prefer if we kept the XCCDF IDs and changed the OVAL IDs. The XCCDF IDs are used for tailoring and changing them breaks tailoring files that users have created.

**Comment by redhatrises** [comment]
Thanks @mpreisler.

@iankko do you also concur?

**Comment by iankko** [comment]
@redhatrises 
> Thanks @mpreisler. One thing to note is that the OVAL id's, OVAL checks themselves, and the remediation scripts will have to change as well (seems like a more complicated change, but nonetheless doable.)
> 
@iankko do you also concur?

Though I agree with Martin it's a bad practice to change XCCDF IDs the users under their hands (they got accustomed to them and comparing the results retrieved across various SSG versions - if the results match, which new rules got included etc.) IMHO sometimes it's necessary to keep the OVAL ID and change the XCCDF ID. Example case would be when e.g. there would be available OVAL checks for multiple products with that them, and <b>mainly</b> if the existing OVAL ID falls better in the existing naming scheme already used for that system property.

Example:
```
$ pwd
 ...  /scap-security-guide/shared/oval
$ ls accounts_password* | wc -l
16
```

In other words would you need to consider renaming rule of the template ```accounts_passwords_pam_...``` whatever to handle another pam setting, I would propose to keep OVAL ID even if this would mean XCCDF ID would change. Another example might be ```audit_rules_*_``` -- would you consider renaming some audit rule checking ```some_systemcall``` it would be better named ```audit_rules_some_systemcall``` rather than some completely unrelated rule name that might be in the XCCDF. I would prefer this scheme because it allows to group the OVAL checks together into the groups (easily see which of them are implemented, and which needs to be yet). Another examples of this naming would be ```kernel_module_*``` or ```sysctl_*```, ```package_*``` etc.

But should you consider renaming some standalone rule, I would say choose the whatever ID (XCCDF or OVAL) which makes more sense (which describes the corresponding requirement more appropriately). And I would prefer XCCDF IDs in this group. But even here if existing OVAL ID is more meaning than XCCDF ID I would tend to use the more meaningful one even if it wouldn't be XCCDF one (IOW even if it might break the tailoring files).

@redhatrises 
When on this already, please check also naming of remediation scripts (if the names are uniform / match the XCCDF / OVAL ID), so we prevent situations we have remediation for that rule already, but it isn't called just due the different name.

Btw. thanks a lot for performing this naming standardization - it's pretty well required feature (people start to depend on the IDs we use already), so we should unify them (e.g. use same ID for XCCDF, OVAL & corresponding remediation) sooner than later.

Hope the above being helpful

Thanks, Jan.

**Comment by redhatrises** [comment]
@iankko I believe that this is ready for your review.

**Comment by iankko** [comment]
@redhatrises 
> @iankko I believe that this is ready for your review.

Thanks, I will have a look. Could you hopefully in the meantime fix the merge conflicts? (the infrastructure changes introducing 'xccdf' folder and renaming 'fixes' to remediations have been merged in between, placing the barrier to be able to merge this).

But I will review anyway (those two merged changes are just cosmetic changes, changing the presentation layer).

**Comment by redhatrises** [comment]
@iankko I will fix merge issues.

**Comment by redhatrises** [comment]
@iankko Jenkins build has passed post merge fixes.

**Comment by iankko** [comment]
LGTM. ACK.

**Comment by redhatrises** [comment]
Thanks @iankko!

**Pull request merged**
