### PR TITLE
[BugFix] [Infrastructure] Fix for issue #1275 Also fix couple of instances of issue #50

### PR DESCRIPTION
**Pull request by iankko**
Fixes: https://github.com/OpenSCAP/scap-security-guide/issues/1275

Modify the buildsystem (namely the ```append()``` routine of ```combineovals.py``` helper) to exit with error in the case multiple OVAL entities share the same ID, but have different implementation / semantics

Also modify the build system not to issue a warning for the case just ```<external_variable>``` with duplicate ID is encountered during OVAL file build. This scenario is safe, since the ```<external_variable>``` is listed another time in the specific OVAL check just for the purpose of ```testoval.py``` helper to replace it with actual local OVAL variable definition in the case just one OVAL check is tested via ```testoval.py``` (but the ID is already present in the final OVAL in the case when SSG is build, since duplicate ID with the same element tag is reported)

Also fixes couple of another instances of issue #50 (replace couple of duplicate OVAL entities declarations with their own dedicated OVAL definition and referencing that definition in the necessary places -- original checks using these entities).

Please review.

Thank you, Jan

### CODE REVIEW

**Comment by iankko** [comment]
I will fix the build failure tomorrow. 

DO NOT MERGE YET

**Comment by iankko** [comment]
The failures has been fixed (this is safe to be reviewed now).

**Comment by iankko** [comment]
Just to clarify this PR will address #1275. But won't completely fix #50 (more changes are necessary that one to be corrected). But those changes can be applied in future PRs (since the duplicate OVAL ID warnings are unrelated with #1275).

**Comment by iankko** [comment]
The routine checking equality of elements will obviously need to ignore differences in the following:
* ```comment``` attribute,
* ```version``` attribute,
* ```xmlns``` namespaces attributes (since the first element got already added into final OVAL, it will have namespaces already expanded to the final form. While the second one, to be added yet, will have just XMLNS from the specific OVAL definition).

These all should be safe to be ignored, since any differences in them won't have impact on semantics of the definition / test / object etc. On the other hand, we want to report inequality if there's some diff in ```check```, ```check_existence``` attributes, or difference in the children (for example included test containing just object, while the other to be included containing both object + state).

@mpreisler , @redhatrises 
Anything else I might possibly forget, that should have been ignored?

**Comment by redhatrises** [comment]
@iankko what about `state_operator` and `deprecated`?

**Comment by iankko** [comment]
This will fail on RHEL-5 content yet (but it's expected failure) -- since children of the duplicate ID aren't same. Will fix that.

**Comment by iankko** [comment]
All OVAL checks that used duplicate IDs for definitions, tests, but differed somewhere below in the implementation of children (OVAL objects, OVAL states) have been corrected now.

This is safe to review now (sorry it took that long).

Thanks, Jan

**Comment by redhatrises** [comment]
@iankko 

- Can `template_umask` and `template_var_accounts_user_umask_as_number` use the consolidated ones under `shared/templates`?

**Comment by iankko** [comment]
@redhatrises 
> @iankko
> Can template_umask and template_var_accounts_user_umask_as_number use the consolidated ones under shared/templates?

Yeah, probably. Will check that. There definitely is intention to move all of the possible templates into ```shared/``` folder (both the OVAL and remediations ones). And keep in per-product folder only those that differ for that product (e.g. sysctl_template RHEL-6 vs RHEL-7 / Fedora to mention some example).

Good catch. Will look into this yet.

**Comment by iankko** [comment]
template_umask and template_var_accounts_user_umask_as_number templates have now been moved to ```shared/templates``` folder.

**Comment by redhatrises** [comment]
LGTM. Ack!

**Pull request merged**
