### PR TITLE
[Bugfix][RHEL/6] Fix ldap client TLS checks

### PR DESCRIPTION
**Pull request by redhatrises**
- Fix pam_ldap.conf TLS XCCDF and OVAL checks in RHEL/6
- Remove ldap_client_pam_ldap_present.xml

### CODE REVIEW

**Comment by redhatrises** [comment]
Retry of #619. Ran `make validate` and get no errors.

As far as Jenkins, are we no longer running Jenkins checks when a PR is made?

**Comment by mpreisler** [comment]
Hi, Jenkins still fails.

```
cd output; ../utils/verify-references.py --rules-with-invalid-checks --ovaldefs-unused ssg-rhel6-xccdf.xml
OVAL Check is not referenced by XCCDF: oval:ssg:def:453
make[1]: *** [validate] Error 1
```

**Comment by redhatrises** [comment]
@mpreisler note sure why Jenkins is failing. Is there any more output or info? Here is some of the testing I did:

`mkdir validate && cd validate`
`git clone https://github.com/redhatrises/scap-security-guide.git`
`cd scap-security-guide`
`git checkout -b redhatrises-pam_ldap_check_fixes_2 master `
`git pull https://github.com/redhatrises/scap-security-guide.git pam_ldap_check_fixes_2 `
`cd RHEL/6`
`make && make validate`

`mkdir validate2 && cd validate2`
`git clone https://github.com/redhatrises/scap-security-guide.git`
`cd scap-security-guide`
`git checkout -b redhatrises-pam_ldap_check_fixes_2 master `
`git pull https://github.com/redhatrises/scap-security-guide.git pam_ldap_check_fixes_2 `
`git format-patch -M -C --patience --full-index -1`
`git checkout master`
`git am 0001-*.patch`
`cd RHEL/6`
`make && make validate`

Both times `make validate` passed.

**Comment by iankko** [comment]
@mpreisler 
> Hi, Jenkins still fails.
>```
cd output; ../utils/verify-references.py --rules-with-invalid-checks --ovaldefs-unused ssg-rhel6-xccdf.xml
OVAL Check is not referenced by XCCDF: oval:ssg:def:453
make[1]: *** [validate] Error 1
```

Not sure why, but there truly seems to be something wonky with that Jenkins slave. I can't reproduce the above reported ```make validate``` failure either (have tried on all three -- most recent RHEL-6, RHEL-7, and Fedora 22 hosts, both running ```make validate``` in ```RHEL/6``` folder directly, and also running ```make && make validate``` at the root of scap-security-guide Git clone).

Nothing like missing ```oval:ssg:def:453``` reported. Hopefully we could identify the issue having look at the Jenkins slave performing the build job in question. Locate the ```453``` item in ```RHEL/6/output/ssg.ini``` file to find out exact rule name it's trying to find && isn't successful to.

Also, we should probably double-check the timestamps on the generated ```RHEL/6/output/ssg.ini``` file with timestamps on the generated OVAL / XCCDF files (if there isn't chance ```ssg.ini``` file wasn't regenerated [IOW was kept the original one], and should be).

Otherwise can't think of another issue, that might be causing Jenkins slave to fail this way (as said tried manually on all three products && can't reproduce the failure reported either).

**Comment by mpreisler** [comment]
Hi,
looking into this again, will post the value in `ssg.ini`.

@redhatrises : Could you rebase and get rid of the merge commit?

**Comment by redhatrises** [comment]
> @redhatrises : Could you rebase and get rid of the merge commit?

@mpreisler rebase done

**Comment by redhatrises** [comment]
@mpreisler any status?

**Comment by mpreisler** [comment]
Hi @redhatrises , thanks for bumping this, it completely slipped under my radar. Will look at this after #660 is done and we are back in a "sane" state regarding `make validate`.

**Comment by mpreisler** [comment]
@redhatrises , this still fails on Jenkins, could you please check why? Your github account can be used for login.

https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/77/console

**Comment by iankko** [comment]
@redhatrises 

This PR is overly complex already (hard to trace down the history of changes). Gabe, please:
* 1) Ignore the fact for now that ```make-validate``` target is currently failing in Fedora </br>
      https://github.com/OpenSCAP/scap-security-guide/issues/661

   I broke it, so will fix it.

* 2) Please create another / clean "Fix ldap client TLS checks" PR containing just the original change / commit you wanted to add (before the effort to trying to fix things in Fedora's ```make-validate``` too).

Thank you && Regards, Jan.

**Pull request closed without merging**
