### PR TITLE
Pci dss cjis ansible tags

### PR DESCRIPTION
**Pull request by mpreisler**
Requested in #2148

### CODE REVIEW

**Comment by mpreisler** [comment]
One thing that I don't like is that if CJIS or PCI-DSS versions changes this will stop working. Should we just check that it starts with some prefix?

**Comment by mpreisler** [comment]
Example:
```
    - name: "Prevent Log In to Accounts With Empty Password"
      replace:
        dest: /etc/pam.d/system-auth
        regexp: 'nullok\s*'
        replace: ''
      tags:
        - no_empty_passwords
        - high_severity
        - configure_strategy
        - low_complexity
        - medium_disruption
        - CCE-27286-4
        - NIST-800-53-AC-6
        - NIST-800-53-IA-5(b)
        - NIST-800-53-IA-5(c)
        - NIST-800-53-IA-5(1)(a)
        - PCI-DSS-Req-8.2.3
        - CJIS-5.5.2
```

**Comment by redhatrises** [comment]
@mpreisler probably should just check if it starts with a prefix.

**Comment by jan-cerny** [comment]
We somehow handle this in OpenSCAP HTML report (eg. "Group By" menu), I don't remember exactly how. I suggest investigating if we can do same or similar thing here.

**Comment by mpreisler** [comment]
> We somehow handle this in OpenSCAP HTML report (eg. "Group By" menu), I don't remember exactly how. I suggest investigating if we can do same or similar thing here.

Thx for the suggestion. I have investigated it and we indeed check for prefix. Implemented a drive by enhancement, see https://github.com/OpenSCAP/openscap/pull/780

Will check in a similar fashion in SSG transforms.

**Comment by mpreisler** [comment]
Now we check by prefixes. I also included NIST 800-171 IDs.

Example:
```
    - name: "Prevent Log In to Accounts With Empty Password"
      replace:
        dest: /etc/pam.d/system-auth
        regexp: 'nullok\s*'
        replace: ''
      tags:
        - no_empty_passwords
        - high_severity
        - configure_strategy
        - low_complexity
        - medium_disruption
        - CCE-27286-4
        - NIST-800-53-AC-6
        - NIST-800-53-IA-5(b)
        - NIST-800-53-IA-5(c)
        - NIST-800-53-IA-5(1)(a)
        - NIST-800-171-3.1.1
        - NIST-800-171-3.1.5
        - PCI-DSS-Req-8.2.3
        - CJIS-5.5.2
```

**Comment by jan-cerny** [comment]
Thank you.

**Pull request merged**
