### PR TITLE
Package firewalld installed

### PR DESCRIPTION
**Pull request by yuumasato**
Adds Rule `package_firewalld_installed` and its remediation.
Also extends remediation of firewalld related rules to install firewalld package.

### CODE REVIEW

**Comment by redhatrises** [comment]
Not sure that the `package_firewalld_installed` rule needs to be added to all the profiles as the remediations will make sure that it is added. One reason that I am bringing this up is that for the STIG profile we need to have a corresponding unique STIGID.

**Comment by dahaic** [comment]
@redhatrises could we consider both rules (together) to be implementation of one STIGID? Because if we put package installation into ```service_firewalld_enabled``` it will be inconsistent with the rest of SSG. (Unless we can remove it across the board, and have only ```service_x_enabled```. But this works only for enabling, because if you want to enable, you have to install. Disabling would need to stay with two rules, which would create just another inconsistency).

**Comment by redhatrises** [comment]
@dahaic we cannot consider as one STIGID. It is a separate installing and enabling are separate configuration items. For the XCCDF portion, we should be implementing similar #2122..... now if only https://github.com/OpenSCAP/openscap/pull/769 was completed and merged.... (/me looks at @yuumasato)

**Comment by yuumasato** [comment]
Can you say which Profiles consider installed and enabled as different configuration items? Just STIG?

> For the XCCDF portion, we should be implementing similar #2122.....

But if we add the `requires` element we will have to add `package_firewalld_installed` into STIG Profile, otherwise `set_firewalld_default_zone` will be deselected.

**Comment by redhatrises** [comment]
Probably all of the government, PCI, etc. profiles.

> But if we add the `requires` element we will have to add `package_firewalld_installed` into STIG Profile, otherwise `set_firewalld_default_zone` will be deselected.

Since it is required, shouldn't it be selected and not deselected?

**Comment by yuumasato** [comment]
The `requires` element deselects Rules whose `requires` are not satisfied. It doesn't select deselected Rules to satisfy a specific Rule `requires`.

So, if Rule `set_firewalld_default_zone` requires `package_firewalld_installed`, and STIG profile has
- `package_firewalld_installed` not selected and,
- `set_firewalld_default_zone` selected, 
the scanner will deselect `set_firewalld_default_zone` because its `requires` were not met.

**Comment by yuumasato** [comment]
Maybe I should drop whole commit 37900e5. 
Or do you see usefulness in XCCDF Rule `package_firewalld_installed`?

**Comment by redhatrises** [comment]
@yuumasato keep the rule just don't add it to the profiles (for now).

**Comment by yuumasato** [comment]
I have dropped the selectors in the Profiles.

**Comment by redhatrises** [comment]
@yuumasato please resolve the conflicts.

**Comment by yuumasato** [comment]
Should be good now.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
