### PR TITLE
Unshadow the bootloader_audit_argument.sh bash fix

### PR DESCRIPTION
**Pull request by mpreisler**

### CODE REVIEW

**Comment by redhatrises** [comment]
Tempting.... but does `/etc/default/grub` exist on RHEL6?

**Comment by redhatrises** [comment]
hahaha.... nevermind... I see what you did there. ;)

**Comment by mpreisler** [comment]
> hahaha.... nevermind... I see what you did there. ;)

wicked smaht, right?

**Comment by redhatrises** [comment]
Ack

**Pull request merged**
