### PR TITLE
Ansible accounts umask etc login defs

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by WesleyCeraso** [comment]
The bash remediation uses the variable var_accounts_user_umask. Is it possible to use it in an ansible remediation?

**Comment by mpreisler** [comment]
> The bash remediation uses the variable var_accounts_user_umask. Is it possible to use it in an ansible remediation?

Isn't that what `line: UMASK (ansible-populate var_accounts_user_umask)` is doing?

**Comment by shawndwells** [comment]
@mpreisler yes

**Comment by WesleyCeraso** [comment]
Oh, sorry... that's fine. Well, it's good for me.

**Comment by WesleyCeraso** [comment]
ACK

**Pull request merged**
