### PR TITLE
Added RHEL 5 SCAP content.

### PR DESCRIPTION
**Pull request by thenefield**
Added SCAP content aligned with the DISA STIG for Red Hat Enterprise Linux 5.

### CODE REVIEW

**Comment by shawndwells** [comment]
and the award for the biggest patch bomb goes to @thenefield =)

it's going to be untenable to review every XCCDF and OVAL check in an initial merge. A possible approach would be to drop a disclaimer (````RHEL/5/DISCLAIMER````) saying this content is under heavy development, etc etc. In this way the community can churn & submit incremental patches.

what does everyone think about that?

**Comment by shawndwells** [comment]
note: as part of the initial merge, please cleanup the misc. RHEL6 artifacts (the STIG notes, mostly) and squash the commits.

**Comment by redhatrises** [comment]
> it's going to be untenable to review every XCCDF and OVAL check in an initial merge. A possible approach would be to drop a disclaimer (RHEL/5/DISCLAIMER) saying this content is under heavy development, etc etc. In this way the community can churn & submit incremental patches.

> what does everyone think about that?

+1

**Comment by thenefield** [comment]
Can you please elaborate on what "squash the commits" means? Thanks!

**Comment by redhatrises** [comment]
@thenefield does this help? http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by shawndwells** [comment]
On 2/25/15 2:38 PM, redhatrises wrote:
>
> @thenefield <https://github.com/thenefield> does this help? 
> http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
>

Exactly. Since we're patch bombing, it helps keep things tidy when 
reviewing.

Something like...

git checkout <your rhel5 branch>
git merge --squash
git commit

it'll generate a single patch that you can then resubmit. e.g.

git push <your rhel5 branch name> origin

Once you push, it should update the pull request automatically.

**Comment by thenefield** [comment]
Excellent! Thanks for the feedback. I will give it a shot.

**Comment by thenefield** [comment]
ok I just tried squashing my commits for firefox. Did it work? I specified
my branch as the remote but it said "(nothing to squash)Already
up-to-date.".

**Comment by thenefield** [comment]
Should this disclaimer go in (RHEL/5/input/auxiliary/DISCLAIMER) as is the
others? Is it acceptable to utilize similar content as follows:

"The SCAP content provided for Red Hat Enterprise Linux 5, is based on the
STIG requirements released by the DISA FSO. However, this content is in its
initial stage of development and will be subject to ongoing changes as it
matures. Use of this content is at your own risk.

As a result of the upstream/downstream relationship between the SCAP
Security
Guide project and the official DISA FSO STIG baseline, users should expect
variance between SSG and DISA FSO content. For official DISA FSO STIG
content,
refer to http://iase.disa.mil/stigs/os/unix/red_hat.html.

While this profile is packaged by Red Hat as part of the SCAP Security Guide
package, please note that commercial support of this SCAP content is NOT
available. This profile is provided as example SCAP content with no
endorsement
for suitability or production readiness. Support for this profile is
provided
by the upstream SCAP Security Guide community on a best-effort basis. The
upstream project homepage is https://fedorahosted.org/scap-security-guide/."

**Comment by shawndwells** [comment]
On 2/25/15 3:28 PM, thenefield wrote:
> Should this disclaimer go in (RHEL/5/input/auxiliary/DISCLAIMER) as is the
> others? Is it acceptable to utilize similar content as follows:

The RHEL5 content doesn't follow the same development relationship 
(yet?) with NSA and DISA, so lets drop the disclaimer directly into 
RHEL/5/DISCLAIMER.

Because the upstream-downstream relationship hasn't been formed, nor 
have we figured out how to ship the content, the first paragraph is 
sufficient:
> "The SCAP content provided for Red Hat Enterprise Linux 5 is based on the
> STIG requirements released by the DISA FSO. However, this content is 
> in its
> initial stage of development and will be subject to ongoing changes as it
> matures. At this point in development there should be no expectation of
> accuracy or completeness.

Note the reqording of 'use at your own risk.' IMHO that sentence is 
always a bit harsh.

**Comment by thenefield** [comment]
Thanks for the feedback! It has been committed.

**Comment by shawndwells** [comment]
On 2/25/15 2:56 PM, thenefield wrote:
> ok I just tried squashing my commits for firefox. Did it work? I specified
> my branch as the remote but it said "(nothing to squash)Already
> up-to-date.".

We can try another way. Make sure you're at the top of your source tree 
(scap-security-guide/).

# Checkout your firefox branch
$ git checkout ssg-firefox

# Reset your branch against origin/master
# This effectively clears out all your commits,
# but keeps your code changes in place
$ git reset origin/master

# Stage all your changes into a single commit
$ git add --all

# Actually do the commit
$ git commit -a

# Push your changes
$ git push origin ssg-firefox

**Comment by thenefield** [comment]
Thanks! I will give that another go. I realized that I need to also include
spec file changes for the new content. I will test it out with that change
for each.

**Comment by thenefield** [comment]
So no luck. It seemed to pull in all the changes when I performed a commit.

Here is what I get when pushing:

[root@localhost scap-security-guide]# git push origin ssg-firefox
To https://thenefield@github.com/thenefield/scap-security-guide.git
 ! [rejected]        ssg-firefox -> ssg-firefox (non-fast-forward)
error: failed to push some refs to '
https://thenefield@github.com/thenefield/scap-security-guide.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes before pushing again.  See the 'Note about
fast-forwards' section of 'git push --help' for details.

Any words of advice?

**Comment by thenefield** [comment]
Should I just use the --force option?

**Comment by thenefield** [comment]
So I went ahead and tried the --force option and it pushed the firefox content. Can you check that to make sure it did what you intended, before I start updating the others?

**Comment by redhatrises** [comment]
> I realized that I need to also include spec file changes for the new content. I will test it out with that change for each.

@thenefield I can update the .spec file for you if you are interested. I was going to do a PR to clean up the .spec file as is. Let me know.

**Comment by thenefield** [comment]
Thanks! I will get the spec file changes in. I have them ready to go. I
just wanted to be sure that the process I used on the firefox content for
"squashing commits" were as expected, so that I can follow suite with the
other changes. Have a look and let me know. Thanks!

**Comment by shawndwells** [comment]
performed merge to get the RHEL5 content into the community. Added a few patches:


c8d945c  - linking shared/verify-input-sanity.py into RHEL5 content
27b1bca  - updated build to reflect upstream profile, removed puppet remediation… …
3050d89  - renamed STIG profile to reflect -upstream
46a7e4a  - removing RHEL5 from RPM build, commented out code for when content is ready to ship
f628527  - removing RHEL6 CCEs from RHEL5 content
13640d4  - removing test attestations
530474e  - updating oscapsupportssvg.py
5481579  - Moved DISCLAIMER from input/auxiliary to RHEL/5/, updated language to… …

**Pull request merged**
