### PR TITLE
continuing french ANSSI integration

### PR DESCRIPTION
**Pull request by pthierry38**
Adding sysctl to Deb8 XCCDF, in conformity with ANSSI NT28 Req 23
Updated existing rules with anssi references
Cleaning XCCDF content (deleted some RH-specific CCE & test-attestation)
Add table-ref for ANSSI best practices.

### CODE REVIEW

**Comment by shawndwells** [comment]
@pthierry38 / @PThierry - Well this is embarrassing. Was looking at pull requests and noticed this never got merged. I can't find any reasons why it shouldn't be, so merging now.

**Comment by iankko** [comment]
@shawndwells 
Thanks for taking this!

@pthierry38 / @PThierry 
Sorry, this was waiting in the queue that long. Maybe small kind request related with this -- unless really necessary to finish the new feature / functionality in question in one batch, would it be possible to split PR having multiple commits rather into more smaller ones?

Bigger PRs are more likely to get stuck in the queue because:
* they have bigger requirements for the time availability of the reviewer,
* there's higher chance something will break / the reviewer will overlook something validating bigger PRs.

Therefore personally I like more having dozen of PRs containing just 3-4 commits, than one big one containing more commits / editing lot of files at once.

Do you think it would be possible to split future ones into smaller pieces? The advantages here are obvious:
* less demanding of time availability of the reviewer (e.g. small one can be reviewed during 10 mins after finishing something and before starting something else),
* less probability to introduce some problem (since the scope / list of changes) of such PRs is limited.

Thank you for the consideration. And sorry again for blocking this one for such long period of time.

Jan

**Comment by PThierry** [comment]
No problem. I can do smaller PR if it is easier for you. 

Le 25 février 2016 14:47:46 GMT+01:00, "Ján Lieskovský" <notifications@github.com> a écrit :
>@shawndwells 
>Thanks for taking this!
>
>@pthierry38 / @PThierry 
>Sorry, this was waiting in the queue that long. Maybe small kind
>request related with this -- unless really necessary to finish the new
>feature / functionality in question in one batch, would it be possible
>to split PR having multiple commits rather into more smaller ones?
>
>Bigger PRs are more likely to get stuck in the queue because:
>* they have bigger requirements for the time availability of the
>reviewer,
>* there's higher chance something will break / the reviewer will
>overlook something validating bigger PRs.
>
>Therefore personally I like more having dozen of PRs containing just
>3-4 commits, than one big one containing more commits / editing lot of
>files at once.
>
>Do you think it would be possible to split future ones into smaller
>pieces? The advantages here are obvious:
>* less demanding of time availability of the reviewer (e.g. small one
>can be reviewed during 10 mins after finishing something and before
>starting something else),
>* less probability to introduce some problem (since the scope / list of
>changes) of such PRs is limited.
>
>Thank you for the consideration. And sorry again for blocking this one
>for such long period of time.
>
>Jan
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenSCAP/scap-security-guide/pull/1023#issuecomment-188790116

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by iankko** [comment]
Brilliant. Thank you.

**Pull request merged**
