### PR TITLE
Debian8: clean generated files

### PR DESCRIPTION
**Pull request by ybznek**
https://github.com/OpenSCAP/scap-security-guide/issues/1668
In oval_5.10 several package_installed remediations were introduced.

### CODE REVIEW

**Comment by ybznek** [comment]
test this please, again

**Comment by ybznek** [comment]
master is failing... https://jenkins.open-scap.org/job/scap-security-guide/

**Comment by ybznek** [comment]
test this please

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
