### PR TITLE
[Bugfix][RHEL6/7] Add IPv6 equivalents to IPv4 sysctl

### LINKED ISSUE #1214: IPv6 sysctl
The IPv4 settings need IPv6 equivalents

### PR DESCRIPTION
**Pull request by redhatrises**
- Adds IPv6 XCCDF/OVAL content that is equivalent to IPv4 sysctl XCCDF/OVAL content
  NOTE: Not all IPv4 sysctl XCCDF/OVAL content has correspond IPv6 sysctl equivalents
- Fixes #1214

### CODE REVIEW

**Comment by iankko** [comment]
@openscap-jenkins 
re[test this please]

**Comment by iankko** [comment]
The Jenkins CI failure is unrelated with changes done within this PR. The cause is rather this: https://github.com/OpenSCAP/scap-security-guide/issues/1288 Will investigate further.

**Comment by iankko** [comment]
@openscap-jenkins 
re[test this please]

**Comment by iankko** [comment]
LGTM. ACK.

Thank you for the new rules.

**Comment by shawndwells** [comment]
Just getting back from 2 weeks PTO, trying to catch up. Does anyone own adding these into a profile?

**Comment by redhatrises** [comment]
@shawndwells I created a blocker ticket #1277 in the RHEL7 Draft milestone for adding these rules and all the other rules that we have added/changed into the STIG profile.

**Pull request merged**
