### PR TITLE
Updating stigs rhel7 stig overlay.xml

### PR DESCRIPTION
**Pull request by MollyJoBault**
I've done a first pass of comparing the rule progress for RHEL7 to the Draft Red Hat 7 STIG Version 1, Release 0.2 - 7/15/16 [Draft Red Hat 7 STIG Version 1, Release 0.2 - Release Memo](http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx)  I left the RHEL6 for items I did not see a RHEL7 analog. 

 Some of the rules are not yet complete to what is required in the STIGs and there are some that are missing.

Here is an attempt to compare the two:
[RHEL7-OSCAP-STIG-Compare.xlsx](https://github.com/OpenSCAP/scap-security-guide/files/825298/RHEL7-OSCAP-STIG-Compare.xlsx)

Hope this helps.

### CODE REVIEW

**Comment by MollyJoBault** [comment]
@redhatrises thank you for your quick response!  

1. Do you have another recommendation for building RPMs?  As far as I can tell the Makefile is the only way to do it right now in the codebase.

2. Sorry, my knowledge of git is very minimal (an evidently less than functional)

3. The xccdf.xml from the provided link is Windows, I filled in the rule, CCI, and the RHEL-07-* the rest was filled in using the refresh-stig-refs.sh script.

4. See 3 above

Do you have any idea what the timeline is on getting a non-draft STIG will be released for RHEL7?

**Comment by shawndwells** [comment]
On 3/7/17 2:10 PM, MollyJoBault wrote:
> Do you have any idea what the timeline is on getting a non-draft STIG
> will be released for RHEL7?
Latest we have (from last week) is the final edition is currently
waiting approval from DISA's Public Affairs office. That generally takes
a week or two.

**Comment by MollyJoBault** [comment]
Commits not wanted at this time.

**Comment by shawndwells** [comment]
Hi @MollyJoBault - While the PR was against out of date content, I think we could learn a lot from how you put together that spreadsheet. Whenever the final DISA content is released (hopefully soon), we'll want to ensure the RHEL-07-* mappings are correct, that SSG contains coverage for everything DISA requires, and that SSG provides remediation wherever possible.

Did you use a script / automated means to generate your spreadsheet? If so, is it shareable? If the work was manual, any tips on workflow/lessons learned to speed up the process when the final STIG was reviewed? Thanks for your work on this!

**Comment by MollyJoBault** [comment]
@shawndwells It is definitely a script.  I'm too lazy to do this manually.  It is basically a tweaking to the refresh-stig-refs.sh script.  My knowledge of sed and awk are definitely sledgehammer level, so please forgive.

[compare-stigs-oscap.sh.txt](https://github.com/OpenSCAP/scap-security-guide/files/828490/compare-stigs-oscap.sh.txt)

Thank you guys so much for all your work on this project and helping make Linux more secure.

**Pull request closed without merging**
