### PR TITLE
Provide `make install` and `make dist` in the root Makefile

### PR DESCRIPTION
**Pull request by mpreisler**
In an effort to push for consistent install paths on all distributions.

Only Fedora, RHEL6 and RHEL7 are installed now. As more content stabilizes I think we should start installing more, on every distro.

### CODE REVIEW

**Comment by iankko** [comment]
Thank you for the proposal, Martin. Generally looks fine but looking at *.spec.in file:
&nbsp; &nbsp; https://github.com/OpenSCAP/scap-security-guide/blob/master/scap-security-guide.spec.in

just plain ```make dist``` for ```make install``` isn't sufficient. While it might be sufficient for RHEL-7 & Fedora content cases, for RHEL-6 case we are also copying the remediations functions library:
&nbsp; &nbsp; https://github.com/OpenSCAP/scap-security-guide/blob/master/scap-security-guide.spec.in#L79

into ```/usr/share/scap-security-guide/functions``` file, which is then used / imported into selected remediation scripts (the audit ones would be one example). The plan is to enhance this file even more (move repeated remediation script tasks into functions & re-use them across the scripts).

Also, we should copy the manual pages into appriopriate place (for RHEL-6, RHEL-7 & Fedora cases). Otherwise (once these issues fixed) I don't have objections against inclusion of this change.

Thank you for the patch!
Jan.

**Comment by redhatrises** [comment]
One question I have is that in the `scap-security-guide.spec.in` we have `mkdir -p %{buildroot}%{_datadir}/xml/scap/ssg/{fedora,rhel{6,7}}`, and the `dist` content is moved there. Should that also be done here like below?
```
install -m 0644 Fedora/dist/content/* $(PREFIX)/$(DATADIR)/xml/scap/ssg/fedora/
install -m 0644 RHEL/6/dist/content/* $(PREFIX)/$(DATADIR)/xml/scap/ssg/rhel6/
install -m 0644 RHEL/7/dist/content/* $(PREFIX)/$(DATADIR)/xml/scap/ssg/rhel7/
```

**Comment by iankko** [comment]
@redhatrises 

Thanks for checking. We should unify the locations for all products (RHEL-6, RHEL-7 & Fedora). Originally the idea behind moving Fedora content under ```ssg/product``` subdirectory was to split per product. But since the count of content files we ship per product isn't that huge (basically is *-oval.xml, *-xccdf.xml & *-ds.xml [probably together with cpe files] => at most 5 files per product) to have all content files in one directory seems more rational solution than to force users to click yet-one level below per product just to see / use those five files.

IOW IMHO it's better to have one location where SCAP content files would be placed (and distinguish in them based on filename), than to force people to visit three different locations.

Just my 2c's.

**Comment by mpreisler** [comment]
Fixed both issues reported by @iankko. Now it installs the manpage and the functions necessary for RHEL6 remediations.

I noticed that there are actually multiple manpages and we need to always install the appropriate one. That is fairly unfortunate from the upstream perspective. I will add some rudimentary platform detection to the Makefile shortly.

In my opinion we should install a single unified manpage in the future. If we are installing all the content all the time there is no reason why we should only include one manpage for a fraction of the content. Thoughts?

**Comment by iankko** [comment]
@mpreisler 
> In my opinion we should install a single unified manpage in the future. If we are installing all the content all the time there is no reason why we should only include one manpage for a fraction of the content. Thoughts?

Agree here (that one unified manual page to be better to three separate ones). Less need to keep them updated @ three different places.

**Comment by iankko** [comment]
FWIW regarding the review of the two newly added patches. They look good to me AFAICT.
One point yet though (when dealing with ```make dist```) - would it be possible to install also the kickstart file?

Like copy the USGCB kickstart file from this location:
```scap-security-guide/RHEL/6/kickstart/usgcb-server-with-gui-ks.cfg``` and place it under:
```/usr/share/scap-security-guide/kickstart/ssg-rhel6-usgcb-server-with-gui-ks.cfg``` location on the system?

Please note the kickstart file name installed on the system got changed (prefixed with ```ssg-rhel6```) wrt to what's actually present in the Git repository. It was done to already now count with presence of other kickstarts, that might be available in the future. Naming them this way could allow us:
* to place them into ```/usr/share/scap-security-guide/kickstart``` directory,
* and have them uniquely recognized for product they are intended for just by kickstart file name
(e.g. ```ssg-rhel6-usgcb-server-with-gui-ks.cfg``` means it's kickstart for Red Hat Enterprise Linux 6 Server corresponding to the set of packages as if "Server with GUI" option would be selected normally during the Anaconda install process). Similarly kickstart for Red Hat Enterprise Linux 7 RHT-CCP profile would be named ```ssg-rhel7-rht-ccp-minimal-server-ks.cfg```  in the case 'Minimal Server' Anaconda option would be used. Etc.

FWIW regarding the current Git USGCB RHEL-6 kickstart name ```scap-security-guide/RHEL/6/kickstart/usgcb-server-with-gui-ks.cfg``` - I will let it to you to decide if:
* we would rename it to ```ssg-rhel6...``` and copy that file directly into /usr/share/scap-security-guide/kickstart folder, or
* we will keep the ```usgcb-server-with-gui-ks.cfg``` name unchanged and change it during copying process to the final version.

Personally I prefer the first option (rename the original kickstart file to have final name), but if you want the second approach I won't have objections against it under assumption the final files in
```/usr/share/scap-security-guide/kickstart``` are easily to be identifier which product they are targeted for.

Thanks, Jan.

**Comment by iankko** [comment]
Maybe to clarify yet. The expected output having that RHEL-6 USGCB kickstart file installed on the system is the following one:
```
# rpm -ql scap-security-guide | grep kickstart
/usr/share/scap-security-guide/kickstart
/usr/share/scap-security-guide/kickstart/ssg-rhel6-usgcb-server-with-gui-ks.cfg
```

And yet for case someone might wonder why those kickstart files would be installed under the ```/usr/share/scap-security-guide/kickstart``` subdirectory (rather than placing them directly under doc sub-directory like ```/usr/share/doc/scap-security-guide/kickstart```) -- the reason being that AFAICT it's not possible to specify /usr/share/doc/package/subdirectory as being the part of %doc section in the *.spec file. So we would end up having dozen of kickstart files mixed together with the manual page. But since we want them separated (want them to clearly indicate they are kickstart files), decided to place them under ```/usr/share/scap-security-guide/kickstart``` subfolder instead.

**Comment by shawndwells** [comment]
On 3/25/15 6:43 AM, iankko wrote:
>
> Maybe to clarify yet. The expected output having that RHEL-6 USGCB 
> kickstart file installed on the system is the following one:
>
> |# rpm -ql scap-security-guide | grep kickstart
> /usr/share/scap-security-guide/kickstart
> /usr/share/scap-security-guide/kickstart/ssg-rhel6-usgcb-server-with-gui-ks.cfg
> |
>
> And yet for case someone might wonder why those kickstart files would 
> be installed under the |/usr/share/scap-security-guide/kickstart| 
> subdirectory (rather than placing them directly under doc 
> sub-directory like |/usr/share/doc/scap-security-guide/kickstart|) -- 
> the reason being that AFAICT it's not possible to specify 
> /usr/share/doc/package/subdirectory as being the part of %doc section 
> in the *.spec file. So we would end up having dozen of kickstart files 
> mixed together with the manual page. But since we want them separated 
> (want them to clearly indicate they are kickstart files), decided to 
> place them under |/usr/share/scap-security-guide/kickstart| subfolder 
> instead.
>

This would mean three folders would contain SSG content:

/usr/share/doc/scap-security-guide: contains HTML tables
/usr/share/xml/scap/ssg/content: DS, XCCDF, OVAL
/usr/share/scap-security-guide/kickstart:  KS files

Should we drop /usr/share/doc and put things into 
/usr/share/scap-security-guide instead?

**Comment by mpreisler** [comment]
I like placing the HTML guides in `/usr/share/security-guide`. Fewer folders are better IMO and the paths are very complex as it is.

Should we be building a guide for every profile of every datastream? That would be a lot of HTML guides.

TODO for me:
 - install HTML guides
 - install kickstarts
 - unify manpages and install one manpage (the same manpage everywhere)

**Comment by shawndwells** [comment]
On 3/26/15 11:23 AM, Martin Preisler wrote:
> Should we be building a guide for every profile of every datastream? 
> That would be a lot of HTML guides.
IMHO, yes. If a profile is important enough for us to ship, then we 
should provide the various HTML guides and tables.

Something like
/usr/share/scap-security-guide/{profile}/
---> profile.ks
---> profile-guide.html
---> profile-ctp.html

**Comment by iankko** [comment]
>> On 3/26/15 11:23 AM, Martin Preisler wrote:
>> Should we be building a guide for every profile of every datastream?
>> That would be a lot of HTML guides.

> IMHO, yes. If a profile is important enough for us to ship, then we
should provide the various HTML guides and tables.
>
> Something like /usr/share/scap-security-guide/{profile}/
> ---> profile.ks
> ---> profile-guide.html
> ---> profile-ctp.html

Agree the above being a good idea. Just would propose we would keep / include the per-product scenario (IOW generate dedicated guides & stats for each product we ship SCAP content for). The motivation behind keeping the per-product scheme includes two points:
* not each product will have same profiles shipped. As we progress with the work on the product guides & stats for new product guides & stats could be added without affecting the formerly generated / shipped guide / stats content,

* the second is maybe yet more important - as the packages are being included & removed permanently selected content might become obsolete for some product (for example the cpuspeed service involving rule on RHEL-7 etc). Another scenario that can happen being the new product will require certain options to be configured via different locations - take the ```sysctl``` rules as an example here (on RHEL-6 there were two locations, on RHEL-7 there will be like 5 of them). IMHO the main thing SSG users seem to care (besides the fact having the content for that product available) being the fact the provided descriptions to be up2date wrt to setting of that service on that platform. In other words majority of the existing rules / requirements will remain the same across the products. What will differ is the way how XCCDF is described & how OVAL checks are implemented. To still have a chance to provide up2date profile information I would suggest to keep generating profile information based on product information. The above proposal would probably become:

```/usr/share/scap-security-guide/common/:
 ---> ssg-rhel6-common.ks
 ---> ssg-rhel6-common-guide.html
 ---> ssg-rhel6-common-ctp.html
 ---> ssg-rhel7-common.ks
 ---> ssg-rhel7-common-guide.html 
 ...
 ---> ssg-jbeap{5,6}-common.ks
 ...
```

IMHO this way we could achieve:
* not all products would need to have all profiles finished in the moment of making an RPM,
* when some product feature changed, we could still keep generating up2date guidance based on updated XCCDF text.

**Comment by iankko** [comment]
LGTM AFAICT from testing:
* XCCDF, OVAL & DS data are installed into proper locations for all three (RHEL-6, RHEL-7 & Fedora) products,
* the remediations functions file is installed & works correctly (tried with some audit rule),
* kickstart file is installed into agreed location,
* manual page is installed & works properly.

Two points yet though:
1) Original RPM content / filelisth (when scap-security-guide build from *.spec) is the following:
```
/usr/share/doc/scap-security-guide-0.1.21
/usr/share/doc/scap-security-guide-0.1.21/BUILD.md
/usr/share/doc/scap-security-guide-0.1.21/Contributors.md
/usr/share/doc/scap-security-guide-0.1.21/DISCLAIMER
/usr/share/doc/scap-security-guide-0.1.21/JBossEAP5_Guide.html
/usr/share/doc/scap-security-guide-0.1.21/LICENSE
/usr/share/doc/scap-security-guide-0.1.21/README.md
/usr/share/doc/scap-security-guide-0.1.21/rhel6-guide.html
/usr/share/doc/scap-security-guide-0.1.21/table-rhel6-cces.html
/usr/share/doc/scap-security-guide-0.1.21/table-rhel6-nistrefs-common.html
/usr/share/doc/scap-security-guide-0.1.21/table-rhel6-nistrefs.html
/usr/share/doc/scap-security-guide-0.1.21/table-rhel6-srgmap-flat.html
/usr/share/doc/scap-security-guide-0.1.21/table-rhel6-srgmap-flat.xhtml
/usr/share/doc/scap-security-guide-0.1.21/table-rhel6-srgmap.html
/usr/share/doc/scap-security-guide-0.1.21/table-rhel6-stig.html
/usr/share/man/en/man8/scap-security-guide.8.gz
/usr/share/scap-security-guide/functions
/usr/share/xml/scap
/usr/share/xml/scap/ssg
/usr/share/xml/scap/ssg/content
/usr/share/xml/scap/ssg/content/eap5-cpe-dictionary.xml
/usr/share/xml/scap/ssg/content/eap5-cpe-oval.xml
/usr/share/xml/scap/ssg/content/eap5-ocil.xml
/usr/share/xml/scap/ssg/content/eap5-oval.xml
/usr/share/xml/scap/ssg/content/eap5-xccdf.xml
/usr/share/xml/scap/ssg/content/ssg-rhel6-cpe-dictionary.xml
/usr/share/xml/scap/ssg/content/ssg-rhel6-cpe-oval.xml
/usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml
/usr/share/xml/scap/ssg/content/ssg-rhel6-oval.xml
/usr/share/xml/scap/ssg/content/ssg-rhel6-xccdf.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-oval.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-oval.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml
```

plus the kickstart file intended to be placed under ```/usr/share/scap-security-guide/kickstart``` as discussed in this PR above, 

vs the new content installed via ```make install``:
```
# tree /usr/share/xml/scap/ssg/content/
/usr/share/xml/scap/ssg/content/
|-- ssg-fedora-ds.xml
|-- ssg-fedora-oval.xml
|-- ssg-fedora-xccdf.xml
|-- ssg-rhel6-cpe-dictionary.xml
|-- ssg-rhel6-cpe-oval.xml
|-- ssg-rhel6-ds.xml
|-- ssg-rhel6-oval.xml
|-- ssg-rhel6-xccdf.xml
|-- ssg-rhel7-cpe-dictionary.xml
|-- ssg-rhel7-cpe-oval.xml
|-- ssg-rhel7-ds.xml
|-- ssg-rhel7-oval.xml
`-- ssg-rhel7-xccdf.xml

0 directories, 13 files

# tree /usr/share/scap-security-guide/
/usr/share/scap-security-guide/
|-- functions
|-- kickstart
|   `-- usgcb-server-with-gui-ks.cfg
|-- rhel6-guide.html
|-- rhel7-ccp-guide.html
`-- ssg-fedora-common-guide.html

1 directory, 5 files
```

As can be seen above, the *.spec version copies also JBossEAP5 content and places also some statistics files under /usr/share/doc/scap-security-guide directory. Assuming we will want ```make install``` to perform the same.

2) The unified manual page works but there are parts like:
```
RHEL6 PROFILES
       The RHEL6 SSG content is broken into ’profiles,’ groupings of security settings that correlate to a known policy. Available profiles are:
...
RHEL7 PROFILES
       The RHEL7 SSG content is broken into ’profiles,’ groupings of security settings that correlate to a known policy. Available profiles are:
...
```
Would it be possible to expand the 'RHEL* PROFILES / SSG' parts into:
* "Profiles for Red Hat Enterprise Linux 6 / 7" (instead of current RHEL{6,7} PROFILES ), and
* "The SCAP Security Guide for Red Hat Enterprise Linux 6 / 7" (instead of current RHEL{6,7} SSG)

strings?

Otherwise looks good to me.

**Comment by iankko** [comment]
Since this PR is getting pretty big, I am going to merge this since the unfixed issues could be split from the fixed ones (IOW it would be possible to focus on the unfixed stuff in future PRs only).

**Pull request merged**
