### PR TITLE
Parallelize the "validate" target

### PR DESCRIPTION
**Pull request by mpreisler**
Validation is very CPU-intensive and doing only one validation at a time is a big time waster.

On my machine (`time make -j 4 validate`):
```
new: 2m19.902s
old: 3m43.738s
```

### CODE REVIEW

**Comment by mpreisler** [comment]
Took 8 minutes 16 seconds to do the whole `make jenkins` thing on our RHEL7 jenkins, see https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/529/label=node-el7/

**Comment by mpreisler** [comment]
Weirdly enough, we did the right thing back in 2014!

https://github.com/OpenSCAP/scap-security-guide/commit/dbcb00b761be68e2014489c203f2084d87869a2e

Somebody must have changed this and I would love to know why.

**Comment by mpreisler** [comment]
Happened in https://github.com/OpenSCAP/scap-security-guide/commit/928a741c8fc399b18c82d4b5df45fc318349137d#diff-b67911656ef5d18c4ae36cb6741b7965

**Comment by redhatrises** [comment]
@mpreisler I had consolidated all the validate targets into a single target so that we weren't having to add a bunch of dist validate targets all over the place. But if we get performance gains over it, I am all for adding them back in.

**Comment by iankko** [comment]
Makes sense to me.

 (actually agree that issuing ```make validate``` just for one product is CPU intensive operation. Experienced this yesterday on RHEL-7 when inspecting reasons of ```make validate``` failure for https://github.com/OpenSCAP/scap-security-guide/pull/1385 ).

Since the products are isolated, ```make validate``` is safe to be isolated too (no need to wait for one CPU and serialize the whole ```validate``` task).

ACK.

**Pull request merged**
