### PR TITLE
Wrong spelling change rmdiri to rmdir

### PR DESCRIPTION
**Pull request by flysen**
#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

### CODE REVIEW

**Comment by cipherboy** [comment]
LGTM.

-- Alex

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
ACK

Thank you for your contribution!

**Pull request merged**
