### PR TITLE
Firefox updates

### PR DESCRIPTION
**Pull request by redhatrises**
- Standardize to existing RHEL content/file layout
- Add Firefox remediations functions to remediation_functions
- Update Firefox remediations to use new remediations functions
- Remove unused templates

### CODE REVIEW

**Comment by ybznek** [comment]
Sorry for inconveniences, I don't know how to remove old tests' results.
Please ignore old bad results (failed due to operations with testing infrastructure).

**Comment by iankko** [comment]
@redhatrises 

Looks good to me in general (Jenkins prior to Zbynek's enhancement was passing on this one, so I am reviewing it).

But please see those two points above:
* looks we are removing old remediation script form for some Firefox rule (and not providing an alternative) -- if that's the case, why not just to keep the old version?,
* for one rule applying the updated remediation script returns ```error``` state -- should we modify corresponding OVAL to require something else? Or the new remediation script needs adjustments?

Once the two issues above are solved / explained / clarified, this one can be merged.

Thank you for your work on this!

Jan

**Comment by redhatrises** [comment]
@iankko 

> for one rule applying the updated remediation script returns error state -- should we modify corresponding OVAL to require something else? Or the new remediation script needs adjustments?

This looks like an error in the build system when building firefox content. When `populate some_var` is used in conjuction with `. /usr/share/openscap/remediation_functions`, `. /usr/share/openscap/remediation_functions` is not added to the `ssg-firefox-xccdf.xml` file which is causing the error.

I am checking to see what is causing this.

**Comment by redhatrises** [comment]
@iankko 

> * for one rule applying the updated remediation script returns ```error``` state -- should we modify corresponding OVAL to require something else? Or the new remediation script needs adjustments?

Looks like the issue is caused with `shared/transforms/combineremediations.py`. When both `populate` and `remediation_functions` exist in the same script, `remediation_functions` is not added to the produced XCCDF.

**Comment by iankko** [comment]
@redhatrises 

Thanks for investigation. Filed under:
  https://github.com/OpenSCAP/scap-security-guide/issues/1075

and will have a further look why it's happening.

**Comment by iankko** [comment]
Since both of the questions above have been answered, ACK for merging this one (we will deal with remediation functions issue via separate ticket).

**Pull request merged**
