### PR TITLE
C2S OVAL and Mapping Cleanup

### PR DESCRIPTION
**Pull request by shawndwells**
Resolves feedback from @iankko in https://github.com/OpenSCAP/scap-security-guide/pull/880

### CODE REVIEW

**Comment by isimluk** [comment]
So this is interesting. The `make validate` fails with
```
cd output; ../utils/verify-references.py --rules-with-invalid-checks --ovaldefs-unused ssg-rhel6-xccdf.xml
OVAL Check is not referenced by XCCDF: oval:ssg:def:1395
OVAL Check is not referenced by XCCDF: oval:ssg:def:1423
Makefile:175: recipe for target 'validate' failed
```
The problematic definitions are
```
Package ntpdate Removed
Package autofs Removed
```

So, why this is happening? You have moved these two definitions (among others) from RHEL/7 directory to shared directory. This is fine and feels very sensible.

The problem is that RHEL/6 buggy build system puts every oval from shared/ directory to resulting rhel6-oval.xml. Then the build system finds out that some of the definitions shouldn't be there -- as they are not referenced from the rhel6-xccdf.xml. That is a bug in the build system and I will look into it.

In the meantime, Shawn, can you please put 
```
Package ntpdate Removed
Package autofs Removed
```
back to rhel7 directory only?

The rest of the pr seems fine. Thanks!

**Comment by redhatrises** [comment]
@shawndwells @isimluk 

I believe that this is failing because both `package_autofs_removed.xml` and `package_ntpdate_removed.xml` need to the the `<platform>` tag updated to:
`<platform>multi_platform_rhel</platform>`
rather than:
 `<platform>Red Hat Enterprise Linux 7</platform>`

**Comment by isimluk** [comment]
Yes, maybe when we switch `shared/oval/package_autofs_removed.xml` FROM `multi_platform_rhel` to `Red Hat Enterprise Linux 7` it may not be picked up by RHEL6 build.

**Comment by redhatrises** [comment]
> Yes, maybe when we switch shared/oval/package_autofs_removed.xml FROM multi_platform_rhel to Red Hat Enterprise Linux 7 it may not be picked up by RHEL6 build.

@isimluk that is correct.

**Comment by iankko** [comment]
Please do <b>NOT</b> merge this into 0.1.27 milestone yet.

**Comment by iankko** [comment]
```RHEL/6``` ```make validate``` failure fixed && changes merged manually. Thanks.

**Pull request merged**
