### PR TITLE
Debs: support for apt unauthenticated repository config check (ANSSI NT-28 - R15)

### PR DESCRIPTION
**Pull request by pthierry38**
- add oval and guide for local apt config unauthenticated repository support detection
- done for debian8, ubuntu 14.04 and 16.04

### CODE REVIEW

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by mpreisler** [comment]
I hate the copy paste in this PR. I know it's common and all the SSG contributors have done their fair share of awful code repetition but we need to stop that practice.

Could you please look into using a shared template to avoid having 3 OVAL defs that are the same?

**Comment by pthierry38** [comment]
@mpreisler I admit, I didn't had, when I wrote the oval files, enough time/energy to write another template support.
What I can do is the following:

- a CSV file containing the file name (without regex support by now), the mode (none_match or all_match), and the regex to match in the file.
- the templated oval file

What is harder here is that the regex may be more complex than for the file access rights. It may contain comas for example and should be protected by double-quotes (as defined in RFC 4180).

Before starting to write any code, what do you think about this solution ? Do you have easier proposition ?

**Comment by ybznek** [comment]
@pthierry38 Maybe I don't understand future steps. But It seems, that that ovals could be stored in shared oval directory (without templating)

Can you write example of csv you would want to introduce?

**Comment by redhatrises** [comment]
Agree with @ybznek. IMO the template generators right now for OVAL are for very simplistic uses and not complicated regex and OVAL permutations. I believe a script that is OVAL centric that can be integrated into the templates build scripts is what would be better.

**Comment by pthierry38** [comment]
@mpreisler @redhatrises @ybznek My fault, I understood that @mpreisler wanted to avoid any duplication of regex matching oval files globally (not just these 3 files) through complete templating. Of course I can create only one oval file supporting two platform (multi_platform_debian and multi_platform_ubuntu).

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

(testing jenkins after cmake merge)

**Comment by mpreisler** [comment]
ACK, looks good now.

**Pull request merged**
