### PR TITLE
Update the RHEL/6 STIG Overlay XML file

### PR DESCRIPTION
**Pull request by redhatrises**
- Updates the RHEL/6/auxiliary/stig_overlay.xml file to the latest DISA STIG release

### CODE REVIEW

**Comment by shawndwells** [comment]
Why create legacy_stig_overlay.xml?

**Comment by redhatrises** [comment]
You originally wanted a way to track retired or removed STIG mappings.

**Comment by redhatrises** [comment]
@shawndwells see your comment in #1750

**Comment by redhatrises** [comment]
Closing as there are some additional changes that need to be made.

**Pull request closed without merging**
