### PR TITLE
Remove oval_5.11 dir checks usage

### PR DESCRIPTION
**Pull request by redhatrises**
#### Description:

- Remove all checks/oval/oval_5.11 directories
- Usage oval_version XML attribute instead

#### Rationale:

- Removes the need to manage OVAL versions by directory and instead uses the new oval_version XML attribute. Makes the content structure easy to use and follow.

### CODE REVIEW

**Comment by yuumasato** [comment]
@redhatrises Content with only OVAL 5.10 content fails to validate, there are checks with `glob_to_regex` which is new in version 5.11.

Not a blocker for meging this PR, but these changes increase need on support for multi def-group handling.

**Comment by redhatrises** [comment]
> @redhatrises Content with only OVAL 5.10 content fails to validate, there are checks with `glob_to_regex` which is new in version 5.11.

Thanks @yuumasato. Found and fixed as well as some other issues.

> Not a blocker for meging this PR, but these changes increase need on support for multi def-group handling.

Yes. This is true, but this is a future handling.

**Comment by yuumasato** [comment]
@redhatrises rhel7-validate target with OVAL 5.10 content outputs following errors:

```
ERROR: Invalid OVAL definition referenced by XCCDF Rule: docker_selinux_enabled
ERROR: Invalid OVAL definition referenced by XCCDF Rule: docker_storage_configured
ERROR: Invalid OVAL definition referenced by XCCDF Rule: chronyd_or_ntpd_set_maxpoll
ERROR: Invalid OVAL definition referenced by XCCDF Rule: postfix_network_listening_disabled
ERROR: Invalid OVAL definition referenced by XCCDF Rule: dovecot_enable_ssl
ERROR: Invalid OVAL definition referenced by XCCDF Rule: dovecot_disable_plaintext_auth
```

**Comment by yuumasato** [comment]
@redhatrises this is log from build
```
WARNING: OVAL definition 'docker_selinux_enabled' extends non-existing 'service_docker_enabled', removing it from OVAL definitions.
WARNING: OVAL definition 'docker_selinux_enabled' extends non-existing 'service_docker_enabled', removing it from OVAL definitions.
WARNING: OVAL definition 'docker_storage_configured' extends non-existing 'service_docker_enabled', removing it from OVAL definitions.
WARNING: OVAL definition 'docker_storage_configured' extends non-existing 'service_docker_enabled', removing it from OVAL definitions.
WARNING: OVAL definition 'chronyd_or_ntpd_set_maxpoll' extends non-existing 'service_ntpd_enabled', removing it from OVAL definitions.
WARNING: OVAL definition 'chronyd_or_ntpd_set_maxpoll' extends non-existing 'service_chronyd_enabled', removing it from OVAL definitions.
WARNING: OVAL definition 'dovecot_disable_plaintext_auth' extends non-existing 'service_dovecot_disabled', removing it from OVAL definitions.
WARNING: OVAL definition 'dovecot_enable_ssl' extends non-existing 'service_dovecot_disabled', removing it from OVAL definitions.
WARNING: OVAL definition 'postfix_network_listening_disabled' extends non-existing 'service_postfix_enabled', removing it from OVAL definitions.
```

**Comment by redhatrises** [comment]
Thanks @yuumasato. I had forgotten to go back and fix that. Should validate now.

**Comment by yuumasato** [comment]
Thanks for fixing the issues for OVAL 5.10 content.
Ack.

**Pull request merged**
