### PR TITLE
Refactor usage of argparse in test_suite

### PR DESCRIPTION
**Pull request by cipherboy**
All that this changes is wrapping argparse in a `parse_args` function and the bulk of the script in a `main` function.

### CODE REVIEW

**Comment by cipherboy** [comment]
Hello @scrutinizer-notifier! Nice to see you again :)

**Comment by cipherboy** [comment]
I'm marking this as WIP as I realized the test suite doesn't work on Python 3.

**Comment by cipherboy** [comment]
I'll update python3 in a separate PR.

**Comment by dahaic** [comment]
@cipherboy does it make sense to also put that default handling logic into function? (Separate, probably)

**Comment by cipherboy** [comment]
@dahaic Let me see if I understood what you said... (I think you're talking about defaults w.r.t. arguments, and the logic around setting them). If so:

Regarding lines [119 to 126](https://github.com/cipherboy/scap-security-guide/blob/1b47a54f3296a8a144ca7877dee992747071c2ea/tests/test_suite.py#L119-L126), I'm inclined to leave them in as-is, because it is updating an existing option based on other, parsed options. (`bench_id` depends on `options.{datastream, xccdf_id}` and you're calling out to an external function (`xml_operations.infer_benchmark_id_from_component_ref_id`)).

Regarding lines [132 to 133](https://github.com/cipherboy/scap-security-guide/blob/1b47a54f3296a8a144ca7877dee992747071c2ea/tests/test_suite.py#L132-L133), I'm also inclined to leave them there, because moving them up to `parse_args` would introduce more lines than it is worth since it only minimally impacts readability. I'd be more inclined to move the comment above it down to after the if, and add a new comment detailing that this is cleaning up the options.

**Comment by dahaic** [comment]
@cipherboy yeah, I was talking about those. Thanks for clarification, I don't see the need for any changes. ACK

**Comment by cipherboy** [comment]
@dahaic Thanks! :)

**Pull request merged**
