### PR TITLE
RHEL7 STIG: Audit Rule Updates

### LINKED ISSUE #172: RHEL7 STIG: CCI-002422 The operating system must maintain the confidentiality and integrity of information during reception.
SC-8 (2)	CCI-002422	SRG-OS-000426		The operating system must maintain the confidentiality and integrity of information during reception.	"Information can be either unintentionally or maliciously disclosed or modified during reception including, for example, during aggregation, at protocol transformation points, and during packing/unpacking. These unauthorized disclosures or modifications compromise the confidentiality or integrity of the information.

Ensuring the confidentiality of transmitted information requires the operating system take measures in preparing information for transmission. This can be accomplished via access control and encryption.

Use of this requirement will be limited to situations where the data owner has a strict requirement for ensuring data integrity and confidentiality is maintained at every step of the data transfer and handling process. When receiving data, operating systems need to leverage protection mechanisms such as TLS, SSL VPNs, or IPSEC."

### PR DESCRIPTION
**Pull request by shawndwells**
placeholder for updating audit rules to RHEL7 STIG requirements.

please don't merge yet (will be patching throughout the afternoon). comments welcome at anytime!

### CODE REVIEW

**Comment by shawndwells** [comment]
merging will resolve https://github.com/OpenSCAP/scap-security-guide/issues/194

**Comment by shawndwells** [comment]
patchset ready for peer review.

**Comment by redhatrises** [comment]
@shawndwells what about the links for ```shared/oval/audit_rules_usergroup_modification.xml``` to ```RHEL\7``` and ```Fedora\```?

**Comment by shawndwells** [comment]
On 4/7/15 4:03 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> what about the links for 
> |shared/oval/audit_rules_usergroup_modification.xml| to |RHEL\7| and 
> |Fedora\|?

yikes - added!

**Comment by redhatrises** [comment]
LGTM. Ack.

**Pull request merged**
