### PR TITLE
Add gid_passwd_group_same to RHE7 STIG

### PR DESCRIPTION
**Pull request by shawndwells**
- update rationale and policy refs
- add to stig profile

image

### CODE REVIEW

**Comment by isimluk** [comment]
LGTM. I will be merging this manually. (As I want to avoid these two merge commits in the history log).

**Comment by isimluk** [comment]
Got so many interrupts today :shit:, will merge tmrw :pray:

**Comment by shawndwells** [comment]
On 3/30/16 3:11 PM, Šimon Lukašík wrote:
> Got so many interrupts today :shit:, will merge tmrw :pray:
Thanks Simon!

**Comment by shawndwells** [comment]
@isimluk requesting bump. Future patches will cause a few merge conflicts, so appreciate getting this merged before the next patch dump =)

**Comment by isimluk** [comment]
I see. I have got distracted again.

It's not trivial to get away these merge commits. Some of the changes are already applied in master and merge commits remove them. When I try to rebase the commits, the commit messages are rendered useless because of that. And then I find that you perhaps resolved the merge conflict differently then I did with the rebase conflicts. I need quiet place to get my mind focused. I guess, I will have quiet moment late on Sunday. And then I run-into some build error that needs to be investigated.

Btw, you can always speed up process by proposing pr without these merge commits. :-)

**Comment by shawndwells** [comment]
Manually fixed the merge conflicts and pushed. Kind of shitty to self-ack, but needed to get this into a build to show to DISA today =/

**Pull request merged**
