### PR TITLE
[issue 1688] update XCCDF for selinux audit

### PR DESCRIPTION
**Pull request by shawndwells**
Added the -F auid!=4294967295 to relevant selinux audit XCCDF

resolves https://github.com/OpenSCAP/scap-security-guide/issues/1688#issuecomment-279004736

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells can you also change `/usr/sbin/chon` to `/usr/bin/chcon` which will fully resolve #1688?

**Comment by rsprudencio** [comment]
@openscap-jenkins retest this please (just checking if we got a bug in Jenkins)

**Comment by shawndwells** [comment]
@redhatrises updated /usr/sbin/chcon --> /usr/bin/chcon

**Comment by redhatrises** [comment]
Thanks @shawndwells Ack.

**Pull request merged**
