### PR TITLE
[Enhancement][Fedora][RHEL6/7] refactor top-level Makefile and rpm spec file

### PR DESCRIPTION
**Pull request by redhatrises**
- Add VERSION file which contains the following information for builds:
  * SSG_PROJECT_NAME
  * SSG_MAJOR_VERSION
  * SSG_MINOR_VERSION
  * SSG_RELEASE_VERSION
  * SSG_RELEASE_DATE
  * SSG_REL_MANAGER
  * SSG_REL_MANAGER_MAIL
  * SSG_VERSION_IS_GIT_SNAPSHOT
- Refactor top-level Makefile
- Builds now use a GIT snapshot in the tarball and rpm builds for testing
  and development purposes
- Merge top-level and Fedora .spec file into a single spec file
- Add a 'make git-tag' to tag a new release

### CODE REVIEW

**Comment by redhatrises** [comment]
This PR refactors the top-level Makefile and rpm.spec files. Not all changes in this may be desired. 
- A git snapshot gets added to the tarball and rpm files for being able to tell the differences between the official tag and any changes in the master to the current date which could be useful for development and testing purposes. 
- Official release builds would either change `SSG_VERSION_IS_GIT_SNAPSHOT="no"` in the `VERSION` file or run as `make SSG_VERSION_IS_GIT_SNAPSHOT=no rpm` in the command line.
- Merges the `Fedora/scap-security-guide.spec` and the `scap-security-guide.spec` into one spec file.
- Adds a `make git-tag` to tag a new version.

**Comment by iankko** [comment]
Taking this one for review.

**Comment by iankko** [comment]
Review result - generally looks very nice & works fine on all three systems (RHEL-6, RHEL-7 & Fedora 20) AFAICT from testing.

The only issue I was able to notice being zipfile isn't generated in case ```make clean``` was run before (```make tarball``` works fine even on clean system):
```
[root@localhost scap-security-guide]# make clean
..
rm -f scap-security-guide.spec
[root@localhost scap-security-guide]# make zipfile
mkdir -p /root/scap-security-guide/rpmbuild/BUILD
mkdir -p /root/scap-security-guide/rpmbuild/RPMS
mkdir -p /root/scap-security-guide/rpmbuild/SOURCES
mkdir -p /root/scap-security-guide/rpmbuild/SPECS
mkdir -p /root/scap-security-guide/rpmbuild/SRPMS
mkdir -p /root/scap-security-guide/rpmbuild/ZIPS
mkdir -p /root/scap-security-guide/rpmbuild/BUILDROOT
# Create a zipfile release, since many SCAP
# tools desire content in that format
# (Note: By default zip will store the full path
#	 relative to the current directory, need
#	 to cd into /root/scap-security-guide/rpmbuild
cp RHEL/6/output/ssg-* /root/scap-security-guide/rpmbuild/ZIPS/
cp: cannot stat ‘RHEL/6/output/ssg-*’: No such file or directory
make: *** [zipfile] Error 1
```

So maybe add 'content' as a dependency for the 'zipfile' Makefile target. I am not sure the previous version behaved the same way (it's possible, didn't try), but would be nice to take care for this (not to need to remember to run ```make``` before ```make zipfile``` target).

Thank you for the patch. Jan.

**Comment by redhatrises** [comment]
Thanks for the review @iankko! The `make zipfile` target originally required that `make` was run before `make zipfile`. Since right now the zipfile target only adds `rhel6` and `JBOSS` products, I added `rhel6` to the `make zipfile` target. Now when `make zipfile` is run, it builds its content as well.

**Comment by iankko** [comment]
@redhatrises 
This version works fine AFAICT.  ACK & merging.

P.S.: Thanks a lot!. Very well & for a long time desired change.

**Pull request merged**
