### PR TITLE
WIP [Enhancement][RHEL/7] Break out audit rules for DISA STIG Draft v2

### LINKED ISSUE #1020: new rule on auditing selinux chcon/restorecon ?
per RHEL-07-030440  SRG-OS-000463-GPOS-00207

### PR DESCRIPTION
**Pull request by redhatrises**
- Break out existing audit rules
- Add new SELinux audit rules
- Fixes #1020

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells since the DISA STIG is breaking out rules, will you take a look at this PR and comment?

**Comment by redhatrises** [comment]
This is a take 2 on a previous PR, and as it is a WIP, the PR will most likely fail to build.

**Comment by iankko** [comment]
@openscap-jenkins 
re[test this please]

**Comment by iankko** [comment]
@redhatrises 
Can you reference those newly added OVALs from RHEL-7 XCCDF? (reason of Jenkins failure below):
```
oscap ds sds-validate output/ssg-sl7-ds.xml
cd output; ../../../shared/utils/verify-references.py --rules-with-invalid-checks --ovaldefs-unused ssg-rhel7-xccdf.xml
OVAL Check is not referenced by XCCDF: oval:ssg-audit_rules_file_deletion_events:def:1
OVAL Check is not referenced by XCCDF: oval:ssg-audit_rules_kernel_module_loading:def:1
OVAL Check is not referenced by XCCDF: oval:ssg-audit_rules_login_events:def:1
OVAL Check is not referenced by XCCDF: oval:ssg-audit_rules_unsuccessful_file_modification:def:1
```

Thanks, Jan

**Comment by redhatrises** [comment]
Thanks @iankko. Before I added the OVAL for Jenkins to pass on this PR, I wanted some feedback (hoping @shawndwells would jump in the conversation) on this PR. In the RHEL7 STIG, there is now a XCCDF rule for every `-S` sudit setting. So, the question is should SSG break out the audit rules like the RHEL7 STIG, or should we add mutiple `ident`s and `stigid`s to a single Rule?

**Comment by iankko** [comment]
@redhatrises 
> Thanks @iankko. Before I added the OVAL for Jenkins to pass on this PR, I wanted some feedback (hoping @shawndwells would jump in the conversation) on this PR. In the RHEL7 STIG, there is now a XCCDF rule for every -S sudit setting. So, the question is should SSG break out the audit rules like the RHEL7 STIG, or should we add mutiple idents and stigids to a single Rule?

The question is just to break XCCDF rules, not OVALs right? Or since now we have XCCDF ID = OVAL ID requirement (otherwise SSG will fail to build), the split one XCCDF rule into more rules, would mean also the need to split OVAL into more OVALs. 

If the split would cause the need to have also the OVAL rules split, I am against that split from engineering point of view. Here's the justification (from ```auditctl``` manual page):

```
       -S [Syscall name or number|all]

              Any syscall name or number may be used. The word 'all' may
also be used.  If the given syscall is made by a program, then start an
audit record.  If a field rule is given and no syscall is specified, it will
default to all syscalls. You may also specify multiple syscalls in the
same rule by using multiple -S options in the same rule. Doing so
improves performance since fewer rules need to be evaluated.
Alternatively, you may pass a comma separated  list of syscall
names. If you are on a bi-arch system, like x86_64, you should be
aware that auditctl simply takes the text, looks it up for the native
arch (in this case b64) and sends that rule to the kernel. If there are
no additional arch directives, IT WILL APPLY TO BOTH 32 & 64
BIT SYSCALLS.  This  can have undesirable effects since there
is no guarantee that any syscall has the same number on both 32
and 64 bit interfaces. You will likely want to  control this and write
2 rules, one with arch equal to b32 and one with b64 to make sure
the kernel finds the  events  that  you intend. See the arch field
discussion for more info.
```

Thus current approach of specifying multiple system calls in one requirement is more effective from the ```auditctls / augenrules``` PoV (the final table of rules to be searched is smaller, thus the match is found sooner). This is also the approach the reference audit policies in ```/usr/share/doc/audit/*.rules``` follow (the more rules you can list at one row, the better for the overall performance).

See also this audit linux ML thread:
  https://www.redhat.com/archives/linux-audit/2015-January/msg00069.html

why having multiple syscalls on one line matters for performance.

Thus if it would be possible to reach the latest RHEL-7 STIG requirements via adding multiple identifiers to more rules, I would vote for going that way (since it won't mean we will need to rewrite the form of OVAL audit rules, and won't decrease the effectiveness of audit scan) 

What's the purpose of system scan that: 
* on one hand will scan everything aligned with the draft, but
* on the other it will take long time to finish?

The more time we spend during the scan, the higher is the change users will tend to apply not-official customizations (not even to mention we will need to explain why ```/usr/share/doc/audit/*.rules``` recommends one form, and we recommend different form).

**Comment by redhatrises** [comment]
> Thus if it would be possible to reach the latest RHEL-7 STIG requirements via adding multiple identifiers to more rules, I would vote for going that way (since it won't mean we will need to rewrite the form of OVAL audit rules, and won't decrease the effectiveness of audit scan) 

@iankko fully agree. @shawndwells thoughts?

**Comment by redhatrises** [comment]
Closing and will re-open with a new PR. Thanks for the comments.

**Pull request closed without merging**
