### PR TITLE
Moved the shared guide from shared to linux_os

### PR DESCRIPTION
**Pull request by mpreisler**
The reasoning is that shared/ contains stuff shared by all products, the
Linux OS guide is only shared by Linux distributions, it doesn't apply
to JRE, Chromium, etc... In the future we can move checks and fixes
applicable to Linux distributions to linux_os and checks and fixes that
are truly applicable to everything (CPE OVALs, etc...) will be in
shared/.

We discussed this at a meeting and this is the best we came up with to
sort out this disconnect.

This PR has a huge conflict creation potential so please review & merge sooner rather than later.

### CODE REVIEW

**Comment by mpreisler** [comment]
Mysteriously failing jenkins on something that this PR doesn't even change :-/

**Comment by mpreisler** [comment]
Running `ctest` locally I don't get this issue at all. Odd...

**Comment by mpreisler** [comment]
Found it, `git rebase -i` confused the hell out of me here.

**Comment by redhatrises** [comment]
begrudingly ack ;) :D

**Comment by mpreisler** [comment]
> begrudingly ack ;) :D

lol

**Pull request merged**
