### PR TITLE
Update RHEL/7 STIG content to match latest STIG ID mapping

### PR DESCRIPTION
**Pull request by redhatrises**
- Update STIG IDs to the latest mappings

### CODE REVIEW

**Comment by redhatrises** [comment]
Please thoroughly go through commit 14942c6 as there are rules that I think that we should have enabled instead of disabled in the STIG profile (such as `package_aide_installed`). 

@shawndwells please take a look as well to see which rules we should keep.

**Comment by shawndwells** [comment]
At this point, I think we'll have to create two unique profiles, dropping the -upstream:

- ospp, which is the "vendor stig"
- rhel7-server-stig-disa, which matches (as much as reasonable) their content

**Comment by redhatrises** [comment]
@shawndwells what about just creating a `stig-rhel7-server-disa` profile and keep the upstream as the vendor stig? Just a thought.

**Comment by radzy** [comment]
@shawndwells, @redhatrises : for what it's worth, I like the convention of using stig-*-disa for DISA approved profiles, and something else with "stig" in it for the vendor stig.

**Comment by redhatrises** [comment]
I have removed the profile changes for this PR and have just updated the mappings. Will have a separate PR for the actual STIG profile changes for better visibility.

@shawndwells please review.

**Comment by shawndwells** [comment]
On 1/30/17 10:28 AM, redhatrises wrote:
>
> I have removed the profile changes for this PR and have just updated
> the mappings. Will have a separate PR for the actual STIG profile
> changes for better visibility.
>
> @shawndwells <https://github.com/shawndwells> please review.
>

Any chance you have the profile changes? Was reviewing w/DISA.

**Comment by redhatrises** [comment]
@shawndwells I do have the profile changes. Would you like it as part of this PR or separate? I had intended them to be in a separate PR.

**Comment by shawndwells** [comment]
@redhatrises  thank you for this. RHT met with DISA last week, slow progress on an official STIG :)

**Pull request merged**
