### PR TITLE
Docker build

### PR DESCRIPTION
**Pull request by konstruktoid**
This PR adds the option of using Docker to build the scap-security-guide content.
Note that the image size can be reduced by using a Ubuntu base image, but as the majority of work in this project is Red Hat related, I've chosen CentOS:7.

Tested on
```
ProductName: Mac OS X
ProductVersion: 10.12.1
BuildVersion:	16B2555
```
```
CentOS Linux release 7.2.1511 (Core) 
```
```
Ubuntu 16.04.1 LTS
```

### CODE REVIEW

**Comment by mpreisler** [comment]
@openscap-jenkins add to whitelist

**Comment by mpreisler** [comment]
This is pretty awesome. You can use this to build SSG even on distros without the necessary packages or on distros with the wrong versions of packages.

I will do a bit more testing before merging this but it looks great.

**Comment by mpreisler** [comment]
One thing that doesn't make sense to me is the git cloning. Wouldn't it be better to use the git version that we are building? The local working copy?

**Comment by mpreisler** [comment]
For some reason I get permission denied IO errors when building RHEL/7 inside the container.

I am running `docker run --cap-drop=all -v$(pwd)/output-docker/:/home/oscap/scap-security-guide/RHEL/7/output/ oscap:latest`. I have run `docker build --no-cache --file Dockerfile --tag oscap:$(date -u +%Y%m%d%H%M) --tag oscap:latest .` to build the container.
```
make[1]: Leaving directory `/home/oscap/scap-security-guide/RHEL/6'
cd RHEL/7/ && /usr/bin/make
make[1]: Entering directory `/home/oscap/scap-security-guide/RHEL/7'
xsltproc -o output/guide.xml ../../shared/transforms/includelogo.xslt ../../shared/xccdf/shared_guide.xml
I/O error : Permission denied
I/O error : Permission denied
make[1]: *** [output/guide.xml] Error 11
make[1]: Leaving directory `/home/oscap/scap-security-guide/RHEL/7'
make: *** [rhel7] Error 2
```

**Comment by konstruktoid** [comment]
Fixed the two issues.

Using `git clone` forced the usage of a up-to-date upstream, but allowing WIP and private repos makes more sense, as you said.

The permission denied was a result of using `USER`, instead of root, and that UID wouldn't match the host. `chmod a+rwx $(pwd)/output-docker/` would have solved it, but I've removed the USER part just to make it a bit more convenient.

**Comment by mpreisler** [comment]
The git clone thing is fixed but I still get the permission issue.

I am building on Fedora 25. Is there any configuration I need to apply locally?

**Comment by konstruktoid** [comment]
`sudo setenforce 0` solved it for me, but there's probably a more correct SELinux way to do this.

**Comment by wrabcak** [comment]
Please, switch SELinux to permissive mode:
# setenforce 0
Then, reproduce the scenario and attach output of:
# ausearch -m USER_AVC,AVC -ts recent

**Comment by konstruktoid** [comment]
Thanks @wrabcak, here's the output:
```
$ sudo ausearch -m USER_AVC,AVC -ts recent
----
time->Wed Dec  7 10:45:11 2016
type=AVC msg=audit(1481107511.432:1252): avc:  denied  { add_name } for  pid=13628 comm="xsltproc" name="guide.xml" scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=1
----
time->Wed Dec  7 10:45:11 2016
type=AVC msg=audit(1481107511.432:1251): avc:  denied  { write } for  pid=13628 comm="xsltproc" name="output-docker" dev="sda1" ino=1972406 scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=1
----
time->Wed Dec  7 10:45:11 2016
type=AVC msg=audit(1481107511.432:1253): avc:  denied  { create } for  pid=13628 comm="xsltproc" name="guide.xml" scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 10:45:11 2016
type=AVC msg=audit(1481107511.432:1254): avc:  denied  { write open } for  pid=13628 comm="xsltproc" path="/home/oscap/scap-security-guide/RHEL/7/output/guide.xml" dev="sda1" ino=1972407 scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 10:45:11 2016
type=AVC msg=audit(1481107511.456:1255): avc:  denied  { read } for  pid=13629 comm="xsltproc" name="guide.xml" dev="sda1" ino=1972407 scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 10:45:20 2016
type=AVC msg=audit(1481107520.387:1257): avc:  denied  { ioctl } for  pid=13709 comm="grep" path="/home/oscap/scap-security-guide/RHEL/7/output/bash-remediations.xml" dev="sda1" ino=1972568 ioctlcmd=0x5401 scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 10:45:19 2016
type=AVC msg=audit(1481107519.138:1256): avc:  denied  { create } for  pid=13648 comm="generate-from-t" name="bash" scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=1
----
time->Wed Dec  7 10:45:39 2016
type=AVC msg=audit(1481107539.681:1259): avc:  denied  { remove_name } for  pid=13733 comm="sed" name="sedDGHb6q" dev="sda1" ino=1972851 scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=1
----
time->Wed Dec  7 10:45:39 2016
type=AVC msg=audit(1481107539.681:1258): avc:  denied  { setattr } for  pid=13733 comm="sed" name="sedDGHb6q" dev="sda1" ino=1972851 scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 10:45:39 2016
type=AVC msg=audit(1481107539.681:1260): avc:  denied  { rename } for  pid=13733 comm="sed" name="sedDGHb6q" dev="sda1" ino=1972851 scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 10:45:39 2016
type=AVC msg=audit(1481107539.681:1261): avc:  denied  { unlink } for  pid=13733 comm="sed" name="ssg-rhel7-xccdf-1.2.xml" dev="sda1" ino=1972850 scontext=system_u:system_r:container_t:s0:c354,c369 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
```

**Comment by wrabcak** [comment]
@konstruktoid
Please run as root:
semanage fcontext -a -t container_file_t /home/oscap/scap-security-guide/
restorecon -Rv /

This should fix your issue.

**Comment by konstruktoid** [comment]
Doesn't fix sorry to say:
```
...
cp output/ssg-sl6-xccdf.xml dist/content
cp output/ssg-sl6-ds.xml dist/content
make[1]: Leaving directory `/home/oscap/scap-security-guide/RHEL/6'
cd RHEL/7/ && /usr/bin/make
make[1]: Entering directory `/home/oscap/scap-security-guide/RHEL/7'
xsltproc -o output/guide.xml ../../shared/transforms/includelogo.xslt ../../shared/xccdf/shared_guide.xml
I/O error : Permission denied
I/O error : Permission denied
make[1]: *** [output/guide.xml] Error 11
make[1]: Leaving directory `/home/oscap/scap-security-guide/RHEL/7'
make: *** [rhel7] Error 2
$ sudo getenforce 
Enforcing
```

```
$ sudo ausearch -m USER_AVC,AVC -ts recent
----
time->Wed Dec  7 13:14:15 2016
type=USER_AVC msg=audit(1481116455.460:1393): pid=410 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  received setenforce notice (enforcing=0)  exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'
----
time->Wed Dec  7 13:14:36 2016
type=USER_AVC msg=audit(1481116476.018:1408): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  received setenforce notice (enforcing=0)  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
----
time->Wed Dec  7 13:19:22 2016
type=AVC msg=audit(1481116762.760:1415): avc:  denied  { add_name } for  pid=19371 comm="xsltproc" name="guide.xml" scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=1
----
time->Wed Dec  7 13:19:22 2016
type=AVC msg=audit(1481116762.760:1414): avc:  denied  { write } for  pid=19371 comm="xsltproc" name="output-docker" dev="sda1" ino=1972406 scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=1
----
time->Wed Dec  7 13:19:22 2016
type=AVC msg=audit(1481116762.760:1416): avc:  denied  { create } for  pid=19371 comm="xsltproc" name="guide.xml" scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 13:19:22 2016
type=AVC msg=audit(1481116762.771:1417): avc:  denied  { write open } for  pid=19371 comm="xsltproc" path="/home/oscap/scap-security-guide/RHEL/7/output/guide.xml" dev="sda1" ino=1972407 scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 13:19:22 2016
type=AVC msg=audit(1481116762.790:1418): avc:  denied  { read } for  pid=19372 comm="xsltproc" name="guide.xml" dev="sda1" ino=1972407 scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 13:19:31 2016
type=AVC msg=audit(1481116771.597:1420): avc:  denied  { ioctl } for  pid=19452 comm="grep" path="/home/oscap/scap-security-guide/RHEL/7/output/bash-remediations.xml" dev="sda1" ino=1972568 ioctlcmd=0x5401 scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 13:19:30 2016
type=AVC msg=audit(1481116770.348:1419): avc:  denied  { create } for  pid=19391 comm="generate-from-t" name="bash" scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=1
----
time->Wed Dec  7 13:19:49 2016
type=AVC msg=audit(1481116789.369:1422): avc:  denied  { remove_name } for  pid=19476 comm="sed" name="sed5UI181" dev="sda1" ino=1972851 scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=1
----
time->Wed Dec  7 13:19:49 2016
type=AVC msg=audit(1481116789.368:1421): avc:  denied  { setattr } for  pid=19476 comm="sed" name="sed5UI181" dev="sda1" ino=1972851 scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 13:19:49 2016
type=AVC msg=audit(1481116789.369:1423): avc:  denied  { rename } for  pid=19476 comm="sed" name="sed5UI181" dev="sda1" ino=1972851 scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
----
time->Wed Dec  7 13:19:49 2016
type=AVC msg=audit(1481116789.369:1424): avc:  denied  { unlink } for  pid=19476 comm="sed" name="ssg-rhel7-xccdf-1.2.xml" dev="sda1" ino=1972850 scontext=system_u:system_r:container_t:s0:c816,c968 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1
```

**Comment by mpreisler** [comment]
@wrabcak we need some more help here. I don't want to merge something that requires users to disable SELinux. At the same time this is a great feature that I want to merge :-/

**Comment by mpreisler** [comment]
@konstruktoid I am no container expert, but wouldn't we work around the issues by using `docker cp` instead of mounting the volume? Should be more elegant too.

**Comment by konstruktoid** [comment]
@mpreisler updated the instructions and tested on Fedora 25.

```
[vagrant@fedora scap-security-guide]$ sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      30
[vagrant@fedora scap-security-guide]$ cat /etc/redhat-release 
Fedora release 25 (Twenty Five)
```

**Comment by mpreisler** [comment]
Awesome, works now. ACK.

Thanks for this great contribution!

**Pull request merged**
