### PR TITLE
remediation for CCE 27243-5, audit log perms

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by shawndwells** [comment]
@redhatrises, did the ````chmod 640```` since the requirement is "640 or less permissive." Ref:
http://people.redhat.com/swells/scap-security-guide/RHEL/6/output/rhel6-guide.html#item-file_permissions_var_log_audit

You're entirely correct that 600 would be better, but that would be exceeding the requirement. "Meeting" the requirement is what should be codified -- and people can perform extra hardening as they wish.

Does bring up a point that perhaps the XCCDF should be updated to reflect 600 vs 640 though. Especially given default permissions. 

What do you think of for now, coding the remediation to meet the requirement... and when we revisit this in RHEL7 we adjust everything to 600?

**Comment by redhatrises** [comment]
@shawndwells sounds good.

**Comment by redhatrises** [comment]
Created issue #482 to track this.

**Comment by redhatrises** [comment]
@shawndwells what about `/etc/audit/auditd.conf` permission remediation to this script?

**Comment by shawndwells** [comment]
On 3/11/15 6:37 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> what about 
> |/etc/audit/auditd.conf| permission remediation to this script?
Because XCCDF/OVAL/remediation scripts represent a unique control (e.g. 
CCE), we'd want anything addressing auditd.conf to be its own rule.

In terms of existing rules, checking /etc/audit/auditd.conf would be be 
addressed by the RPM Verify rule.

e.g., the default permissions on /etc/audit/auditd.conf are:
> # ll /etc/audit/auditd.conf
> -rw-r-----. 1 root root 701 Aug 10  2014 /etc/audit/auditd.conf

If you change them and run an RPM Verify, you'll get a mismatch:
> # chmod 755 /etc/audit/auditd.conf
> [root@ssg-rhel6-devbox 6]# rpm -V -f /etc/audit/auditd.conf
> .M.......  c /etc/audit/auditd.conf
... and thus fail rpm_verify_permissions.

The sysadmin can then do rpm --setperms to fix the file permissions.

**Comment by redhatrises** [comment]
arg. Totally forgot about that. ack.

**Comment by shawndwells** [comment]
thanks!

**Pull request merged**
