### PR TITLE
[Enhancement][Infrastucture] Update disa references

### PR DESCRIPTION
**Pull request by redhatrises**
- Update to the latest DISA STIG references for RHEL5
- Add new DISA STIG references for RHEL6 and RHEL7
- Add SUSE DISA STIG reference
- Update DISA OS SRG reference
- Add DISA Mainframe URI

### CODE REVIEW

**Comment by redhatrises** [comment]
[retest this please]

**Comment by shawndwells** [comment]
[retest this please]

**Comment by shawndwells** [comment]
not immediately clear why this is failing, retesting

**Comment by iankko** [comment]
@shawndwells 
> not immediately clear why this is failing, retesting

This is just another manifestation of https://github.com/OpenSCAP/scap-security-guide/issues/1290 issue. IOW during the build xsltproc failed to load some external entity XML file (looks like:
```
warning: failed to load external entity "output/guide.xml"
unable to parse output/guide.xml
```
in this case, leading to scenario when instead of SSG build to terminate with proper error message, it continued to build as much as possible (due to xsltproc issue just warning instead of error, when this happens), till the moment it wasn't possible to continue.

I will try to allocate time for https://github.com/OpenSCAP/scap-security-guide/issues/1290 in couple of next days. In any case, the fix for that one will just exit sooner (right in the moment XML EE file failed to load). The true reason of the issue (wrong XML EE location / URI or invalid XML EE file content leading to 'unable to parse' message will need to be fixed separately in this PR).

**Comment by redhatrises** [comment]
@iankko looks like Jenkins may be failing here:

`rm -rf build
make[1]: Leaving directory '/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-fedora24/Fedora'
cd JRE && make clean
cp: cannot create regular file 'build/fedora_oval': No such file or directory
cp: cannot create regular file 'build/fedora_oval': No such file or directory
make[1]: Entering directory '/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-fedora24/JRE'`

**Comment by redhatrises** [comment]
[retest this please]

**Comment by iankko** [comment]
@redhatrises 
The issue isn't in Jenkins. The issue is in current ```master``` content (from https://jenkins.open-scap.org/job/scap-security-guide/). Seems https://jenkins.open-scap.org/job/scap-security-guide/703/ broke it.

**Comment by redhatrises** [comment]
@iankko Jenkins is passing now.

**Comment by mpreisler** [comment]
@iankko @redhatrises Sorry about the disruption. This was all caused by `clean` being a dependency of `jenkins` target. Therefore with parallel builds Jenkins was both creating files and deleting them in parallel. I have fixed that in https://github.com/OpenSCAP/scap-security-guide/pull/1372

**Comment by iankko** [comment]
@mpreisler 
> @iankko @redhatrises Sorry about the disruption. This was all caused by clean being a dependency of jenkins target. Therefore with parallel builds Jenkins was both creating files and deleting them in parallel. I have fixed that in #1372

No worries. Yeah, noticed once Gabe merged that PR it magically started working again (thus closed the ticket I opened in between).

What I am worried more WRT to this being why ```scap-security-guide-pull-request``` Jenkins job reported all is OK, and we needed to push it in order to find out ```scap-security-guide``` Jenkins job to start returning failure. Looks there's is some difference in the configuration of both jobs (and for this case it's good there is since we were able to detect the failure).

But this makes me to be more worried about trustworthness of ```scap-security-guide-pull-request``` Jenkins job (the trust into the fact that when it returns SUCCESS, everything truly is OK).

Should we investigate the reason further? (/me doesn't like this kind of nondeterminism / randomness to be honest)

**Comment by mpreisler** [comment]
> What I am worried more WRT to this being why scap-security-guide-pull-request Jenkins job reported all is OK, and we needed to push it in order to find out scap-security-guide Jenkins job to start returning failure. Looks there's is some difference in the configuration of both jobs (and for this case it's good there is since we were able to detect the failure).

The pull request builder wasn't using parallel builds while the normal CI job was using parallel builds. That's why everything was fine in the pull request jenkins job but failed just minutes later during normal CI build. Now both are using parallel builds.

**Comment by redhatrises** [comment]
Bump for review.

**Comment by iankko** [comment]
LGTM. ACK.

**Pull request merged**
