### PR TITLE
Move OpenStack XCCDF to shared XCCDF

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by mpreisler** [comment]
I don't understand the point of tihs. This is OpenStack-only XCCDF, why move it to shared?

**Comment by redhatrises** [comment]
Sorry @mpreisler. I didn't provide a bit more context. This is to allow the building of OSP 8, 9, and 10 content. Rather than copying the XCCDF multiple times, it made sense to first move the content into the shared folder.

**Comment by mpreisler** [comment]
Ah, OK. Shouldn't we use `prodtype` to make sure it doesn't get included in other products?

**Comment by redhatrises** [comment]
> Ah, OK. Shouldn't we use prodtype to make sure it doesn't get included in other products?

@mpreisler good point. Although nothing right now is calling for it except OSP7, would you like me to add it in this PR or in a separate PR?

**Comment by mpreisler** [comment]
@redhatrises AFAIK our goal is to include everything in shared in all products at some point in the future.

So I think we should do that in this PR.

**Comment by redhatrises** [comment]
Will do @mpreisler

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
