### PR TITLE
OpenSSH 7.4 allows only Protocol 2

### LINKED ISSUE #2296: Rule "Allow only SSH protocol 2" reports false negatives on RHEL7.4
Rule "Allow Only SSH Protocol 2" checks that  /etc/sshd_config contains string "Protocol 2".

However In RHEL 7.4 SSH protocol 1 was removed. This configuration option was removed from /etc/sshd_config as well. See https://access.redhat.com/articles/3022681

As a result, OpenSCAP reports that this rule fails, even if it's not possible to use other protocol.

(See the implementation of this check:
 https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/oval/sshd_allow_only_protocol2.xml )

Because some people might be running the old openssh from RHEL7.3. we shouldn't remove this check completely. Instead, we can improve the check to say that every OpenSSH RPM package >=7.4 will
satisfy this rule. If we have older version the check should be left as it was.

See the original email https://lists.fedorahosted.org/archives/list/scap-security-guide@lists.fedorahosted.org/thread/MLTTMWSNNFJNRRZSXMOWAL636NFC2OZI/  for further information.

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Add a check for `sshd_allow_only_protocol2` that also verifies OpenSSH Server version. If OpenSSH Server version is equal to or higher than 7.4, rule should pass.

#### Rationale:

- From OpenSSH Version 7.4, only protocol 2 is supported. If version 7.4 or newer is installed, rule should pass even without `Protocol 2` in `/etc/ssh/sshd_config` file.

- Fixes #2296

### CODE REVIEW

**Comment by redhatrises** [comment]
@yuumasato will you add a `<warning />` to `shared/services/ssh.xml` stating something like:
```
As of <tt>openssh-server</tt> version <tt>7.4</tt> and above, this option will be removed.
```
or something similar? We need to bring a bit more awareness in the XCCDF.

**Comment by redhatrises** [comment]
@yuumasato also `sshd_allow_only_protocol2.xml` should be in `shared/checks/oval` and should probably now check that `Protocol 1` is not set.

**Comment by yuumasato** [comment]
@redhatrises Ok, I'll add something to XCCDF Rule.

Regarding OVAL definition for `sshd_allow_only_protocol2` it will not be so easy for it to be in  in `share/checks/oval`, because now it relies on `rpminfo` to get package version and current check in `shared` is agnostic of package manager.

And I don't understand why we should check that `Protocol 1` is not set, what is the scenario?

**Comment by redhatrises** [comment]
> Regarding OVAL definition for `sshd_allow_only_protocol2` it will not be so easy for it to be in  in `share/checks/oval`, because now it relies on `rpminfo` to get package version and current check in `shared` is agnostic of package manager.

This check needs to be in `shared` as it is applicable to more products than just `RHEL7`. 

> And I don't understand why we should check that `Protocol 1` is not set, what is the scenario?

Ignore me on this one as I was thinking about the client and not the service config.

**Comment by yuumasato** [comment]
> This check needs to be in shared as it is applicable to more products than just RHEL7.

I agree.

>This is also no need to have 2 different checks for this because of an additional rpm version check.

How to do that? Problem is that this check would not work for `apt` based distros. I would have to implement something like `prodtype` for OVAL. Is there already a mechanism for that that I don't know of?

**Comment by yuumasato** [comment]
@redhatrises Added warning note. I feel like `description` and `ocil` fields should be updated too. What do you think?

Regarding the check living in `shared`, what do you think of having multiple `<def-group>` elements in the same file? One would apply to deb based distros, and the other for rpm based.
Both definitions would co exist in same file, and build system would pick them according to platform.

I ask because I remember you mentioned there should be only one definiiton per file...

**Comment by redhatrises** [comment]
`ocil` clause should be updated probably as well.

> I ask because I remember you mentioned there should be only one definiiton per file...

Why not just add the debian version of the check to the ``id="sshd_version_equal_or_higher_than_74"``? Or does this break something.

**Comment by yuumasato** [comment]
> Why not just add the debian version of the check to the id="sshd_version_equal_or_higher_than_74"? 

You mean like this: https://pastebin.com/4wn4gMf0 ?
This is very clever, but unfortunately it doesn't work. `dpkginfo` Item value will be `notcollected` which  test result in `unknown`, and then whole `sshd_version_equal_or_higher_than_74` will be `unknown`.

**Comment by yuumasato** [comment]
I have updated the OCIL check, and rebased to make use of Value `sshd_required`.

**Comment by redhatrises** [comment]
@yuumasato please just put the checks into one OVAL definition with the following OR:

```
<criteria comment="OpenSSH Server version is equal or higher than 7.4" operator="OR">
      <criterion comment="Check OpenSSH Server is equal or higher than 7.4"
      test_ref="test_deb_openssh-server_version" />
      <criterion comment="Check OpenSSH Server is equal or higher than 7.4"
      test_ref="test_rpm_openssh-server_version" />
    </criteria>
```

**Comment by yuumasato** [comment]
@redhatrises I doesn't work, see https://github.com/OpenSCAP/scap-security-guide/pull/2410#issuecomment-336419994

**Comment by redhatrises** [comment]
@yuumasato 

> @redhatrises I doesn't work, see #2410 (comment)

That's one of the reasons that `installed_OS_is` OVAL checks exist.

**Comment by yuumasato** [comment]
> That's one of the reasons that installed_OS_is OVAL checks exist.

Oh, thank you, lesson learned.

@redhatrises I have updated `sshd_version_higher_than_74` and removed RHEL7 overrider `rhel7/checks/oval/sshd_allow_only_protocol2.xml`.

**Comment by redhatrises** [comment]
Thanks Ack!

**Pull request merged**
