### PR TITLE
Fedora cleanup

### PR DESCRIPTION
**Pull request by ybznek**
https://github.com/OpenSCAP/scap-security-guide/issues/1668
Several service_enabled remediations introduced.

### CODE REVIEW

**Comment by jan-cerny** [comment]
I'll try to review this.

**Comment by jan-cerny** [comment]
I think we can get rid of `input/oval/service_sshd_disabled.xml` as well. In RHEL7 we just negate the service_sshd_enabled rule using extend definition, so it looks like it could be done here the same way.

**Comment by ybznek** [comment]
Jenkins ssg master build failing, it could cause failure if this PR.

**Comment by jan-cerny** [comment]
I have verified that this PR doesn't break Fedora's OVAL content, compared with current master. Great work, @ybznek !

**Comment by ybznek** [comment]
test this please

**Comment by ybznek** [comment]
test this please

**Comment by linux-modder** [comment]
I'll check tonight when I get home. @ybznek

**Comment by redhatrises** [comment]
Ack.

**Comment by linux-modder** [comment]
Still testing but so far no regressions or major issues noted @ybznek

**Pull request merged**
