### PR TITLE
[PATCH] [RHEL6][bugfix] Have sysctl OVAL check if IPv6 in use

### PR DESCRIPTION
**Pull request by shawndwells**
If a RHEL6 host has IPv6 disabled, the IPv6 sysctl checks will continue to fail
as they do not account for enable/disablement of IPv6 (the ipv6 sysctl settings
can not be set if ipv6 is disabled, and since the OVAL expects them, it fails the rule).

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells looks like our Jenkins server may be down.

**Comment by shawndwells** [comment]
On 4/8/15 4:17 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> looks like our Jenkins 
> server may be down.
Odd. Pulled up the console and it was kernel panicked. Just updated it 
in attempt for exposing build reports globally. Will continue poking at it.

**Comment by redhatrises** [comment]
@shawndwells ```${SHARED_DIR}/create_sysctl_ipv6_checks.py``` needs to be added to this PR as ```${SHARED_DIR}/create_sysctl_ipv6_checks.py``` does not exist.

**Comment by shawndwells** [comment]
thanks @redhatrises -- added.

**Comment by redhatrises** [comment]
@shawndwells should there be a `negate=true` added to `<extend_definition comment="is IPv6 enabled?" definition_ref="kernel_module_ipv6_option_disabled" />` so that if IPv6 is not enabled the check passes?

**Comment by redhatrises** [comment]
LGTM. Ack.

**Pull request merged**
