### PR TITLE
Update rhel7-cpe-dictionary.xml

### PR DESCRIPTION
**Pull request by rprice**
* Removed CentOS7 and Scientific Linux 7 as CPE items.
* Updated with supported RHEL variants.

@mpreisler - would these changes break anything ssg+openscap wise?  No sense in having CentOS/Scientific Linux in the CPE dictionary, right?

### CODE REVIEW

**Comment by mpreisler** [comment]
Hi @rprice, we support CentOS and SL in SCAP Security Guide. Why remove them?

**Comment by rprice** [comment]
@mpreisler Sure we do.  But does it need to be in the rhel7-cpe-dictionary.xml ?  Why not in the centos7-cpe-dictionary.xml?  

When I do an rpm-ql scap-security-guide I do not see any support for CentOS or Scientific Linux content.  Would removing their content from the RHEL content not make sense?

**Comment by mpreisler** [comment]
@rprice Yeah, it does. The way it works the RHEL7 XCCDF references RHEL7 OVAL and RHEL7 CPE + CPE OVAL. The CentOS7 XCCDF references RHEL7 OVAL and RHEL7 CPE + CPE OVAL. Does that make sense?

The `rpm -ql scap-security-guide` situation is downstream where we may decide to ship all upstream SSG provides or omit some products to make the UX better. Therefore you may see a different set of guides downstream and upstream.

**Comment by rprice** [comment]
@mpreisler I see.  If they need to be in there, lets keep them in there, but the other RHEL variants I added should be included because it is the support RHEL variants and some were missing.

**Comment by mpreisler** [comment]
Yup, agreed. Add them back and I will merge this.

**Comment by mpreisler** [comment]
ACK.

**Pull request merged**
