### PR TITLE
Don't generate roles for empty profiles

### LINKED ISSUE #2129: Don't generate roles for empty profiles
The bash roles are generated for the "default" profile, but "default" profile contains no rules, the script is an empty file. For example `ssg-rhel7-role-default.sh`.

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #2129

### CODE REVIEW

**Comment by redhatrises** [comment]
Probably a better way of doing this than what I did.... brain is just not working.

**Comment by jan-cerny** [comment]
@redhatrises I think you can do it based on profile ID.

**Comment by mpreisler** [comment]
Definitely NACK, we should do this more elegantly.

**Comment by mpreisler** [comment]
Look at line 155. We don't even have to generate it in the first place.

**Comment by redhatrises** [comment]
@mpreisler remove default profile generation.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
