### PR TITLE
[BugFix] [RHEL/6] Various NIST SCAP content validation test suite fixes

### PR DESCRIPTION
**Pull request by iankko**
Fixes:
* https://github.com/OpenSCAP/scap-security-guide/issues/1041
* https://github.com/OpenSCAP/scap-security-guide/issues/1042

### CODE REVIEW

**Comment by iankko** [comment]
For the failing Jenkins CI ```el6``` job -- it's expected that it's failing:
&nbsp; &nbsp; [1] https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/397/consoleFull

This will fail till fix from https://github.com/OpenSCAP/scap-security-guide/pull/1048 isn't merged (since right now / with current ```master``` the ```make validate``` target for ```RHEL/7``` is failing when built on RHEL/6 [with openscap-1.0.x]).

Once fix for https://github.com/OpenSCAP/scap-security-guide/pull/1048 is merged, the testing job for this PR should be rescheduled and it should pass in that moment (since the underlying changes are not related with OVAL checks).

**Comment by iankko** [comment]
re[test this please]

**Comment by iankko** [comment]
@jan-cerny 
Honzo, could you possibly review this one too? (should be easy to review -- two small changes, pretty straightforward).

Thanks, Jan!

**Comment by jan-cerny** [comment]
@iankko Thank you for fixing those issues. LGTM. ACK.

**Comment by iankko** [comment]
Thanks too!

**Pull request merged**
