### PR TITLE
[Enhancement] Enhance the 'profile-stats.py' helper yet

### PR DESCRIPTION
**Pull request by iankko**
It to be able also to:

* Print also implemented OVALs, remediations, and CCEs assigned (this could be handy to create release notes / diffs across releases easily),
* Print the stats in the form of JSON file if --json option was provided (suitable for further machine processing)

Please review.

Thank you, Jan

### CODE REVIEW

**Comment by radzy** [comment]
+1 : To a newb, this looks like it would be more useful than the previous behavior.

**Comment by iankko** [comment]
Below is some sample output of updated version:
```
$ ./profile_stats.py -p pcidss -b /tmp/github/scap-security-guide/RHEL/7/output/ssg-rhel7-xccdf.xml 
No such profile "pcidss" found in the benchmark!
* Available profiles:
** standard
** pci-dss
** C2S
** rht-ccp
** common
** stig-rhel7-workstation-upstream
** stig-rhel7-server-gui-upstream
** stig-rhel7-server-upstream
** ospp-rhel7-server
** nist-cl-il-al
** cjis-rhel7-server
** docker-host
```

```
$ ./profile_stats.py -p docker-host -b /tmp/github/scap-security-guide/RHEL/7/output/ssg-rhel7-xccdf.xml --missing

* SCAP Security Guide 0.1.30 statistics of 'docker-host' profile:
** Count of rules: 5
** Count of ovals: 5 [100% complete]
** Count of fixes: 3 [60% complete]
** Count of CCEs: 4 [80% complete]
*** Rules of 'docker-host' profile missing remediation: 2 of 5 [60% complete]
   service_docker_enabled                          docker_selinux_enabled                       
***Rules of 'docker-host' profile missing CCE identifier: 1 of 5 [80% complete]
   docker_selinux_enabled                       
```

```
$ ./profile_stats.py -p docker-host -b /tmp/github/scap-security-guide/RHEL/7/output/ssg-rhel7-xccdf.xml --implemented

* SCAP Security Guide 0.1.30 statistics of 'docker-host' profile:
** Count of rules: 5
** Count of ovals: 5 [100% complete]
** Count of fixes: 3 [60% complete]
** Count of CCEs: 4 [80% complete]
*** Rules of 'docker-host' profile having OVAL check: 5 of 5 [100% complete]
   service_docker_enabled                          enable_selinux_bootloader                    
   selinux_state                                   selinux_policytype                           
   docker_selinux_enabled                       
*** Rules of 'docker-host' profile having remediation script: 3 of 5 [60% complete]
   enable_selinux_bootloader                       selinux_state                                
   selinux_policytype                           
*** Rules of 'docker-host' profile having CCE assigned: 4 of 5 [80% complete]
   service_docker_enabled                          enable_selinux_bootloader                    
   selinux_state                                   selinux_policytype             
```

```
$ ./profile_stats.py -p docker-host -b /tmp/github/scap-security-guide/RHEL/7/output/ssg-rhel7-xccdf.xml --implemented --json
{
    "profile_id": "docker-host", 
    "implemented_ovals_pct": 100.0, 
    "ssg_version": "SCAP Security Guide 0.1.30", 
    "implemented_fixes": [
        "enable_selinux_bootloader", 
        "selinux_state", 
        "selinux_policytype"
    ], 
    "implemented_fixes_pct": 60.0, 
    "rules_count": 5, 
    "assigned_cces_pct": 80.0, 
    "assigned_cces": [
        "service_docker_enabled", 
        "enable_selinux_bootloader", 
        "selinux_state", 
        "selinux_policytype"
    ], 
    "implemented_ovals": [
        "service_docker_enabled", 
        "enable_selinux_bootloader", 
        "selinux_state", 
        "selinux_policytype", 
        "docker_selinux_enabled"
    ]
}
```

Like in the previous version, if profile is omitted, it will print the info for all of the available profiles.

**Comment by mpreisler** [comment]
I noticed that if you use `--json` and don't specify a profile the resulting JSON is invalid. It is missing the delimiters between profiles.

**Comment by mpreisler** [comment]
I tried to put a quick script together that would generate a json for all SSG releases so I can create a nice chart. The json the script outputs when you don't specify any profile is invalid and can't be loaded.

```
>>> json.load(open("./v0.1.30-rhel7.json", "r"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 49 column 1 - line 4341 column 1 (char 1681 - 176641)
```

**Comment by mpreisler** [comment]
I found an easy workaround, let's merge this and fix it later.

**Comment by mpreisler** [comment]
json fixed in 23fc41f57adef53c51e26426ca14822218eaa2c3

**Comment by mpreisler** [comment]
[ssg-release-stats.zip](https://github.com/OpenSCAP/scap-security-guide/files/417150/ssg-release-stats.zip)

JSONs for RHEL6 and RHEL7 profiles or all SSG releases.

**Comment by iankko** [comment]
@mpreisler 
> json fixed in 23fc41f

Hi Martin, thank's for noticing the issue && also fixing it! (didn't have chance to use that previously generated json for all profiles in some script => it's great you checked it && noticed the issue).

**Comment by iankko** [comment]
@mpreisler 
>  ssg-release-stats.zip
> JSONs for RHEL6 and RHEL7 profiles or all SSG releases.

Woot, very nice (from a very quick look it's visible e.g. we assigned all CCEs for pci-dss profile between 0.1.29 and 0.1.30 releases). Assuming more information might be data mined from those stats if desired.

Do you plan to share that 'stats making script' via e.g. jenkins job?

**Pull request merged**
