### PR TITLE
[Enhancement][RHEL/6][RHEL/7][Fedora] add functions for services and packages

### PR DESCRIPTION
**Pull request by redhatrises**
- Add function that can enable/disable service in RHEL and Fedora
- Add function that can install/uninstall packages in RHEL and Fedora
- Update services enabled/disabled templates
- Update packages installed/removed templates

### CODE REVIEW

**Comment by redhatrises** [comment]
@iankko I am not sure when you plan on releasing 0.1.26. Do you mind checkout out this one as well? If possible, I would like to clean up duplicates in the Fedora, RHEL-6, and RHEL-7 remediation scripts, and adding these functions would help with some of that.

**Comment by iankko** [comment]
@redhatrises 
> @iankko I am not sure when you plan on releasing 0.1.26.

Today or tomorrow (depending how quickly I will able to finish all the 13 missing remediations for RHEL-7's PCI-DSS profile). Actually promised it to happen last Monday already (IIRC), but got distracted by  other internal duties. In any case count it should be very soon.

> Do you mind checkout out this one as well?

Will have a look at it. From a brief look I can tell I like the abstraction layer introduced by the proposal (IOW not checking if we are using ```yum``` or ```dnf``` on per remediation script basis, but rather moving this check into that newly introduced routine to take care for that). This way all of RHEL-6, RHEL-7, and Fedora remediation scripts can be more universal and re-used.

Same holds for services approach. This is the way we should go in the future. Thanks for taking time
for implementing / proposing this. Btw. for the future -- should you want something like this to be reviewed by an urgent manner, feel free to use the 'infrastructure' label / tag on the pull request (so it's noticeable / distinguishable from other more specific PRs, which can be reviewed && merged basically any time). Even don't be afraid to use the "blocker" tag / label, when you think it's appropriate. It's here for that purpose (this helps me to prioritize things which needs to be looked at with higher priority within release closing tasks).

> If possible, I would like to clean up duplicates in the Fedora, RHEL-6, and RHEL-7 remediation scripts, and adding these functions would help with some of that. 

Sure. I can see the point behind having these available. Will review shortly.

Thanks, Jan.

**Comment by iankko** [comment]
Two margin points / notes for review:
* when changing some infrastructure templates would be good to show one example of calling of the new template to see if that's working (without need to regenerate the remediations at appropriate places) -- just note for future PR's like this one,
* we are copying the same content on multiple locations:
 ```
scap-security-guide]$ git status
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean

$ diff -s RHEL/6/input/checks/templates/template_BASH_package_removed RHEL/7/input/checks/templates/template_BASH_package_removed
Files RHEL/6/input/checks/templates/template_BASH_package_removed and RHEL/7/input/checks/templates/template_BASH_package_removed are identical

$ diff -s RHEL/6/input/checks/templates/template_BASH_package_removed Fedora/input/checks/templates/template_BASH_package_removed 
Files RHEL/6/input/checks/templates/template_BASH_package_removed and Fedora/input/checks/templates/template_BASH_package_removed are identical
```

This can be fixed in the future though (it's not a blocker for the merge). As I said already, I like the abstraction layer these new routines are introducing, and IMHO that advantage overcomes the fact same templates are copied multiple times over different places.

**Comment by iankko** [comment]
Another point being since from yesterday the remediation scripts require ```# platform``` tag to be included into them (they to be incorporated into final XCCDF), the corresponding templates should be updated to include the ```# platform``` tag in them (RHEL-6 templates to include ```# platform = Red Hat Enterprise Linux 6``` etc.).

This would also solve the issue having multiple identical copies of same template on multiple places (the requirement the template to contain the ```# platform = ``` tag would make the templates differ one from each other).

Can you enhance the proposal with these changes yet?

Also, when on that, could you regenerate one existing remediaton script of type ```package installed```, ```package removed```, ```service enabled```, and ```service disabled``` for each of the products (RHEL-6, RHEL-7, and Fedora) so it would be visible right from the testing / reviewing the PR the new templates are working?

Thanks, Jan.

Once these two changes are done I will re-review.

**Comment by redhatrises** [comment]
> Btw. for the future -- should you want something like this to be reviewed by an urgent manner, feel free to use the 'infrastructure' label / tag on the pull request (so it's noticeable / distinguishable from other more specific PRs, which can be reviewed && merged basically any time). Even don't be afraid to use the "blocker" tag / label, when you think it's appropriate. It's here for that purpose (this helps me to prioritize things which needs to be looked at with higher priority within release closing tasks).

Will do. Thanks @iankko. Updated PR per your comments. Ready for your review.

**Comment by redhatrises** [comment]
> This should be 'ypserv'. But I will fix that manually.

@iankko I went a head and added a fix so that you wouldn't have to.

**Comment by iankko** [comment]
Thanks! This version looks good to me (manually tried to build on RHEL-7 till Jenkins finished & verified the content works).

ACK.

**Pull request merged**
