### PR TITLE
Remove testoval.py clones

### PR DESCRIPTION
**Pull request by ybznek**

### CODE REVIEW

**Comment by redhatrises** [comment]
I say NACK on this. The `testoval.py` is supposed to be wherever the "static" oval files are as it makes it easier to test them, and trying to find `testoval.py` or path `testoval.py` would be incredibly annoying.

**Comment by ybznek** [comment]
@redhatrises I recommend to use something like this ```alias ssgbuild='/home/zmoravec/gitRepos/ssg-build.sh'```
Let's wait for opinions of others.

**Comment by redhatrises** [comment]
IMO not helpful. This is not only for the creation of OVAL files but testing changes to existing static OVAL files.

**Comment by mpreisler** [comment]
I agree with @ybznek . Having duplicated files just to avoid typing in a path doesn't seem right to me.

**Comment by shawndwells** [comment]
+1 with @redhatrises . The testoval scripts are extremely useful to have in the current working directory. If I'm working in the RHEL7 OVAL (scap-security-guide/RHEL/7/input/oval), having to type something like ``./../../../../shared/oval/testoval.py <oval>`` is super frustrating. 

Also realize multiple copies of testoval is frustrating to maintain though. Symlinks could be an option... but even though git supports them... that feels dirty.

**Comment by redhatrises** [comment]
We could create a scap-security-guide-devel package that contains all the python scripts that have to be executed and require that package be installed to build. That would remove the duplicates, path issues, etc., but that would probably come with its own set of issues. Could also be the happy medium for everyone.

**Comment by ybznek** [comment]
I still think, that contributor can use wholePath/bash alias/PATH.  Devel package is quite complicated - not only rpm distros exist.

**Comment by mpreisler** [comment]
> I still think, that contributor can use wholePath/bash alias/PATH. Devel package is quite complicated - not only rpm distros exist.

+1 I have an alias for the SSG shared utils directory and regularly use it to test.

**Comment by yuumasato** [comment]
I think that value added in design by not duplicating files is bigger than value added by solving practical problem of using `testoval.py`, which can be solved in different way, depending on personal taste.

If the desirable way of working is to have `testoval.py` in directory, maybe it could be enhanced somehow to be copy-pastable in any directory under SSG and still work as expected.

**Comment by shawndwells** [comment]
@yuumasato could you update the README with what to put into bashrc (or wherever) to set the shared/utils path? seems like a reasonable compromise.

**Comment by yuumasato** [comment]
Sure, I can update it. I'll add a commit to this PR.
`README-layout.md` Looks like a good place to put this kind of info.

**Comment by ybznek** [comment]
test this please

**Comment by shawndwells** [comment]
LGTM. @redhatrises ?

**Comment by mpreisler** [comment]
@redhatrises ping

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

(testing jenkins after cmake merge)

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
