### PR TITLE
[Enhancement] [Infrastructure] Don't rely on absolute path of the remediation functions library to be able to perform remediations

### PR DESCRIPTION
**Pull request by iankko**
Replace the necessity of ```/usr/share/scap-security-guide/remediation-functions``` remediation functions library to be installed in order to be able to perform remediations with use of ```<xccdf:sub>``` elements for each general remediation functions used in the specific remediation script

Fixes (upstream): https://github.com/OpenSCAP/scap-security-guide/issues/590
Fixes (upstream): https://github.com/OpenSCAP/scap-security-guide/issues/1055
Fixes (downstream): https://bugzilla.redhat.com/show_bug.cgi?id=1313491

Overview of the changes performed by specific patches (present within this PR):
* patch https://github.com/OpenSCAP/scap-security-guide/commit/a2c069238c6d56861260b9f085fc9555ceb9020c modifies the ```combineremediations.py``` helper to substitute every occurrence / instance of remediation function call with corresponding ```<xccdf:sub>``` element,
* patch https://github.com/OpenSCAP/scap-security-guide/commit/e0ee706f787c6216e6d9cdbb220e4d43ca255f48 applies the new functionality against ```RHEL/7``` benchmark,
* patch https://github.com/OpenSCAP/scap-security-guide/commit/8b9be626ee491e1ad42a990e3604eb31fcbc4206 applies the new functionality to the remaining benchmarks:
  *  ```Webmin```
  * ```RHEVM3```
  * ```RHEL/6```
  * ```RHEL/5```
  * ```OpenStack/RHEL-OSP/7```
  * ```JRE```
  * ```JBoss/Fuse/6```
  * ```JBoss/EAP/5```
  * ```Firefox```
  * ```Fedora```
  * ```Debian/8``` and
  * ```Chromium```
* patch https://github.com/OpenSCAP/scap-security-guide/commit/79817066a4d2322cd90e937e6cbeffa461ff808d fixes multiple (by testing identified) issues in newly added ```expand_xccdf_subs()``` routine, and finally
* patch https://github.com/OpenSCAP/scap-security-guide/commit/a0e046940825ec31ea2767e12a05914703201186 approaches the problem of absenting support for ```flags``` parameter in Python's ```re.split()``` routine in Python < 2.7 (thus RHEL-6 and older) in more official way (instead of using custom ugly workaround uses more official ```re.compile()``` method).

Testing report:
This PR has been tested on the following systems:
* ```RHEL-6```, and
* ```RHEL-7```
in the following testing scope:
* ```make jenkins``` target was performed on both of them as was identified as passing,
* the new approach how to implemented execution of remediations (having remediations present directly in the benchmark rather than rely on existence of external ```/usr/share/scap-security-guide/remediation-functions``` shell library with their definition) has been tested (on both systems) on the following three different rules (categories of rules):
  * ```Ensure SELinux State is Enforcing``` (using ```replace_or_append``` function)
  * ```Ensure auditd Collects Information on the Use of Privileged Commands``` (using ```perform_audit_rules_privileged_commands_remediation``` function), and
  * ```Ensure auditd Collects File Deletion Events by User``` (using ```fix_audit_syscall_rule``` remediation function).

Testing of these tree different routines / categories confirmed on both (RHEL/6 and RHEL/7) systems the remediations are still working properly.

Known limitations of the PR (to be corrected in the future):
* If remediation function is called multiple times in the ```fix.text```, a new ```<xccdf:sub>``` element will be created for each such a call (this will be optimized to add ```<xccdf:sub>``` only first time not yet substituted remediation function is called),
* The newly added ```shared/xccdf/remediation_functions.xml``` location (containing definition of ```<xccdf:Values``` the ```<xccdf:sub>``` elements to point to) has been generated manually for now. In future PR, I will add a routine generating content of ```shared/xccdf/remediation_functions.xml``` file from the content of ```shared/remediations/bash/templates/remediation_functions``` automatically (to handle also the case new remediation function is added into the library).

Please review.

Thank you, Jan.

### CODE REVIEW

**Comment by iankko** [comment]
@mpreisler 
Martin, since you proposed the original idea of https://github.com/OpenSCAP/scap-security-guide/issues/590 , could you please review this one?

Thank you, Jan

**Comment by iankko** [comment]
Hold on your horses. Will have a look while Jenkins failed (and if it's related with changes done with this PR).

**Comment by iankko** [comment]
> Hold on your horses. Will have a look while Jenkins failed (and if it's related with changes done with this PR).

Looks Jenkins CI is currently being restarted (```Please wait while Jenkins is getting ready to work..```) since Zbynek is currently working on fixing some issues in the infrastructure. Thus hard to tell what was the reason of the failure.

But as already mentioned in c#0 of this PR, I have tested the changed on both ```openscap-1.0.x``` and ```openscap-1.2.x``` and it seems to be working fine.

**Comment by iankko** [comment]
And it's back. From looking at:
  https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/242/

the testing jobs on all the different slaves have passed (are green). Just the parent job is red (so IMHO the reason of the failure isn't related with the changes done in this PR).

**Comment by iankko** [comment]
Here's the result of this PR, when started manually:
  https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/248/

**Comment by redhatrises** [comment]
> Known limitations of the PR (to be corrected in the future):
* If remediation function is called multiple times in the ```fix.text```, a new ```<xccdf:sub>``` element will be created for each such a call (this will be optimized to add ```<xccdf:sub>``` only first time not yet substituted remediation function is called),
* The newly added ```shared/xccdf/remediation_functions.xml``` location (containing definition of ```<xccdf:Values``` the ```<xccdf:sub>``` elements to point to) has been generated manually for now. In future PR, I will add a routine generating content of ```shared/xccdf/remediation_functions.xml``` file from the content of ```shared/remediations/bash/templates/remediation_functions``` automatically (to handle also the case new remediation function is added into the library).

@iankko can you create tickets for these so that we can keep track of the future enhancements?

**Comment by redhatrises** [comment]
@iankko A couple of questions for clarity:

* Is `shared/xccdf/remediation_functions.xml` replacing `shared/remediations/bash/templates/remediation_functions`?
* Will `shared/xccdf/remediation_functions.xml` always exist and have to be updated or do you envision having `combineremediations.py` handle the `<xccdf:Values` and `<xccdf:sub>` elements?

**Comment by iankko** [comment]
@redhatrises 
> @iankko A couple of questions for clarity:
> Is shared/xccdf/remediation_functions.xml replacing shared/remediations/bash/templates/remediation_functions?

No. The reason is ```shared/xccdf/remediation_functions.xml``` requires functions expressed in XML / HTML syntax / format (entities escaped). Which IMHO isn't convenient for function writer. Thus the expectation is still to keep ```shared/remediations/bash/remplates/remediation_functions``` and derive ```shared/xccdf/remediation_functions.xml``` automatically from the content of that.
The difference is that ```shared/remediations/bash/templates/remediation_functions``` from now on won't need to be installed on the system the remediations to work.

This approach (derive ```remediation_functions.xml``` from ```remediation_functions``` expressed in shell syntax) might seem overly complex. But IMHO will be more convenient in the moment new function is being added.

>    Will shared/xccdf/remediation_functions.xml always exist and have to be updated or do you envision having combineremediations.py handle the <xccdf:Values and <xccdf:sub> elements?

```shared/xccdf/remediation_functions.xml``` needs to exists always. Like the ```<xccdf:Values>``` need their definition stored somewhere. Another approach would be to create only one value from whole ```shared/remediations/bash/templates/remediation_functions``` file content, and use that value in each remediation fix. But in that case we would include also not necessary functions into the specific remediation (given the file has 920 lines now), the ```Remediation script``` element presented in the HTML guide would be very long for each of the rules (take e.g. 200 rules each of them having 920 lines remediation script). This won't change the benchmark size (since it's substituted only when viewed), but still the presented HTML would be very big.

**Comment by iankko** [comment]
> @iankko can you create tickets for these so that we can keep track of the future enhancements?

Good catch! Thanks, will do that.

**Comment by redhatrises** [comment]
>>    Will shared/xccdf/remediation_functions.xml always exist and have to be updated or do you envision having combineremediations.py handle the <xccdf:Values and <xccdf:sub> elements?

>```shared/xccdf/remediation_functions.xml``` needs to exists always. Like the ```<xccdf:Values>``` need their definition stored somewhere. Another approach would be to create only one value from whole ```shared/remediations/bash/templates/remediation_functions``` file content, and use that value in each remediation fix. But in that case we would include also not necessary functions into the specific remediation (given the file has 920 lines now), the ```Remediation script``` element presented in the HTML guide would be very long for each of the rules (take e.g. 200 rules each of them having 920 lines remediation script). This won't change the benchmark size (since it's substituted only when viewed), but still the presented HTML would be very big.

Automating it would be handy. Also not having to store/update the file every time there is a new script. I wonder if we can create the file automatically, output it into the content's `output` directory, and merge it that way in the future?

**Comment by iankko** [comment]
@redhatrises 
> Automating it would be handy. Also not having to store/update the file every time there is a new script. I wonder if we can create the file automatically, output it into the content's output directory, and merge it that way in the future?

Yes, having current ```shared/xccdf/remediation_functions.xml``` implemented this way would be an alternative too (something like we are doing now for ```contributors.xml```). Have a universal XSLT transformation (since it would apply for every benchmark) translating ```shared/remediations/bash/templates/remediation_functions``` to `$(OUT)/remediation_functions.xml``` and use that output in the benchmark (we just would need to ensure such ```$(OUT)/remediation_functions.xml``` is completed before current ```$(OUT)/xccdf-unlinked-unresolved.xml``` target so it would be included).

Thanks, Gabe. This is great proposal (and actually not deriving much from the UX experience we have today).

**Comment by iankko** [comment]
@openscap-jenkins 
re[test this please]

**Comment by mpreisler** [comment]
I agree with @redhatrises about generating the xccdf:Value from normal bash scripts. However I think we can merge this PR here and change that later.

I like the function split. I know I originally proposed to put all functions into a single value but this is better and doesn't bloat the generated fix snippet as much.

ACK.

**Pull request merged**
