### PR TITLE
Fix for Issue 2264

### PR DESCRIPTION
**Pull request by chopskxw**
**Summary**
All instances of `rhn_register` replaced with `subscription-manager register`.

**Files modified**
RHEL/6/xccdf/system/software/updating.xml
shared/references/disa-stig-rhel6-v1r12-xccdf-manual.xml
shared/xccdf/system/software/updating.xml

### CODE REVIEW

**Comment by chopskxw** [comment]
#2264

**Comment by redhatrises** [comment]
@chopskxw please undo your changes to `shared/references/disa-stig-rhel6-v1r12-xccdf-manual.xml`. This is an official document that we do not create or make changes to except for add new versions.

**Comment by redhatrises** [comment]
Thanks for your contribution! Ack.

**Comment by shawndwells** [comment]
Whoa, that was fast. Thanks @chopskxw !

**Pull request merged**
