### PR TITLE
Keep human readable hints in SSG IDs after relabelling

### PR DESCRIPTION
**Pull request by mpreisler**
OVAL mandates that each ID is in the form of `oval:namespace:type:ID` where ID is numeric. This means that as part of the build we turn nice IDs that are human readable and mean something -- like `package_pam_pkcs11_installed` -- into useless numeric IDs such as `oval:ssg:def:3794`. This makes debugging and bug reports very annoying.

I present to you a fine example of **specification abuse**: I have changed the `idtranslate.py` file to put the human readable part of the ID into the namespace part of OVAL ID. This is legal and validates correctly, the resulting content builds and works. Here are a few excerpts from the built OVAL content:

```
    <definition class="compliance" id="oval:ssg-package_rsh-server_removed:def:160" version="1">
      <metadata>
        <title>Package rsh-server Removed</title>
        <affected family="unix">
...
```

```
      <criteria comment="SSH is not being used or conditions are met" operator="OR">
        <extend_definition comment="sshd service is disabled" definition_ref="oval:ssg-service_sshd_disabled:def:167"/>
        <criterion comment="Check HostbasedAuthentication in /etc/ssh/sshd_config" test_ref="oval:ssg-test_sshd_hostbasedauthentication:tst:168"/>
      </criteria>
```

This makes the debugging work by @jan-cerny a lot more useful, see http://www.jan-cerny.cz/2015/12/09/verbose-mode-in-openscap-1-2-7/
What do you think?

### CODE REVIEW

**Comment by iankko** [comment]
Looks good IMHO. 

Side note -- once this is applied OVAL code changes applied will be visible in the final benchmark (e.g. if some OVAL definition is completely rewritten or parts of it changed, new corresponding OVAL objects / variables  will appear in the final benchmark, and the former ones will be missing).

So this might be actually something customers might welcome to better track the changes across SSG releases. +1 from me to consider application of this.

@shawndwells , @redhatrises Any thoughts on the above?

**Comment by mpreisler** [comment]
By abolishing the IDs completely we can have stable IDs between releases. Example: `oval:ssg-some-human-radable-id:def:1`. That's a valid ID. It goes against the spirit of the specification but is valid and would work.

**Comment by mpreisler** [comment]
Another example of where this helps:

```
$ oscap oval eval ssg-fedora-oval.xml 
Definition oval:ssg-system_info_architecture_x86_64:def:105: true
Definition oval:ssg-system_info_architecture_x86:def:149: false
Definition oval:ssg-sysctl_kernel_ipv6_disable:def:362: false
Definition oval:ssg-sysctl_kernel_exec_shield:def:145: true
Definition oval:ssg-sshd_set_keepalive:def:297: true
Definition oval:ssg-sshd_set_idle_timeout:def:180: true
Definition oval:ssg-sshd_disable_root_login:def:299: true
Definition oval:ssg-sshd_disable_empty_passwords:def:183: true
Definition oval:ssg-snmpd_use_newer_protocol:def:415: true
Definition oval:ssg-snmpd_not_default_password:def:287: true
Definition oval:ssg-set_password_hashing_algorithm_logindefs:def:236: true
Definition oval:ssg-set_firewalld_default_zone:def:953: false
Definition oval:ssg-service_sshd_disabled:def:181: true
Definition oval:ssg-service_firewalld_enabled:def:1004: false
Definition oval:ssg-service_crond_enabled:def:1022: true
Definition oval:ssg-service_chronyd_enabled:def:126: true
Definition oval:ssg-service_auditd_enabled:def:336: true
Definition oval:ssg-securetty_root_login_console_only:def:100: true
Definition oval:ssg-rsyslog_files_permissions:def:1038: false
Definition oval:ssg-rsyslog_files_ownership:def:1024: true
Definition oval:ssg-rsyslog_files_groupownership:def:1016: true
...
```

**Comment by redhatrises** [comment]
> Side note -- once this is applied OVAL code changes applied will be visible in the final benchmark (e.g. if some OVAL definition is completely rewritten or parts of it changed, new corresponding OVAL objects / variables will appear in the final benchmark, and the former ones will be missing).

Which would lead to confusion by users as to the change. But IMHO, I don't think that users should truly care about that as things change.

Ack from me!

**Comment by isimluk** [comment]
I vote for having the 1 on `oval:ssg-some-human-radable-id:def:1`. There are several users who want to have stable IDs across the ssg releases.

**Comment by mpreisler** [comment]
> I vote for having the 1 on oval:ssg-some-human-radable-id:def:1. There are several users who want to have stable IDs across the ssg releases.

Agreed. Doing this would also simplify the SSG build process -- `ssg.ini` is no longer required and the `idtranslator.py` can be removed.

**Comment by shawndwells** [comment]
Content users are consistently encouraged to create any mappings against CCEs, not XCCDF/OVAL IDs. A few of our downstream friends (@gregelin, @trevor-vaughan) should be tipped off, but this seems like a great step towards usability!

**Comment by mpreisler** [comment]
OK, it seems there is a consensus that we want the human readable IDs. **Do no merge** this yet, I will change it to fully stable IDs based on the idea outlined previously.

**Comment by mpreisler** [comment]
Debian and RHEL7 fails `make validate` but that's unrelated to this PR.

I still want to do one change before this is merged and that is to unify RHEL5 relabelids with the shared one. Should happen later today.

**Comment by mpreisler** [comment]
Turns out I just had to remove an unused file and that was it.

Now this is ready for review and merge.

**Comment by iankko** [comment]
@mpreisler 
> Now this is ready for review.

Thanks. Will have a look

**Comment by iankko** [comment]
Basic sanity testing:
* verified the content properly builds on all RHEL-6, RHEL-7, and Fedora 23 systems,
* verified scanning selected profiles && tailoring works,
* verified ```make validate``` still passes for ```RHEL/6``` and ```Fedora``` products on all three systems,
* verified the case when XCCDF ID possibly doesn't match OVAL ID in the content is still properly recognized && reported:
```
../../shared/transforms/relabelids.py unlinked-rhel6-xccdf.xml ssg
The OVAL ID does not match the XCCDF Rule ID!

  OVAL ID:       'sample_entropy_oval'
  XCCDF Rule ID: 'kernel_disable_entropy_contribution_for_solid_state_drives'

Both OVAL and XCCDF Rule IDs must match!
make: *** [content] Error 1
```

=> No problem here.

**Comment by iankko** [comment]
LGTM (AFAICT from testing). ACK for merging this.

**Pull request merged**
