### PR TITLE
Remove unneeded Fedora 20 CPE check.

### PR DESCRIPTION
**Pull request by isimluk**
Not used by anything.

### CODE REVIEW

**Comment by redhatrises** [comment]
@isimluk `installed_OS_is_fedora19.xml` should be removed and `shared/oval/accounts_password_pam_retry.xml` should be updated to `installed_OS_is_fedora20.xml`

**Comment by shawndwells** [comment]
Agree on the need to remove stale platforms. Before doing so, there are 11 Fedora 19 OVAL checks lurking, with another 57 using the Fedora 20 platform tag. They should be updated before this gets merged.

Ref:

````
$ grep -rin "<platform>Fedora 19" *
input/checks/file_permissions_binary_dirs.xml:6:        <platform>Fedora 19</platform>
input/checks/templates/template_package_removed:8:        <platform>Fedora 19</platform>
input/checks/templates/template_package_installed:8:        <platform>Fedora 19</platform>
input/checks/file_permissions_library_dirs.xml:6:        <platform>Fedora 19</platform>
input/checks/file_ownership_library_dirs.xml:6:        <platform>Fedora 19</platform>
input/checks/service_ntpd_enabled.xml:6:        <platform>Fedora 19</platform>
input/checks/installed_OS_is_fedora19.xml:7:        <platform>Fedora 19</platform>
input/checks/file_ownership_binary_dirs.xml:6:        <platform>Fedora 19</platform>
input/checks/package_ntp_installed.xml:8:        <platform>Fedora 19</platform>
input/checks/service_sshd_disabled.xml:6:        <platform>Fedora 19</platform>
input/checks/package_openssh-server_removed.xml:8:        <platform>Fedora 19</platform>

$ grep -rin "<platform>Fedora 19" *|wc -l
11

$ grep -rin "<platform>Fedora 20" *
input/checks/file_user_owner_grub2_cfg.xml:7:        <platform>Fedora 20</platform>
input/checks/file_permissions_home_dirs.xml:8:        <platform>Fedora 20</platform>
input/checks/dconf_gnome_screensaver_idle_delay.xml:7:        <platform>Fedora 20</platform>
input/checks/ntpd_specify_remote_server.xml:8:        <platform>Fedora 20</platform>
input/checks/accounts_no_uid_except_zero.xml:8:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_minlen.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_lcredit.xml:7:        <platform>Fedora 20</platform>
input/checks/ensure_gpgcheck_never_disabled.xml:9:        <platform>Fedora 20</platform>
input/checks/no_insecure_locks_exports.xml:8:        <platform>Fedora 20</platform>
input/checks/dconf_gnome_banner_enabled.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_minclass.xml:8:        <platform>Fedora 20</platform>
input/checks/installed_OS_is_fedora20.xml:7:        <platform>Fedora 20</platform>
input/checks/no_netrc_files.xml:8:        <platform>Fedora 20</platform>
input/checks/dconf_gnome_login_banner_text.xml:7:        <platform>Fedora 20</platform>
input/checks/sysctl_kernel_ipv6_disable.xml:8:        <platform>Fedora 20</platform>
input/checks/ensure_gpgcheck_globally_activated.xml:8:        <platform>Fedora 20</platform>
input/checks/sshd_set_idle_timeout.xml:8:        <platform>Fedora 20</platform>
input/checks/dconf_gnome_disable_thumbnailers.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_retry.xml:8:        <platform>Fedora 20</platform>
input/checks/restrict_serial_port_logins.xml:8:        <platform>Fedora 20</platform>
input/checks/no_shelllogin_for_systemaccounts.xml:8:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_dcredit.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_ucredit.xml:7:        <platform>Fedora 20</platform>
input/checks/dconf_gnome_screensaver_mode_blank.xml:7:        <platform>Fedora 20</platform>
input/checks/package_dconf_installed.xml:9:        <platform>Fedora 20</platform>
input/checks/ntpd_specify_multiple_servers.xml:8:        <platform>Fedora 20</platform>
input/checks/accounts_root_path_dirs_no_write.xml:9:        <platform>Fedora 20</platform>
input/checks/accounts_minimum_age_login_defs.xml:8:        <platform>Fedora 20</platform>
input/checks/sshd_set_keepalive.xml:8:        <platform>Fedora 20</platform>
input/checks/sshd_disable_empty_passwords.xml:8:        <platform>Fedora 20</platform>
input/checks/no_empty_passwords.xml:8:        <platform>Fedora 20</platform>
input/checks/ftp_present_banner.xml:8:        <platform>Fedora 20</platform>
input/checks/bootloader_password.xml:7:        <platform>Fedora 20</platform>
input/checks/snmpd_use_newer_protocol.xml:8:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_maxrepeat.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_password_minlen_login_defs.xml:9:        <platform>Fedora 20</platform>
input/checks/ftp_log_transactions.xml:8:        <platform>Fedora 20</platform>
input/checks/dconf_gnome_screensaver_lock_enabled.xml:7:        <platform>Fedora 20</platform>
input/checks/file_permissions_grub2_cfg.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_maximum_age_login_defs.xml:8:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_ocredit.xml:7:        <platform>Fedora 20</platform>
input/checks/sshd_disable_root_login.xml:8:        <platform>Fedora 20</platform>
input/checks/dconf_gnome_disable_automount.xml:7:        <platform>Fedora 20</platform>
input/checks/require_singleuser_auth.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_password_pam_difok.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_passwords_pam_faillock_deny.xml:8:        <platform>Fedora 20</platform>
input/checks/securetty_root_login_console_only.xml:8:        <platform>Fedora 20</platform>
input/checks/package_net-snmp_removed.xml:10:        <platform>Fedora 20</platform>
input/checks/accounts_password_all_shadowed.xml:8:        <platform>Fedora 20</platform>
input/checks/install_antivirus.xml:9:        <platform>Fedora 20</platform>
input/checks/dconf_gnome_screensaver_idle_activation_enabled.xml:7:        <platform>Fedora 20</platform>
input/checks/file_group_owner_grub2_cfg.xml:7:        <platform>Fedora 20</platform>
input/checks/accounts_password_warn_age_login_defs.xml:8:        <platform>Fedora 20</platform>
input/checks/disable_prelink.xml:7:        <platform>Fedora 20</platform>
input/checks/enable_dconf_user_profile.xml:7:        <platform>Fedora 20</platform>
input/checks/sysctl_kernel_exec_shield.xml:8:        <platform>Fedora 20</platform>
input/checks/snmpd_not_default_password.xml:8:        <platform>Fedora 20</platform>

[shawnw@ssg-rhel6-devbox Fedora]$ grep -rin "<platform>Fedora 20" * | wc -l
57
````

**Comment by isimluk** [comment]
On 03/04/2015 08:18 PM, redhatrises wrote:
> @isimluk <https://github.com/isimluk> |installed_OS_is_fedora19.xml|
> should be removed and |shared/oval/accounts_password_pam_retry.xml|
> should be updated to |installed_OS_is_fedora20.xml|
>
> —

I believe that this is not true.


I think PAM has changed in fedora20 and that's the reason why this 
particular check has fedora19/rhel7/rhel6 sticker on it.

-- 
Simon Lukasik
Security Technologies, Red Hat, Inc.

**Comment by isimluk** [comment]
On 03/04/2015 09:01 PM, Shawn Wells wrote:
> Agree on the need to remove stale platforms. Before doing so, there are
> 11 Fedora 19 OVAL checks lurking, with another 57 using the Fedora 20
> platform tag. They should be updated before this gets merged.
>
> Ref:
>
> |$ grep -rin "<platform>Fedora 19" *
> input/checks/file_permissions_binary_dirs.xml:6:        <platform>Fedora 19</platform>
> input/checks/templates/template_package_removed:8:        <platform>Fedora 19</platform>
> input/checks/templates/template_package_installed:8:        <platform>Fedora 19</platform>
> input/checks/file_permissions_library_dirs.xml:6:        <platform>Fedora 19</platform>
> input/checks/file_ownership_library_dirs.xml:6:        <platform>Fedora 19</platform>
> input/checks/service_ntpd_enabled.xml:6:        <platform>Fedora 19</platform>
> input/checks/installed_OS_is_fedora19.xml:7:        <platform>Fedora 19</platform>
> input/checks/file_ownership_binary_dirs.xml:6:        <platform>Fedora 19</platform>
> input/checks/package_ntp_installed.xml:8:        <platform>Fedora 19</platform>
> input/checks/service_sshd_disabled.xml:6:        <platform>Fedora 19</platform>
> input/checks/package_openssh-server_removed.xml:8:        <platform>Fedora 19</platform>
>
> $ grep -rin "<platform>Fedora 19" *|wc -l
> 11
>
> $ grep -rin "<platform>Fedora 20" *
> input/checks/file_user_owner_grub2_cfg.xml:7:        <platform>Fedora 20</platform>
> input/checks/file_permissions_home_dirs.xml:8:        <platform>Fedora 20</platform>
> input/checks/dconf_gnome_screensaver_idle_delay.xml:7:        <platform>Fedora 20</platform>
> input/checks/ntpd_specify_remote_server.xml:8:        <platform>Fedora 20</platform>
> input/checks/accounts_no_uid_except_zero.xml:8:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_minlen.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_lcredit.xml:7:        <platform>Fedora 20</platform>
> input/checks/ensure_gpgcheck_never_disabled.xml:9:        <platform>Fedora 20</platform>
> input/checks/no_insecure_locks_exports.xml:8:        <platform>Fedora 20</platform>
> input/checks/dconf_gnome_banner_enabled.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_minclass.xml:8:        <platform>Fedora 20</platform>
> input/checks/installed_OS_is_fedora20.xml:7:        <platform>Fedora 20</platform>
> input/checks/no_netrc_files.xml:8:        <platform>Fedora 20</platform>
> input/checks/dconf_gnome_login_banner_text.xml:7:        <platform>Fedora 20</platform>
> input/checks/sysctl_kernel_ipv6_disable.xml:8:        <platform>Fedora 20</platform>
> input/checks/ensure_gpgcheck_globally_activated.xml:8:        <platform>Fedora 20</platform>
> input/checks/sshd_set_idle_timeout.xml:8:        <platform>Fedora 20</platform>
> input/checks/dconf_gnome_disable_thumbnailers.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_retry.xml:8:        <platform>Fedora 20</platform>
> input/checks/restrict_serial_port_logins.xml:8:        <platform>Fedora 20</platform>
> input/checks/no_shelllogin_for_systemaccounts.xml:8:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_dcredit.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_ucredit.xml:7:        <platform>Fedora 20</platform>
> input/checks/dconf_gnome_screensaver_mode_blank.xml:7:        <platform>Fedora 20</platform>
> input/checks/package_dconf_installed.xml:9:        <platform>Fedora 20</platform>
> input/checks/ntpd_specify_multiple_servers.xml:8:        <platform>Fedora 20</platform>
> input/checks/accounts_root_path_dirs_no_write.xml:9:        <platform>Fedora 20</platform>
> input/checks/accounts_minimum_age_login_defs.xml:8:        <platform>Fedora 20</platform>
> input/checks/sshd_set_keepalive.xml:8:        <platform>Fedora 20</platform>
> input/checks/sshd_disable_empty_passwords.xml:8:        <platform>Fedora 20</platform>
> input/checks/no_empty_passwords.xml:8:        <platform>Fedora 20</platform>
> input/checks/ftp_present_banner.xml:8:        <platform>Fedora 20</platform>
> input/checks/bootloader_password.xml:7:        <platform>Fedora 20</platform>
> input/checks/snmpd_use_newer_protocol.xml:8:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_maxrepeat.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_password_minlen_login_defs.xml:9:        <platform>Fedora 20</platform>
> input/checks/ftp_log_transactions.xml:8:        <platform>Fedora 20</platform>
> input/checks/dconf_gnome_screensaver_lock_enabled.xml:7:        <platform>Fedora 20</platform>
> input/checks/file_permissions_grub2_cfg.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_maximum_age_login_defs.xml:8:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_ocredit.xml:7:        <platform>Fedora 20</platform>
> input/checks/sshd_disable_root_login.xml:8:        <platform>Fedora 20</platform>
> input/checks/dconf_gnome_disable_automount.xml:7:        <platform>Fedora 20</platform>
> input/checks/require_singleuser_auth.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_password_pam_difok.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_passwords_pam_faillock_deny.xml:8:        <platform>Fedora 20</platform>
> input/checks/securetty_root_login_console_only.xml:8:        <platform>Fedora 20</platform>
> input/checks/package_net-snmp_removed.xml:10:        <platform>Fedora 20</platform>
> input/checks/accounts_password_all_shadowed.xml:8:        <platform>Fedora 20</platform>
> input/checks/install_antivirus.xml:9:        <platform>Fedora 20</platform>
> input/checks/dconf_gnome_screensaver_idle_activation_enabled.xml:7:        <platform>Fedora 20</platform>
> input/checks/file_group_owner_grub2_cfg.xml:7:        <platform>Fedora 20</platform>
> input/checks/accounts_password_warn_age_login_defs.xml:8:        <platform>Fedora 20</platform>
> input/checks/disable_prelink.xml:7:        <platform>Fedora 20</platform>
> input/checks/enable_dconf_user_profile.xml:7:        <platform>Fedora 20</platform>
> input/checks/sysctl_kernel_exec_shield.xml:8:        <platform>Fedora 20</platform>
> input/checks/snmpd_not_default_password.xml:8:        <platform>Fedora 20</platform>
>
> [shawnw@ssg-rhel6-devbox Fedora]$ grep -rin "<platform>Fedora 20" * | wc -l
> 57
> |
>

Shawn,

While I do agree that this should be done, I don't think it blocks this 
PR. It is unrelated. The <platform> element in *OVAL* file has merely 
documentation purpose.

I will create new pr removing these platform elements (as they are not 
kept complete and not really beneficial to anyone).

However, it will require further work. As the `make templates` is broken 
for Fedora.

Thanks!

-- 
Simon Lukasik
Security Technologies, Red Hat, Inc.

**Pull request merged**
