### PR TITLE
Replace references of RHEV-M with RHEL OSP in OpenStack guide

### PR DESCRIPTION
**Pull request by jeffcpullen**
OpenStack content references RHEV-M in multiple files. It also suggests the removal of subscription-manager which is required in some deployments.

### CODE REVIEW

**Comment by iankko** [comment]
[add to whitelist]

**Comment by redhatrises** [comment]
@jeffcpullen can you also update the RHEV references in `OpenStack/input/auxiliary/srg_support.xml` and `OpenStack/input/intro/intro.xml` to OpenStack/OSP?

**Comment by jeffcpullen** [comment]
@redhatrises I thought I had captured all the instances of RHEV in those files. Or are you suggesting that I use OpenStack/OSP rather than the official product name Red Hat Enterprise Linux OpenStack Platform (RHEL OSP)?

**Comment by redhatrises** [comment]
@jeffcpullen sorry. You are right. I looked at this wrong. Ack.

**Pull request merged**
