### PR TITLE
[Enhancement][RHEL/7] Move GNOME XCCDF content into its own gnome.xml XCCDF file

### PR DESCRIPTION
**Pull request by redhatrises**
As more and more GNOME and GDM checks are added to the STIG and SSG, it doesn't make sense to have GNOME/GDM checks in a bunch of disparate files. This centralizes much of the GNOME content into a single file except for cases where GNOME and other rules will implement the same shared variable.

- Move majority of GNOME XCCDF content (excluding banners) into gnome.xml.
- Preps for additional GNOME/GDM STIG settings
- Part of #481

### CODE REVIEW

**Comment by iankko** [comment]
@redhatrises 
Could you fix the failing Jenkins? Looks there are duplicate OVAL rules entries defined somewhere.

Should you need help identifying the source of the failures, let me know.

**Comment by redhatrises** [comment]
Thanks @iankko. I believe that it has been fixed. (See if Jenkins proves me right. :) )

**Comment by iankko** [comment]
Thanks! Will have a look at this.

**Comment by shawndwells** [comment]
Thanks for doing this @redhatrises ! Makes finding the Desktop settings much easier.

**Comment by shawndwells** [comment]
Since @iankko assigned to himself, will hold until he merges -- but looks good to me.

**Comment by iankko** [comment]
Just maybe one nitpick - do we plan to perform same Gnome rules merge under separate Gnome umbrella also for RHEL/6 and Fedora content? (of course to be part of separate PR)

To this specific PR:
AFAIK from the testing all the moved rules are still present, the RHEL-7 content builds, and PCI DSS profile (using some of the moved rules) still works properly. Makes sense && LGTM. ACK.

**Comment by redhatrises** [comment]
> Just maybe one nitpick - do we plan to perform same Gnome rules merge under separate Gnome umbrella also for RHEL/6 and Fedora content? (of course to be part of separate PR)

@iankko yes, but probably after official RHEL7 STIG release.

**Comment by iankko** [comment]
@redhatrises 
OK, fair enough. Tracked now under: https://github.com/OpenSCAP/scap-security-guide/issues/1205 so we won't forget about it.

**Pull request merged**
