### PR TITLE
Added Java SCAP content.

### PR DESCRIPTION
**Pull request by thenefield**
Added SCAP content aligned with the DISA STIG for JRE7 for UNIX.

### CODE REVIEW

**Comment by shawndwells** [comment]
The same comments from Webmin apply here (macros, SSG artifacts, etc). After fixing, please squash your commits so it's easier to identify what is/isn't present.

**Comment by redhatrises** [comment]
@shawndwells should `Java/input/checks/jre_is_up_to_date.xml` actually be checking that the java versions are up-to-date. Seems like we could be updating it a lot. Or is that statisfied with the 'operating system configured for updates'? Or what about here: http://www.redhat.com/security/data/oval/?

**Comment by shawndwells** [comment]
On 2/25/15 2:26 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> should 
> |Java/input/checks/jre_is_up_to_date.xml| actually be checking that 
> the java versions are up-to-date. Seems like we could be updating it a 
> lot. Or is that statisfied with the 'operating system configured for 
> updates'? Or what about here: http://www.redhat.com/security/data/oval/?

Yeah, you're totally right. Way to much effort to keep this OVAL check 
updated.

When running on RHEL, things are simplified by the OVAL patch stream you 
referenced. IMHO, dropping the OVAL content and updating the XCCDF to 
highlight this control would be inherited from the operating system 
makes sense.

**Comment by thenefield** [comment]
I agree that this check is a pain to maintain. I simply added it to provide
completeness to the STIG. But yeah, it would be updated at least every
quarter. I am not exactly sure how to implement what you have suggested
(making it inherited by the OS).

**Comment by shawndwells** [comment]
On 2/25/15 3:02 PM, thenefield wrote:
> I agree that this check is a pain to maintain. I simply added it to 
> provide
> completeness to the STIG. But yeah, it would be updated at least every
> quarter. I am not exactly sure how to implement what you have suggested
> (making it inherited by the OS).
we'll figure it out after the initial merge.

**Comment by shawndwells** [comment]
make content compiles, generates valid content:

````
$ oscap xccdf validate output/ssg-java-xccdf.xml 

$ oscap info output/ssg-java-xccdf.xml 
Document type: XCCDF Checklist
Checklist version: 1.1
Status: draft
Generated: 2015-02-27
Imported: 2015-02-27T13:44:26
Resolved: true
Profiles:
	java-stig
Referenced check files:
	ssg-java-oval.xml
		system: http://oval.mitre.org/XMLSchema/oval-definitions-5

````

However, if you attempt to run a scan on RHEL:
````
$ oscap xccdf eval --profile java-stig output/ssg-java-xccdf.xml 
Title   A configuration file must be present to deploy properties for JRE.
Rule    deployment_config_exists
Ident   CCE-
Ident   JRE0070-UX
Result  notapplicable

Title   The configuration file must contain proper keys and values to deploy settings correctly.
Rule    deployment_config_configured
Ident   CCE-
Ident   JRE0060-UX
Result  notapplicable

Title   A properties file must be present to hold all the keys that 
establish properties within the Java control panel.
Rule    deployment_properties_exists
Ident   CCE-
Ident   JRE0080-UX
Result  notapplicable

Title   The dialog to enable users to grant permissions to execute signed 
content from an un-trusted authority must be disabled.
Rule    untrusted_sources
Ident   CCE-
Ident   JRE0001-UX
Result  notapplicable

Title   The dialog enabling users to grant permissions to execute signed 
content from an un-trusted authority must be locked.
Rule    untrusted_sources_locked
Ident   CCE-
Ident   JRE0010-UX
Result  notapplicable

Title   The setting for users to check publisher certificates for revocation 
must be enabled.
Rule    validation_crl
Ident   CCE-
Ident   JRE0020-UX
Result  notapplicable

Title   The setting enabling users to configure the check publisher certificates 
for revocation must be locked.
Rule    validation_crl_locked
Ident   CCE-
Ident   JRE0030-UX
Result  notapplicable

Title   The option to enable online certificate validation must be enabled.
Rule    validation_ocsp
Ident   CCE-
Ident   JRE0040-UX
Result  notapplicable

Title   The option to enable online certificate validation must be locked.
Rule    validation_ocsp_locked
Ident   CCE-
Ident   JRE0050-UX
Result  notapplicable

Title   The version of the JRE running on the system must be the most current available.
Rule    jre_is_up_to_date
Ident   CCE-
Ident   JRE0090-UX
Result  notapplicable
````

**Comment by shawndwells** [comment]
dropped the CPE tags from input/guide.xml, now compiles and scans.... commented them out for now.

**Comment by shawndwells** [comment]
````
$ oscap xccdf eval --profile java-stig output/ssg-java-xccdf.xml 
Title   A configuration file must be present to deploy properties for JRE.
Rule    deployment_config_exists
Ident   CCE-
Ident   JRE0070-UX
Result  fail

Title   The configuration file must contain proper keys and values to deploy settings correctly.
Rule    deployment_config_configured
Ident   CCE-
Ident   JRE0060-UX
Result  fail

Title   A properties file must be present to hold all the keys that 
establish properties within the Java control panel.
Rule    deployment_properties_exists
Ident   CCE-
Ident   JRE0080-UX
Result  fail

Title   The dialog to enable users to grant permissions to execute signed 
content from an un-trusted authority must be disabled.
Rule    untrusted_sources
Ident   CCE-
Ident   JRE0001-UX
Result  fail

Title   The dialog enabling users to grant permissions to execute signed 
content from an un-trusted authority must be locked.
Rule    untrusted_sources_locked
Ident   CCE-
Ident   JRE0010-UX
Result  fail

Title   The setting for users to check publisher certificates for revocation 
must be enabled.
Rule    validation_crl
Ident   CCE-
Ident   JRE0020-UX
Result  fail

Title   The setting enabling users to configure the check publisher certificates 
for revocation must be locked.
Rule    validation_crl_locked
Ident   CCE-
Ident   JRE0030-UX
Result  fail

Title   The option to enable online certificate validation must be enabled.
Rule    validation_ocsp
Ident   CCE-
Ident   JRE0040-UX
Result  fail

Title   The option to enable online certificate validation must be locked.
Rule    validation_ocsp_locked
Ident   CCE-
Ident   JRE0050-UX
Result  fail

Title   The version of the JRE running on the system must be the most current available.
Rule    jre_is_up_to_date
Ident   CCE-
Ident   JRE0090-UX
Result  pass

````

**Comment by shawndwells** [comment]
manually merged to remove conflicts. removed from RPM build process until content stabilizes / further vetted. added a few cleanup patches:

1dad297c55406ad821dc24749084c696905c1412 - removing CPE tags
1dad297  - removing stats.sh call
3b3403e  - adding testcheck util to Java content
1298466  - updated transforms/oscapsupportssvg

**Pull request merged**
