### PR TITLE
Fix minor typoe (sic)

### PR DESCRIPTION
**Pull request by radzy**
Signed-off-by: T.O. Radzy Radzykewycz <radzy@windriver.com>

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-jenkins test this please

**Comment by jan-cerny** [comment]
ACK, just wainting for CI.

**Comment by redhatrises** [comment]
retest this please

**Comment by redhatrises** [comment]
Going to merge this as this PR is not causing a CI failure on RHEL6. It looks like `build-remediations.py` is what is failing with:

```
../../shared/utils/build-remediations.py --output ./templates clean
Traceback (most recent call last):
  File "../../shared/utils/build-remediations.py", line 282, in <module>
    func()
  File "../../shared/utils/build-remediations.py", line 68, in clean
    sys.stderr.write("Remove: {}\n".format(dir))
ValueError: zero length field name in format
make[1]: *** [clean] Error 1
make[1]: Leaving directory `/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-el6-openscap-new/RHEL/5'
make: *** [clean] Error 2
```

**Pull request merged**
