### PR TITLE
Update RHEL7 Audit Rules XCCDF for current STIG draft

### LINKED ISSUE #389: NIST 800-53 AU-5 -  Halt on audit daemon failure
update audit.rules to reflect `-f 2`

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #389
- Fixes #1050

### CODE REVIEW

**Comment by shawndwells** [comment]
Like modernization towards ``-F key=foo``, but realize OVAL also needs updating to support both methods. I'm OK merging the XCCDF component now, and creating a blocker ticket for next release to get OVAL updated to match. That sound good?

**Comment by redhatrises** [comment]
> The modernization towards -F key=foo is really really needed, but realize OVAL also needs updating to support both methods of -k foo and -F key=foo. I'm OK merging the XCCDF component now, and creating a blocker ticket for next release to get OVAL updated to match. That sound good?

Sounds good to me.

**Comment by redhatrises** [comment]
@shawndwells typo fixed.

**Comment by redhatrises** [comment]
Fixed merge issues and merged per @shawndwells.

**Pull request merged**
