### PR TITLE
Don't limit Fedora template generation

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by redhatrises** [comment]
This fixes a CMake build issue.

**Comment by jan-cerny** [comment]
@redhatrises In current master, we don't generate an OVAL definition for `package_libreswan_installed`. Is it a bug? Have you added libreswan into the csv list as a bugfix? Then why isn't `package_libreswan_installed` included in any profile?

**Comment by redhatrises** [comment]
> Is it a bug? Have you added libreswan into the csv list as a bugfix? Then why isn't package_libreswan_installed included in any profile?

@jan-cerny yes it is a bug hence this PR. OVAL doesn't have to be enabled in the profile as it is enabled in the XCCDF.

`WARNING: OVAL check 'package_libreswan_installed' was not found, removing <check-content> element from the XCCDF rule.`

**Comment by jan-cerny** [comment]
@redhatrises Thanks for explanation and thanks for fixing that. 👍 
The commit looks good to me.

**Pull request merged**
