### PR TITLE
bash remediations cleanup & fix

### PR DESCRIPTION
**Pull request by ybznek**

### CODE REVIEW

**Comment by ybznek** [comment]
I had to stop jenkins job. test this please, again

**Comment by redhatrises** [comment]
@ybznek what is the remediation fix?

**Comment by ybznek** [comment]
@redhatrises https://github.com/OpenSCAP/scap-security-guide/pull/1732/commits/15ba7046fb72d9fa82c622466da8eb15817daa60

**Comment by redhatrises** [comment]
@ybznek for historical and searching purposes, can you provide more information on what you are fixing?

**Comment by ybznek** [comment]
@redhatrises I hoped that commit message is enough. Should I update it?

It reads every single key from file and check fingerprint of it. If fingerprint is valid, it will import the file.
But if file contains multiple keys and at least one key has valid fingerprint, remediation will import whole file - and can import some attacker key too.

So, now the key file is imported only if it contains no keys without valid fingerprint.

**Comment by redhatrises** [comment]
> @redhatrises I hoped that commit message is enough. Should I update it?

No @ybznek. I missed the commit message.... wasn't really awake when I read it. Sorry for the noise.

Ack.

**Pull request merged**
