### PR TITLE
Introduce an xccdf folder per product

### LINKED ISSUE #772: [Enhancement] Introduce 'xccdf' folder
The actual structure of many products in SSG is as follows:
```
$ tree -d RHEL/6
RHEL/6
├── input
│   ├── auxiliary
│   ├── checks
│   │   ├── platform
│   │   └── templates
│   ├── fixes
│   │   └── bash
│   │       └── templates
│   ├── intro
│   ├── profiles
│   ├── services
│   └── system
│       ├── accounts
│       │   └── restrictions
│       ├── network
│       ├── permissions
│       └── software
├── kickstart
├── output
│   └── images
├── tests
│   └── kickstart
├── transforms
└── utils

24 directories
```

Experienced SSG users are familiar that ```services``` and ```systems``` folders are those relevant to XCCDF prose. But this knowledge is hard to be discovered by initial users, and current state is creating additional starting barrier for potential future contributors.

To fix / improve this state, I propose new ```xccdf``` folder (as a parent of existing ```system````, and ```services``` one to be introduced). From that point on, it would be visible at first sight, where the XCCDF prose code for that particular product lives.

The proper fix for this issue expects the ```xccdf```` folder to be introduced into the Git directory structure (as a parent of ```system``` and ```services``` folders. [1])

The introduction of the ```xccdf``` folder for each product of:
* ```Chromium```,
* ```Fedora```, 
* ```Firefox```,
* ```JRE```,
* ```OpenStack```,
* ```RHEL/5```,
* ```RHEL/6```,
* ```RHEL/7```,
* ```RHEVM3```, and
* ```Webmin```

might not by itself be sufficient change. From what I can quickly tell at least ```input/guide.xslt``` for each of the products from the above list will need to be modified too, to cope with the new ```xccdf``` directory introduction. There might be also other (unknown at this point of time) changes required, the XCCDF prose for each of the aforementioned products to be properly merged into the final XCCDF and DataStream documents like it's performed one (for example both the main ```Makefile``` and per-product ```Makefiles``` would need to be inspected if anything is to be changed there once the ```xccdf``` directory is introduced etc.).

--
[1] Actually after some time / in the future we might want to merge also ```intro``` and ```profiles``` folders under ```xccdf``` folder. But for the start, let's keep things simple, and merge under ```xccdf``` just ```system``` and ```services```.

### PR DESCRIPTION
**Pull request by msrubar**
Move system and services folders of all products to a new xccdf directory.
It will help initial users to recognize where the xccdf prose code is.

The commit fixes #772.

### CODE REVIEW

**Comment by mpreisler** [comment]
I find it strange that you excluded `intro/intro.xml` from the change. That file is also pure XCCDF.

**Comment by mpreisler** [comment]
I think we should postpone this and merge it after 0.1.26. @iankko , do you agree? Assigning 0.1.27 milestone.

It's a relatively harmless change but it affects every product and I would prefer to have it in the repo for some time before we release with it.

**Comment by iankko** [comment]
@mpreisler 
> 
I think we should postpone this and merge it after 0.1.26. @iankko , do you agree? Assigning 0.1.27 milestone.
> 
It's a relatively harmless change but it affects every product and I would prefer to have it in the repo for some time before we release with it.

Definitely agree with that. Would rather give the things time to settle down (ensure everything is working fine with new the layering) after merging this one. So yes, 0.1.27 is fine by me.

Thanks

**Comment by iankko** [comment]
@mpreisler 
And for the
> I find it strange that you excluded intro/intro.xml from the change. That file is also pure XCCDF.

part - it's covered in the ticket (for the start to port just ```system/``` and ```services``` directories). Of course should we find time to do the complete change, we should include ```intro/intro.xml``` and ```profiles/``` folders too).

Just an explanation why the current version looks as it looks like - to omit ```intro.xml``` was requested by me for the start to be simpler.

**Comment by msrubar** [comment]
@mpreisler ianko noted in the description of the issue #772 that `intro` and `profiles` should also be moved to xccdf folders but not in this PR.

**Comment by msrubar** [comment]
Do not merge yet. I think I forgot sth and I have to take a look at one more time.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
