### PR TITLE
Move templates & split generations

### PR DESCRIPTION
**Pull request by ybznek**
DO NOT MERGE (I haven't compared results output & I want jenkins test)

- shared/remediations/bash/*py -> shared/templates
- divide generations of oval+bash to separate files
- move Debian8 files

### CODE REVIEW

**Comment by ybznek** [comment]
(Debian8 DS miss some fixes.)

**Comment by ybznek** [comment]
Needs to be rebased after merge of https://github.com/OpenSCAP/scap-security-guide/pull/1389 (this PR is based on it)

**Comment by iankko** [comment]
@ybznek 
> Needs to be rebased after merge of #1389 (this PR is based on it)

Please rebase it if not done yet. Will look @ this shortly.

**Comment by ybznek** [comment]
I think it is ready to review

**Comment by iankko** [comment]
Looks good to me. ACK (so far can't see any issues from testing of this one).

**Pull request merged**
