### PR TITLE
Rhel6 use generated bash

### PR DESCRIPTION
**Pull request by ybznek**
It needs rebase after merge of https://github.com/OpenSCAP/scap-security-guide/pull/1398

Maybe I don't generate all possible files, but we can improve it later.

### CODE REVIEW

**Comment by ybznek** [comment]
I will provide some script to check changes in remediations.

**Comment by ybznek** [comment]
Script to compare
```
#!/bin/bash

git clone --depth 1 https://github.com/OpenSCAP/scap-security-guide.git original && {
    pushd original 
    make -j4
    popd
}

git clone --depth 1 https://github.com/ybznek/scap-security-guide.git -b master-combine-ovals update && {
    pushd update 
    make -j4
    popd
}


function generateFinalRemediation() {

    local base="$1"
    local product="$2"
    local outputFile="$3"
    # create temporary director
    OUT=$(mktemp -d)
    rm -rf "${OUT}"
    mkdir ${OUT}
    pushd "$base" && {
	local makefilePath="${product}/templates"
	[ -f "${makefilePath}/Makefile" ] && {
	    make -C "${makefilePath}"
	}
	mkdir -p ${product}/templates/output/bash
	find ./shared/templates/static/bash ${product}/templates/output/bash ${product}/templates/static/bash -name "*.sh" -exec cp '{}' "${OUT}" ';'

	find "$OUT" -name "*.sh" -exec basename "{}" ';' | sort | while read filename;
	do
	    echo "==========================[ $filename ]=============================" >> "$outputFile"
	    
	    cat "${OUT}/$filename" >> "$outputFile"
	done
	popd
    }
    rm -rf "${OUT}"
}

function compareFinalRemediations() {
    product="$1"
    old=$(mktemp /tmp/old.XXXXXXX.txt)
    new=$(mktemp /tmp/new.XXXXXXX.txt)
    generateFinalRemediation "./original/"	"${product}"	"${old}"
    generateFinalRemediation "./update/"	"${product}"	"${new}"
    echo "${old}" "<->" "${new}"
    meld "${old}" "${new}"
}

compareFinalRemediations "RHEL/6"


```
You can compare generated files here - there are changes due to used templates:
[old remediations](https://github.com/OpenSCAP/scap-security-guide/files/418370/old.Tbq7uCv.txt)
[new remediations](https://github.com/OpenSCAP/scap-security-guide/files/418371/new.JobffmT.txt)

**Comment by shawndwells** [comment]
Should we add a .gitignore for templates/output/*.sh and ../../shared/templates/output/*.sh?

Looks good otherwise. Scripts are properly included into XCCDF during `````make content`````, e.g:
`````
          <fix system="urn:xccdf:fix:script:sh" id="kernel_module_hfsplus_disabled">echo "install hfsplus /bin/true" &gt; /etc/modprobe.d/hfsplus.conf
</fix>
`````

**Comment by shawndwells** [comment]
Actually, that's a silly reason not to merge. Created https://github.com/OpenSCAP/scap-security-guide/issues/1418 to track the .gitignore updates

**Pull request merged**
