### PR TITLE
Cleanup rhel7 package removed 5.11

### PR DESCRIPTION
**Pull request by ybznek**
- I've found some mess (https://github.com/OpenSCAP/scap-security-guide/issues/1665). We generate remediations for package_removed in oval_5.10, but we don't have any OVAL check for it.
So I have written csv/packages_removed to don't cause changes - but we should remove it or write oval5.10 check it.

- `version` attribute of some generated definitions are changed
- some new remediations for existing oval checks introduced (were missing previously)

compare_generated.sh can be used for review...

### CODE REVIEW

**Comment by mpreisler** [comment]
Why is package removed in OVAL 5.11? 5.10 should be enough to implement it and then it works for 5.10 or 5.11.

**Comment by ybznek** [comment]
@mpreisler It was already there.

I don't think that it is a good idea to do refactoring & fix bugs at once. Currently I can compare old DS with a new one and see what was changed. If I would fix such bugs, it will produce huge "diff" and it will be impossible see whether I broke something ~ If I move rwmpl from oval5.11 to oval5.10, it will change oval_5.10 output.

So I think that better idea is reduce amount of files and then we will be able to fix it more easily.

**Comment by ybznek** [comment]
More info: https://github.com/OpenSCAP/scap-security-guide/issues/1668

**Comment by mpreisler** [comment]
OK, makes sense. ACK.

**Pull request merged**
