### PR TITLE
Add release badge to README

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by mpreisler** [comment]
We are slowly becoming the coolest project on github.

**Comment by shawndwells** [comment]
Improves the code, but still unclear what is actually passing:

image

Could this be something like:
Build: <<image>>
Nightly Zip: << image >>

**Comment by shawndwells** [comment]
gahhhh @mpreisler beat me by like 45sec

**Comment by redhatrises** [comment]
@mpreisler @shawndwells I used https://shields.io/ to help with this. You can generate a custom one that might solve the issue with the builds.

**Pull request merged**
