### PR TITLE
Unshadow shared check service_dovecot_disabled

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Drop service_dovecot_disabled check from shared 
- ~~Drop Ansible fix service_avahi-daemon_disabled form shared~~ commit dropped
- ~~Drop templated fixes for account_password_pam_~~ commit dropped
  - ~~maxclassrepeat~~
  - ~~maxrepeat~~
  - ~~minlen~~
- ~~Improve regex in template for accounts_password_pam to match commented and or indented line~~ commit dropped

#### Rationale:

- This will unshadow for other products as well.

### Note 
- Ansible fix for `service_avahi-daemon_disabled` from shared also included task to disable the socket associated with the service, but the templated fix doesn't disable sockets. I have filed #2983 to investigate usage and templating for disabling sockets.

### CODE REVIEW

**Comment by mpreisler** [comment]
> Ansible fix for service_avahi-daemon_disabled from shared also included task to disable the socket associated with the service, but the templated fix doesn't disable sockets. I have filed #2983 to investigate usage and templating for disabling sockets.

AFAIK that's why it's shadowed right now, it also disables a socket. We can't unshadow it as you suggest in this PR.

**Comment by yuumasato** [comment]
Right, we cannot generate the Ansible fix for `service_avahi-daemon_disabled` exactly as in shared right now, it makes sense to keep it.
Its unshadowing can be done in different PR, I have dropped the commit.

**Comment by mpreisler** [comment]
You dropped the shared ansible fixes which means they will be missing for RHEL6 if this gets merged. Was that intentional?

**Comment by yuumasato** [comment]
I was careless when dropping them, I will look into templating them for RHEL6. But I think in another PR. I will drop these commits soon.

**Comment by yuumasato** [comment]
I have dropped the commits.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
