### PR TITLE
Move OVAL_5.11 static files

### PR DESCRIPTION
**Pull request by ybznek**
Move files to consistent location & fix missing OVALs in DS after cmake transition.

### CODE REVIEW

**Comment by mpreisler** [comment]
This goes against conventions in all the other paths.

**Comment by jan-cerny** [comment]
@ybznek Which bug does this patch fix?

**Comment by ybznek** [comment]
@jan-cerny we have some differences with cmake than before. it should fix it
@mpreisler ok... I will look into it. Maybe I will move some files.
I will use this PR, please let it open...

**Comment by mpreisler** [comment]
Added a BLOCKER label. We need to fix this before release. Either change paths or move files around.

**Comment by ybznek** [comment]
@mpreisler where is RHEL-OSP7? It seems it should work, but I cannot find output datastream after build.

**Comment by mpreisler** [comment]
@ybznek Yes, should be marked as broken.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
