### PR TITLE
Chromium: Remove puppet example

### PR DESCRIPTION
**Pull request by ybznek**
https://github.com/OpenSCAP/scap-security-guide/issues/1668

### CODE REVIEW

**Comment by redhatrises** [comment]
Actually not a fan of moving static OVAL files to the templates directories as they are not templates and can cause more confusion to potential SSG contributors who may not very technical.

**Comment by ybznek** [comment]
@redhatrises Please share our opinions https://github.com/OpenSCAP/scap-security-guide/issues/1668. We have it for remediations, currently.
I want to have unified way for building of everything and then we can select better structure.

**Comment by ybznek** [comment]
@redhatrises It make me easier cleaning, because I can see which files were considered to be not generated, etc

**Comment by redhatrises** [comment]
Ack for removing.

**Pull request merged**
