### PR TITLE
Remove RHEL6 tests directory

### PR DESCRIPTION
**Pull request by redhatrises**
#### Description:

- Remove RHEL6 tests directory

#### Rationale:

- Directory and its contents don't appear to be used anymore. `shared/tests` is preferred.

### CODE REVIEW

**Comment by mpreisler** [comment]
Assigned to @dahaic 

Could you please look into whether we can salvage any of this for the SSG test suite?

**Comment by dahaic** [comment]
Yeah @mpreisler you are right - even though we can dig it later from the history, it's probably more sensible to use it right away within SSGTT:).

So I'll merge it after creating PR with testsuited screnarios ;)

**Comment by jan-cerny** [comment]
@dahaic Is this going to be postponed after 0.1.36 release?

**Comment by dahaic** [comment]
Thank you for this catch! Merging (test suite scenarios won't be made in an instant, no need for this to wait)

@redhatrises just a note - `./tests` i.e. SSG Test Suite is preferred :)

**Pull request merged**
