### PR TITLE
Continue converting XSLT macros to jinja (part 2)

### PR DESCRIPTION
**Pull request by matusmarhefka**
See the #2835 PR for rationale and description.

### CODE REVIEW

**Comment by matejak** [comment]
Let's rename `sysctl_check_complete_ocil_entry` to `complete_ocil_entry_sysctl_option_value` to be in line with naming changes from previous PRs.
Aside from that, those two macros seem the last non-trivial user-facing ones!

**Comment by matusmarhefka** [comment]
@matejak I named it to be consistent with naming in your PR: https://github.com/OpenSCAP/scap-security-guide/pull/2835/commits/f4363d6751d714a68d7a28c93056c09384d2fb6e#diff-e6a1d3c766635d24f9c0ce23fe33b4adR85

But if you insist on renaming I will do so.

**Comment by matejak** [comment]
Naming scheme has evolved, see https://github.com/OpenSCAP/scap-security-guide/pull/2861 for reference.

**Comment by matusmarhefka** [comment]
Naming scheme fixed in the commit 030b85e.

**Comment by mpreisler** [comment]
@matusmarhefka this needs a rebase

**Comment by matusmarhefka** [comment]
I rebased upon the latest master, this PR can be reviewed and merged.

**Comment by mpreisler** [comment]
@matusmarhefka sorry but this needs another rebase

**Comment by matusmarhefka** [comment]
@mpreisler Another rebase done  :sweat: :smile:

**Comment by mpreisler** [comment]
ACK, great stuff!

**Pull request merged**
