### PR TITLE
Docker profile added

### PR DESCRIPTION
**Pull request by thetuxracer**
A docker profile is added. As a starting point, I am checking if docker package and services are installed and enabled.

### CODE REVIEW

**Comment by redhatrises** [comment]
@iankko Jenkins may be failing here:

`make[1]: Leaving directory '/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-fedora24/Fedora'
cd JRE && make clean
cp: cannot create regular file 'build/fedora_oval': No such file or directory
cp: cannot create regular file 'build/fedora_oval': No such file or directory
make[1]: Entering directory '/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-fedora24/JRE'`

**Comment by redhatrises** [comment]
[retest this please]

**Comment by redhatrises** [comment]
@thetuxracer the `package_docker_installed` OVAL is missing from this PR.

**Comment by thetuxracer** [comment]
@redhatrises ack, checking it. Thanks for the pointer.

**Comment by redhatrises** [comment]
@thetuxracer need to associate the profile and OVAL content with some XCCDF content. Maybe add a new docker service XCCDF under `RHEL/7/input/xccdf/services/docker.xml`?

**Comment by iankko** [comment]
@thetuxracer 
Thank you for the update.

Gabe is right, what the current form of PR is missing now being yet the XCCDF prose for ```service_docker_enabled``` rule. But to split the recommendation into more detailed steps, pls see below.

For some example have a look e.g at this commit:

  https://github.com/iankko/scap-security-guide/commit/405d319897077fe65e2ebe7913b9a5b9cea0b781

the most relevant part is the change for ``` RHEL/6/input/xccdf/services/sssd.xml ``` location.

This PR is missing change in ```RHEL/7/input/xccdf/services/docker.xml``` -- basically the content of the XCCDF rule would be similar, but you would replace ```<title>```, ```<description>``` etc elements with proper form for the ```docker``` service (instead of using ```sssd``` you would use ```docker``` service there and properly describe the title, rationale etc elements).

Once this is done, you need to link the ```service_docker_enabled``` XCCDF rule with the corresponding OVAL check yet. This would be achieved by adding ```<oval id="service_docker_enabled"``` element to that XCCDF rule. To see exact example, have a look e.g. at:

  https://github.com/iankko/scap-security-guide/commit/29b2cb925cb1ca738ab276ad33c2c159e4cd154d

change (mainly the ```RHEL/6/input/xccdf/services/sssd.xml``` part of it).

In that moment, the newly added ```service_docker_enabled``` OVAL check won't be not-referenced anymore, and Jenkins should pass.

Hope this helps, Jan

**Comment by iankko** [comment]
@thetuxracer 
Any update on this one?

**Comment by thetuxracer** [comment]
@iankko I pushed an update to my fork yesterday, but it doesnt seem to have updated this PR. Ill see whats the problem.

**Comment by jan-cerny** [comment]
@thetuxracer Your pull request shouldn't contain commits of other people. Try rebasing on the top of current upstream master, e.g.:
```
git rebase -i upstream/master
git push -f thetuxracer master
```

**Comment by thetuxracer** [comment]
@jan-cerny Eesh. I have messed this PR beyond saving. Its very ugly to look at as well; I'm closing this and trying again. Apologies for the mess.

**Pull request closed without merging**
