### PR TITLE
[issue #671/#672] remediation and OVAL for bootloader_nousb_argument

### LINKED ISSUE #671: OVAL for RHEL7 bootloader_nousb_argument

### LINKED ISSUE #672: Remediation for RHEL7 bootloader_nousb_argument

### PR DESCRIPTION
**Pull request by shawndwells**
Added remediation for bootloader_nousb_argument into RHEL6/7/fedora

Added OVAL for bootloader_no_usb argument into rhel7/fedora

Resolves #671 and #672

### CODE REVIEW

**Comment by mpreisler** [comment]
There are commits not relevant to the pull request. They seem to be coming from other pull requests. Could you please strip them and keep this clean? Ideally base it directly on top of the `master` branch.

Thanks!

**Comment by shawndwells** [comment]
Unsure why merges were showing up. Closing. Replaced by https://github.com/OpenSCAP/scap-security-guide/pull/767

**Comment by iankko** [comment]
@shawndwells 
> Unsure why merges were showing up. Closing. Replaced by #767

Is it possible when creating git branch to hold changes for new feature you are branching against the currently used (previously created) branch, instead of branching against master? E.g.:
* create feature_1_branch from master in your fork, push some commits in. Create PR,
* create feature_2_branch from feature_1_branch to hold commits for another feature (now feature_2_branch will contain all the commits in the previous PR). 

IMHO the correct approach would be always to create new branch against master of your fork (even if this might mean that branch would be couple of commits behind those in different branch / PR). If some commit depends on some previous commit to be merged first:
* either put both of them into the same branch,
* split them. But wait till the first PR is merged.

Just couple of possible reasons, why branches might contain unwanted commits.

**Comment by shawndwells** [comment]
On 9/30/15 4:27 AM, iankko wrote:
>
> @shawndwells <https://github.com/shawndwells>
>
>     Unsure why merges were showing up. Closing. Replaced by #767
>     <https://github.com/OpenSCAP/scap-security-guide/pull/767>
>
> Is it possible when creating git branch to hold changes for new 
> feature you are branching against the currently used (previously 
> created) branch, instead of branching against master? E.g.:
>
>   * create feature_1_branch from master in your fork, push some
>     commits in. Create PR,
>   * create feature_2_branch from feature_1_branch to hold commits for
>     another feature (now feature_2_branch will contain all the commits
>     in the previous PR).
>
> IMHO the correct approach would be always to create new branch against 
> master of your fork (even if this might mean that branch would be 
> couple of commits behind those in different branch / PR). If some 
> commit depends on some previous commit to be merged first:
>
>   * either put both of them into the same branch,
>   * split them. But wait till the first PR is merged.
>
> Just couple of possible reasons, why branches might contain unwanted 
> commits.
>

@iankko, took a look at my remote and branch settings:

> [shawnw@localhost 7]$ git remote -v
> origin    git@github.com:shawndwells/scap-security-guide.git (fetch)
> origin    git@github.com:shawndwells/scap-security-guide.git (push)
> upstream    https://github.com/OpenSCAP/scap-security-guide.git (fetch)
> upstream    https://github.com/OpenSCAP/scap-security-guide.git (push)
> [shawnw@localhost 7]$ git branch -a
>   bootloader_nousb_argument
> * master
>   remotes/origin/HEAD -> origin/master
>   remotes/origin/bootloader_nousb_argument
>   remotes/origin/master
>   remotes/upstream/master

Was doing a "git pull ; git fetch upstream ; git merge upstream/master," 
then getting a "tracking remote branch upstream/master" message. 
Possible branch collisions? I couldn't immediately figure it out, so 
reforked upstream which cleared away the problem.

**Pull request closed without merging**
