### PR TITLE
Drop firewalld default zone and sshd port fixes

### LINKED ISSUE #2202: SSG does not open port 22
When hardening the default firewall rules, SSG does not open port 22. This makes default installations of RHEL 7.4 unusable.

### PR DESCRIPTION
**Pull request by yuumasato**
- Fixes #2202 

The proper fix for #2202 is to have a remediation for `firewalld_sshd_port_enabled` which set ups a firewalld zone with SSH and an interface assigned to it.

But providing a good fix for `firewalld_sshd_port_enabled` can be very complicated
and will very likely not fit to everyone's use case. And because of that
we will drop remediation for `set_firewalld_sshd_port`, which is causing the
remediated machine to lock down and refuse all connections.

Existent test cases for 'firewalld_sshd_port_enabled' are kept because they are still useful to test the OVAL definition.

### CODE REVIEW

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
I would prefer to comment these because otherwise somebody will re-add them. It's also not good to lose arguably good fixes.

**Comment by yuumasato** [comment]
I'm afraid that empty remediation might cause bad user experience.
I guess it will be picked up by `--remediate`, executed, and marked as fixed, because no errors happened. And then it will still fail evaluation as nothing was done.

**Comment by mpreisler** [comment]
Crap, didn't realize that. OK then.

ACK

**Comment by yuumasato** [comment]
Maybe we need to introduce some kind of sample/example remediation system, this remediation would be present in source code but not used by build system during build.
That would be a way for these sample/example remediations (that  are "not good for everyone") be in the source code but not used by build system.
These example/sample remediations  can serve as evidence that these are not easy, and should not be added by default, and still serve as starting point by content writers.

Would other remediations benefit from this sample/example remediation mechanism?

**Pull request merged**
