### PR TITLE
[Bugfix][Infrastructure] Remove RHEL idents for derivative OSes

### LINKED ISSUE #1452: Scientific Linux 6/Centos & other derivates empty <ident />
I have tried SL6, centos6/7

```
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_common  /usr/share/xml/scap/ssg/content/ssg-centos6-ds.xml
```

**Result:**
```
Title   Ensure /var/log/audit Located On Separate Partition
Rule    xccdf_org.ssgproject.content_rule_partition_for_var_log_audit
Ident
          
Ident
          
Result  notapplicable
```

**Rhel6 result(different rule):**
```
Title   Require Client SMB Packet Signing, if using smbclient
Rule    xccdf_org.ssgproject.content_rule_require_smb_client_signing
Ident   CCE-26328-5
Ident   DISA FSO RHEL-06-000272
Result  notapplicable

```

**Xml:**
```
...
 <ns10:ident system="https://nvd.nist.gov/cce/index.cfm" />
...
```

**Expected result:**
Valid identifier / Or no empty "Ident" line

**Question:**

- Do we want have CCE/... identifiers for derivates or we rather want to remove them completely?
- Shall we fix it in opensca base to not print empty "Ident"?

### PR DESCRIPTION
**Pull request by redhatrises**
- Remove RHEL DISA references for derivatives to stand on their own.
- Fixes #1452

### CODE REVIEW

**Comment by mpreisler** [comment]
will wait for jenkins to finish

**Comment by mpreisler** [comment]
This failed on RHEL6. Python2 on RHEL6 doesn't support predicates in xpath. This is a blocker for this PR.

**Comment by mpreisler** [comment]
@redhatrises doesn't the last commit completely change the logic of the code? You can use the `get` method instead of a xpath predicate to do the same thing.

**Comment by redhatrises** [comment]
@mpreisler yes it does change it. It seems to me to be cleaner, no? Want me to close this and re-submit?

**Comment by mpreisler** [comment]
IMO it is wrong now. It removes all `ident` elements, regardless of what's in them.

**Comment by redhatrises** [comment]
@mpreisler added rhel specific check.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
