### PR TITLE
Map rules to pci-dss

### PR DESCRIPTION
**Pull request by ybznek**
Issue #606

### CODE REVIEW

**Comment by ybznek** [comment]
Not complete

**Comment by iankko** [comment]
@ybznek 
> Not complete

No worries. We don't need to fix #606  in one PR.

**Comment by ybznek** [comment]
ok to test

**Comment by ybznek** [comment]
I was doing my best, but the mapping of some rules wasn't easy.

Still I have some rules without mapping.

-audit_rules_media_export
	- #9 is about medias, but about their storage/transportation
        - #10 explicitly doesn't mention something with external media


-display_login_attempts
	- best match with 10.2.1, but I think it isn't the same.

I have mapped userowner_shadow_file to #8, because It makes password cracking more complicated, but I don't know how to map these rules:
-file_owner_etc_group
-file_groupowner_etc_group
-file_permissions_etc_group
-file_owner_etc_passwd
-file_groupowner_etc_passwd
-file_permissions_etc_passwd
-file_user_owner_grub2_cfg
-file_group_owner_grub2_cfg

**Comment by shawndwells** [comment]
This work is great! Could the `````make table-refs````` be updated as part of this?

e.g.

`````
table-refs: shorthand2xccdf
        xsltproc -stringparam ref "nist" -o $(OUT)/table-$(PROD)-nistrefs.html $(TRANS)/xccdf2table-byref.xslt $(OUT)/unlinked-$(PROD)-empty-groups-xccdf.xml
        xsltproc -stringparam profile "common" -o $(OUT)/table-$(PROD)-nistrefs-common.html \
                $(TRANS)/xccdf2table-profilenistrefs.xslt $(OUT)/unlinked-$(PROD)-empty-groups-xccdf.xml
.....
        xsltproc -stringparam ref "pcidss" -o $(OUT)/table-$(PROD)-pcidss.html $(TRANS)/xccdf2table-byref.xslt $(OUT)/unlinked-$(PROD)-empty-groups-xccdf.xml
        xsltproc -stringparam profile "pci-dss" -o $(OUT)/table-$(PROD)-pcidss.html \
                $(TRANS)/xccdf2table-profilenistrefs.xslt $(OUT)/unlinked-$(PROD)-empty-groups-xccdf.xml

`````

**Comment by shawndwells** [comment]
(happy to put table references in another PR once this gets merged)

**Comment by iankko** [comment]
1) Resolved the merge conflict with current master,
2) Updated PCIDSS ID for 'security_patches_up_to_date' rule from 'Req-5' to 'Req-6' (base on https://github.com/ybznek/scap-security-guide/commit/2f0ba22daed44f8a99dada15528abcda22598ed4#commitcomment-13348306 ),
3) And merged this change manually (since all of the remaining PCI-DSS IDs assigments have been reviewed and identified as to be correct -- see above comments per commit message for details).

**Comment by iankko** [comment]
The two issues unresolved so far:
* https://github.com/OpenSCAP/scap-security-guide/pull/659#issuecomment-141158257 , and
* https://github.com/OpenSCAP/scap-security-guide/pull/659#issuecomment-142364635

have been copied to:
  https://github.com/OpenSCAP/scap-security-guide/issues/606

to deal with them within future PRs.

**Pull request merged**
