### PR TITLE
[WIP] Add initial OSP8, 9, & 10 content

### PR DESCRIPTION
**Pull request by redhatrises**
This PR just adds the initial OSP8, 9, & 10 content. Builds are currently disabled as the build scripts are not detecting the versions appropriately.

### CODE REVIEW

**Comment by mpreisler** [comment]
NACK

Please don't add things that don't build.

**Comment by redhatrises** [comment]
> Please don't add things that don't build.

As you wish... I will add the build fixes to this PR as well.

**Comment by shawndwells** [comment]
The OSP7 directory is far behind the current templating structure. If creating directory trees, you may be best served by starting with RHEL7 structures.

Current PR has things like ``OpenStack/RHEL-OSP/10/templates/csv/oval_5.11/services_disabled.csv`` which are not needed.

**Comment by shawndwells** [comment]
Also, is content expected for the older OSP releases? Or should we fast-forward to OSP 11?

**Comment by redhatrises** [comment]
@shawndwells we should probably fast-forward to OSP 11.

**Comment by redhatrises** [comment]
Closing as content is way out of date.

**Pull request closed without merging**
