### PR TITLE
Add dod_banners option to banner_login_text

### PR DESCRIPTION
**Pull request by lsteinke**
Add an option to accept either DoD banner, rather than forcing a selection of one or the other.

### CODE REVIEW

**Comment by redhatrises** [comment]
This is not a valid DoD banner. For systems that cannot display the full DoD banner, (in this case `dod_default`) the short version (`dod_short`) is to be used. It is an either/or not an and which is per the DoD CIO memo.

**Comment by shawndwells** [comment]
Welcome back, @lsteinke! 👋  Like the intent of this (having OVAL accept either official DoD banner, because who knows which one users configure and both are fine). 

Attempted to test this locally, and the regex isn't matching the dod_short banner. Did this work for you?

**Comment by redhatrises** [comment]
@shawndwells this worked for me. I wonder though if instead of creating a new variable we should remove the `dod_short` and just modify the `dod_default` profile to handle both the full and short version of the banner rather than having a separate one.

**Comment by shawndwells** [comment]
On 8/1/17 10:25 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> this worked for me. I
> wonder though if instead of creating a new variable we should remove
> the |dod_short| and just modify the |dod_default| profile to handle
> both the full and short version of the banner rather than having a
> separate one.

Having both might make sense for supporting opinionated control
assessors who prefer one over the other.

Alternatively: Could we make the combined language the default in
profile selections?

**Comment by redhatrises** [comment]
> Alternatively: Could we make the combined language the default in profile selections?

I say we should rather than having someone customize the profile just for banner selection with either being valid.

**Comment by shawndwells** [comment]
Sounds good. Merging this and will submit a new PR with the default choice updated.

**Comment by shawndwells** [comment]
Thanks, @lsteinke !

**Pull request merged**
