### PR TITLE
[Enhancement] Add new JBoss directory structure

### PR DESCRIPTION
**Pull request by redhatrises**
- Part of #1046

### CODE REVIEW

**Comment by iankko** [comment]
Will look at this one.

**Comment by iankko** [comment]
@redhatrises 
Looks good to me. ACK.

Thank you for your work on this. Looking forward to subsequent changes.

Small question though -- assuming at some moment we will remove content of existing ```JBossEAP5``` and ```JBossFuse6``` folders, right? If I got this change correctly it is copying the existing ```JBossEAP5``` and ```JBossFuse6``` content under new locations (they better to map for structure used by other SSG products) and creating the ```input/oval``` etc locations.
  ```
  $ tree -d 1 JBoss
1 [error opening dir]
JBoss
├── EAP
│   └── 5
│       ├── docs
│       ├── input
│       │   ├── auxiliary
│       │   ├── intro
│       │   ├── oval
│       │   │   ├── platform
│       │   │   └── templates
│       │   ├── profiles
│       │   ├── remediations
│       │   │   └── bash
│       │   └── xccdf
│       │       └── application
│       ├── transforms
│       └── utils
└── Fuse
    └── 6
        ├── docs
        ├── input
        │   ├── auxiliary
        │   ├── intro
        │   ├── oval
        │   │   ├── platform
        │   │   └── templates
        │   ├── profiles
        │   ├── remediations
        │   │   └── bash
        │   └── xccdf
        │       └── application
        ├── transforms
        └── utils

32 directories
```

But at some point in the future we should remove the existing ```JBossEAP5``` and ```JBossFuse6``` folders (after modifying the ```tarball``` target of the main ```Makefile``` to start using the newly introduced content from new ```JBoss/EAP/5``` folder).

But this is truly just side note. I overly like the progress done on these two products the content to in more close way mirror the workflow we use for other SSG products.

**Comment by redhatrises** [comment]
> Small question though -- assuming at some moment we will remove content of existing ```JBossEAP5``` and ```JBossFuse6``` folders, right?

@iankko That is correct. Once the JBoss content has been satisfactorily migrated, we can remove the legacy folders.

**Comment by iankko** [comment]
Ok. Reasonable. Thanks.

**Pull request merged**
