### PR TITLE
Add missing rpm_verify_ownership bash script

### PR DESCRIPTION
**Pull request by redhatrises**
#### Description:

- Add missing rpm_verify_ownership bash script

#### Rationale:

- Script was accidentally removed and missing from older PRs on this topic

### CODE REVIEW

**Comment by matejak** [comment]
Aside from some very minor issues, the code quality of this snippet is outstanding, and I think that the code is so readable, that it even doesn't have to have comments.
Great work!

**Comment by redhatrises** [comment]
> Aside from some very minor issues, the code quality of this snippet is outstanding, and I think that the code is so readable, that it even doesn't have to have comments.
Great work

@matejak thanks! Although I feel as if I must be honest with you.... I copied it from
`rpm_verify_permissions.sh`.

**Comment by redhatrises** [comment]
@matejak made suggested changes.

**Comment by matejak** [comment]
Great, nice!

**Pull request merged**
