### PR TITLE
Add tasks to set GNOME3 banner message

### PR DESCRIPTION
**Pull request by hooksie1**
Added tasks to set banner and lock it. Just used "approved banner" since it's going to change between environments and I figured they could just customize that.

### CODE REVIEW

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
@openscap-ci add to whitelist

**Comment by redhatrises** [comment]
@hooksie1 this needs to be broken up to match what is in `shared/xccdf/system/accounts/banners.xml`. In addition, variables need to be set like in PR #2238

**Comment by yuumasato** [comment]
@hooksie1 Changes look ok for me. There are just some conflicts to fix.

**Comment by yuumasato** [comment]
@hooksie1 last commit (acb84028) contains a lot of unrelated changes.

**Comment by hooksie1** [comment]
I'm going to close this one also and open a new one. I shouldn't be allowed on GitHub any more.

**Pull request closed without merging**
