### PR TITLE
[issue 1842] nosuid on /home

### PR DESCRIPTION
**Pull request by shawndwells**
resolves https://github.com/OpenSCAP/scap-security-guide/issues/1842

### CODE REVIEW

**Comment by mpreisler** [comment]
This fails on Debian:
```
RROR: it's not possible to use the same ID: mount_option_home_nosuid for two semantically different OVAL entities:
First entity  <ns17:definition xmlns:ns17="http://oval.mitre.org/XMLSchema/oval-definitions-5" class="compliance" id="mount_option_home_nosuid" version="1">
    <ns17:metadata>
      <ns17:title>Add nosuid Option to /home</ns17:title>
      <ns17:affected family="unix">
        <platform>Debian 8</platform></ns17:affected>
      <ns17:description>/home should be mounted with mount option nosuid.</ns17:description>
    </ns17:metadata>
    <ns17:criteria>
      <ns17:criterion comment="nosuid on /home" test_ref="test_home_nosuid"/>
    </ns17:criteria>
  </ns17:definition>
  
Second entity <definition xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5" xmlns:ind="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" xmlns:unix="http://oval.mitre.org/XMLSchema/oval-definitions-5#unix" xmlns:linux="http://oval.mitre.org/XMLSchema/oval-definitions-5#linux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" class="compliance" id="mount_option_home_nosuid" version="1">
    <metadata>
      <title>Add nosuid Option to /home</title>
      <affected family="unix">
	</affected>
      <description>The nosuid mount option should be set for user home directory
      partitions such as /home. The suid/sgid permissions should not be required
      in these directories.</description>
    </metadata>
    <criteria>
      <criterion comment="nosuid on /home" test_ref="test_nosuid_home"/>
    </criteria>
  </definition>
  
Use different ID for the second entity!!!
```

**Comment by shawndwells** [comment]
@mpreisler - updated platform tags to only rhel+fedora. Not sure what is causing that error and don't have time to fully test.

**Comment by mpreisler** [comment]
> @mpreisler - updated platform tags to only rhel+fedora. Not sure what is causing that error and don't have time to fully test.

I think it's because Debian already had this. So the solution could be as simple as keeping the new code as it is but removing the old Debian only check. But that's just a guess and we could use the workaround you suggested for the release.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
