### PR TITLE
dod_banners: allow optional whitespace around "--"

### PR DESCRIPTION
**Pull request by jamescassell**
#### Description:

- This makes it so that a single banner can satisfy both RHEL 6 and RHEL 7 STIGs.

#### Rationale:

- Currently, you can't have a single banner that satisfies the check for both RHEL 6 and RHEL 7.  This is because RHEL 7 check requires no white space around "--" while the RHEL 6 check requires whitespace around "--".

### CODE REVIEW

**Comment by jamescassell** [comment]
the easiest way I've found to look at this diff is:
```
git log -1 -p --color-words --word-diff-regex=.
```

**Comment by matejak** [comment]
Nice one, thank you for your contribution!

**Comment by shawndwells** [comment]
This will unfortunately need to be reverted. DoD requires no spaces before/after the dashes:
``..... to protect USG interests--not for your personal benefit or privacy``

**Comment by jamescassell** [comment]
@shawndwells why is it required to have no spaces?  Can we at least update the RHEL 6 version to match?

**Comment by jamescassell** [comment]
@shawndwells from V1R4 "Fix Text": `to protect USG interests -- not for your personal benefit or privacy.`

**Comment by jamescassell** [comment]
within the STIG it is inconsistent.  The discussion has no spaces, but the fix text has spaces. RHEL-07-010050  "The operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a command line user logon."

**Comment by shawndwells** [comment]
This has actually been an issue for some time.

In 2008 DoD CIO issued the following, which aligns to the banner text DISA includes in their content:
http://dodcio.defense.gov/Portals/0/Documents/DoDBanner-9May2008-ocr.pdf

(note the ``--``'s do not have space before/after).

In 2013 the DoD updated their required banner text, however DISA still carries forward the 2008 memo. The current DoD mandated text can be found here:
- Section 6.2 @ http://www.dss.mil/documents/odaa/ODAA%20Process%20Manual%20Version%203.2.pdf
- http://www.dss.mil/documents/odaa/dod_warning_banner.pdf

The DISA profile can be aligned to whatever they wish it to be, but the others (OSPP, Vendor STIG) should likely align against DoD conf settings.

**Comment by shawndwells** [comment]
@jamescassell the DISA fix text from v16 does not have spaces.

From RHEL-06-000073 and RHEL-06-000326

example:
https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/references/disa-stig-rhel6-v1r16-xccdf-manual.xml#L1798#L1806

**Comment by jamescassell** [comment]
@shawndwells sounds like we could at least keep the part of this PR that changes the RHEL 6 to make the spaces optional?  Prior to this PR, RHEL 6 REQUIRED the spaces and RHEL 7 REQUIRED NOT to have the spaces.  After this PR, it is optional on both.

**Comment by shawndwells** [comment]
from SRG-OS-000228 / RHEL-06-000326...

check:
`````
<check-content>If the GConf2 package is not installed, this is not applicable.^M
^M
To ensure login warning banner text is properly set, run the following: ^M
^M
$ gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --get /apps/gdm/simple-greeter/banner_message_text^M
^M
If properly configured, the proper banner text will appear within this schema. ^M
^M
The DoD required text is either: ^M
^M
"You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only. By using this IS (which includes any device attached to this IS), you consent to the following conditions: ^M
-The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations. ^M
-At any time, the USG may inspect and seize data stored on this IS. ^M
-Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose. ^M
-This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy. ^M
-Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details." ^M
^M
OR: ^M
^M
"I've read &amp; consent to terms in IS user agreem't."^M
^M
If the DoD required banner text does not appear in the schema, this is a finding.</check-content>
`````

fix:
`````
fixtext fixref="F-43638r5_fix">To set the text shown by the GNOME Display Manager in the login screen, run the following command: ^M
^M
# gconftool-2^M
--direct \^M
--config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory \^M
--type string \^M
--set /apps/gdm/simple-greeter/banner_message_text \^M
"[DoD required text]"^M
^M
Where the DoD required text is either: ^M
^M
"You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only. By using this IS (which includes any device attached to this IS), you consent to the following conditions: ^M
-The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations. ^M
-At any time, the USG may inspect and seize data stored on this IS. ^M
-Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose. ^M
-This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy. ^M
-Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details." ^M
^M
OR: ^M
^M
"I've read &amp; consent to terms in IS user agreem't."^M
^M
When entering a warning banner that spans several lines, remember to begin and end the string with """. This command writes directly to the file "/etc/gconf/gconf.xml.mandatory/apps/gdm/simple-greeter/%gconf.xml", and this file can later be edited directly if necessary.</fixtext>
`````

**Comment by shawndwells** [comment]
and SRG-OS-000228 / RHEL-06-000073

check:
`````
<check-content-ref name="M" href="DPMS_XCCDF_Benchmark_RHEL_6_STIG.xml" /><check-content>To check if the system login banner is compliant, run the following command: ^M
^M
$ cat /etc/issue^M
^M
^M
Note: The full text banner must be implemented unless there are character limitations that prevent the display of the full DoD logon banner.^M
^M
If the required DoD logon banner is not displayed, this is a finding.^M
</check-content>
`````

fix:
`````
<fixtext fixref="F-43540r3_fix">To configure the system login banner: ^M
^M
Edit "/etc/issue". Replace the default text with a message compliant with the local site policy or a legal disclaimer. The DoD required text is either: ^M
^M
"You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only. By using this IS (which includes any device attached to this IS), you consent to the following conditions: ^M
-The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations. ^M
-At any time, the USG may inspect and seize data stored on this IS. ^M
-Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose. ^M
-This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy. ^M
-Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details." ^M
^M
If the device cannot support the full DoD logon banner due to character limitations, the following text can be used:^M
^M
"I've read &amp; consent to terms in IS user agreem't."</fixtext>
`````

**Comment by jamescassell** [comment]
or would it be better to update rhel6 to require no spaces?  I do see that the RHEL 6 STIG has no spaces in the STIG manual.

**Comment by shawndwells** [comment]
@jamescassell , The DISA STIG profile within SSG tries to align as much as possible with whatever DISA publishes. While spaces seem trivial, if DISA says no spaces in the RHEL6 content... then SSG needs to align =/ 

Adding appropriate spaces should be brought up directly with DISA. Bumping to @tbrunell to ensure that happens from the Red Hat side, but you (@jamescassell) should let them know about the discrepancy too. Their public email is [disa.stig_spt@mail.mil](disa.stig_spt@mail.mil).

**Comment by jamescassell** [comment]
@shawndwells looks like the STIG text matches most closely (almost exact) with the "DoD SIPRNet Warning Banner" listed in your ODAA Process Manual reference above.  I'll send another PR that reverts this and updates RHEL6 to require the absence of spaces.

**Comment by shawndwells** [comment]
@jamescassell thanks. It's so silly to have to worry about spaces. For the DISA profiles alignment is pretty important, especially as people like @tbrunell work towards re-establishing some collaboration with DISA in the open source space. 

Hope this doesn't come across as discouraging. Your help with tickets and PRs has been great!

**Pull request merged**
