### PR TITLE
Update table-refs in order to include the PCI-DSS v3 standard mapping information

### PR DESCRIPTION
**Pull request by ybznek**
Issue https://github.com/OpenSCAP/scap-security-guide/issues/801

Only initial version, please do not merge yet.
screenshot_2015-12-01_09-58-43

### CODE REVIEW

**Comment by iankko** [comment]
Thank you for the proposal, Zbynek. Looks very nice in general IMHO. Couple of nitpicks though:
* would change the ```pcidss``` in parenthesis to ```PCI DSS```,
* assuming that Rationale in the particular column above comes from our <rationale> element from XCCDF prose for that rule. I would add also PCI DSS rationale if possible,
* regarding the mapping assuming the requirement id will be more granular once the granularized links are merged,
* and one final point is that "Req-5" a link to official PCI DSS v3 document. If not, it probably should be.

But as already said, for the first attempt looks very nice from my PoV. Thank you for your effort!

**Comment by mpreisler** [comment]
Could you regenerate the table now that we have granular mappings merged in SSG?

**Comment by ybznek** [comment]
@iankko 
- ```would change the pcidss in parenthesis to PCI DSS,```
I have made translation table. I think that other similar table can use it too
- ```assuming that Rationale in the particular column above comes from our element from XCCDF prose for that rule. I would add also PCI DSS rationale if possible,``` 
I think, we can do it only with lot of manual work
- ```regarding the mapping assuming the requirement id will be more granular once the granularized links are merged,```
There are still refs with not very good granularity, but it is not issue of this PR.
- ```and one final point is that "Req-5" a link to official PCI DSS v3 document. If not, it probably should be.```
I have done it for e.g. Req-5, Req-10, but the code allows to add better page reference for e.g Req-5.1.

It works with Firefox/Chrome. Maybe it is not working with different browser, but i think that there is no better way how to do that.

I have also wanted to sort these rules, but I have big problems with it. The main problem is that here are refs e.g. Req-10 vs Req-5.2.3c and it is not very easy to compare it. I was trying to do some operations on it, but most string functions are in xslt 2.0 and not for xslt 1.0

If you have any tips/feedback, feel free to share.
screenshot_2015-12-08_16-23-19

**Comment by isimluk** [comment]
@ybznek, oh no, this PR also got conflict with some of the recent merges. Can you please take a look?

**Comment by shawndwells** [comment]
Since my C2S table in Makefile caused the conflict, went ahead and manually merged & pushed.

**Pull request merged**
