### PR TITLE
Get rid of attestation references

### PR DESCRIPTION
**Pull request by mpreisler**
This pull request removes "test_attestation" references from OVAL and XCCDF. These references are a pain to keep up to date. As a result they are not up to date at all. In fact we have test attestation in XCCDF and OVAL generated from templates and those attestations don't even apply! Some attestations are super old (2012) and since then the code has changed drastically. Overall I think all of this code just complicates the build process and provides very little value to users.

If somebody wants to see who is responsible for XCCDF or OVAL code they have to use `git blame -u` in the end. I believe all of us do that when we need some code explained.

Plus this removes the test attestation refs from HTML guides.

Not sure which version of SSG I should target, personally I would love to push this out in 0.1.31 but I realize it's a big change and the release will happen quite soon. Give me your thoughts :-)

### CODE REVIEW

**Comment by mpreisler** [comment]
I polled 4 users and 1 Red Hat solution architect and nobody has ever seen anyone use the test attestation references.

**Comment by redhatrises** [comment]
I say Ack with a 'heck yes', and yes, it is a pain to update test attestations. If we have to have them in the future, I say that they just point to the contributor list with whatever date the release was tagged.

**Comment by mpreisler** [comment]
Holy crap, this was easier to get through than I thought ;-D Thx for the review, @redhatrises !

**Comment by redhatrises** [comment]
HAHAHA.... @mpreisler I was actually thinking of getting rid of them at some point myself as it didn't make PRs and updates annoying, and I don't know of anyone using them as well.

**Comment by shawndwells** [comment]
On 10/19/16 4:59 PM, redhatrises wrote:
> I say Ack with a 'heck yes', and yes, it is a pain to update test
> attestations. If we have to have them in the future, I say that they
> just point to the contributor list with whatever date the release was
> tagged.

When SSG started, Jeff, Dave and I mass imported RHEL5 content to create
RHEL6. We then went rule-by-rule updating things for RHEL6 and used the
test attestations to document what rules were reviewed. Totally agree
the tags are unneeded these days!

**Pull request merged**
