### PR TITLE
Add common python module for centralizing reusable code

### PR DESCRIPTION
**Pull request by redhatrises**
#### Description:

- Add common python module for centralizing reusable code and python content

#### Rationale:

- Allows to reduce current duplicated code as well as future code in our python scripts and also provide a future API/framework possibilities for scripts.

### CODE REVIEW

**Comment by jan-cerny** [comment]
Great idea!

**Comment by redhatrises** [comment]
Except for the conflict, what do people think of this PR so far?

**Comment by mpreisler** [comment]
> Except for the conflict, what do people think of this PR so far?

I think these kind of changes are great, let's fix the conflicts and merge this.

**Comment by redhatrises** [comment]
@mpreisler ready for review

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
