### PR TITLE
Updating STIG References for RHEL7

### PR DESCRIPTION
**Pull request by MollyJoBault**
Fixed the STIG references for issue #2001 .

### CODE REVIEW

**Comment by MollyJoBault** [comment]
I hear what you are saying.  The CentOS 7 installer references the RHEL7 STIGs as a list of security recommendations for its parent OS.  I assume the goal here is to help provide information to Linux users to help make their systems more secure.  Don't you think, if you were running CentOS, it would be useful to know there were DoD security recommendations for your parent OS?

**Comment by redhatrises** [comment]
That's what the OSSRG, DISA, and NIST tags are for. The STIGIDs map to an actual vendor product/version STIG like the CCEs. The STIGIDs in this case would need to map to a CentOS7 STIG and not a RHEL7 STIG.

**Comment by MollyJoBault** [comment]
I made the change as you requested.  Thank you for helping make Linux more secure.

**Comment by redhatrises** [comment]
Ack. Thanks!

**Pull request merged**
