### PR TITLE
Add support for Ubuntu/trusty (14.04)

### PR DESCRIPTION
**Pull request by pthierry38**
Support for Ubuntu Trusty (14.04).

Same content as for Xenial (16.04). Both build tested (and bench respectively run) on Xenial and Trusty.
Last "big" PR. Update will obviously be smaller (new oval files, guide content...).

I will try to add new XCCDF as much as possible in both Ubuntu and in Debian 8 in the same time to keep them synchronized.

### CODE REVIEW

**Comment by mpreisler** [comment]
We are preparing for the `0.1.31` release. This change is big so please let's wait with it until `0.1.32`.

**Comment by pthierry38** [comment]
ACK. No problem.

**Comment by pthierry38** [comment]
Rebased branch on current master HEAD to help merge work.

**Comment by mpreisler** [comment]
@pthierry38 I noticed that the PR has files that should be generated by templates. Is that by accident or did you do that on purpose? We now generate all files when building instead of having to run a separate script as before. Check out `generate-from-templates.py`.

**Comment by pthierry38** [comment]
@mpreisler It was an accident, sorry. Two of these files need to be keeped and I added all of them. Correction done, rebase done and Makefile conflict corrected.
I'll try to take time to update the generation of oval files to support regex based file paths to generate according oval files.

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
