### PR TITLE
[Enhancement][RHEL/7] Add sshd port check content for firewalld

### LINKED ISSUE #1434: RHEL 7.3 beta error: SSH not allowed by default rules
If hardening to STIG upstream profile, firewalld blocks SSH access. need rule to add firewall rule?

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #1434

### CODE REVIEW

**Comment by mpreisler** [comment]
Shouldn't the port itself be a value with 22 being the default? AFAIK a lot of people set different ssh ports to cut down on brute forcing attacks.

**Comment by redhatrises** [comment]
@mpreisler I am not sure that we can check for SSH running on non-standard ports. Say I configure SSH to run on port 2292, and run the following command:

```firewall-cmd --permanent --zone=public --add-port=2292/tcp```

How would you know that port 2292 is for SSH? Are you want an `external_variable` in the XCCDF that can be customized for a custom profile if SSH is running on a different port?

**Comment by mpreisler** [comment]
> How would you know that port 2292 is for SSH? Are you want an external_variable in the XCCDF that can be customized for a custom profile if SSH is running on a different port?

yeah

**Comment by redhatrises** [comment]
@mpreisler added the external_variable so that the SSH port can be customized in the XCCDF.

**Comment by mpreisler** [comment]
Great! ACK.

**Comment by mpreisler** [comment]
Crap, I didn't notice it when merging but this breaks references:

```
File '/home/mpreisle/d/scap-security-guide/build/ssg-rhel7-ds.xml' line 36966: Element '{http://checklists.nist.gov/xccdf/1.2}select', attribute 'idref': 'dangling reference to firewalld_ssh_port_enabled!' is not a valid value of the atomic type 'xs:NCName'.
File '/home/mpreisle/d/scap-security-guide/build/ssg-rhel7-ds.xml' line 36966: Element '{http://checklists.nist.gov/xccdf/1.2}select', attribute 'idref': Warning: No precomputed value available, the value was either invalid or something strange happend.
File '/home/mpreisle/d/scap-security-guide/build/ssg-rhel7-ds.xml' line 37337: Element '{http://checklists.nist.gov/xccdf/1.2}select', attribute 'idref': 'dangling reference to firewalld_ssh_port_enabled!' is not a valid value of the atomic type 'xs:NCName'.
File '/home/mpreisle/d/scap-security-guide/build/ssg-rhel7-ds.xml' line 37337: Element '{http://checklists.nist.gov/xccdf/1.2}select', attribute 'idref': Warning: No precomputed value available, the value was either invalid or something strange happend.
File '/home/mpreisle/d/scap-security-guide/build/ssg-rhel7-ds.xml' line 37708: Element '{http://checklists.nist.gov/xccdf/1.2}select', attribute 'idref': 'dangling reference to firewalld_ssh_port_enabled!' is not a valid value of the atomic type 'xs:NCName'.
File '/home/mpreisle/d/scap-security-guide/build/ssg-rhel7-ds.xml' line 37708: Element '{http://checklists.nist.gov/xccdf/1.2}select', attribute 'idref': Warning: No precomputed value available, the value was either invalid or something strange happend.
```

**Comment by mpreisler** [comment]
Fixed the ID in a0c2a71b9826d651a1583b99fc8ed0f9a18e9cf6

**Pull request merged**
