### PR TITLE
RHEL7 generate accounts_password

### PR DESCRIPTION
**Pull request by ybznek**
I will check changes during jenkins build...

### CODE REVIEW

**Comment by redhatrises** [comment]
@ybznek please remove using CCE numbers from being generated. XSLT will replace CCENUM with the ident cce number.

**Comment by ybznek** [comment]
@redhatrises 

Hi, I have tried to remove these CCE NUMBERS
and then I got such diffs

Original:
```
replace_or_append '/etc/security/pwquality.conf' '^dcredit' $var_password_pam_dcredit 'CCE-27214-6' '%s = %s'
```

New:
```
replace_or_append '/etc/security/pwquality.conf' '^dcredit' $var_password_pam_dcredit 'CCENUM' '%s = %s'
```

```'CCENUM'``` weren't replaced. Should I use different placeholder?

--- 
I currently don't see any diff after current changes, so I will remove DO NOT MERGE

**Comment by redhatrises** [comment]
`'CCENUM' weren't replaced. Should I use different placeholder?`

@ybznek no. CCENUM is by default and is valid. I am currently working on the XSLT to replace CCENUM of any remediation script. The CCE numbers should have never been added to the remediation script in the first place.

**Comment by mpreisler** [comment]
LGTM

**Pull request merged**
