### PR TITLE
%VAR% for template replace, @VAR@ for build system replace

### PR DESCRIPTION
**Pull request by mpreisler**
Conventions make things easier to read and debug.

All hail vim macros, sed and regular expressions.

Please review carefully.

### CODE REVIEW

**Comment by mpreisler** [comment]
```
OpenSCAP Error: Invalid selector '0' for xccdf:value/@id='sysctl_net_ipv4_conf_all_log_martians_value'. Using null value instead. [xccdf_policy.c:2103]
Could not resolve xccdf:sub/@idref='sysctl_net_ipv4_conf_all_log_martians_value'! [xccdf_policy_substitute.c:107]
```

This looks suspicious. Might have to look more into this. If anybody knows what's causing this I am all ears.

**Comment by shawndwells** [comment]
On 7/14/17 5:04 PM, Martin Preisler wrote:
> |OpenSCAP Error: Invalid selector '0' for
> xccdf:value/@id='sysctl_net_ipv4_conf_all_log_martians_value'. Using
> null value instead. [xccdf_policy.c:2103] Could not resolve
> xccdf:sub/@idref='sysctl_net_ipv4_conf_all_log_martians_value'!
> [xccdf_policy_substitute.c:107] |
>
> This looks suspicious. Might have to look more into this. If anybody
> knows what's causing this I am all ears.
>

From the variable definition:

<Value id="sysctl_net_ipv4_conf_all_log_martians_value" type="number"
operator="equals" interactive="0">
<title>net.ipv4.conf.all.log_martians</title>
<description>Disable so you don't Log Spoofed Packets, Source
Routed Packets, Redirect Packets</description>
<value selector="">1</value>
<value selector="enabled">1</value>
<value selector="disabled">0</value>
</Value>


I'm guessing there is a selector="0" instead of selector="disabled" in
an xccdf profile somewhere.

$ grep -rin sysctl_net_ipv4_conf_all_log_martians_value
../../../6/input/profiles/
../../../6/input/profiles/common.xml:281:<refine-value
idref="sysctl_net_ipv4_conf_all_log_martians_value" selector="enabled"/>
../../../6/input/profiles/fisma-medium-rhel6-server.xml:136:<refine-value
idref="sysctl_net_ipv4_conf_all_log_martians_value" selector="0" />
../../../6/input/profiles/nist-CL-IL-AL.xml:92:<refine-value
idref="sysctl_net_ipv4_conf_all_log_martians_value" selector="enabled" />
../../../6/input/profiles/usgcb-rhel6-server.xml:138:<refine-value
idref="sysctl_net_ipv4_conf_all_log_martians_value" selector="enabled" />

Appears fisma-medium-rhel6 contains the error. That should be
"selector=disabled"

**Comment by redhatrises** [comment]
@mpreisler why did you make the template scripts non-executable?

**Comment by mpreisler** [comment]
> @mpreisler why did you make the template scripts non-executable?

Because we no longer execute them, they are just modules with classes now.

**Comment by mpreisler** [comment]
> This looks suspicious. Might have to look more into this. If anybody knows what's causing this I am all ears.

This is unrelated to this PR and has been fixed in #2168

**Comment by redhatrises** [comment]
@mpreisler seems like `%MOUNTOPTIONS%` is not being replaced in the ansible templates:

````
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /tmp"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /tmp"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /tmp"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /home"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /dev/shm"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /dev/shm"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /dev/shm"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /tmp"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /tmp"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /tmp"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /home"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /dev/shm"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /dev/shm"
ssg-rhel7-ds.xml:- name: "Ensure permission %MOUNTOPTIONS% are set on /dev/shm"
````

**Comment by mpreisler** [comment]
> @mpreisler seems like %MOUNTOPTIONS% is not being replaced in the ansible templates:

good catch, fixed

**Comment by yuumasato** [comment]
Looks good now, thank you for standardizing it.

**Comment by redhatrises** [comment]
I will review this again tonight.

**Comment by redhatrises** [comment]
LGTM. Ack.

**Pull request merged**
