### PR TITLE
Fix tarball generation in Makefile

### PR DESCRIPTION
**Pull request by yuumasato**

### CODE REVIEW

**Comment by redhatrises** [comment]
@yuumasato shouldn't this be:
```
cd build
cmake ../
make package
```
?

**Comment by redhatrises** [comment]
@yuumasato ignore previous comment. cmake still fails to build package correctly.

**Comment by yuumasato** [comment]
@redhatrises I was out of the loop with this, didn't notice this capabilities.

But yeah, `make package` has failed here, and `make package_source` works but looks incomplete.

**Comment by yuumasato** [comment]
@redhatrises Any other comment on this PR?

**Comment by yuumasato** [comment]
I'm self-merging this for the 0.1.32 release.

**Comment by shawndwells** [comment]
@yuumasato When is the 0.1.32 release? Still time to sneak some things in?

Now that DISA has released an official STIG, we'll want to ensure the next release aligns with their content and we refactor the stig-upstream profile

**Comment by yuumasato** [comment]
@shawndwells Release is today. It is four days late, actually.

**Pull request merged**
