### PR TITLE
Remove old "suse" mapping.

### PR DESCRIPTION
**Pull request by Joeri-MS**

### CODE REVIEW

**Comment by redhatrises** [comment]
@Joeri-MS please fix the build error. Also change `multi_platform_suse` to `multi_platform_sle` in `config/oval.config`

**Comment by radzy** [comment]
@Joeri-MS : When you are ready to upload a new version, you don't need to close this one and open a new PR.  Instead, just use --force to update the same branch, and this PR will be updated.
Something like: git push --force https://github.com/Joeri-MS/scap-security-guide.git master:master

**Comment by Joeri-MS** [comment]
@redhatrises where do i find these build error? Till now the suse part wont build at all.

**Comment by redhatrises** [comment]
I would try to run jenkins by doing the following:

 `cd scap-security-guide && make jenkins`

which would show you build errors before submitting PRs. 

However, this is the build error that exists because of the changes in this PR:

```File 'output/ssg-rhel-osp7-oval.xml' line 8: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}definitions': Missing child element(s). Expected is ( {http://oval.mitre.org/XMLSchema/oval-definitions-5}definition ).
File 'output/ssg-rhel-osp7-oval.xml' line 9: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}tests': Missing child element(s). Expected is one of ( {http://oval.mitre.org/XMLSchema/oval-definitions-5}test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}interim_fix_test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}fileset_test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}fix_test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}no_test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}oslevel_test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#apache}httpd_test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}line_test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}module_test, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}version55_test ).
File 'output/ssg-rhel-osp7-oval.xml' line 10: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}objects': Missing child element(s). Expected is one of ( {http://oval.mitre.org/XMLSchema/oval-definitions-5}object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}interim_fix_object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}fileset_object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}fix_object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}no_object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}oslevel_object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#apache}httpd_object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}line_object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}module_object, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}version55_object ).
File 'output/ssg-rhel-osp7-oval.xml' line 11: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}states': Missing child element(s). Expected is one of ( {http://oval.mitre.org/XMLSchema/oval-definitions-5}state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}interim_fix_state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}fileset_state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}fix_state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}no_state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#aix}oslevel_state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#apache}httpd_state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}line_state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}module_state, {http://oval.mitre.org/XMLSchema/oval-definitions-5#catos}version55_state ).
OpenSCAP Error: Invalid OVAL Definition (5.11) content in output/ssg-rhel-osp7-oval.xml. [oscap_source.c:319]
make[1]: *** [content] Error 1
make[1]: Leaving directory `/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-el7/OpenStack/RHEL-OSP/7'
make: *** [rhel-osp7] Error 2```

**Comment by radzy** [comment]
@redhatrises : I hadn't known about "make jenkins".  Glad to have that info!

**Comment by Joeri-MS** [comment]
Okay. I will try.

**Comment by Joeri-MS** [comment]
Okay, jenkis is building.

**Comment by redhatrises** [comment]
Not sure why this was closed.

**Comment by redhatrises** [comment]
LGTM. Ack.

**Pull request merged**
