### PR TITLE
Refactor and modularize build-scripts 

### PR DESCRIPTION
**Pull request by cipherboy**
Continuation of #2949.

~Dependencies: #2949. Will rebase after merge. Note that this currently has commits from #2949 as well.~

#### Description & Scope

The aim of this PR is to share code between various parts of the build system by turning them into modules. This fixes internal PEP8 issues and refactors the existing code.

 - ~`testoval_module.py` is moved to `ssg/_oval.py`~ -- Part of #2949. 
 - `add_stig_references.py` has code moved to `ssg/_stig.py`
 - `build-all-guides.py` has code moved to `ssg/_build_guides.py`
 - `build-all-remediation-roles.py` has code moved to `ssg/_build_roles.py`
 - `enable-derivatives.py` has code moved to `ssg/_build_derivatives`
 - `relabel-ids.py` has code moved to `ssg/_build_renumber.py`
 - `yaml-to-shorthand.py` has code moved to `ssg/_build_yaml.py` -- this is in keeping with `_build_roles.py`, where the name is based off of the source files, not the target. 
 - ... and more! See commit log for explicit list.

The eventual goal is to move all build-related modules into a submodule called `build`. (E.g., all files with `_build` as a prefix). 

#### Rationale

Each of these build scripts has significant internal code, including some that can be easily shared between multiple scripts. By converting these into modules and refactoring, eventually these parts can be unit tested and better documented.

#### Future Plans

Three more refactoring PRs will likely follow:
 - One for `/utils`, in a similar vein as this one
 - One for `/ssg`, to better organize the final module
 - One for the entire system, replacing `-` in paths with `_` for global consistency. 

After the refactoring is complete, two additional PRs will likely follow:
 - Documentation (inline + external) of the new system
 - Unit tests of critical components

### CODE REVIEW

**Comment by cipherboy** [comment]
@mpreisler Could I get initial feedback on this?

**Comment by mpreisler** [comment]
@cipherboy this needs a rebase and then I think it can be merged

**Comment by cipherboy** [comment]
@mpreisler Okay; rebased and explicitly added changes from #2991.

**Comment by mpreisler** [comment]
ACK

Great stuff!

**Pull request merged**
