### PR TITLE
Combine OVAL - stop copying generated oval

### PR DESCRIPTION
**Pull request by ybznek**
Do not merge yet!

### CODE REVIEW

**Comment by mpreisler** [comment]
+100000

**Comment by mpreisler** [comment]
@ybznek Why is this marked as **do not merge**? Is the output different after applying those patches? I need this to proceed with the cmake PR.

**Comment by ybznek** [comment]
@mpreisler Yes. I had some differences in output. I hope it will be ready early.

Currently we can have quite different outputs which depends on order of files in directory(inodes order). Build process do some merges of ovals - if we do merge in different order we will get different results.

IOW: From SAME source files we can build DIFFERENT data-streams (with different texts inside) - I don't think it is very good.

**Comment by ybznek** [comment]
Currently I don't see any differences.

During revision, please pay attention on https://github.com/OpenSCAP/scap-security-guide/pull/1389/commits/86827432023695375d0a895c04bab6a897dae46e - it should fix different behavior with different order of files in directory.



---
I have used this script to compare DSs
```
#!/bin/bash


git clone --depth 1 https://github.com/OpenSCAP/scap-security-guide.git original && {
    pushd original 
    make -j4
    popd
}

git clone --depth 1 https://github.com/ybznek/scap-security-guide.git -b master-combine-ovals update && {
    pushd update 
    make -j4
    popd
}


function removeDifferences() {
    xmllint --c14n11 /dev/stdin | \
    xmllint --format /dev/stdin | \
    sed 's;timestamp>[^<]*<;timepstamp><;g' | \
    sed 's;timestamp="[^"]*";;g' | \
    sed 's;date="[^"]*";"";g'

}

function compareFile() {
    local originalFile="$1"
    toCompare=$(echo "$originalFile" | sed -E 's;^./original;./update;')
    echo "-----------------------------------------------------------------"
    echo "$originalFile <=> $toCompare" 
    echo "-----------------------------------------------------------------"
    
    cat "$originalFile" | removeDifferences | sort > /tmp/original
    cat "$toCompare"    | removeDifferences | sort > /tmp/new
    
    diff /tmp/original /tmp/new -q || {
        meld /tmp/original /tmp/new
    }
}


#compareFile ./original/Debian/8/output/ssg-debian8-ds.xml
#exit

find ./original -name "*-ds.xml" | grep output | while read originalFile;
do
    compareFile "$originalFile"
done
```

**Comment by iankko** [comment]
Here's the script I have used for comparing XCCDFs:
```
#!/bin/bash

OLDREPO="/tmp/before_1389/scap-security-guide/"
NEWREPO="/tmp/with_1389/scap-security-guide/"

PRODUCTS=("Debian/8" "Fedora" "Firefox" "Chromium" "JRE" "OpenStack/RHEL-OSP/7" "OpenSUSE" "RHEL/5" "RHEL/6" "RHEL/7" "SUSE" "Webmin")

for i in "${PRODUCTS[@]}"
do
  echo "Checking $i"
  product=${i//\//_}
  rm -f "/tmp/${product}-before" "/tmp/${product}-after"
  cd "${OLDREPO}/$i" && make content >& /dev/null && "${OLDREPO}shared/utils/profile_stats.py" -b output/*-xccdf.xml --all > "/tmp/${product}-before"
  cd "${NEWREPO}/$i" && make content >& /dev/null && "${NEWREPO}shared/utils/profile_stats.py" -b output/*-xccdf.xml --all > "/tmp/${product}-after"
  diff -s "/tmp/${product}-before" "/tmp/${product}-after"
  cd "${OLDREPO}"
  cd "${NEWREPO}"
done
```

where OLDREPO resp. NEWREPO is SSG repo clone without or with changes from this PR.

And here's the output:
```
[user@host] $ ./test_1389_pr.sh
Checking Debian/8
Files /tmp/Debian_8-before and /tmp/Debian_8-after are identical
Checking Fedora
Files /tmp/Fedora-before and /tmp/Fedora-after are identical
Checking Firefox
Files /tmp/Firefox-before and /tmp/Firefox-after are identical
Checking Chromium
Files /tmp/Chromium-before and /tmp/Chromium-after are identical
Checking JRE
Files /tmp/JRE-before and /tmp/JRE-after are identical
Checking OpenStack/RHEL-OSP/7
Files /tmp/OpenStack_RHEL-OSP_7-before and /tmp/OpenStack_RHEL-OSP_7-after are identical
Checking OpenSUSE
diff: /tmp/OpenSUSE-before: No such file or directory
diff: /tmp/OpenSUSE-after: No such file or directory
Checking RHEL/5
Files /tmp/RHEL_5-before and /tmp/RHEL_5-after are identical
Checking RHEL/6
Files /tmp/RHEL_6-before and /tmp/RHEL_6-after are identical
Checking RHEL/7
Files /tmp/RHEL_7-before and /tmp/RHEL_7-after are identical
Checking SUSE
diff: /tmp/SUSE-before: No such file or directory
diff: /tmp/SUSE-after: No such file or directory
Checking Webmin
Files /tmp/Webmin-before and /tmp/Webmin-after are identical
```

For ```OpenSUSE``` the ```make content``` target fails:
```
$ make content
../shared/transforms/combineremediations.py opensuse ../shared/templates/static/bash templates/static/bash output/bash-remediations.xml
Traceback (most recent call last):
  File "../shared/transforms/combineremediations.py", line 328, in <module>
    main()
  File "../shared/transforms/combineremediations.py", line 288, in main
    for filename in os.listdir(fixdir):
OSError: [Errno 2] No such file or directory: 'templates/static/bash'
../shared/product-make.include:101: recipe for target 'output/bash-remediations.xml' failed
make: *** [output/bash-remediations.xml] Error 1
```

For ```SUSE``` product there isn't such ```make content``` target:
```
$ make content
make: *** No rule to make target 'content'.  Stop.
```

For the rest of the products, the generated XCCDFs are identical => ACK from me.

@ybznek Thank you for this effort! Much appreciated.

**Pull request merged**
