### PR TITLE
Consolidate common README files and update

### PR DESCRIPTION
**Pull request by radzy**
Update the README file that was common to multiple OS/app
directories and move it to shared.

Signed-off-by: T.O. Radzy Radzykewycz <radzy@windriver.com>

### CODE REVIEW

**Comment by radzy** [comment]
I wanted to update README with some of the things I've found.  Since the identical file was in multiple locations, I moved them all to shared and made the updates there.

**Comment by redhatrises** [comment]
Would prefer that this go under the top level and be renamed to `layout-README`, `README-layout`, `DEV-README`, or something else that is obvious.

**Comment by radzy** [comment]
Easy enough, and a good suggestion.  Done.

**Comment by radzy** [comment]
Not sure what's the problem.  Will try a different branch.

**Comment by shawndwells** [comment]
README-layout works for me. Thanks @radzy !

**Comment by shawndwells** [comment]
(note I did administratively add .md extension so it renders when clicking on the file)

**Comment by radzy** [comment]
Thanks, @shawndwells

**Pull request merged**
