### PR TITLE
Updating refresh stig refs.sh

### PR DESCRIPTION
**Pull request by MollyJoBault**
I'm still not sure how to remove from this the Makefile changes.  I've updated refresh-stig-refs.sh script to point to the new locations and to deal with multiple rule ids for the same STIG rule.

### CODE REVIEW

**Comment by mpreisler** [comment]
I recommend:
```
git rebase -i master
# now drop the rpm makefile commit
git push force fork Updating-refresh-stig-refs.sh
```

It will get rid of the first commit and also the merge commit.

HTH!

**Comment by mpreisler** [comment]
Hi @MollyJoBault , any updates here?

**Comment by MollyJoBault** [comment]
I think I did it.  I need to learn how to use git better. :(

**Comment by redhatrises** [comment]
Closing in favor of #1904

**Pull request closed without merging**
