### PR TITLE
[Enhancement][Infrastructure] testcheck.py: detect oscap version

### PR DESCRIPTION
**Pull request by redhatrises**
- Detect oscap version from openscap.py to determine OVAL version
  If testcheck.py cannot determine the OVAL version, use version in oval.config

### CODE REVIEW

**Comment by iankko** [comment]
```openscap-python``` RPM package should be added into the ```Requires:``` section of the main *.spec file:
```
[root@localhost scap-security-guide]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@localhost scap-security-guide]# cd RHEL/7/input/oval/
[root@localhost oval]# ./testcheck.py oval_5.11/service_chronyd_or_ntpd_enabled.xml 
Traceback (most recent call last):
  File "./testcheck.py", line 8, in <module>
    import testcheck_module
  File "../../../../shared/modules/testcheck_module.py", line 7, in <module>
    from openscap import oscap_get_version
ImportError: No module named openscap
```
Once ```openscap-python``` RPM is installed:
```
[root@localhost oval]# rpm -q openscap-python
openscap-python-1.2.5-3.el7.x86_64
```
it works fine:
```
[root@localhost oval]# ./testcheck.py oval_5.11/service_chronyd_or_ntpd_enabled.xml 
Evaluating with OVAL tempfile : /tmp/service_chronyd_or_ntpd_enabledAEqS7L.xml
Writing results to : /tmp/service_chronyd_or_ntpd_enabledAEqS7L.xml-results
Definition oval:scap-security-guide.testing:def:106: false
Definition oval:scap-security-guide.testing:def:103: true
Definition oval:scap-security-guide.testing:def:102: false
Definition oval:scap-security-guide.testing:def:101: true
Definition oval:scap-security-guide.testing:def:100: true
Evaluation done.
```

Please add that ```*.spec``` Requires: change yet. Otherwise it looks good to me.

**Comment by redhatrises** [comment]
@iankko thanks for the review. You came across a bug that should be fixed now. If openscap-python is not installed, the testcheck.py should fail back to using the `oval_version` from `oval.config`. I also added the installation requirement of `openscap-python` to `Build.md` as `openscap-python` is not required for the rpm to build or install, so a `Requires: openscap-python` is not really required for installation in the rpm `.spec` file.

**Comment by iankko** [comment]
@redhatrises 
You are probably right adding ```openscap-python``` to Requires: for the whole RPM is a bit overloaded solution (since ```testcheck.py``` isn't installed in the RPM it would be "artificial" Requires).

But IMHO we should at least wrap the newly added:
``` + from openscap import oscap_get_version ```

clause (https://github.com/redhatrises/scap-security-guide/commit/9a43dfa106b8c5d30c7b4a716b9be8f5b339e1ba#diff-eae180f6bb03ec6241fd6dff111e4ad5R7 ) with ```try: catch:``` statements.

As far as I got, ```testcheck.py``` script is heavily used tool by some developers to quickly check the work of OVAL check (without the need to build whole RPM, install it & tailor the benchmark & run the scan). We should do our best to simplify their lifes if possible. The ideas is to add something as follows:

```
try:
  from openscap import oscap_get_version
except ImportError, e:
  if OS_is_RHEL_7:
    print "Install openscap-python RPM package to produce 5.11 version of OVAL for RHEL-7"
    sys.exit(1)
```
or something like that. The idea is to fail gracefully and notify users they probably want to have ```openscap-python``` RPM installed rather than each time to need to investigate possible failure reasons behind those ```Invalid OVAL definition content(5.10) in ...``` ```testcheck.py``` error messages.

**Comment by iankko** [comment]
ACK for merging this one (the corresponding ```import``` clause to be enhanced in some of future PRs).

**Pull request merged**
