### PR TITLE
cmake/SSGCommon.cmake: added check for override attribute

### PR DESCRIPTION
**Pull request by matusmarhefka**
#### Description:

- Checks that all profile titles and descriptions in generated XCCDF files contain `override="true"` attribute.

#### Rationale:

- This check should prevent us from releasing SSG with profiles which are extending other profile but have no `override` attribute set for their `title` and `description` tags.

### CODE REVIEW

**Comment by shawndwells** [comment]
@openscap-ci ok to test

**Comment by shawndwells** [comment]
@openscap-ci add to whitelist

**Comment by shawndwells** [comment]
Jenkins may need to be ignored on this one, as the patchset properly fails the unit tests.

The tests only fail if a full ``make`` is executed. Should/can the unit tests be updated to also fail builds when doing a targeted build (e.g. ``make rhel7``)?

**Comment by dahaic** [comment]
@matusmarhefka as the tests are failing because of missing override tags on many profiles, can you fix it across whole SSG? I know the PR will get bigger, but that way, we won't introduce always failing check. No need to create new PR, just make this PR passing.

**Comment by mpreisler** [comment]
I agree with @dahaic , we should fix this in all profiles before merging.

**Comment by matusmarhefka** [comment]
The commit ae91818 sets `override="true"` for all profile titles and descriptions.

**Comment by mpreisler** [comment]
Great stuff! This was a problem in multiple releases and now it can't happen any more!

**Pull request merged**
