### PR TITLE
Further improved replace_or_append

### PR DESCRIPTION
**Pull request by matejak**
Further improvements to the function:

- Harmless improvement: Synchronized the case sensitivity option of `grep` and `sed` commands. In cases where the provided and actual keys differed by case, the substitution would fail.
The modification is backwards-compatible (c-insensitivity is on by default) and controlled from a single point.

- Potentially controversial, but needed improvement: I have appended the word boundary right after the key for the matching.
Although this change alters behavior of the function, remediations that are not broken already shouldn't break, as this change just prevents longer strings that begin with the substring that happens to be the ky to be mistaken for it. For example, `space_left_action` begins with substring `space_left`, so remediation for `auditd_data_retention_space_left` rule could break the `auditd_data_retention_space_left_action` rule.

### CODE REVIEW

**Comment by yuumasato** [comment]
I'm totally in favor of the potentially controversial improvement, although I don't see it can be controversial.

**Comment by mpreisler** [comment]
I think the "controversial" improvement is a great improvement for additional sanity of the fixes.

**Comment by matejak** [comment]
While I also think that it is a good idea, it changes the behavior of the function. Although I think that it shouldn't break anything, somebody who is very cautious might oppose this change.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
