### PR TITLE
Add Debian/8/input/oval/oval_5.11/ folder

### PR DESCRIPTION
**Pull request by msrubar**
I had to create an empty `.gitignore` file to be able to add an empty directory.

### CODE REVIEW

**Comment by redhatrises** [comment]
PR #905 is adding the OVAL checks to `oval_5.11`, so I think this PR should be closed in favor of #905

**Comment by isimluk** [comment]
I am ok to merge this now. Once the jenkins finishes. It may take a while before #905 is merged and till then every other one's `make validate` will fail.

The worst downside is we end-up with an extra gitignore.

**Comment by iankko** [comment]
@isimluk 
> I am ok to merge this now. Once the jenkins finishes. It may take a while before #905 is merged and till then every other one's make validate will fail.
> 
The worst downside is we end-up with an extra gitignore.

+1 for this approach. Jenkins finished successfully. ACK from me for merging this.

**Comment by iankko** [comment]
Fixes: https://github.com/OpenSCAP/scap-security-guide/issues/902

**Pull request merged**
