### PR TITLE
Rpm compatibility

### PR DESCRIPTION
**Pull request by thenefield**
Added the following defines to the rpmbuild process to allow for backwards compatibility to RHEL 5 and RHEL 4, when building from RHEL6 or greater: 

--define '_source_filedigest_algorithm md5'
--define '_binary_filedigest_algorithm md5'
--define '_source_payload w9.bzdio'
--define '_binary_payload w9.bzdio'

### CODE REVIEW

**Comment by shawndwells** [comment]
@iankko, @isimluk because you guys handle the RHEL packaging, are you OK with these changes?

**Comment by isimluk** [comment]
I would advise to build packages separately for older releases. (There is this `rpmbuild-md5` tool) for production purposes. However, for the purpose of scap-security-guide master, I have no objections.

**Comment by redhatrises** [comment]
> I would advise to build packages separately for older releases.

Fully agree here.

> (There is this rpmbuild-md5 tool)

Personally would rather refer to this in BUILD.md about building from/for "legacy" systems.

**Comment by iankko** [comment]
@shawndwells 
As already clarified by Simon and Gabe, I don't think hard-coding specific constants should be the right way to go (even if this should produce workaround that would work on older systems ).

Did I got it right that this would be an issue only in case the scap-security-guide rpm would be built on system using SHA256 as the digest algorithm & then subsequently tried to be installed on system using MD5 as the digest algorithm? If so, why is the "cross-compilation" necessary? Isn't possible to built that RPM directly on Red Hat Enterprise Linux 5 or 4 system? Are there some build issues? If so, IMHO we should rather fix those to support native builds than introduce some RPM build process arguments that might not work in the future (for all versions).

**Comment by thenefield** [comment]
Agree with comments. I wasn't sure the intention of the RPM to bundle separately for each OS version or not, given that both RHEL6 and RHEL7 content were bundled together. Perhaps instead, separate if statements should be included for each OS-specific content (RHEL4, RHEL5, RHEL6, RHEL7). Also, to support building and using on RHEL4, some packages will need to be updated. Based on feedback, I will go ahead and close this request.

**Pull request closed without merging**
