### PR TITLE
Update map_product_module.py

### PR DESCRIPTION
**Pull request by Joeri-MS**
Fix for sles11/12 with double digit version. Part of issue #1469

### CODE REVIEW

**Comment by redhatrises** [comment]
@Joeri-MS only change that needs to takes place in ```map_product_module.py``` is 
```re.findall('suse', version):``` to ```if re.findall('sle', version):```.

**Comment by mpreisler** [comment]
@openscap-jenkins add to whitelist

**Comment by Joeri-MS** [comment]
No. The parse_product_name change is needed. Because now the product is sle1 and the product_version is 2, when using sle12.

**Comment by redhatrises** [comment]
Actually it is not needed as `\d+` is the same as `[0-9]+`.

**Comment by mpreisler** [comment]
I think it might be needed because without the first capture group the regex won't greedily find the biggest match.

**Comment by redhatrises** [comment]
Yup. You both are right. My bad.

**Comment by mpreisler** [comment]
We should however unify `sle` vs `suse` instead of accepting both of them. Let's just use `sle` because it's the name of the product. `opensuse` is also valid but just `suse` shouldn't be IMO.

@Joeri-MS are you interested in finishing change?

**Comment by Joeri-MS** [comment]
I made an new pull request. Right? Iam still new to github :)

**Pull request closed without merging**
