### PR TITLE
Issue #1889: remediation sshd_use_approved_macs

### PR DESCRIPTION
**Pull request by jan-cerny**
This pull request provides a remediation specific for RHEL7 and fixes the OVAL definition in rule `sshd_use_approved_macs`

### CODE REVIEW

**Comment by redhatrises** [comment]
@jan-cerny could you make the cipher list an `<external_variable>` and add the variable to the XCCDF?

**Comment by shawndwells** [comment]
Variable would be awesome. Trouble makers like @trevor-vaughan customize the available ciphers for downstream projects like SIMP. That change could positively impact users.

**Comment by jan-cerny** [comment]
@redhatrises I agree, I will try it, but I think that then I will have to rewrite the nasty regular expression again 😬 😀

**Comment by jan-cerny** [comment]
I have reworked both OVAL and bash script by using an xccdf:Value.

**Comment by yuumasato** [comment]
These are great changes!
Ack

**Pull request merged**
