### PR TITLE
Docker profile added

### PR DESCRIPTION
**Pull request by thetuxracer**
Created the docker profile. 
Copied the cjis profile and mistakenly edited,renamed the incorrect profiles, have fixed that in the 4th commit of this PR.

Here's hoping third time's the charm.

### CODE REVIEW

**Comment by iankko** [comment]
@thetuxracer 
There are three issues why the current form is failing (https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/516/label=node-el7/consoleFull ).

* the ```RHEL/7/input/xccdf/services/docker.xml``` is missing enclosing xccdf ```</Group>``` tag (the opening is there, but enclosing one is missing). This leads to the following warning during the build being issued:
```
[user@host] make content
xsltproc -o output/guide.xml ../../shared/transforms/includelogo.xslt input/guide.xml
xsltproc --stringparam SHARED_RP "/tmp/github/scap-security-guide/shared" -o output/shorthand.xml input/guide.xslt output/guide.xml
input/xccdf/services/docker.xml:30: parser error : Premature end of data in tag Group line 1
...
```

This is fixed by the following change:
```
$ git diff RHEL/7/input/xccdf/services/docker.xml
diff --git a/RHEL/7/input/xccdf/services/docker.xml b/RHEL/7/input/xccdf/services/docker.xml
index c40413e..3866c44 100644
--- a/RHEL/7/input/xccdf/services/docker.xml
+++ b/RHEL/7/input/xccdf/services/docker.xml
@@ -27,3 +27,4 @@ stigid="" />
 <oval id="service_docker_enabled" />
 </Rule>
 
+</Group>
```

* The ```RHEL/7/input/guide.xslt``` needs to be modified to contain definition of the docker section, thus something like:
```
$ git diff RHEL/7/input/guide.xslt
diff --git a/RHEL/7/input/guide.xslt b/RHEL/7/input/guide.xslt
index d02451c..8bda108 100644
--- a/RHEL/7/input/guide.xslt
+++ b/RHEL/7/input/guide.xslt
@@ -127,6 +127,7 @@
       <xsl:apply-templates select="document('xccdf/services/obsolete.xml')" />
       <xsl:apply-templates select="document('xccdf/services/base.xml')" />
       <xsl:apply-templates select="document('xccdf/services/cron.xml')" />
+      <xsl:apply-templates select="document('xccdf/services/docker.xml')" />
       <xsl:apply-templates select="document('xccdf/services/ssh.xml')" />
       <xsl:apply-templates select="document('xccdf/services/sssd.xml')" />
       <xsl:apply-templates select="document('xccdf/services/xorg.xml')" />
```
will fix this.

* Finally the corresponding OVAL ```service_docker_enabled.xml``` needs to be placed into ```RHEL/7/input/oval/oval_5.11/service_docker_enabled.xml``` location (rather than current ```RHEL/7/input/oval/service_docker_enabled.xml``` location).

The reasoning here being the ```service_docker_enabled.xml``` OVAL uses OVAL-5.11 language constructs, and thus needs to be in the proper directory in order to be included into the benchmark only in moment, the underlying oscap version on the system supports OVAL-5.11. This is ensured by placing such OVAL file into ```RHEL/7/input/oval/oval_5.11/``` location.

The current ```RHEL/7/input/oval/``` is dedicated for OVAL checks using just OVAL-5.10 language constructs. If you have a look e.g. at ```service_nails_enabled.xml``` check it's using different code (chkconfig OVAL entity to be exact), rather than systemdunit* entity, which got introduced only in OVAL-5.11 language version.

**Comment by iankko** [comment]
Once all three of the above changes are applied, the RHEL-7 content builds && validates properly:
```
$ make validate
oscap xccdf validate-xml output/ssg-rhel7-xccdf.xml
oscap oval validate-xml --schematron output/ssg-rhel7-oval.xml
oscap cpe validate-xml output/ssg-rhel7-cpe-dictionary.xml
oscap oval validate-xml --schematron output/ssg-rhel7-cpe-oval.xml
oscap ds sds-validate output/ssg-rhel7-ds.xml
oscap xccdf validate-xml output/ssg-centos7-xccdf.xml
oscap ds sds-validate output/ssg-centos7-ds.xml
oscap xccdf validate-xml output/ssg-sl7-xccdf.xml
oscap ds sds-validate output/ssg-sl7-ds.xml
cd output; ../../../shared/utils/verify-references.py --rules-with-invalid-checks --ovaldefs-unused ssg-rhel7-xccdf.xml
```

**Comment by iankko** [comment]
To sum up what needs to be done 
* Move the ```service_docker_enabled``` OVAL
```
git mv RHEL/7/input/oval/service_docker_enabled.xml RHEL/7/input/oval/oval_5.11/service_docker_enabled.xml
```
* And apply the following patch yet:
```
$ git diff
diff --git a/RHEL/7/input/guide.xslt b/RHEL/7/input/guide.xslt
index d02451c..8bda108 100644
--- a/RHEL/7/input/guide.xslt
+++ b/RHEL/7/input/guide.xslt
@@ -127,6 +127,7 @@
       <xsl:apply-templates select="document('xccdf/services/obsolete.xml')" />
       <xsl:apply-templates select="document('xccdf/services/base.xml')" />
       <xsl:apply-templates select="document('xccdf/services/cron.xml')" />
+      <xsl:apply-templates select="document('xccdf/services/docker.xml')" />
       <xsl:apply-templates select="document('xccdf/services/ssh.xml')" />
       <xsl:apply-templates select="document('xccdf/services/sssd.xml')" />
       <xsl:apply-templates select="document('xccdf/services/xorg.xml')" />
diff --git a/RHEL/7/input/xccdf/services/docker.xml b/RHEL/7/input/xccdf/services/docker.xml
index c40413e..3866c44 100644
--- a/RHEL/7/input/xccdf/services/docker.xml
+++ b/RHEL/7/input/xccdf/services/docker.xml
@@ -27,3 +27,4 @@ stigid="" />
 <oval id="service_docker_enabled" />
 </Rule>
 
+</Group>
```

**Comment by iankko** [comment]
Also, it would be nice if the PR contained just truly necessary changes (IOW those changes related with CJIS profile [deleting it's content, and then moving it back] would be removed for more cleaner history).

**Comment by mpreisler** [comment]
@thetuxracer unassigning because reviews shouldn't be done by the author.

**Comment by jan-cerny** [comment]
@thetuxracer Thank you very much for your work.

I have squashed the commits and merged manually onto master as https://github.com/OpenSCAP/scap-security-guide/commit/3d2b5181b020979d316c59537e10bb3f5b1e497a

Closing this PR.

**Comment by iankko** [comment]
@jan-cerny 
> @thetuxracer Thank you very much for your work.
> 
I have squashed the commits and merged manually onto master as 3d2b518
> 
Closing this PR.

Thanks for this. +1 on this approach (since it makes more cleaner history).

**Comment by iankko** [comment]
@thetuxracer 
Thank you for your contribution!

Two kind requests for the future PRs though:
* Please use different commit message across different commits (meaning the first sentence). The point of the commit should be visible right in the first message (so there's no need to diff them to realize what got added in the N+1 commit),

* If issues are reported during PR lifecycle (which happens), please use git squashing mechanism to reduce the count of necessary commits. See e.g.: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ how to do that. The issue is after making new SSG release we still produce Changelog manually. And inspecting commits just undoing the change made in some of the previous commit within same PR is just time waste for the person responsible for creating the release changelog.

Thank you again.

Regards, Jan

**Comment by thetuxracer** [comment]
@jan-cerny Thank you for the merge!

@iankko I shall keep your advice in mind for future PRs. Thank you jan-cerny, iankko, redhatrises and mpreisler for your guidance and timely suggestions.

**Pull request closed without merging**
