### PR TITLE
Remove global Makefile as cmake is the build system now

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by mpreisler** [comment]
I wanted to do this as well but the global makefile is building the RPM and tarball. We have yet to port that over to something else.

We could probably change it to something like `make-rpm.sh` and use `make package_source` in cmake to build the tarball.

**Comment by redhatrises** [comment]
@mpreisler I was just realizing this. Doesn't cmake have the capability to generate tarballs and rpms with CPack?

**Comment by mpreisler** [comment]
@redhatrises It does and it sort of works, I haven't finished it though. If you can make the cpack RPM similar to the one created by rpmbuild I think we could move to the cpack RPM.

CC @shawndwells

**Comment by yuumasato** [comment]
The only missing piece to remove the old `Makefile` is to build zip archives through `CMakelists.txt`. I'll work on this now.

**Comment by redhatrises** [comment]
[retest this please]

**Comment by redhatrises** [comment]
With #1913 and #1901, this is ready for review.

**Comment by mpreisler** [comment]
Remove `scap-security-guide.spec.in` as well.

**Comment by redhatrises** [comment]
> Remove `scap-security-guide.spec.in` as well.

@mpreisler done

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
