### PR TITLE
Extra Apache STIG rules

### PR DESCRIPTION
**Pull request by shawndwells**
Adding a few extra Apache STIG rules.

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells `apache_stigid` is not valid.

**Comment by shawndwells** [comment]
On 4/8/18 3:49 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> |apache_stigid| is not 
> valid.
derp. Thanks!

**Comment by matejak** [comment]
@shawndwells Great work, could you please share with us the source for those rules, so somebody can properly review the PR?

**Comment by yuumasato** [comment]
I noticed that you add CCE numbers for existing rules but you didn't add CCE numbers for the newly written rules. Any particular reason for that?

**Comment by shawndwells** [comment]
On 4/9/18 10:43 AM, Matěj Týč wrote:
> @shawndwells <https://github.com/shawndwells> Great work, could you 
> please share with us the source for those rules, so somebody can 
> properly review the PR?
https://iase.disa.mil/stigs/app-security/web-servers/Pages/apache.aspx

The prose is a copy/paste from the DISA content, vs having to interpret 
anything.

**Comment by redhatrises** [comment]
Ack.

**Pull request merged**
