### PR TITLE
[Enhancement][RHEL6/7][Fedora] remove remediation script symlinks

### PR DESCRIPTION
**Pull request by redhatrises**
- Remove symlinks to remediation scripts and add multi_platform variable

### CODE REVIEW

**Comment by redhatrises** [comment]
Also requires #768

**Comment by iankko** [comment]
This change again is just:
* removing existing symlinks, 
* and adding platform tags for ```shared/``` remediation scripts, where applicable to more than one product =>

it's enough to compare if count of remediation scripts included for that product before matches the count of remediation scripts included for that product now.

**Comment by iankko** [comment]
Previous state:
```
$ git checkout 3aa03f045e81605efc4021984d1c1cdc64cabaf3
..
$ ls RHEL/6/input/fixes/bash/*.sh | wc -l
238
$ ls RHEL/7/input/fixes/bash/*.sh | wc -l
214
$ ls Fedora/input/fixes/bash/*.sh | wc -l
16
```
Current state:
```
$ cd RHEL/6
$ make | grep remediation
# Make intermediate build/rhel6_fixes directory to hold final list of remediation scripts for rhel6
# Search ../../shared/fixes/bash and input/FIXES directories to find all product specific remediation scripts,
../../shared/transforms/combinefixes.py ../../config rhel6 build/rhel6_fixes output/bash-remediations.xml

Notification: Merged 40 remediation scripts into XML document.
$ cd RHEL/7
$ make | grep remediation
# Make intermediate build/rhel7_fixes directory to hold final list of remediation scripts for rhel7
# Search ../../shared/fixes/bash and input/FIXES directories to find all product specific remediation scripts,
../../shared/transforms/combinefixes.py ../../config rhel7 build/rhel7_fixes output/bash-remediations.xml

Notification: Merged 35 remediation scripts into XML document.
$ cd Fedora/
$ make | grep remediation
..
# Make intermediate build/fedora_fixes directory to hold final list of remediation scripts for fedora
# Search ../shared/fixes/bash and input/FIXES directories to find all product specific remediation scripts,
../shared/transforms/combinefixes.py ../config fedora build/fedora_fixes output/bash-remediations.xml

Notification: Merged 8 remediation scripts into XML document.
```

Checking the generated benchmark the count of actually found ```<fix>``` elements returns:
* RHEL/6 case (```make``` has been run previously):
```
$ cat RHEL/6/output/ssg-rhel6-xccdf.xml | grep "<fix" | wc -l
40
```
* RHEL/7 case (```make``` has been run previously):
```
$ cat RHEL/7/output/ssg-rhel7-xccdf.xml | grep "<fix" | wc -l
35
```
* Fedora case (```make``` has been run previously):
```
$ cat Fedora/output/ssg-fedora-xccdf.xml | grep "<fix" | wc -l
6
```

@redhatrises 

Do you actually plan to add the missing ones? (compare the huge difference in the counts for RHEL-6 and RHEL-7 before and now)

Thanks, Jan.

**Comment by iankko** [comment]
@redhatrises 
> @redhatrises
>
Do you actually plan to add the missing ones? (compare the huge difference in the counts for RHEL-6 and RHEL-7 before and now)
>
Thanks, Jan.

I am going to merge this one (but we need to ensure also RHEL-6, RHEL-7, and Fedora specific fixes are included too). I will with priority create such pull request for RHEL-7 product. You can take RHEL-6 and Fedora ones, if you wish.

**Comment by iankko** [comment]
RHEL-7 case is covered within this PR: 
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/pull/775

I will do RHEL-6 && Fedora case shortly (will add links here).

**Comment by iankko** [comment]
The corresponding change for ```RHEL/6``` and ```Fedora``` products is in this PR:
&nbsp; &nbsp; [2] https://github.com/OpenSCAP/scap-security-guide/pull/776

**Comment by redhatrises** [comment]
> @redhatrises 
>> @redhatrises
>>
Do you actually plan to add the missing ones? (compare the huge difference in the counts for RHEL-6 and RHEL-7 before and now)
>>
Thanks, Jan.

> I am going to merge this one (but we need to ensure also RHEL-6, RHEL-7, and Fedora specific fixes are included too). I will with priority create such pull request for RHEL-7 product. You can take RHEL-6 and Fedora ones, if you wish.

Thanks @iankko for taking care of the RHEL-6 and RHEL-7 remediation fixes! I wasn't able to get to them over the weekend or today, so thanks!

**Comment by iankko** [comment]
@redhatrises 
> Thanks @iankko for taking care of the RHEL-6 and RHEL-7 remediation fixes! I wasn't able to get to them over the weekend or today, so thanks!

No worries. You are welcome.

IMHO, actually thinking adding / changing the remediation scripts functionality so it would honor the platform tag was more trickier task => thank you for not getting scared of it and pursuing its implementation!

Adding the tags for RHEL-7, RHEL-6 & Fedora was just a routine. It's good it's done already too though :).

**Pull request merged**
