### PR TITLE
Ansible disable ctrlaltdel reboot

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by konstruktoid** [comment]
Why not use `command`? 

```
---
# CCE-27511-5

- name: disable ctrl-alt-del
  command: systemctl mask ctrl-alt-del.target
...
```

(https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/21_ctrlaltdel.yml)

**Comment by mpreisler** [comment]
Hmm, I really dislike the ansible syntax for this particular thing but there is nothing we can do.

`src -> dest` with `state: link` actually means linking `dest` to `src`. In other words creating a symlink at `dest` that links to `src. These are confusing terms when used for symlinks or hardlinks.

**Comment by shawndwells** [comment]
@konstruktoid trying to avoid use of shell/command, use ansible capabilities whenever possible

**Comment by shawndwells** [comment]
@openscap-ci test this please

**Comment by shawndwells** [comment]
openci build: https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/213/

**Comment by hooksie1** [comment]
You can mask without using command.

    - name: disable ctrl-alt-delete
      systemd:
        name: ctrl-alt-del.target
        enabled: no
        masked: yes

**Comment by dahaic** [comment]
Jenkins test this please.

**Comment by bgjoseluis** [comment]
Hello,


just trying to help.

According to this tech note "https://cgit.freedesktop.org/systemd/systemd/commit/?id=2e5c94b9aa" if you press 7x in less than 2s the fix doesn't work.

In RHEL7.4 there is also a new option in systemd configuration "CtrlAltDelBurstAction" that needs to be configured:

CtrlAltDelBurstAction=none

So for RHEL7.4 you need to run (to work properly):

( ln -sf /dev/null /etc/systemd/system/ctrl-alt-del.target or systemctl mask ctrl-alt-del.target)
and
cp -p /etc/systemd/system.conf /etc/systemd/system.conf.ori
sed -i 's/#CtrlAltDelBurstAction=reboot-force/CtrlAltDelBurstAction=none/' /etc/systemd/system.conf

RHEL7.4 release notes: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/7.4_Release_Notes/index.html

Thanks in advance.

**Comment by shawndwells** [comment]
On 8/22/17 5:05 AM, Jose Luis Barquin Guerola wrote:
>
> Hello,
>
> just trying to help.
>
> According to this tech note
> "https://cgit.freedesktop.org/systemd/systemd/commit/?id=2e5c94b9aa"
> if you press 7x in less than 2s the fix doesn't work.
>
> In RHEL7.4 there is also a new option in systemd configuration
> "CtrlAltDelBurstAction" that needs to be configured:
>
> CtrlAltDelBurstAction=none
>
> So for RHEL7.4 you need to run (to work properly):
>
> ( ln -sf /dev/null /etc/systemd/system/ctrl-alt-del.target or
> systemctl mask ctrl-alt-del.target)
> and
> cp -p /etc/systemd/system.conf /etc/systemd/system.conf.ori
> sed -i
> 's/#CtrlAltDelBurstAction=reboot-force/CtrlAltDelBurstAction=none/'
> /etc/systemd/system.conf
>
> RHEL7.4 release notes:
> https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/7.4_Release_Notes/index.html
>
> Thanks in advance.
>

Thanks for this! Hard to track all the nuances in the minor releases.
Made a ticket to track creation of a new rule for this:
https://github.com/OpenSCAP/scap-security-guide/issues/2277

**Comment by mpreisler** [comment]
> You can mask without using command or file for this, but you need to specify .target for it to work.
> 
> - name: disable ctrl-alt-delete
>   systemd:
>     name: ctrl-alt-del.target
>     enabled: no
>     masked: yes

We should absolutely do this. `systemd` ansible module is `stableinterface`. See https://docs.ansible.com/ansible/latest/systemd_module.html

**Pull request closed without merging**
