### PR TITLE
Check if SSH keys are present before validating file permissions

### LINKED ISSUE #2211: SSH Keys fails OVAL check if not present
See discussion in #2194 
Ran xccdf_org.ssgproject.content_rule_file_permissions_sshd_pub_key and got the following error:

chmod: cannot access '/etc/ssh/*.pub': No such file or directory
chmod: cannot access '/etc/ssh/*_key': No such file or directory

Decided to leave script be and update OVAL to not fail if file doesn't exist.

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #2211

### CODE REVIEW

**Comment by mpreisler** [comment]
NACK.

`A value of 'any_exist' means that zero or more objects defined by the description exist on the system.`

This means that if at least one ssh key has the correct permissions this whole thing will pass even if other private keys are world writable.

**Comment by redhatrises** [comment]
> Weirdly enough any_exist means 0 or more and not at least one. So nvm.

Sooo..... Ack? 🥇

**Comment by mpreisler** [comment]
So `any_exist` is more of a `if_any_exist`? For any that exist and match the object the criteria is matched. Is that correct?

**Comment by redhatrises** [comment]
That's how I read it and observed it. 

http://making-security-measurable.1364806.n2.nabble.com/check-existence-difference-between-any-exist-and-atleast-one-exists-td23719.html

**Comment by mpreisler** [comment]
This is the second time I got confused by this... Names matter specification people, they matter...

ACK

**Pull request merged**
