### PR TITLE
Add Initial RHVH profile

### PR DESCRIPTION
**Pull request by redhatrises**
- This is a very early, incomplete profile based off of the ESXi STIG.

### CODE REVIEW

**Comment by mpreisler** [comment]
We have 4 STIG profiles now, we should use inheritance more to make it maintainable. Is there any way you could extend this profile from another profile and decrease the amount of selects?

**Comment by redhatrises** [comment]
> We have 4 STIG profiles now, we should use inheritance more to make it maintainable. Is there any way you could extend this profile from another profile and decrease the amount of selects?

@mpreisler I totally agree with you. Unfortunately, the `RHV-H` profile is a very stripped down profile of all of the STIG profiles. If inheritance is used, there is going to be a lot of `selected="false"` in the profile which I don't think that that would be a good solution either. If RHT is going to submit a `RHV-H` profile to the US Govt based off of the OSPP profile, then we should use inherit from the OSPP profile. So maybe not yet? @shawndwells might be able to point us in the right direction here.

@shawndwells do you have thoughts on what some of the OS-specific checks that would be submitted in a `RHV-H` profile?

**Comment by shawndwells** [comment]
Timely PR :) Speaking with DISA this Thursday at 1pm about RHEL7 and future STIGS.

Intent for RHV-H is to use the "DoD Annex for Protection Profile for Server Virtualization," available here:

http://iasecontent.disa.mil/stigs/pdf/U_DoD_Annex_for_Protection_Profile_for_Server_Virtualization_V1-1_V1R1.pdf

The super broad approach in discussion with DISA is to inherit the RHEL7 Server STIG and tailor against the controls from Table 2-1 and refine values from Table 3-1.

**Comment by redhatrises** [comment]
@mpreisler @shawndwells Updated RHV-H profile to inherit the RHEL7 Server STIG profile.

**Comment by tonyjames** [comment]
@redhatrises As of version 4.0 Red Hat Enterprise Virtualization (RHEV) has been renamed to just Red Hat Virtualization (RHV).  With that said, the DoD PDF that @shawndwells  linked would be a good starting point.

**Comment by mpreisler** [comment]
@redhatrises Is this ready to be merged? Looks like it's the same profile as the server variant right now.

**Comment by redhatrises** [comment]
@mpreisler is is the same profile as the server variant. I done anything with looking at Table 2-1 or 3-1 as @shawndwells mentioned. However @shawndwells mentioned that the discussion with DISA was to inherit from the base RHEL7 Server STIG, that part is done. So, if you want to merge this now and we can add the tailoring from Table 2-1 or 3-1, I am fine with that.

**Comment by mpreisler** [comment]
@redhatrises OK, makes sense.

**Pull request merged**
