### PR TITLE
Initial ansible support (rhel7)

### PR DESCRIPTION
**Pull request by ybznek**
Add initial ansible remediation scripts

### CODE REVIEW

**Comment by redhatrises** [comment]
@ybznek 

```
../../shared/transforms/combineremediations.py rhel7 ansible build/shared/output/ansible    ../../shared/templates/static/ansible   templates/static/ansible output/ansible-remediations.xml
make -C ../../../shared/templates/ PREFIX_DIR=/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-el7/OpenStack/RHEL-OSP/7/build/shared ansible
make[2]: Entering directory `/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-el7/shared/templates'
make[2]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
mkdir -p /home/jenkins/workspace/scap-security-guide-pull-requests/label/node-el7/OpenStack/RHEL-OSP/7/build/shared/output/ansible
.//create_ANSIBLE_package_installed.py       .//csv/package_installed.csv
Traceback (most recent call last):
  File "../../shared/transforms/combineremediations.py", line 384, in <module>
    main()
  File "../../shared/transforms/combineremediations.py", line 344, in main
    for filename in os.listdir(fixdir):
OSError: [Errno 2] No such file or directory: 'templates/static/ansible'
make[1]: *** [output/ansible-remediations.xml] Error 1
make[1]: Leaving directory `/home/jenkins/workspace/scap-security-guide-pull-requests/label/node-el7/RHEL/7'
make: *** [rhel7] Error 2
make: *** Waiting for unfinished jobs....
```

Please fix this warning:

```make[2]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.```

as well as this failure:

```OSError: [Errno 2] No such file or directory: 'templates/static/ansible'```

**Comment by ybznek** [comment]
@redhatrises Thank you, I haven't noticed job server issue. It should be fixed now.

If test pass will pass, it should be ready to review.

**Comment by iankko** [comment]
@ybznek Looked more into this one, pls see results below.

Verified (for RHEL/7 product):
* the content of ```output/bash-remediations.xml``` is identical before and after this change (IOW all previously included RHEL-7 remediations are included once this change is applied too),
* the content of produced ```ssg-rhel7-xccdf.xml``` differs just by added ansible fix parts (see the attached / inlined ```rhel7-PR#1419-output-xccdf-diff.txt``` file): 
[rhel7-PR#1419-output-xccdf-diff.txt](https://github.com/OpenSCAP/scap-security-guide/files/444457/rhel7-PR.1419-output-xccdf-diff.txt) ,
* the bash remediations from produced RHEL-7 XCCDF still work properly.

The above is <b> OK </b>.

But I have also tried to use the ```ansible``` form of the remediation as follows:
I have used ```package_aide_installed``` as example of rule if provided ansible playbooks are working properly (commented out the bash remediation / fix part for this rule from XCCDF) -- changed the ```ssg-rhel7-xccdf.xml``` file as follows:
```
5815c5815
<             <fix system="urn:xccdf:fix:script:sh" id="package_aide_installed"><sub idref="function_package_command"/>
---
>             <!-- <fix system="urn:xccdf:fix:script:sh" id="package_aide_installed"><sub idref="function_package_command"/>
5817c5817
< </fix>
---
> </fix> -->
```
Installed ansible RPM from EPEL:
```
# rpm -q ansible
ansible-2.1.1.0-1.el7.noarch
```
and tried to perform remediation on that tailoring file (containing just ```package_aide_installed``` rule) via scap-workbench. This resulted into an ```error``` reported by oscap (looks due to some syntax issue in the playbook). The screenshot of the relevant part of the HTML report is attached below:

pr 1419_screenshot

Could you have a look @ this issue yet?

Thanks, Jan

**Comment by iankko** [comment]
Consulted the above issue with @ybznek and the conclusion being it's actually expected the provided playbooks aren't runnable by default (we are intentionally removing the header, oscap not to execute them).

Having something like (cat aide.yml):
```
# cat aide.yml 
---
- hosts: localhost
  tasks:
   - name: Ensure aide is installed
     package: name="{{item}}" state=present
     with_items:
     - aide
```

will work properly, but execute the playbook as part of the remediation. Since we would like to show just the differences against existing ansible inventory playbooks, not execute them (basically the functionality provided by ```--check``` and ```--diff```` arguments), we need to find yet a way, how to achieve this via playbook attributes. For now the removed header is a way, how to achieve playbook not to be run by accident.

Otherwise this PR looks good to me (as mentioned earlier). ACK.

**Pull request merged**
