### PR TITLE
Create & consolidate bash-remediations.xml as a separate target

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Comment by isimluk** [comment]
Seems that buid in Debian/8 directory is still broken on rhel6 platfrom: https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/332/console

[test this please]

**Comment by redhatrises** [comment]
LGTM.

**Comment by redhatrises** [comment]
@isimluk didn't get any errors from the Debian branch. I wonder if either you or jenkins has the latest master?

**Comment by isimluk** [comment]
@redhatrises thanks for merge!

I hope the jenkins purges the workspace correctly. I guess the failure has something to do with oval.config and using oval5.10 on rhel6 while building debian/8. But this definitely needs to be investigated more in depth.

**Pull request merged**
