### PR TITLE
add support for Ubuntu Xenial in SSG. Based on Debian 8

### PR DESCRIPTION
**Pull request by pthierry38**
Hi guys,

Sorry for this big merge request, but I've added the support for Ubuntu Xenial, based on the work done on Debian 8 and I didn't know how to make a little merge request for a new distribution support. I've also added the Ubuntu Trusty, but in a separated branch to simplify the integration.

I'll have some more time for SSG now that my son is no more a baby :-)

If you prefer to make this merge request smaller (in multiple, separated merges for example) don't hesitate to ask me, I'll make the modifications if needed.

Regards,

### CODE REVIEW

**Comment by shawndwells** [comment]
Content builds. Ship it. 

It's terribly impossible to attest the XCCDF and OVAL for Ubuntu in large PRs like this. There are community members who are/were interested in Ubuntu content (@gregelin , Fen / @openprivacy) that may be interested in helping develop content or reviewing future PRs.

You're largely leading the way with Ubuntu content (which is awesome!!), so until more community forms, wagering PRs will mostly be reviewed for obvious errors and build system issues.

**Comment by pthierry38** [comment]
Thank's Shawn for the merge.

I'll check with the community members if they wish to work on the Ubuntu 
support and to review the content for the Ubuntu- specific (and for 
Debian-, a large part works on both, I will update the oval files to 
support both multi_platform_ubuntu and multi_platform_debian after 
checking them).

I'll also try to recruit a friend which is interested by Ubuntu support 
in OpenSCAP.

**Comment by gregelin** [comment]
@PThierry @shawndwells What's the best way for us to assist with the review of the merge request?

@PThierry Do you have a set of instructions of installing OpenSCAP and SSG on Ubuntu? I'd be happy to test.

**Comment by PThierry** [comment]
For Ubuntu Xenial, the Ubuntu OpenSCAP package (libopenscap8, v1.2.8) 
can directly be used (, even if it has not been compiled against libdbus 
for systemd support (allowing detection of running services).
On Ubuntu Trusty, the OpenSCAP package is 1.0.9, but is able to support 
the execution of the SSG content if built on the same target.

To test the Ubuntu specific SSG content before a PR, you can:
- clone my repository for review (branch ubuntu/xenial_trusty-current)
- run
$ make ubuntu1604
(for ubuntu xenial)
$ make ubuntu1404
(for ubuntu trusty)
Beware to have all dependencies to build SSG content (mostly XML and 
XSLT tools)
you can then use one of the five profiles I've made by now (common, 
anssi_np_nt28_{minimal,average,restricted,high}) if you want to check 
XCCDF benchmarks or oval.

I will write a little note on my wiki about that.

@shawndwells Is there mechanism to "formalize" a peer-review ? Is it 
done during a PR via a post or something like this ?

**Comment by gregelin** [comment]
@pthierry thanks! Will give this a try

**Comment by shawndwells** [comment]
On 11/19/16 8:36 AM, Philippe Thierry wrote:
> For Ubuntu Xenial, the Ubuntu OpenSCAP package (libopenscap8, v1.2.8)
> can directly be used (, even if it has not been compiled against libdbus
> for systemd support (allowing detection of running services).
> On Ubuntu Trusty, the OpenSCAP package is 1.0.9, but is able to support
> the execution of the SSG content if built on the same target.
>
> To test the Ubuntu specific SSG content before a PR, you can:
> - clone my repository for review (branch ubuntu/xenial_trusty-current)
> - run
> $ make ubuntu1604
> (for ubuntu xenial)
> $ make ubuntu1404
> (for ubuntu trusty)
> Beware to have all dependencies to build SSG content (mostly XML and
> XSLT tools)
> you can then use one of the five profiles I've made by now (common,
> anssi_np_nt28_{minimal,average,restricted,high}) if you want to check
> XCCDF benchmarks or oval.
>
> I will write a little note on my wiki about that.

If you're willing, authoring a page directly on the OpenSCAP and SSG
wiki's on how to build for Ubuntu would be great. This way the
information is centralized and can easily be found from GitHub.

> @shawndwells Is there mechanism to "formalize" a peer-review ? Is it
> done during a PR via a post or something like this ?

Nothing formal aside from submitting a pull request. That process is
documented here:
https://github.com/OpenSCAP/scap-security-guide/wiki/SSG-on-GitHub-Primer

Once a PR comes in, community members chirp in with comments and someone
merges. If a PR was reviewed by a non-commit access community member,
they can bump someone with merge rights (e.g. @mpriesler, @redhatrises).

We've been moderately picky about who has merge rights. Red Hat employee
engineers do (e.g. @mpriesler, @iankko, @ybznek), as do select members
of the US Government (@jeffbank), and trusted community members like
@redhatrises. Tried to ensure a balance of commit-access beyond just
@redhat.com people.

As community content gets built we need to figure a process to give
maintainers merge access. I'll start a thread on the mailing list about
that now.

**Comment by PThierry** [comment]
Le 19/11/2016 19:30, Shawn Wells a écrit :
>
>
> On 11/19/16 8:36 AM, Philippe Thierry wrote:
> > For Ubuntu Xenial, the Ubuntu OpenSCAP package (libopenscap8, v1.2.8)
> > can directly be used (, even if it has not been compiled against libdbus
> > for systemd support (allowing detection of running services).
> > On Ubuntu Trusty, the OpenSCAP package is 1.0.9, but is able to support
> > the execution of the SSG content if built on the same target.
> >
> > To test the Ubuntu specific SSG content before a PR, you can:
> > - clone my repository for review (branch ubuntu/xenial_trusty-current)
> > - run
> > $ make ubuntu1604
> > (for ubuntu xenial)
> > $ make ubuntu1404
> > (for ubuntu trusty)
> > Beware to have all dependencies to build SSG content (mostly XML and
> > XSLT tools)
> > you can then use one of the five profiles I've made by now (common,
> > anssi_np_nt28_{minimal,average,restricted,high}) if you want to check
> > XCCDF benchmarks or oval.
> >
> > I will write a little note on my wiki about that.
>
> If you're willing, authoring a page directly on the OpenSCAP and SSG
> wiki's on how to build for Ubuntu would be great. This way the
> information is centralized and can easily be found from GitHub.
>
I've seen this morning that I can edit directly the OpenSCAP wiki. I 
Thought the edition was restricted.
Ok I will edit a page on Debian/Ubuntu specific information directly on it.


> > @shawndwells Is there mechanism to "formalize" a peer-review ? Is it
> > done during a PR via a post or something like this ?
>
> Nothing formal aside from submitting a pull request. That process is
> documented here:
> https://github.com/OpenSCAP/scap-security-guide/wiki/SSG-on-GitHub-Primer
>
> Once a PR comes in, community members chirp in with comments and someone
> merges. If a PR was reviewed by a non-commit access community member,
> they can bump someone with merge rights (e.g. @mpriesler, @redhatrises).
Ok. we can use this mechanism by now.

>
> We've been moderately picky about who has merge rights. Red Hat employee
> engineers do (e.g. @mpriesler, @iankko, @ybznek), as do select members
> of the US Government (@jeffbank), and trusted community members like
> @redhatrises. Tried to ensure a balance of commit-access beyond just
> @redhat.com people.
>
> As community content gets built we need to figure a process to give
> maintainers merge access. I'll start a thread on the mailing list about
> that now.
Ok thanks. having worked on various integration projects I understand 
how difficult is it to keep them clean when too many people have the 
capacity to merge.

**Pull request merged**
