### PR TITLE
[BugFix] [Infrastructure] Various "cpe_generate.py" shared/ transform hardenings

### PR DESCRIPTION
**Pull request by iankko**
This changeset is performing the following:
* patch https://github.com/OpenSCAP/scap-security-guide/commit/887bd51e12d5a3f9eea113f058b6aa863653045a is hardening the ```cpe_generate.py``` shared transformation to actually check if OVAL checks, referenced from CPE OVAL file, actually exist. This helps to detect issues like:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/pull/913#issuecomment-164571360
&nbsp; &nbsp; [2] https://jenkins.open-scap.org/job/scap-security-guide/470/console
&nbsp; &nbsp; [3] https://jenkins.open-scap.org/job/scap-security-guide-nightly-oval510-zip/110/console

* patch https://github.com/OpenSCAP/scap-security-guide/commit/90e2cf221119e9f91ee663907d3ef3d1779187c1 is fixing mistyped OVAL check name in the ```Debian/8/input/oval/platform/debian8-cpe-dictionary.xml``` path (in the future this issue should be caught by the previous patch),

* patch https://github.com/OpenSCAP/scap-security-guide/commit/9d627add60490300e263d4925036f53241aa79c0 is hardening the ```cpe_generate.py``` transform even more (to actually check, if all OVAL definitions defined in OVAL checks referenced from OVAL CPE checks are already defined in ```unlinked-$(PROD)-oval.xml``` files provided as input to the ```cpe_generate.py``` transforms. This use case need to be caught by this sanity check, because otherwise we risk the generated ```$(ID)-$(PROD)-cpe-oval.xml``` file will be invalid (oscap will print out error message about missing child elements like can be seen e.g. in:
&nbsp; &nbsp; https://github.com/OpenSCAP/scap-security-guide/pull/913#issuecomment-164571360

and finally patch:
* https://github.com/OpenSCAP/scap-security-guide/commit/196da55c4a292e1c6998ecd52a07d52d994b99ce is fixiing the ```<platform>``` tag for ```installed_OS_is_debian8``` OVAL check in the way the OVAL definition would be included into ```unlinked-debian8-oval.xml``` (and subsequently into ```ssg-debian8-cpe-oval.xml``` file => so we don't generate invalid ```ssg-debian8-cpe-oval.xml``` file, and don't raise those "missing child elements" openscap error).

Testing report:

--

All of the above changes have been tested in the following scenarios:
* working product (e.g. ```RHEL/6```) and on
* not-working product:
  * either OVAL def referenced from CPE OVAL has mistyped name, or
  * is completely missing due to improper ```<platform>``` tags settings)

and AFAICT from testing it's working fine (raises no error for the first case, raises corresponding error message for the subsequent two scenarios).

Please review.

Thank you, Jan.

Fixes issues: 
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/pull/913#issuecomment-164571360
&nbsp; &nbsp; [2] https://jenkins.open-scap.org/job/scap-security-guide/470/console
&nbsp; &nbsp; [3] https://jenkins.open-scap.org/job/scap-security-guide-nightly-oval510-zip/110/console

### CODE REVIEW

**Comment by iankko** [comment]
Add the Jenkins failure:
```
Error: Can't locate "installed_OS_is_osp" OVAL file in the                 
	list of OVAL checks for this product! Exiting..
```
It's actually showing the hardening is working. Looks Openstack content has been before referencing some unexisting OVAL. Will have a look at that yet.

**Comment by iankko** [comment]
Once the Jenkins on last commit from this changeset finished, review of this one is appreciated. Since it should bring the following Jenkins job:
&nbsp; &nbsp; [1] https://jenkins.open-scap.org/job/scap-security-guide-nightly-oval510-zip/112/console

back to passing state.

**Comment by isimluk** [comment]
It fails with
```
cd output; ../../../shared/utils/verify-references.py --ovaldefs-unused ssg-debian8-xccdf.xml
OVAL Check is not referenced by XCCDF: oval:ssg:def:138
```

**Comment by iankko** [comment]
Yeah, noticed. Will have a look yet, why.

**Comment by iankko** [comment]
[re-test this please]

**Comment by iankko** [comment]
I have wiped out the workspace on the slave (el6) testing this PR (looks the workspace contained something from previous PRs). I can't reproduce that failure on my vanilla RHEL-6.7 guest.

**Pull request merged**
