### PR TITLE
[Enhancement][Bugfix][RHEL/7] add additional OVAL and remediation scripts

### LINKED ISSUE #692: Remediation for RHEL7 require_singleuser_auth

### LINKED ISSUE #693: OVAL for RHEL7 disable_interactive_boot

### LINKED ISSUE #694: Remediation for RHEL7 disable_interactive_boot

### LINKED ISSUE #728: OVAL for RHEL7 no_rsh_trust_files

### LINKED ISSUE #729: Remediation for RHEL7 no_rsh_trust_files

### LINKED ISSUE #733: Remediation for RHEL7 uninstall_talk-server

### PR DESCRIPTION
**Pull request by redhatrises**
- Add no_rsh_trust_files and disable_interactive_boot OVAL
- Add remediations scripts for RHEL/7
- Fix typo in obsolete.xml
- Resolves #733
- Resolves #729
- Resolves #728
- Resolves #694
- Resolves #693
- Resolves #692

### CODE REVIEW

**Comment by iankko** [comment]
@redhatrises 

Can you update this PR to:
* fix the conflicts with the current ```master```, and
* drop the symlinks for the touched remediation scripts? (and replace them with the new ```# platform = ``` tag where appropriate)

Thanks, Jan.

**Comment by redhatrises** [comment]
Thanks @iankko. I thought about that yesterday but didn't get to it. Jenkins build is testing now.

**Comment by redhatrises** [comment]
- Fixes #699 as well

**Comment by redhatrises** [comment]
Bump for review when possible.

**Comment by mpreisler** [comment]
Sorry about the delay.

Conflicts have been fixed, symlinks have been removed, remediation scripts were moved to shared and tagged appropriately.

LGTM

**Pull request merged**
