### PR TITLE
Move example profile ("CS2") from RHEL6 to docs

### PR DESCRIPTION
**Pull request by cipherboy**
Perhaps the branch name is misleading, but we remove the CS2 (**NOT C2S**) example profile from `rhel6` and add it to the developer documentation. 

This prevents it from being built every time we build SSG or the `rhel6` product.

### CODE REVIEW

**Comment by redhatrises** [comment]
Are we still using guide.xslt?

**Comment by shawndwells** [comment]
CS2 is a baseline for a very specific set of customers. Didn't realize the profile description was so vague.

Hey @jeffblank, can we be more... verbose... about the profile description? Looks like it was never changed to reflect attribution.

**Comment by redhatrises** [comment]
@shawndwells are you sure that it is CS2 and not C2S?

**Comment by shawndwells** [comment]
On 6/28/18 12:58 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> are you sure that it is 
> CS2 and not C2S?

Yah. C2S is the CIA's public cloud image, CS2 is... some other agency... 
that apparently was never publicly attributed but Jeff and I spoke 
onstage at Summit about several times.

**Comment by cipherboy** [comment]
I'm marking this as closed to prevent merging. Pending feedback from @jeffblank, we can add a more suitable description and title.

Perhaps we should also consider porting this profile to RHEL7.

**Pull request closed without merging**
