### PR TITLE
change to also check inside of /etc/security/limits.d to verify core …

### PR DESCRIPTION
**Pull request by rybal06**

### CODE REVIEW

**Comment by redhatrises** [comment]
Thanks for the PR @rybal06!

A bit more work needs to be done in this PR to handle the case where `/etc/security/limits.conf` and `/etc/security/limits.d` are configured at the same time. See `accounts_max_concurrent_login_sessions` for an example of what I am talking about as well as https://access.redhat.com/solutions/199993 for the global issue.

**Comment by redhatrises** [comment]
@rybal06 can you also amend your commit to add the following to link to the ticket you opened:

`- Fixes #2249`

**Comment by rybal06** [comment]
Tested cases where it was configured in /etc/security/limits.conf, /etc/security/limits.d, and where it was configured in both but had a bad value in /etc/security/limits.conf.  Seems it works under those circumstances.

**Comment by mpreisler** [comment]
@rybal06 , thank you for your contribution.

ACK.

**Pull request merged**
