### PR TITLE
Removed package_*_{installed,removed} from shared that are templated

### PR DESCRIPTION
**Pull request by mpreisler**
These files are not needed in the git repo because these checks are
templated.

### CODE REVIEW

**Comment by mpreisler** [comment]
I will also template the rest of them to get rid of all bash and oval files in shared that can be templated.

**Comment by mpreisler** [comment]
> I will also template the rest of them to get rid of all bash and oval files in shared that can be templated.

DONE

**Comment by matejak** [comment]
Great cleanup work! However, I have noticed that we don't have any tests for installed package. Although I have verified that this PR works, it would be nice to have a test as part of the SSG test suite. Would you like to add one?

**Comment by mpreisler** [comment]
> Would you like to add one?

not particularly

**Comment by matejak** [comment]
OK, that can be done later.

**Pull request merged**
