### PR TITLE
Sample fix for Issue #932

### PR DESCRIPTION
**Pull request by GautamSatish**
This patch fixes the problem described in issue #932 for a single rule.

The changes include updating the OVAL check and the remediation script to start using the XCCDF:value field as well as documentation changes in comments and the rule name itself to make them more appropriate.

Since there are multiple changes, including the name of the rule, I thought it would be appropriate to send a sample for review before opening a pull request for the entire rule set.

### CODE REVIEW

**Comment by iankko** [comment]
[test this please]

**Comment by GautamSatish** [comment]
I have built and tested the proposed changes on an RHEL 6.5 system. Used the "refine-value" tag to verify that OVAL and the "fix" script perform the correct evaluation and remediation for both "enabled" and "disabled" values.

@iankko I didn't find any test-suite details on the wiki. Do I need to pass some testing criteria? 

Thank you.

**Comment by iankko** [comment]
@GautamSatish 
> @iankko I didn't find any test-suite details on the wiki.

Yeah, sorry, They need to be clarified officially. Will file a ticket for that.

> Do I need to pass some testing criteria? 

Yes. Namely:
* the proposed change is expected to work for the product(s) it applies against / to (like changing the RHEL/6 content, it's expected the benchmark / SRPM / RPM to build successfully for that product, and the modified feature in question to work properly -- by building the benchmark & testing the rule),
* besides the above the change should not break the following:
 * ```make validate``` target for ```RHEL/6`` product (when run with both pre-oval-5.11 and post-oval-5.11 versions), where pre-oval-5.11 == openscap < 1.2.4, post-oval-5.11 == openscap >= 1.2.4,
* ```make validate``` target for ```Fedora``` product (when run in both scenarios like in the previous item).

I will file a ticket this expectations to be expressed on the wiki.

**Comment by isimluk** [comment]
Gautam, I think that when iankko said *test this please* it was an instruction for our jenkins. You can read about our jenkins deployment at https://blog-zbynek.rhcloud.com/2015/10/12/contribution-to-openscap-with-jenkins/

When contributing, please run `make jenkins` locally before you create the PR. The jenkins will run this command anyway. :-)

**Comment by iankko** [comment]
[re-test this please]

**Comment by iankko** [comment]
And once again. [test this please]

**Comment by iankko** [comment]
@isimluk 
> Gautam, I think that when iankko said test this please it was an instruction for our jenkins. You can read about our jenkins deployment at https://blog-zbynek.rhcloud.com/2015/10/12/contribution-to-openscap-with-jenkins/

Definitely!

@GautamSatish the above command wasn't intended at you that you should test it. But rather instruction for our Jenkins infrastructure to start testing of this PR. Sorry, if my terse formulation sounded in the wrong (ambiguous) way.

@isimluk Thanks for clarifying this!

**Comment by GautamSatish** [comment]
Hello folks,
Thank you for clarifying this. I will ensure that I run Jenkins and validate locally henceforth.

@isimluk , I have posted this on the mailing list as well, but just in case, another point that wanted to check with you was on the changes I need to make on the documentation. The rule that I modified for the sample pull request, "sysctl_net_ipv4_conf_all_accept_source_route" has a title "Disable Kernel Parameter for Accepting Source-Routed Packets for All Interfaces". When we are providing the option to enable or disable the parameter to the user, the title, description, rationale and OCIL content become inaccurate (and confusing) because they all refer to just disabling the parameter.

I changed the rule name to "Configure Kernel Parameter for Accepting Source-Routed Packets for All Interfaces" to make it slightly unambiguous leaving all the other content intact. I later realized that this is probably not a good thing to do either because there might be user tailored profiles which use the original rule name and these would now break. Should I just leave all the XCCDF content untouched and leave it at that?

**Comment by isimluk** [comment]
Sorry Gautam, for keeping this unresolved so long. I hope I'll find some time to look into this over the weekend.

**Comment by isimluk** [comment]
Gautam, the changes you propose seems sensible to me. Further, I appreciate that you have noticed the need for documentation change. I think the word 'Configure' is much more fitting here.

I know this pr is just a sample of the final solution. Nevertheless, please be aware that we should not merge changes editing the autogenerated oval without modification of the related template.

**Comment by GautamSatish** [comment]
Closing this PR. Will re-open with the documentation changes and appropriate changes to the correct template file.

Thank you!

**Pull request closed without merging**
