### PR TITLE
STIG updates for rhel7/set_password_hashing_algorithm_systemauth

### PR DESCRIPTION
**Pull request by shawndwells**
- add to stig profile
- rationale and policy ref updates

image

### CODE REVIEW

**Comment by redhatrises** [comment]
[retest this please]

**Comment by jeffblank** [comment]
Why is this being added?  The default is good.  And nobody would ever change it.  I suggest removing it, and simply state that the product is good out-of-the-box.

**Comment by shawndwells** [comment]
@jeffblank - Mandated by DISA =/ Rule is isolated just to DISA STIG profile

**Comment by shawndwells** [comment]
Screwed up the branch rebase - closing & reopening

**Pull request closed without merging**
