### PR TITLE
Fix typo in auditd OVAL files

### PR DESCRIPTION
**Pull request by cakernstock**
#### Description:

- Fix one typo located in three files for shared/OVAL: external variable comment contains the word "settting" which should be "setting".

#### Rationale:

- This is a cosmetic change, but a correction nonetheless.

### CODE REVIEW

**Comment by redhatrises** [comment]
@openscap-ci add to whitelist

**Comment by redhatrises** [comment]
@cakernstock can you remove commit 7403e38. It does not belong in this PR.

**Comment by cakernstock** [comment]
@redhatrises Ok I will do that. Should I close this one and open a new pull request for that?

**Comment by redhatrises** [comment]
@cakernstock you can do a `git rebase -i` or open a new pull request.

**Pull request closed without merging**
