### PR TITLE
Added Firefox SCAP content

### PR DESCRIPTION
**Pull request by thenefield**
Added SCAP content aligned with the DISA STIG requirements for Firefox.

### CODE REVIEW

**Comment by shawndwells** [comment]
Same comments from Webmin & java - kind nack while misc. RHEL artifacts are cleaned out. Please squash your commits to make it easier to review once cleaned up :)

**Comment by shawndwells** [comment]
hey @jeffblank, do you have people who'd be interested in reviewing this?

**Comment by redhatrises** [comment]
@shawndwells could this be put under the RHEL os content like the Apache and Bind settings are and maybe a separate profile is created for just scanning for firefox?

**Comment by shawndwells** [comment]
On 2/25/15 2:29 PM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> could this be put under 
> the RHEL os content like the Apache and Bind settings are and maybe a 
> separate profile is created for just scanning for firefox?


I lean towards having Firefox content become it's own stream because it 
lends itself to supporting future patches to expand the content to 
Windows. Duplicating the content for RHEL{5 6 7 future} would be 
cumbersome as well.

**Comment by shawndwells** [comment]
OCIL tags are set to ````<ocil clause="r">```` -- better to leave blank if no OCIL created yet. Please clean these up for merge.

**Comment by shawndwells** [comment]
````make clean``` contains errors:
````
$ make clean
/bin/sh: transforms/oscapsupportssvg.py: cannot execute binary file
````

you can copy in that file from RHEL/6/transforms if needed

**Comment by shawndwells** [comment]
the CPE settings generate notapplicable results:
````
$ oscap xccdf eval --profile firefox-stig output/ssg-firefox-xccdf.xml 
Title   Firefox Preferences-Addons plugin updates
Rule    firefox_preferences-addons_plugin_updates
Ident   CCE-
Ident   DTBF090
Result  notapplicable

Title   FireFox Preferences - Autofill forms
Rule    firefox_preferences-autofill_forms
Ident   CCE-
Ident   DTBF140
Result  notapplicable

Title   FireFox Preferences - Autofill passwords
Rule    firefox_preferences-autofill_passwords
Ident   CCE-
Ident   DTBF150
Result  notapplicable

Title   Firefox Preferences-Auto-update of Firefox
Rule    firefox_preferences-auto-update_of_firefox
Ident   CCE-
Ident   DTBF080
Result  notapplicable

````

update the CPE listing in input/guide.xml (or take it out)

**Comment by shawndwells** [comment]
the lack of CCEs causes empty Ident tags in the results, e.g:
````
Title   Non-secure Page Warning
Rule    non-secure_page_warning
Ident   CCE-
Ident   DTBF130
Result  fail
````

remove the CCE tag, e.g.:
````find . -type f -print0 | xargs -0 sed -i 's/ident.*stig/ident stig/g'````

**Comment by shawndwells** [comment]
since the firefox content will be undergoing some churn, copy in the RHEL/5/DISCLAIMER (+minor tweaks to reflect Firefox, not RHEL5)...

````
$ pwd
/var/www/html/gh/upstreams/scap-security-guide/Firefox
$ cp ../RHEL/5/DISCLAIMER .
````

**Comment by shawndwells** [comment]
@thenefield just a few small tweaks and this will be ready to merge! great work! let me know if the comments above make sense, happy to help.

**Comment by thenefield** [comment]
Regarding the CPE settings, you need to explicitly call out its CPE dictionary '--cpe /usr/share/xml/scap/ssg/content/ssg-firefox-cpe-dictionary.xml' for it to pull in the CPE checks for firefox. When this is not explicitly stated in the oscap command, it defaults to the CPEs provided within the OpenSCAP package, which will not include Firefox CPE checks.

I will incorporate the other changes, as suggested. Thanks!

**Comment by thenefield** [comment]
Fixes are now merged. I have tested that they build, scan, and remediate as expected. Here is the command I used to test:

oscap xccdf eval --remediate --profile firefox-stig --cpe output/ssg-firefox-cpe-dictionary.xml  output/ssg-firefox-xccdf.xml

Title   Firefox Preferences-Addons plugin updates
Rule    firefox_preferences-addons_plugin_updates
Ident   DTBF090
Result  fail

Title   FireFox Preferences - Autofill forms
Rule    firefox_preferences-autofill_forms
Ident   DTBF140
Result  fail

Title   FireFox Preferences - Autofill passwords
Rule    firefox_preferences-autofill_passwords
Ident   DTBF150
Result  fail

Title   Firefox Preferences-Auto-update of Firefox
Rule    firefox_preferences-auto-update_of_firefox
Ident   DTBF080
Result  fail

Title   FireFox Preferences - Cookies
Rule    firefox_preferences-cookies
Ident   DTBF170
Result  fail

Title   Firefox Preferences - Lock settings
Rule    firefox_preferences-lock_settings
Ident   DTBF070
Result  fail

Title   FireFox Preferences - Open Confirmation
Rule    firefox_preferences-open_confirmation
Ident   DTBF110
Result  fail

Title   FireFox Preferences - Password store
Rule    firefox_preferences-password_store
Ident   DTBF160
Result  fail

Title   Firefox Preferences -Search update
Rule    firefox_preferences-search_update
Ident   DTBF085
Result  fail

Title   FireFox Preferences - Shell Protocol
Rule    firefox_preferences-shell_protocol
Ident   DTBF105
Result  fail

Title   Firefox Preferences - SSL 2.0 Protocol
Rule    firefox_preferences-SSL_2.0_protocol
Ident   DTBF010
Result  fail

Title   Firefox Preferences - SSL Protocols TLS
Rule    firefox_preferences-SSL_protocols_TLS
Ident   DTBF030
Result  fail

Title   FireFox Preferences - Verification
Rule    firefox_preferences-verification
Ident   DTBF050
Result  fail

Title   FireFox Preferences-Use of SSL Version 3
Rule    firefox_preferences-use_of_ssl_version_3
Ident   DTBF020
Result  fail

Title   Home Page
Rule    home_page
Ident   DTBF017
Result  fail

Title   Installed version of FireFox not supported
Rule    installed_version_of_firefox_not_supported
Ident   DTBF003
Result  pass

Title   JavaScript can change the status bar text
Rule    javaScript_can_change_the_status_bar_text
Ident   DTBF185
Result  fail

Title   JavaScript Context Menus
Rule    javaScript_context_menus
Ident   DTBF183
Result  fail

Title   JavaScript hiding or changing status bar
Rule    javaScript_hiding_or_changing_status_bar
Ident   DTBF184
Result  fail

Title   JavaScript move or resize windows
Rule    javaScript_move_or_resize_windows
Ident   DTBF181
Result  fail

Title   JavaScript raise or lower windows
Rule    javaScript_raise_or_lower_windows
Ident   DTBF182
Result  fail

Title   Non-secure Page Warning
Rule    non-secure_page_warning
Ident   DTBF130
Result  fail

Title   Pop-up windows
Rule    pop-up_windows
Ident   DTBF180
Result  fail

Title   Firefox Preferences - auto-download actions
Rule    firefox_preferences-auto-download_actions
Ident   DTBF100
Result  fail


 --- Starting Remediation ---
Title   Firefox Preferences-Addons plugin updates
Rule    firefox_preferences-addons_plugin_updates
Ident   DTBF090
Result  fixed

Title   FireFox Preferences - Autofill forms
Rule    firefox_preferences-autofill_forms
Ident   DTBF140
Result  fixed

Title   FireFox Preferences - Autofill passwords
Rule    firefox_preferences-autofill_passwords
Ident   DTBF150
Result  fixed

Title   Firefox Preferences-Auto-update of Firefox
Rule    firefox_preferences-auto-update_of_firefox
Ident   DTBF080
Result  fixed

Title   FireFox Preferences - Cookies
Rule    firefox_preferences-cookies
Ident   DTBF170
Result  fixed

Title   Firefox Preferences - Lock settings
Rule    firefox_preferences-lock_settings
Ident   DTBF070
Result  fixed

Title   FireFox Preferences - Open Confirmation
Rule    firefox_preferences-open_confirmation
Ident   DTBF110
Result  fixed

Title   FireFox Preferences - Password store
Rule    firefox_preferences-password_store
Ident   DTBF160
Result  fixed

Title   Firefox Preferences -Search update
Rule    firefox_preferences-search_update
Ident   DTBF085
Result  fixed

Title   FireFox Preferences - Shell Protocol
Rule    firefox_preferences-shell_protocol
Ident   DTBF105
Result  fixed

Title   Firefox Preferences - SSL 2.0 Protocol
Rule    firefox_preferences-SSL_2.0_protocol
Ident   DTBF010
Result  fixed

Title   Firefox Preferences - SSL Protocols TLS
Rule    firefox_preferences-SSL_protocols_TLS
Ident   DTBF030
Result  fixed

Title   FireFox Preferences - Verification
Rule    firefox_preferences-verification
Ident   DTBF050
Result  fixed

Title   FireFox Preferences-Use of SSL Version 3
Rule    firefox_preferences-use_of_ssl_version_3
Ident   DTBF020
Result  fixed

Title   Home Page
Rule    home_page
Ident   DTBF017
Result  fixed

Title   JavaScript can change the status bar text
Rule    javaScript_can_change_the_status_bar_text
Ident   DTBF185
Result  fixed

Title   JavaScript Context Menus
Rule    javaScript_context_menus
Ident   DTBF183
Result  fixed

Title   JavaScript hiding or changing status bar
Rule    javaScript_hiding_or_changing_status_bar
Ident   DTBF184
Result  fixed

Title   JavaScript move or resize windows
Rule    javaScript_move_or_resize_windows
Ident   DTBF181
Result  fixed

Title   JavaScript raise or lower windows
Rule    javaScript_raise_or_lower_windows
Ident   DTBF182
Result  fixed

Title   Non-secure Page Warning
Rule    non-secure_page_warning
Ident   DTBF130
Result  fixed

Title   Pop-up windows
Rule    pop-up_windows
Ident   DTBF180
Result  fixed

Title   Firefox Preferences - auto-download actions
Rule    firefox_preferences-auto-download_actions
Ident   DTBF100
Result  fixed

**Comment by thenefield** [comment]
Also based on the above output, added the change to preface each STIG ID with "DISA FSO ".

**Comment by thenefield** [comment]
One other thing I will mention. The current Firefox STIG has not been updated to require SSLv3 to be disabled. It currently allows it to be set on or off. For the purposes of Poodle, that check for "DTBF020" has been set to require SSLv3 to be disabled.

**Comment by shawndwells** [comment]
tested ````make```` and ran a scan:

````
# oscap xccdf eval --remediate --profile firefox-stig --cpe output/ssg-firefox-cpe-dictionary.xml output/ssg-firefox-xccdf.xml
Title   Firefox Preferences-Addons plugin updates
Rule    firefox_preferences-addons_plugin_updates
Ident   DISA FSO DTBF090
Result  fail

Title   FireFox Preferences - Autofill forms
Rule    firefox_preferences-autofill_forms
Ident   DISA FSO DTBF140
Result  fail

Title   FireFox Preferences - Autofill passwords
Rule    firefox_preferences-autofill_passwords
Ident   DISA FSO DTBF150
Result  fail

Title   Firefox Preferences-Auto-update of Firefox
Rule    firefox_preferences-auto-update_of_firefox
Ident   DISA FSO DTBF080
Result  fail

Title   FireFox Preferences - Cookies
Rule    firefox_preferences-cookies
Ident   DISA FSO DTBF170
Result  fail

Title   Firefox Preferences - Lock settings
Rule    firefox_preferences-lock_settings
Ident   DISA FSO DTBF070
Result  fail

Title   FireFox Preferences - Open Confirmation
Rule    firefox_preferences-open_confirmation
Ident   DISA FSO DTBF110
Result  fail

Title   FireFox Preferences - Password store
Rule    firefox_preferences-password_store
Ident   DISA FSO DTBF160
Result  fail

Title   Firefox Preferences -Search update
Rule    firefox_preferences-search_update
Ident   DISA FSO DTBF085
Result  fail

Title   FireFox Preferences - Shell Protocol
Rule    firefox_preferences-shell_protocol
Ident   DISA FSO DTBF105
Result  fail

Title   Firefox Preferences - SSL 2.0 Protocol
Rule    firefox_preferences-SSL_2.0_protocol
Ident   DISA FSO DTBF010
Result  fail

Title   Firefox Preferences - SSL Protocols TLS
Rule    firefox_preferences-SSL_protocols_TLS
Ident   DISA FSO DTBF030
Result  fail

Title   FireFox Preferences - Verification
Rule    firefox_preferences-verification
Ident   DISA FSO DTBF050
Result  fail

Title   FireFox Preferences-Use of SSL Version 3
Rule    firefox_preferences-use_of_ssl_version_3
Ident   DISA FSO DTBF020
Result  fail

Title   Home Page
Rule    home_page
Ident   DISA FSO DTBF017
Result  fail

Title   Installed version of FireFox not supported
Rule    installed_version_of_firefox_not_supported
Ident   DISA FSO DTBF003
Result  pass

Title   JavaScript can change the status bar text
Rule    javaScript_can_change_the_status_bar_text
Ident   DISA FSO DTBF185
Result  fail

Title   JavaScript Context Menus
Rule    javaScript_context_menus
Ident   DISA FSO DTBF183
Result  fail

Title   JavaScript hiding or changing status bar
Rule    javaScript_hiding_or_changing_status_bar
Ident   DISA FSO DTBF184
Result  fail

Title   JavaScript move or resize windows
Rule    javaScript_move_or_resize_windows
Ident   DISA FSO DTBF181
Result  fail

Title   JavaScript raise or lower windows
Rule    javaScript_raise_or_lower_windows
Ident   DISA FSO DTBF182
Result  fail

Title   Non-secure Page Warning
Rule    non-secure_page_warning
Ident   DISA FSO DTBF130
Result  fail

Title   Pop-up windows
Rule    pop-up_windows
Ident   DISA FSO DTBF180
Result  fail

Title   Firefox Preferences - auto-download actions
Rule    firefox_preferences-auto-download_actions
Ident   DISA FSO DTBF100
Result  fail


 --- Starting Remediation ---
Title   Firefox Preferences-Addons plugin updates
Rule    firefox_preferences-addons_plugin_updates
Ident   DISA FSO DTBF090
Result  fixed

Title   FireFox Preferences - Autofill forms
Rule    firefox_preferences-autofill_forms
Ident   DISA FSO DTBF140
Result  fixed

Title   FireFox Preferences - Autofill passwords
Rule    firefox_preferences-autofill_passwords
Ident   DISA FSO DTBF150
Result  fixed

Title   Firefox Preferences-Auto-update of Firefox
Rule    firefox_preferences-auto-update_of_firefox
Ident   DISA FSO DTBF080
Result  fixed

Title   FireFox Preferences - Cookies
Rule    firefox_preferences-cookies
Ident   DISA FSO DTBF170
Result  fixed

Title   Firefox Preferences - Lock settings
Rule    firefox_preferences-lock_settings
Ident   DISA FSO DTBF070
Result  fixed

Title   FireFox Preferences - Open Confirmation
Rule    firefox_preferences-open_confirmation
Ident   DISA FSO DTBF110
Result  fixed

Title   FireFox Preferences - Password store
Rule    firefox_preferences-password_store
Ident   DISA FSO DTBF160
Result  fixed

Title   Firefox Preferences -Search update
Rule    firefox_preferences-search_update
Ident   DISA FSO DTBF085
Result  fixed

Title   FireFox Preferences - Shell Protocol
Rule    firefox_preferences-shell_protocol
Ident   DISA FSO DTBF105
Result  fixed

Title   Firefox Preferences - SSL 2.0 Protocol
Rule    firefox_preferences-SSL_2.0_protocol
Ident   DISA FSO DTBF010
Result  fixed

Title   Firefox Preferences - SSL Protocols TLS
Rule    firefox_preferences-SSL_protocols_TLS
Ident   DISA FSO DTBF030
Result  fixed

Title   FireFox Preferences - Verification
Rule    firefox_preferences-verification
Ident   DISA FSO DTBF050
Result  fixed

Title   FireFox Preferences-Use of SSL Version 3
Rule    firefox_preferences-use_of_ssl_version_3
Ident   DISA FSO DTBF020
Result  fixed

Title   Home Page
Rule    home_page
Ident   DISA FSO DTBF017
Result  fixed

Title   JavaScript can change the status bar text
Rule    javaScript_can_change_the_status_bar_text
Ident   DISA FSO DTBF185
Result  fixed

Title   JavaScript Context Menus
Rule    javaScript_context_menus
Ident   DISA FSO DTBF183
Result  fixed

Title   JavaScript hiding or changing status bar
Rule    javaScript_hiding_or_changing_status_bar
Ident   DISA FSO DTBF184
Result  fixed

Title   JavaScript move or resize windows
Rule    javaScript_move_or_resize_windows
Ident   DISA FSO DTBF181
Result  fixed

Title   JavaScript raise or lower windows
Rule    javaScript_raise_or_lower_windows
Ident   DISA FSO DTBF182
Result  fixed

Title   Non-secure Page Warning
Rule    non-secure_page_warning
Ident   DISA FSO DTBF130
Result  fixed

Title   Pop-up windows
Rule    pop-up_windows
Ident   DISA FSO DTBF180
Result  fixed

Title   Firefox Preferences - auto-download actions
Rule    firefox_preferences-auto-download_actions
Ident   DISA FSO DTBF100
Result  fixed
````

**Comment by shawndwells** [comment]
- make validate was failing, patched via 2045f21

**Comment by shawndwells** [comment]
inconsistencies between FireFox vs Firefox:

````
$ grep -rn "FireFox" *
auxiliary/stig_overlay.xml:25:		<title>FireFox is configured to ask which certificate to present to a web site when a certificate is required.</title>
auxiliary/stig_overlay.xml:49:		<title>Network shell protocol is enabled in FireFox.</title>
auxiliary/stig_overlay.xml:57:		<title>FireFox plug-in for ActiveX controls is installed.</title>
auxiliary/stig_overlay.xml:73:		<title>FireFox is configured to use a password store with or without a master password.</title>
auxiliary/stig_overlay.xml:81:		<title>FireFox is not configured to block pop-up windows.</title>
</title>y/stig_overlay.xml:85:		<title>FireFox is configured to allow JavaScript to move or resize windows.
checks/firefox_preferences-autofill_forms.xml:4:      <title>FireFox Preferences - Autofill forms</title>
checks/firefox_preferences-password_store.xml:4:      <title>FireFox Preferences - Password store</title>
checks/firefox_preferences-shell_protocol.xml:4:      <title>FireFox Preferences - Shell Protocol</title>
checks/firefox_preference-use_of_ssl_version_3.xml:4:  	<title>FireFox Preferences-Use of SSL Version 3</title>
checks/firefox_preferences-autofill_passwords.xml:4:      <title>FireFox Preferences - Autofill passwords</title>
checks/firefox_preferences-verification.xml:5:      <title>FireFox Preferences - Verification</title>
checks/firefox_preferences-auto-download_actions.xml:4:     <title>FireFox Preferences-auto-download actions</title>
checks/firefox_preferences–cookies.xml:4:      <title>FireFox Preferences - Cookies</title>
checks/firefox_preferences-open_confirmation.xml:4:      <title>FireFox Preferences - Open Confirmation</title>
checks/installed_version_of_firefox_not_supported.xml:4:      <title> Installed version of FireFox not supported</title>
system/settings.xml:36:<title>FireFox Preferences - Autofill forms</title>
system/settings.xml:51:<title>FireFox Preferences - Autofill passwords</title>
system/settings.xml:80:<title>FireFox Preferences - Cookies</title>
system/settings.xml:108:<title>FireFox Preferences - Open Confirmation</title>
system/settings.xml:122:<title>FireFox Preferences - Password store</title>
system/settings.xml:150:<title>FireFox Preferences - Shell Protocol</title>
system/settings.xml:192:<title>FireFox Preferences - Verification</title>
system/settings.xml:206:<title>FireFox Preferences-Use of SSL Version 3</title>
system/settings.xml:234:<title>Installed version of FireFox not supported</title>
````

changed to "Firefox" to match Mozilla, but left auxiliary/stig_overlay alone:

````
$ sed -i 's/FireFox/Firefox/g' checks/* system/settings.xml 
sed: couldn't edit checks/platform: not a regular file
$ sed -i 's/FireFox/Firefox/g' system/settings.xml 
[shawnw@ssg-rhel6-devbox input]$ grep -rn "FireFox" *
auxiliary/stig_overlay.xml:25:		<title>FireFox is configured to ask which certificate to present to a web site when a certificate is required.</title>
auxiliary/stig_overlay.xml:49:		<title>Network shell protocol is enabled in FireFox.</title>
auxiliary/stig_overlay.xml:57:		<title>FireFox plug-in for ActiveX controls is installed.</title>
auxiliary/stig_overlay.xml:73:		<title>FireFox is configured to use a password store with or without a master password.</title>
auxiliary/stig_overlay.xml:81:		<title>FireFox is not configured to block pop-up windows.</title>
</title>y/stig_overlay.xml:85:		<title>FireFox is configured to allow JavaScript to move or resize windows.
````

patched via ff94ffa

**Comment by shawndwells** [comment]
there were still references to the OS SRG:
````
$ grep -rin disa-os-srg-v1r1 *
Makefile:71:		$(TRANS)/table-srgmap.xslt $(REFS)/disa-os-srg-v1r1.xml
Makefile:73:		$(TRANS)/table-srgmap.xslt $(REFS)/disa-os-srg-v1r1.xml
transforms/xccdf2table-profileccirefs.xslt:7:<xsl:variable name="os_srg" select="document('../../../shared/references/disa-os-srg-v1r1.xml')/cdf:Benchmark" />
transforms/xccdf-addrefs.xslt:10:<xsl:variable name="os_srg" select="document('../references/disa-os-srg-v1r1.xml')/cdf:Benchmark" />
````

this is relatively minor and can be patched later

**Comment by shawndwells** [comment]
@thenefield, merged the Firefox content. Thank you!

There are still a few things which can be fixed incrementally:
- Spacing around the "-" in XCCDF rules titles
- Various tables cite OS SRG

What's the best way for you to track such things? Opening issue trackers and assigning them to you? Mentioning on the mailing list?

**Comment by thenefield** [comment]
Thanks for the feedback! I am still new to github, so I am not quite sure
what process may work best. Lets go with the issue tracker and see how that
pans out. Thanks again sir!

**Pull request merged**
