### PR TITLE
RHEL5/Fedora use bash templates

### PR DESCRIPTION
**Pull request by ybznek**
I have used templates for most common files remediation files

It needs to be rebased after merge of https://github.com/OpenSCAP/scap-security-guide/pull/1386

Found changes in output DS: Fedora (I think it is correct change)
```
service_command enable chronyd.service => service_command enable chronyd
```

### CODE REVIEW

**Comment by iankko** [comment]
@ybznek 
Please rebase this (#1386 has been merged already).

**Comment by mpreisler** [comment]
Is this still not ready for merging?

**Comment by ybznek** [comment]
@mpreisler yes, sorry. I forget to change title.

**Comment by mpreisler** [comment]
The Fedora fix script change is correct. Both are equivalent under current circumstances and I think not having the suffix there is correct.

ACK

**Pull request merged**
