### PR TITLE
Remove the suppor.sh script

### LINKED ISSUE #872: Drop 'support.sh' remediation script -- move 'populate()' function definition to /usr/share/scap-security-guide/remediation_functions
Currently there are couple of instances on the ```support.sh``` script:
```
$ find . -name support.sh -print
```
containing definition only of the ```populate()``` function:
* ```./shared/remediations/bash/templates/support.sh```
* ```./Webmin/input/remediations/bash/templates/support.sh```
* ```./RHEL/7/input/remediations/bash/templates/support.sh```
* ```./RHEL/6/input/remediations/bash/templates/support.sh```
* ```./RHEL/5/input/remediations/bash/templates/support.sh```
* ```./Firefox/input/remediations/bash/templates/support.sh```
* ```./Fedora/input/remediations/bash/templates/support.sh```

Since the common remediation functions (expected to be used across remediation scripts) are located in:
```
shared/remediations/bash/templates/remediation_functions
```

* the ```populate()``` function definition should be moved to this location too,
* all the remediation scripts including / importing ```support.sh``` now, should include aforementioned ```remediation_functions``` location instead,
* those multiple copies of ```support.sh``` script should be deleted.

### PR DESCRIPTION
**Pull request by msrubar**
The content of the script was moved because it's same for all the products and
it doesn't make sence to have it duplicated. The commit resolves #872.

### CODE REVIEW

**Comment by mpreisler** [comment]
Will the path to remediation_functions be correct in the final XCCDF after everything is installed using `make install`?

**Comment by iankko** [comment]
@msrubar 
Small hint -- Michal, check out the way this is implemented in other remediations (already using that functionality), and possibly comment why it needs to be implemented the way it is :).

Jan.

**Comment by msrubar** [comment]
After discussion with @iankko I finally understand the purpose of the `support.sh` script. It's not used directly by SSG at the moment but it can be used for testing purposes and will be used in SSG Testsuite.

**Comment by mpreisler** [comment]
> After discussion with @iankko I finally understand the purpose of the support.sh script. It's not used directly by SSG at the moment but it can be used for testing purposes and will be used in SSG Testsuite.

Please document it somewhere. Comments in the scripts itself would be a good place.

**Comment by isimluk** [comment]
I am confused. Are we removing the script or not?

**Comment by iankko** [comment]
@isimluk 
> I am confused. Are we removing the script or not?
Yes. The plan is to remove that script and move the only ```populate``` function into existing ```/usr/share/scap-security-guide/remediation_functions```.

But I am not going to merge this within 0.1.27 yet, because that change has the potential to possibly break the remediation capability (IOW the change needs to be more tested after merging it && possible issues fixed prior next release).

Please do <b> NOT </b> merge this into 0.1.27 yet.

**Comment by isimluk** [comment]
Understood. Thanks!

**Comment by iankko** [comment]
Verified on F-23 guest the remediations are working properly also after having this change applied.

ACK.

**Pull request merged**
