### PR TITLE
Added a build system schema to illustrate what SSG is about

### PR DESCRIPTION
**Pull request by mpreisler**
Just a minor addition, I think it helps to have pictures along side the text. Please feel free to improve the visuals in later PRs, my talents lie elsewhere..

### CODE REVIEW

**Comment by redhatrises** [comment]
The only thing that I would say that is missing is future/other inputs and outputs. This way we can show that we want and are willing to accept other content.

**Comment by mpreisler** [comment]
> The only thing that I would say that is missing is future/other inputs and outputs. This way we can show that we want and are willing to accept other content.

yeah, that's a good point. not sure how to fix it. if I added ellipsis to the outputs, do you think that would fix it?

**Comment by mpreisler** [comment]
> @mpreisler why not just add a separate input box and output box?

I don't follow, what would be in the input box? both new boxes would have ellipsis?

**Comment by redhatrises** [comment]
@mpreisler:

```
Bash Fix Snippets -> Build system -> Bash fix scripts
Ansible Fix Snippets -> Build system -> Ansible Playbooks
{Future/Other} -> Build system -> {Future/Other outputs}
```

**Comment by mpreisler** [comment]
OK, I get it now. I don't like that approach and I will explain why:

1) that's not how it works, we basically parse all data and then (from the combination of all data) we output the playbooks, just the ansible snpipets won't give you the playbook, there is more in them than that. that's why I think what you suggest would be confusing
2) I think it would make the project look a bit unfocused and uncertain, the ellipsis for outputs makes it look like there is more generated or there is more that could be generated, this makes it look like we don't know what we want

**Comment by jan-cerny** [comment]
In the first beige box, is it OpenControl YAML rule metadata? Isn't it our custom format?

**Comment by mpreisler** [comment]
> In the first beige box, is it OpenControl YAML rule metadata? Isn't it our custom format?

it is but in my experience saying that just confuses people even more. what do you suggest to replace it with?

**Comment by jan-cerny** [comment]
@mpreisler 
I have 2 options:
1. We could give a name to the our format.
2. We can put into this picture a YAML, without mentioning OpenControl.

**Comment by mpreisler** [comment]
> We can put into this picture a YAML, without mentioning OpenControl.

I like this idea. I will change it then.

**Comment by mpreisler** [comment]
> I like this idea. I will change it then.

DONE

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
Jenkins has a problem with this PR.
It says:
```
stderr: error: unable to create file docs/readme_images/build_schema.svg (Permission denied)
```
The, it throws a Java Exception.

For more details, please see https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/1376/label=ssg_new/console

**Comment by mpreisler** [comment]
> Jenkins has a problem with this PR.

It's a jenkins problem, not a problem with the PR. I suggest to clean the workspace in Jenkins.

**Comment by yuumasato** [comment]
@openscap-ci test this please

Jenkins just died, I have restarted it.

**Pull request merged**
