### PR TITLE
[Bugfix][RHEL/7] use_kerberos_security_all_exports.xml

### LINKED ISSUE #1201: [RHEL/7] Enhance existing "use_kerberos_security_all_exports" OVAL check not to return "fail" result on empty /etc/exports file
The ```use_kerberos_security_all_exports``` RHEL/7 rule checks if (more from the description of the particular rule):
```
Using Kerberos on all exported mounts prevents a malicious client or user from
impersonating a system user. To cryptography authenticate users to the NFS server,
add sec=krb5:krb5i:krb5p to each export in /etc/exports.
```
But the current implementation doesn't check if the ```/etc/exports``` file isn't actually empty:
&nbsp; &nbsp; https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/oval/use_kerberos_security_all_exports.xml

IOW the current implementation returns ```fail``` as a result even in the case there's no NFS
mount point configured in ```/etc/exports```.

We should enhance the test to return ```fail``` only in moment:
* there's at least NFS mount row present in ```/etc/exports```,
* the recommended ```krb5:krb5i:krb5p``` options aren't applied / enforced on such a row.

Something like the OVAL to do:
* get the count of NFS mount rows from ```/etc/exports```,
* get the count of NFS mount rows from ```/etc/exports``` having at least one of ```krb5:krb5i:krb5p``` option set,
then:
* ensure the count of NFS mount rows > 0,
* and count of NFS mount rows matches the count of NFS mount rows using krb5 security options.

### PR DESCRIPTION
**Pull request by redhatrises**
- Pass if /etc/exports does not contain an export
- Fixes #1201

### CODE REVIEW

**Comment by redhatrises** [comment]
Mmmmm.... build was successful but didn't report back that it was successful.

**Comment by iankko** [comment]
@ybznek Zbynek, could you probably look why despite of the child jobs having succeeded, the main interface didn't return back with a report about successful completion of the whole testing job? (IOW why it seems stuck in "yellow" state?)

Thanks, Jan

In between I will review this one.

**Comment by iankko** [comment]
Ad the non-updated interface result:
  https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/151/console

suggests further details. 
```
Setting status of 89923cad860cdae08efcd532e2db521eadd4040c to SUCCESS with url https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/151/ and message: 'Build finished. No test results found.'
Could not update commit status of the Pull Request on GitHub.
java.net.UnknownHostException: api.github.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
...
```

I will probably just restart the testing job (maybe it was just temporary failure / error / timeout in DNS resolution) or something like that.

**Comment by iankko** [comment]
re[test this please]

**Comment by iankko** [comment]
Looks good to me. Verified the check passes when ```/etc/exports``` is empty, also passes when there's just one export having the expected krb5 sec options set, and fails, when there are two exports (one having the krb5 options, the second not).

ACK for merging this (Jenkins sanitized it's behaviour in between too).

**Pull request merged**
