### PR TITLE
Support scripts

### PR DESCRIPTION
**Pull request by thenefield**
Two scripts are being added to facilitate some useful functions.

Both scripts should be executed from within the root folder of a given project (e.g. RHEL\6).

shared\transforms\stats.sh

The above script provides useful statistics based on the information presented in 'auxiliary\stig_overlay.xml'. It will identify the number of checks included, the number of fixes included, an overall number of STIG requirements indicated in the stig_overlay, and the number of STIG requirements in the XCCDF STIG document. This is useful for providing an overview of how much STIG coverage is accounted for. It is also useful for comparison against newly released STIGs to support identifying new requirements and deprecated requirements to ensure complete alignment. 

shared\transforms\stig_refs.sh

The above script facilitates automating the updating of STIG information within the SCAP content. It will initially use 'auxiliary\stig_overlay.xml' to provide a mapping of STIG ID to SCAP RULE. Once that mapping has been created, it will update the 'auxiliary\stig_overlay.xml' data and the XML data associated with each rule in the 'services' and  'system' sub-folders. The script is also dependent on the XCCDF STIG document being located within the references folder of the project folder (e.g. RHEL\6\references). 

The following data is updated in each location:

CCI
CCE
SEVERITY
SVKEY
VRELEASE
IA CONTROLS
TITLE

In addition it also includes a 'stig=' reference in the 'ident' section of each rule with the STIG ID. This will support a separate change to be committed, that will help identifying the appropriate STIG ID for each rule within the scan report.

### CODE REVIEW

**Comment by redhatrises** [comment]
Kind Nack. You included changes from a PR that you previously opened. Please remove the `shared/transforms/combinechecks.py` from this PR.

**Comment by thenefield** [comment]
Did I remove it properly?

**Comment by redhatrises** [comment]
You actually removed the entire file from the git tree. It will probably be best to close this PR and submit a new one with just the `.sh` scripts. Typically the best way of submitting changes is to create a branch that you make changes in off of a clean master branch. For example:

```
git clone https://github.com/OpenSCAP/scap-security-guide.git   
git checkout -b support_scripts   
```
Make changes to the files you want; then, `git add` and `git commit`.
Submit your branch (in this case `support_scripts`) for review.

This way, you can contain only the changes needed for the PR that you are submitting.

**Comment by thenefield** [comment]
Thanks for the feedback! I am pulling hair trying to get this process down.
So I should rebase after each commit? I did create different branches. But
I guess it merged in all my previous changes. Stand by.

**Pull request closed without merging**
