### PR TITLE
Updating invalid e-mail in Author list

### PR DESCRIPTION
**Pull request by pthierry38**
Just correcting an invalid e-mail to public address.

### CODE REVIEW

**Comment by redhatrises** [comment]
[retest this please]

**Comment by redhatrises** [comment]
@mpreisler looks like we are having jenkins problems again with the `el6` node.

**Comment by redhatrises** [comment]
Acking this as it doesn't really break anything.

**Comment by mpreisler** [comment]
This shouldn't have been merged. `Contributors.md` is auto-generated and as such this PR makes no sense. The email has to be changed in the tool that auto-generaates the file, not in the file itself.

We also generate `contributors.xml` which is now out of sync...

The script is in `shared/misc` IIRC.

**Pull request merged**
