### PR TITLE
Fix Anaconda package install template typo

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by mpreisler** [comment]
@redhatrises @shawndwells Was this really a typo? This fix reboots anaconda. See https://bugzilla.redhat.com/show_bug.cgi?id=1450731

CC @dahaic

**Comment by mpreisler** [comment]
See https://github.com/OpenSCAP/oscap-anaconda-addon/blob/rhel7-branch/org_fedora_oscap/rule_handling.py#L59
https://github.com/OpenSCAP/oscap-anaconda-addon/blob/rhel7-branch/org_fedora_oscap/rule_handling.py#L61

**Comment by redhatrises** [comment]
@mpreisler according to https://www.open-scap.org/tools/oscap-anaconda-addon/doc/ it should be `-add`, `-remove`, etc. However with the links that you have referenced, the code references `--add`, `--remove`, etc. So which is the correct way, the code or documentation? Or am I reading the documentation completely wrong?

**Comment by mpreisler** [comment]
@redhatrises I think this is most probably a formatting issue in the docs.

Thx for confirming!

**Comment by mpreisler** [comment]
I have submitted a PR and fixed the doc issue reported by @redhatrises

**Comment by redhatrises** [comment]
Thanks @mpreisler. #2005 is merged.

**Pull request merged**
