### PR TITLE
Initial Wind River Linux support

### PR DESCRIPTION
**Pull request by radzy**
Hi folks

I'd like to add support for wrlinux.  This patch adds the basic dictionary and such, and I expect to make any needed enhancements in the future as this gets further along.

Enjoy!

-- radzy

### CODE REVIEW

**Comment by iankko** [comment]
@radzy 
Thanks for the contribution! Could you first resolve the merge conflicts against the current master?

Thanks, Jan

**Comment by radzy** [comment]
Yes, thanks.  I'll resolve the merge conflicts and re-submit.

Enjoy!

-- radzy

________________________________________

**Comment by mpreisler** [comment]
Copying content around is really getting out of hand. If we accept more of this we will create big maintenance nightmares in the future.

I think we should look into using the RHEL XCCDF texts in more products instead of copying them as they are. Please do not merge this until we establish how we will proceed in the long term.

**Comment by redhatrises** [comment]
> Copying content around is really getting out of hand. If we accept more of this we will create big maintenance nightmares in the future.

@mpreisler agreed. What do you think about implementing something like #942?

**Comment by mpreisler** [comment]
@openscap-jenkins add to whitelist

**Comment by radzy** [comment]
Will submit a new PR when it's ready.

**Pull request closed without merging**
