### PR TITLE
Generate all roles, not just the last one

### PR DESCRIPTION
**Pull request by mpreisler**
LOL, what a screw up...

### CODE REVIEW

**Comment by shawndwells** [comment]
.... so how did building ansible roles work at all? Currently we get all ansible tasks when we generate remediations.

**Comment by mpreisler** [comment]
> .... so how did building ansible roles work at all? Currently we get all ansible tasks when we generate remediations.

It went through all the profiles and generated all the roles but the target file was screwed up so it kept overwriting it. It only generated one role per datastream and the file path didn't necessarily match what was inside.

**Comment by dahaic** [comment]
The change was obvious, to I merged it, but I do wonder about the same Shawn raised - role_path was not initiated in the function ```builder``` at all. Shouldn't it error horribly without writing anything?

**Comment by mpreisler** [comment]
> The change was obvious, to I merged it, but I do wonder about the same Shawn raised - role_path was not initiated in the function builder at all. Shouldn't it error horribly without writing anything?

It's beacuse it's written in Python and in Python variables bleed through scopes. `role_path` is used in some previous code, then in the loop only guide_path was being set but it was using the last value of `role_path`.

**Pull request merged**
