### PR TITLE
Fix errors in audit remediation bash scripts

### PR DESCRIPTION
**Pull request by Iambchop**
The first is just a simple typo fix: "EACCES**S**" should be "EACCES" and "EPRM" should be "EP**E**RM".

### CODE REVIEW

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by mpreisler** [comment]
Thank you for your contribution, this patch looks awesome!

Will do some testing and run it through jenkins before merging.

**Comment by redhatrises** [comment]
The "-F key=$key" is correct and should be the audit key syntax going forward. `fix_audit_syscall_rule` should be fixed to handle both cases.

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by mpreisler** [comment]
@lambchop could you please remove the second commit? Then I think we can merge this.

**Comment by Iambchop** [comment]
@mpreisler, done.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
