### PR TITLE
Make build easier, improve error messages

### PR DESCRIPTION
**Pull request by mpreisler**

### CODE REVIEW

**Comment by shawndwells** [comment]
While you're tinkering, could you drop a note in the README to look at the BUILD.md file for compiling?

**Comment by mpreisler** [comment]
> While you're tinkering, could you drop a note in the README to look at the BUILD.md file for compiling?

It is there. Perhaps we could make it more visible but I am not sure how.

**Comment by shawndwells** [comment]
On 6/20/17 5:08 PM, Martin Preisler wrote:
>
>     While you're tinkering, could you drop a note in the README to
>     look at the BUILD.md file for compiling?
>
> It is there. Perhaps we could make it more visible but I am not sure how.
>

.... I just looked three times, gave up, and had to grep for BUILD to
see what you referred to. It's buried under "installation."



Can we separate "Downstream Installation" from "Compiling from Source" ?

**Comment by mpreisler** [comment]
> Can we separate "Downstream Installation" from "Compiling from Source" ?

I separated it into "Installation" and "Build from source".

**Comment by jan-cerny** [comment]
Great!

**Comment by rybal06** [comment]
Could this page be either updated or removed? https://github.com/OpenSCAP/scap-security-guide/wiki/Building-from-Source

**Comment by shawndwells** [comment]
@rybal06 looks like @redhatrises just took care of that. Thanks for calling this out!

**Pull request merged**
